# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "bluez"
PV = "5.87+2.git8750129efca8"
PR = "1.el10"
PACKAGES = " \
 bluez \
 bluez-cups \
 bluez-libs \
 bluez-libs-devel \
 bluez-obexd \
 "

SRC_URI = "${ALMALINUXSRC_MIRROR}/BaseOS/Source/Packages/bluez-5.87+2.git8750129efca8-1.el10.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "62d27ea8191d93705c17934de4cb299e96fa51b9b9545a51eb0bb6f9918d5a62"

SRC_URI:append = " ${ALMALINUX_MIRROR}/BaseOS/x86_64_v2/os/Packages/bluez-5.87+2.git8750129efca8-1.el10.x86_64_v2.rpm;name=x86_64_v2_bluez;unpack=0"
SRC_URI[x86_64_v2_bluez.sha256sum] = "25a68caff36a71331576e43506cf0cf0be25c9bb1e830579bbfc70361665fb83"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/bluez-cups-5.87+2.git8750129efca8-1.el10.x86_64_v2.rpm;name=x86_64_v2_bluez-cups;unpack=0"
SRC_URI[x86_64_v2_bluez-cups.sha256sum] = "fbf916814ca63befb75955ecf7f434c32f42e6086dddcfb28df9f991f13f6efc"

SRC_URI:append = " ${ALMALINUX_MIRROR}/BaseOS/x86_64_v2/os/Packages/bluez-libs-5.87+2.git8750129efca8-1.el10.x86_64_v2.rpm;name=x86_64_v2_bluez-libs;unpack=0"
SRC_URI[x86_64_v2_bluez-libs.sha256sum] = "24fad38aef9aae5a08de2a7cafead47652029da688ec0829fd58ceb1cb69e48b"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/bluez-libs-devel-5.87+2.git8750129efca8-1.el10.x86_64_v2.rpm;name=x86_64_v2_bluez-libs-devel;unpack=0"
SRC_URI[x86_64_v2_bluez-libs-devel.sha256sum] = "8ed9bbceb9302ce703f1662cc9ad5e049c93beec4a7cfb76b08c9b287c3a2289"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/bluez-obexd-5.87+2.git8750129efca8-1.el10.x86_64_v2.rpm;name=x86_64_v2_bluez-obexd;unpack=0"
SRC_URI[x86_64_v2_bluez-obexd.sha256sum] = "ebce57d58ee803b9f8454912f6bfbb27f7fe92ba8729292a0dece2cd7e456e6c"

SRC_URI:append = " ${ALMALINUX_MIRROR}/BaseOS/aarch64/os/Packages/bluez-5.87+2.git8750129efca8-1.el10.aarch64.rpm;name=aarch64_bluez;unpack=0"
SRC_URI[aarch64_bluez.sha256sum] = "770600aa345bb9ac51ef9504b3f8bb1723830e3f87ab2d89efb0aa590525f96d"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/bluez-cups-5.87+2.git8750129efca8-1.el10.aarch64.rpm;name=aarch64_bluez-cups;unpack=0"
SRC_URI[aarch64_bluez-cups.sha256sum] = "07bf076956bb8dfc0f5198a449eb9639fa9445cc5006a4f4fdccf440491ae8a4"

SRC_URI:append = " ${ALMALINUX_MIRROR}/BaseOS/aarch64/os/Packages/bluez-libs-5.87+2.git8750129efca8-1.el10.aarch64.rpm;name=aarch64_bluez-libs;unpack=0"
SRC_URI[aarch64_bluez-libs.sha256sum] = "1d1e9d06bd364678b8afafa789953e15a845ff32e718565c3515e008a619e88d"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/bluez-libs-devel-5.87+2.git8750129efca8-1.el10.aarch64.rpm;name=aarch64_bluez-libs-devel;unpack=0"
SRC_URI[aarch64_bluez-libs-devel.sha256sum] = "cb81fdb99c9637e4df5df7e3e96dc61dd079c319f4f987399a1a5cf1486488cc"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/bluez-obexd-5.87+2.git8750129efca8-1.el10.aarch64.rpm;name=aarch64_bluez-obexd;unpack=0"
SRC_URI[aarch64_bluez-obexd.sha256sum] = "b1b47c668e09f2d3a4db4d97bbd3a95846b01cd46b041018e1d04d25757c7d1e"

RDEPENDS:bluez = " \
 bash \
 dbus \
 dbus-libs \
 glib2 \
 glibc \
 readline \
 systemd \
 systemd-libs \
 "
RDEPENDS:bluez-cups = " \
 bluez \
 cups \
 dbus-libs \
 glib2 \
 glibc \
 "
RDEPENDS:bluez-libs = " \
 glibc \
 "
RDEPENDS:bluez-libs-devel = " \
 bluez-libs \
 glibc \
 pkgconf-pkg-config \
 "
RDEPENDS:bluez-obexd = " \
 bash \
 bluez \
 bluez-libs \
 dbus-libs \
 glib2 \
 glibc \
 libical \
 systemd-libs \
 "
