# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "cockpit-files"
PV = "42"
PR = "1.el10"
PACKAGES = " \
 cockpit-files \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/cockpit-files-42-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a65289d3cf0a37f6acb91f044f3dbbab709d282638a30806cb117b5417e5209c"

URI_x86_64_v2_cockpit-files = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/cockpit-files-42-1.el10.noarch.rpm;name=x86_64_v2_cockpit-files;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_cockpit-files}"
SRC_URI[x86_64_v2_cockpit-files.sha256sum] = "30dadd1706f4362c78aa81bc68ed0f646bb4d718f8a5c38aa32ab01d2671ea46"

URI_aarch64_cockpit-files = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/cockpit-files-42-1.el10.noarch.rpm;name=aarch64_cockpit-files;unpack=0"
SRC_URI:append = " ${URI_aarch64_cockpit-files}"
SRC_URI[aarch64_cockpit-files.sha256sum] = "30dadd1706f4362c78aa81bc68ed0f646bb4d718f8a5c38aa32ab01d2671ea46"

RDEPENDS:cockpit-files = " \
 cockpit-bridge \
 "
