# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "firewalld"
PV = "2.4.3"
PR = "2.el10"
PACKAGES = " \
 firewall-applet \
 firewall-config \
 firewalld \
 firewalld-filesystem \
 python3-firewall \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/BaseOS/Source/Packages/firewalld-2.4.3-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "eaa08031e8e51618856548fc9acaf7d36ea90f669ae2d1fc2034a4ac977edce9"

URI_x86_64_v2_firewall-applet = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/firewall-applet-2.4.3-2.el10.noarch.rpm;name=x86_64_v2_firewall-applet;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_firewall-applet}"
SRC_URI[x86_64_v2_firewall-applet.sha256sum] = "c3e5049ab018c80c5e67e949fb2ab30d4c9037e2f579e86347033ca61230310d"

URI_x86_64_v2_firewall-config = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/firewall-config-2.4.3-2.el10.noarch.rpm;name=x86_64_v2_firewall-config;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_firewall-config}"
SRC_URI[x86_64_v2_firewall-config.sha256sum] = "042e880015be0ecd3f2305ca9f11e8b717e697b10a79e0c9c2775240d90d2b2d"

URI_x86_64_v2_firewalld = "${ALMALINUX_MIRROR}/BaseOS/x86_64_v2/os/Packages/firewalld-2.4.3-2.el10.noarch.rpm;name=x86_64_v2_firewalld;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_firewalld}"
SRC_URI[x86_64_v2_firewalld.sha256sum] = "de4c1c77a50c9c62a830468225e990353092cbbf47be409b5f4137972ba0db64"

URI_x86_64_v2_firewalld-filesystem = "${ALMALINUX_MIRROR}/BaseOS/x86_64_v2/os/Packages/firewalld-filesystem-2.4.3-2.el10.noarch.rpm;name=x86_64_v2_firewalld-filesystem;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_firewalld-filesystem}"
SRC_URI[x86_64_v2_firewalld-filesystem.sha256sum] = "c9dfa34d144677716b023c42fbacc53f05bbeade4db44d8edfcf6ed8caf2dd86"

URI_x86_64_v2_python3-firewall = "${ALMALINUX_MIRROR}/BaseOS/x86_64_v2/os/Packages/python3-firewall-2.4.3-2.el10.noarch.rpm;name=x86_64_v2_python3-firewall;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python3-firewall}"
SRC_URI[x86_64_v2_python3-firewall.sha256sum] = "87e657ff214eba61973fc5209ebf85968b3923bd7309c3197d65848b93b74a7d"

URI_aarch64_firewall-applet = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/firewall-applet-2.4.3-2.el10.noarch.rpm;name=aarch64_firewall-applet;unpack=0"
SRC_URI:append = " ${URI_aarch64_firewall-applet}"
SRC_URI[aarch64_firewall-applet.sha256sum] = "c3e5049ab018c80c5e67e949fb2ab30d4c9037e2f579e86347033ca61230310d"

URI_aarch64_firewall-config = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/firewall-config-2.4.3-2.el10.noarch.rpm;name=aarch64_firewall-config;unpack=0"
SRC_URI:append = " ${URI_aarch64_firewall-config}"
SRC_URI[aarch64_firewall-config.sha256sum] = "042e880015be0ecd3f2305ca9f11e8b717e697b10a79e0c9c2775240d90d2b2d"

URI_aarch64_firewalld = "${ALMALINUX_MIRROR}/BaseOS/aarch64/os/Packages/firewalld-2.4.3-2.el10.noarch.rpm;name=aarch64_firewalld;unpack=0"
SRC_URI:append = " ${URI_aarch64_firewalld}"
SRC_URI[aarch64_firewalld.sha256sum] = "de4c1c77a50c9c62a830468225e990353092cbbf47be409b5f4137972ba0db64"

URI_aarch64_firewalld-filesystem = "${ALMALINUX_MIRROR}/BaseOS/aarch64/os/Packages/firewalld-filesystem-2.4.3-2.el10.noarch.rpm;name=aarch64_firewalld-filesystem;unpack=0"
SRC_URI:append = " ${URI_aarch64_firewalld-filesystem}"
SRC_URI[aarch64_firewalld-filesystem.sha256sum] = "c9dfa34d144677716b023c42fbacc53f05bbeade4db44d8edfcf6ed8caf2dd86"

URI_aarch64_python3-firewall = "${ALMALINUX_MIRROR}/BaseOS/aarch64/os/Packages/python3-firewall-2.4.3-2.el10.noarch.rpm;name=aarch64_python3-firewall;unpack=0"
SRC_URI:append = " ${URI_aarch64_python3-firewall}"
SRC_URI[aarch64_python3-firewall.sha256sum] = "87e657ff214eba61973fc5209ebf85968b3923bd7309c3197d65848b93b74a7d"

RDEPENDS:firewall-applet = " \
 NetworkManager-libnm \
 dbus-x11 \
 firewall-config \
 firewalld \
 hicolor-icon-theme \
 libnotify \
 python3 \
 python3-firewall \
 python3-gobject \
 python3-pyqt6-base \
 "
RDEPENDS:firewall-config = " \
 NetworkManager-libnm \
 dbus-x11 \
 firewalld \
 gtk3 \
 hicolor-icon-theme \
 python3 \
 python3-firewall \
 python3-gobject \
 "
RDEPENDS:firewalld = " \
 bash \
 firewalld-filesystem \
 python3 \
 python3-firewall \
 systemd \
 "
RDEPENDS:firewalld-filesystem = " \
 "
RDEPENDS:python3-firewall = " \
 python3 \
 python3-dbus \
 python3-gobject-base \
 python3-nftables \
 "
