# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "freerdp"
PE = "2"
PV = "3.28.0"
PR = "4.el10"
PACKAGES = " \
 freerdp \
 freerdp-devel \
 freerdp-libs \
 freerdp-server \
 libwinpr \
 libwinpr-devel \
 "

SRC_URI = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/freerdp-3.28.0-4.el10.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "209d51e49b9c755fed39e63ba335006135e2e3ae24f02fd3c6eecab972bc59e1"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/freerdp-3.28.0-4.el10.x86_64_v2.rpm;name=x86_64_v2_freerdp;unpack=0"
SRC_URI[x86_64_v2_freerdp.sha256sum] = "c3e7ba387b01f2b90b195e5a925689c5fbd8a1fe6476363e89df36924255df80"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/freerdp-devel-3.28.0-4.el10.x86_64_v2.rpm;name=x86_64_v2_freerdp-devel;unpack=0"
SRC_URI[x86_64_v2_freerdp-devel.sha256sum] = "d9489e07c368452fd619d331ed01d57d2f40877fdf79cd9c898d92a1a10a0ca4"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/freerdp-libs-3.28.0-4.el10.x86_64_v2.rpm;name=x86_64_v2_freerdp-libs;unpack=0"
SRC_URI[x86_64_v2_freerdp-libs.sha256sum] = "2c9706defd9437bf0822c4556cc793b2e7abae4665246407f3ef43a505f38770"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/freerdp-server-3.28.0-4.el10.x86_64_v2.rpm;name=x86_64_v2_freerdp-server;unpack=0"
SRC_URI[x86_64_v2_freerdp-server.sha256sum] = "5581b6ea9b4446ba1ff2f2419685e3101209c78dff08174777b871ccf54c2398"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/libwinpr-3.28.0-4.el10.x86_64_v2.rpm;name=x86_64_v2_libwinpr;unpack=0"
SRC_URI[x86_64_v2_libwinpr.sha256sum] = "4edddb91c5921a494ebfd6394ede591becb6ec7fee5eff8447584b7962dc9941"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/libwinpr-devel-3.28.0-4.el10.x86_64_v2.rpm;name=x86_64_v2_libwinpr-devel;unpack=0"
SRC_URI[x86_64_v2_libwinpr-devel.sha256sum] = "253700f72a5b9c58ff8bd556678c91eeada1e3e3a928ef0ca91c457c3443e059"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/freerdp-3.28.0-4.el10.aarch64.rpm;name=aarch64_freerdp;unpack=0"
SRC_URI[aarch64_freerdp.sha256sum] = "69030812c0a8fa0f1013a65ad8ad3c32f5179a2bcd8bbc0a13538027e8c5b6a7"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/freerdp-devel-3.28.0-4.el10.aarch64.rpm;name=aarch64_freerdp-devel;unpack=0"
SRC_URI[aarch64_freerdp-devel.sha256sum] = "a4f81d069a2cc06b653538bd52227b4cf40ffc15aa72f8947049ca8d1bfd2086"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/freerdp-libs-3.28.0-4.el10.aarch64.rpm;name=aarch64_freerdp-libs;unpack=0"
SRC_URI[aarch64_freerdp-libs.sha256sum] = "499ecad9d48ffeee35038e627bb2be0d739f49a48731a2702dd818cde6c96b15"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/freerdp-server-3.28.0-4.el10.aarch64.rpm;name=aarch64_freerdp-server;unpack=0"
SRC_URI[aarch64_freerdp-server.sha256sum] = "0fbbcb321e350ba9f3b909cb8395972043f5b9d8c61c533b254711b3a5130630"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/libwinpr-3.28.0-4.el10.aarch64.rpm;name=aarch64_libwinpr;unpack=0"
SRC_URI[aarch64_libwinpr.sha256sum] = "197a21293b7e9f43c805d6bdce628258aad284596c072b1d9308d3c7374ecacb"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/libwinpr-devel-3.28.0-4.el10.aarch64.rpm;name=aarch64_libwinpr-devel;unpack=0"
SRC_URI[aarch64_libwinpr-devel.sha256sum] = "cd6231be4a92530d745217ec662771492f4fc26916719c80c35226c17437441b"

RDEPENDS:freerdp = " \
 freerdp-libs \
 glibc \
 libX11 \
 libXcursor \
 libXext \
 libXfixes \
 libXi \
 libXinerama \
 libXrandr \
 libXrender \
 libwayland-client \
 libwayland-cursor \
 libwinpr \
 libxkbcommon \
 "
RDEPENDS:freerdp-devel = " \
 cmake \
 cmake-filesystem \
 freerdp-devel \
 freerdp-libs \
 libwinpr-devel \
 pkgconf-pkg-config \
 "
RDEPENDS:freerdp-libs = " \
 alsa-lib \
 cairo \
 cups-libs \
 fdk-aac-free \
 fuse3-libs \
 glibc \
 gsm \
 lame-libs \
 libX11 \
 libXdamage \
 libXext \
 libXfixes \
 libXinerama \
 libXtst \
 libcbor \
 libfido2 \
 libgcc \
 libstdc++ \
 libusb1 \
 libwinpr \
 libxkbfile \
 openssl-libs \
 opus \
 pam-libs \
 pulseaudio-libs \
 zlib-ng-compat \
 "
RDEPENDS:freerdp-server = " \
 freerdp-libs \
 glibc \
 libwinpr \
 "
RDEPENDS:libwinpr = " \
 glibc \
 json-c \
 krb5-libs \
 libcom_err \
 libgcc \
 libicu \
 libjpeg-turbo \
 libpng \
 libwebp \
 openssl-libs \
 "
RDEPENDS:libwinpr-devel = " \
 cmake \
 cmake-filesystem \
 libwinpr \
 libwinpr-devel \
 pkgconf-pkg-config \
 "
