# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "gnome-kiosk"
PV = "49.0"
PR = "12.el10"
PACKAGES = " \
 gnome-kiosk \
 gnome-kiosk-script-session \
 gnome-kiosk-search-appliance \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/gnome-kiosk-49.0-12.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c175cb504f7796f805d798b424ada3e34f1e8fb38869d607a8c80e2326521056"

URI_x86_64_v2_gnome-kiosk = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/gnome-kiosk-49.0-12.el10.x86_64_v2.rpm;name=x86_64_v2_gnome-kiosk;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_gnome-kiosk}"
SRC_URI[x86_64_v2_gnome-kiosk.sha256sum] = "3c9d50fa8d8f48e8c692d8a43c0ccfc0c4052c0bd3f01ca0f3f2e0a8fe61f29b"
RPROVIDES:gnome-kiosk:x86_64_v2 = "virtual/weston_or_cage_or_kwin-wayland_or_mutter_or_gnome-kiosk"

URI_x86_64_v2_gnome-kiosk-script-session = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/gnome-kiosk-script-session-49.0-12.el10.noarch.rpm;name=x86_64_v2_gnome-kiosk-script-session;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_gnome-kiosk-script-session}"
SRC_URI[x86_64_v2_gnome-kiosk-script-session.sha256sum] = "33d414748f11f61533b642b9dded28be4fb647036868b495c02db338842b39dd"

URI_x86_64_v2_gnome-kiosk-search-appliance = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/gnome-kiosk-search-appliance-49.0-12.el10.noarch.rpm;name=x86_64_v2_gnome-kiosk-search-appliance;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_gnome-kiosk-search-appliance}"
SRC_URI[x86_64_v2_gnome-kiosk-search-appliance.sha256sum] = "f2e6265d412b9c3eedfb6d42c3d2816edac92058621b86d6c21bed20169b9a85"

URI_aarch64_gnome-kiosk = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/gnome-kiosk-49.0-12.el10.aarch64.rpm;name=aarch64_gnome-kiosk;unpack=0"
SRC_URI:append = " ${URI_aarch64_gnome-kiosk}"
SRC_URI[aarch64_gnome-kiosk.sha256sum] = "a12cdd94722edfcc9fc8b3365471fb2ef5d7e76329f90697c98e1709730aa7b3"
RPROVIDES:gnome-kiosk:aarch64 = "virtual/weston_or_cage_or_kwin-wayland_or_mutter_or_gnome-kiosk"

URI_aarch64_gnome-kiosk-script-session = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/gnome-kiosk-script-session-49.0-12.el10.noarch.rpm;name=aarch64_gnome-kiosk-script-session;unpack=0"
SRC_URI:append = " ${URI_aarch64_gnome-kiosk-script-session}"
SRC_URI[aarch64_gnome-kiosk-script-session.sha256sum] = "33d414748f11f61533b642b9dded28be4fb647036868b495c02db338842b39dd"

URI_aarch64_gnome-kiosk-search-appliance = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/gnome-kiosk-search-appliance-49.0-12.el10.noarch.rpm;name=aarch64_gnome-kiosk-search-appliance;unpack=0"
SRC_URI:append = " ${URI_aarch64_gnome-kiosk-search-appliance}"
SRC_URI[aarch64_gnome-kiosk-search-appliance.sha256sum] = "f2e6265d412b9c3eedfb6d42c3d2816edac92058621b86d6c21bed20169b9a85"

RDEPENDS:gnome-kiosk = " \
 cairo \
 gdk-pixbuf2 \
 glib2 \
 glibc \
 gnome-desktop4 \
 gnome-settings-daemon \
 graphene \
 gsettings-desktop-schemas \
 ibus-libs \
 libX11 \
 libgcc \
 libglvnd-gles \
 mutter \
 systemd-libs \
 "
RDEPENDS:gnome-kiosk-script-session = " \
 bash \
 gnome-kiosk \
 gnome-session \
 "
RDEPENDS:gnome-kiosk-search-appliance = " \
 flatpak \
 gnome-kiosk \
 gnome-session \
 "

PROVIDES:append:x86_64_v2 = " rpm/virtual/weston_or_cage_or_kwin-wayland_or_mutter_or_gnome-kiosk"

PROVIDES:append:aarch64 = " rpm/virtual/weston_or_cage_or_kwin-wayland_or_mutter_or_gnome-kiosk"
