# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "go-rpm-macros"
PV = "3.6.0"
PR = "4.el10"
PACKAGES = " \
 go-filesystem \
 go-rpm-macros \
 go-rpm-templates \
 go-srpm-macros \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/go-rpm-macros-3.6.0-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0e93d3fca155655211429067b7dd89330b0d36b74e9253480b64b27a8c3ad570"

URI_x86_64_v2_go-filesystem = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/go-filesystem-3.6.0-4.el10.x86_64_v2.rpm;name=x86_64_v2_go-filesystem;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_go-filesystem}"
SRC_URI[x86_64_v2_go-filesystem.sha256sum] = "292e289d78da956455924a08356536ab4a8739d3e58d07ba4d0730b56a817396"

URI_x86_64_v2_go-rpm-macros = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/go-rpm-macros-3.6.0-4.el10.x86_64_v2.rpm;name=x86_64_v2_go-rpm-macros;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_go-rpm-macros}"
SRC_URI[x86_64_v2_go-rpm-macros.sha256sum] = "b103886a097f5604b5dd6035db128357e7df33c4ecd4a10ab4952b278c90dbb7"

URI_x86_64_v2_go-rpm-templates = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/go-rpm-templates-3.6.0-4.el10.x86_64_v2.rpm;name=x86_64_v2_go-rpm-templates;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_go-rpm-templates}"
SRC_URI[x86_64_v2_go-rpm-templates.sha256sum] = "33708e2f0a99427c897f194a34f7bd0fb7125889c63d77a3a7a26f900a85fd10"

URI_x86_64_v2_go-srpm-macros = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/go-srpm-macros-3.6.0-4.el10.noarch.rpm;name=x86_64_v2_go-srpm-macros;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_go-srpm-macros}"
SRC_URI[x86_64_v2_go-srpm-macros.sha256sum] = "a94e5e5cdd5040cac24a47c98d09df36a1f20b0053dca855fc7a0f5b8cb60276"

URI_aarch64_go-filesystem = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/go-filesystem-3.6.0-4.el10.aarch64.rpm;name=aarch64_go-filesystem;unpack=0"
SRC_URI:append = " ${URI_aarch64_go-filesystem}"
SRC_URI[aarch64_go-filesystem.sha256sum] = "3ac54ba9070c5740e1af2a33f2ef388511c3765c90a8ebb5bcdb16767d84ad32"

URI_aarch64_go-rpm-macros = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/go-rpm-macros-3.6.0-4.el10.aarch64.rpm;name=aarch64_go-rpm-macros;unpack=0"
SRC_URI:append = " ${URI_aarch64_go-rpm-macros}"
SRC_URI[aarch64_go-rpm-macros.sha256sum] = "f96cbde41a4ee0e9145653ad8e49eb527197613c8c6f5b0b6d9ae094ce537f9d"

URI_aarch64_go-rpm-templates = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/go-rpm-templates-3.6.0-4.el10.aarch64.rpm;name=aarch64_go-rpm-templates;unpack=0"
SRC_URI:append = " ${URI_aarch64_go-rpm-templates}"
SRC_URI[aarch64_go-rpm-templates.sha256sum] = "8a414a7aaa0600c414824c4a32b2fdd3b481cd088c975862415d3220b12f81cb"

URI_aarch64_go-srpm-macros = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/go-srpm-macros-3.6.0-4.el10.noarch.rpm;name=aarch64_go-srpm-macros;unpack=0"
SRC_URI:append = " ${URI_aarch64_go-srpm-macros}"
SRC_URI[aarch64_go-srpm-macros.sha256sum] = "a94e5e5cdd5040cac24a47c98d09df36a1f20b0053dca855fc7a0f5b8cb60276"

RDEPENDS:go-filesystem = " \
 "
RDEPENDS:go-rpm-macros = " \
 bash \
 glibc \
 go-filesystem \
 go-srpm-macros \
 golang \
 python3 \
 "
RDEPENDS:go-rpm-templates = " \
 go-rpm-macros \
 "
RDEPENDS:go-srpm-macros = " \
 redhat-rpm-config \
 "
