# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "gperf"
PV = "3.1"
PR = "21.el10"
PACKAGES = " \
 gperf \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/gperf-3.1-21.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "78f1c874cdce1c469640a195daf77d9d85d2760fe7b378b939036e80378e3443"

URI_x86_64_v2_gperf = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/gperf-3.1-21.el10.x86_64_v2.rpm;name=x86_64_v2_gperf;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_gperf}"
SRC_URI[x86_64_v2_gperf.sha256sum] = "cd682fcf83bc330c265f9aae45fd2e97f7a16aa7c3bd5ba5e06ece3ff5e92ed3"

URI_aarch64_gperf = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/gperf-3.1-21.el10.aarch64.rpm;name=aarch64_gperf;unpack=0"
SRC_URI:append = " ${URI_aarch64_gperf}"
SRC_URI[aarch64_gperf.sha256sum] = "9e5b8fc85ac6caccecc5ef282688e00e819d018e3266a932f83b8d68e1c87f28"

RDEPENDS:gperf = " \
 glibc \
 libgcc \
 libstdc++ \
 "
