# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "hunspell-ku"
PV = "0.21"
PR = "35.el10"
PACKAGES = " \
 hunspell-ku \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/hunspell-ku-0.21-35.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4d6c1ebc4eb9be3777476a473ae07c8b0b5735ceac2915f3ea22c5ff2ecb9713"

URI_x86_64_v2_hunspell-ku = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/hunspell-ku-0.21-35.el10.noarch.rpm;name=x86_64_v2_hunspell-ku;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_hunspell-ku}"
SRC_URI[x86_64_v2_hunspell-ku.sha256sum] = "7141554d2c1d1de7d1121263d3bffa3cb38947b939b0f9973e7c5e3837ee7864"

URI_aarch64_hunspell-ku = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/hunspell-ku-0.21-35.el10.noarch.rpm;name=aarch64_hunspell-ku;unpack=0"
SRC_URI:append = " ${URI_aarch64_hunspell-ku}"
SRC_URI[aarch64_hunspell-ku.sha256sum] = "7141554d2c1d1de7d1121263d3bffa3cb38947b939b0f9973e7c5e3837ee7864"

RDEPENDS:hunspell-ku = " \
 hunspell-filesystem \
 "
