# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "hunspell-wa"
PV = "0.4.17"
PR = "26.el10"
PACKAGES = " \
 hunspell-wa \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/hunspell-wa-0.4.17-26.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c7828883c23007da0bd5f96893e0781707bba5e39a822776aefdf7b99b70040b"

URI_x86_64_v2_hunspell-wa = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/hunspell-wa-0.4.17-26.el10.noarch.rpm;name=x86_64_v2_hunspell-wa;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_hunspell-wa}"
SRC_URI[x86_64_v2_hunspell-wa.sha256sum] = "33c7043bee17983ff432e22782b78bdb1ed6acd098cbd870e5d8723338493c8b"

URI_aarch64_hunspell-wa = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/hunspell-wa-0.4.17-26.el10.noarch.rpm;name=aarch64_hunspell-wa;unpack=0"
SRC_URI:append = " ${URI_aarch64_hunspell-wa}"
SRC_URI[aarch64_hunspell-wa.sha256sum] = "33c7043bee17983ff432e22782b78bdb1ed6acd098cbd870e5d8723338493c8b"

RDEPENDS:hunspell-wa = " \
 hunspell-filesystem \
 "
