# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "hyphen-ga"
PV = "0.20040220"
PR = "32.el10"
PACKAGES = " \
 hyphen-ga \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/hyphen-ga-0.20040220-32.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c50ba60fb282b4239f0219f4aadadd5c553d6050482f09d332a3afb4c08f1ef4"

URI_x86_64_v2_hyphen-ga = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/hyphen-ga-0.20040220-32.el10.noarch.rpm;name=x86_64_v2_hyphen-ga;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_hyphen-ga}"
SRC_URI[x86_64_v2_hyphen-ga.sha256sum] = "d10667fa9f1d50a43898d792363712655df017a4b0a1880858014b709307fc30"

URI_aarch64_hyphen-ga = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/hyphen-ga-0.20040220-32.el10.noarch.rpm;name=aarch64_hyphen-ga;unpack=0"
SRC_URI:append = " ${URI_aarch64_hyphen-ga}"
SRC_URI[aarch64_hyphen-ga.sha256sum] = "d10667fa9f1d50a43898d792363712655df017a4b0a1880858014b709307fc30"

RDEPENDS:hyphen-ga = " \
 hyphen \
 "
