# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "libfabric"
PV = "1.22.0"
PR = "1.el10"
PACKAGES = " \
 libfabric \
 libfabric-devel \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/libfabric-1.22.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "09f7ce7ba4d6e9fa64a7578f8decc20280fb8235b5cc35cbe96a3aeac4f19143"

URI_x86_64_v2_libfabric = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/libfabric-1.22.0-1.el10.x86_64_v2.rpm;name=x86_64_v2_libfabric;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libfabric}"
SRC_URI[x86_64_v2_libfabric.sha256sum] = "e5fab8574eae8e42c0aa4e7e994ecfc8be1893ea501a5831fa5555f5afab84b9"

URI_x86_64_v2_libfabric-devel = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/libfabric-devel-1.22.0-1.el10.x86_64_v2.rpm;name=x86_64_v2_libfabric-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libfabric-devel}"
SRC_URI[x86_64_v2_libfabric-devel.sha256sum] = "a441b71031cb4b709d26c34d19315ecd742ab6e7ba3d1d1280bf2c9c053c18b5"

URI_aarch64_libfabric = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/libfabric-1.22.0-1.el10.aarch64.rpm;name=aarch64_libfabric;unpack=0"
SRC_URI:append = " ${URI_aarch64_libfabric}"
SRC_URI[aarch64_libfabric.sha256sum] = "738e8ee696d165a3e4e99aeebc379a67d281f177b0dddb3414826807282ddb04"

URI_aarch64_libfabric-devel = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/libfabric-devel-1.22.0-1.el10.aarch64.rpm;name=aarch64_libfabric-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_libfabric-devel}"
SRC_URI[aarch64_libfabric-devel.sha256sum] = "3deec85af3fe1eb40df1d9582c449cfdfd6b0c213de4f94de3b821098c486f14"

RDEPENDS:libfabric:x86_64_v2 = " \
 glibc \
 libibverbs \
 libnl3 \
 librdmacm \
"
RDEPENDS:libfabric:aarch64 = " \
 glibc \
 libatomic \
 libibverbs \
 libnl3 \
 librdmacm \
"
RDEPENDS:libfabric-devel = " \
 libfabric \
 pkgconf-pkg-config \
 "
