# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "libnotify"
PV = "0.8.6"
PR = "1.el10"
PACKAGES = " \
 libnotify \
 libnotify-devel \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/libnotify-0.8.6-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "6f46891596508892da43824b82b8ed1fc2ad70f19a6b20655d1b0385ba1ea8b0"

URI_x86_64_v2_libnotify = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/libnotify-0.8.6-1.el10.x86_64_v2.rpm;name=x86_64_v2_libnotify;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libnotify}"
SRC_URI[x86_64_v2_libnotify.sha256sum] = "2745c943a17469e1552ec57093883a2ab996e853b23f67fe924e611dcac6f80b"

URI_x86_64_v2_libnotify-devel = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/libnotify-devel-0.8.6-1.el10.x86_64_v2.rpm;name=x86_64_v2_libnotify-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libnotify-devel}"
SRC_URI[x86_64_v2_libnotify-devel.sha256sum] = "ce6d179c71e6b6acaf79bf7c7531a822127002ae78dfc688f7a20bd46cd034a2"

URI_aarch64_libnotify = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/libnotify-0.8.6-1.el10.aarch64.rpm;name=aarch64_libnotify;unpack=0"
SRC_URI:append = " ${URI_aarch64_libnotify}"
SRC_URI[aarch64_libnotify.sha256sum] = "d41e826fe1aeb9e444d6c06f3e43eef4b814469e67c43ed6cb58f7c990d680e6"

URI_aarch64_libnotify-devel = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/libnotify-devel-0.8.6-1.el10.aarch64.rpm;name=aarch64_libnotify-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_libnotify-devel}"
SRC_URI[aarch64_libnotify-devel.sha256sum] = "31fb58a4804f8c713096aa56d867b6dcb3694fb7469648b4eb34263ad4ecc3cc"

RDEPENDS:libnotify = " \
 gdk-pixbuf2 \
 glib2 \
 glibc \
 "
RDEPENDS:libnotify-devel = " \
 gdk-pixbuf2-devel \
 glib2-devel \
 libnotify \
 pkgconf-pkg-config \
 "
