# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "libwacom"
PV = "2.14.0"
PR = "3.el10_0"
PACKAGES = " \
 libwacom \
 libwacom-data \
 libwacom-devel \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/libwacom-2.14.0-3.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "54353ef0448ddaf25227a50461db61ea075e5faea75694183f9be0be00d86a2a"

URI_x86_64_v2_libwacom = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/libwacom-2.14.0-3.el10_0.x86_64_v2.rpm;name=x86_64_v2_libwacom;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libwacom}"
SRC_URI[x86_64_v2_libwacom.sha256sum] = "1a87d0fa35144e4abcc80b2eae48cdceba11740eac487fdd66a9f56931a87505"

URI_x86_64_v2_libwacom-data = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/libwacom-data-2.14.0-3.el10_0.noarch.rpm;name=x86_64_v2_libwacom-data;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libwacom-data}"
SRC_URI[x86_64_v2_libwacom-data.sha256sum] = "6c6757f5a74cc7cf7e4204f0b5b5e7325cdb55033fef06b89f0b8b82e449db74"

URI_x86_64_v2_libwacom-devel = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/libwacom-devel-2.14.0-3.el10_0.x86_64_v2.rpm;name=x86_64_v2_libwacom-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libwacom-devel}"
SRC_URI[x86_64_v2_libwacom-devel.sha256sum] = "45582149a098f7c167389e8b3810fad76a7fdde1d134658f542a9a9392ee5ffa"

URI_aarch64_libwacom = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/libwacom-2.14.0-3.el10_0.aarch64.rpm;name=aarch64_libwacom;unpack=0"
SRC_URI:append = " ${URI_aarch64_libwacom}"
SRC_URI[aarch64_libwacom.sha256sum] = "e49ab83b633d4cde22f9416e22e76e28b761dc64a607747cbe88b268c4daab66"

URI_aarch64_libwacom-data = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/libwacom-data-2.14.0-3.el10_0.noarch.rpm;name=aarch64_libwacom-data;unpack=0"
SRC_URI:append = " ${URI_aarch64_libwacom-data}"
SRC_URI[aarch64_libwacom-data.sha256sum] = "6c6757f5a74cc7cf7e4204f0b5b5e7325cdb55033fef06b89f0b8b82e449db74"

URI_aarch64_libwacom-devel = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/libwacom-devel-2.14.0-3.el10_0.aarch64.rpm;name=aarch64_libwacom-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_libwacom-devel}"
SRC_URI[aarch64_libwacom-devel.sha256sum] = "06bf658af97fdd95c4cd471c34e9b8c9ca9cf25c17c7c35f68fa62aade1c5e5d"

RDEPENDS:libwacom = " \
 glib2 \
 glibc \
 libevdev \
 libgudev \
 libwacom-data \
 python3 \
 "
RDEPENDS:libwacom-data = " \
 "
RDEPENDS:libwacom-devel = " \
 glib2-devel \
 libevdev-devel \
 libgudev-devel \
 libwacom \
 pkgconf-pkg-config \
 "
