# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "libxml2"
PV = "2.12.5"
PR = "15.el10"
PACKAGES = " \
 libxml2 \
 libxml2-devel \
 libxml2-static \
 python3-libxml2 \
 "

SRC_URI = "${ALMALINUXSRC_MIRROR}/BaseOS/Source/Packages/libxml2-2.12.5-15.el10.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "8dd9041368e80376d01df3e8eb587339f3a1490dd5c204b6c3e17cc44802f08b"

SRC_URI:append = " ${ALMALINUX_MIRROR}/BaseOS/x86_64_v2/os/Packages/libxml2-2.12.5-15.el10.x86_64_v2.rpm;name=x86_64_v2_libxml2;unpack=0"
SRC_URI[x86_64_v2_libxml2.sha256sum] = "d9f7c80f6b8dbcec7b4512e81fc8ebb71eabf9144d6ef16555f5ad1bfa4f0b30"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/libxml2-devel-2.12.5-15.el10.x86_64_v2.rpm;name=x86_64_v2_libxml2-devel;unpack=0"
SRC_URI[x86_64_v2_libxml2-devel.sha256sum] = "88aa34d93c285de73dda9b9936b4c6d06af0a8672d5bb351495e2b3dd500483f"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/libxml2-static-2.12.5-15.el10.x86_64_v2.rpm;name=x86_64_v2_libxml2-static;unpack=0"
SRC_URI[x86_64_v2_libxml2-static.sha256sum] = "4f38b96ff8ef68a0a355b3b4f43d635e2cce83593f7a4f03f3b98f692f6fc2e0"

SRC_URI:append = " ${ALMALINUX_MIRROR}/BaseOS/x86_64_v2/os/Packages/python3-libxml2-2.12.5-15.el10.x86_64_v2.rpm;name=x86_64_v2_python3-libxml2;unpack=0"
SRC_URI[x86_64_v2_python3-libxml2.sha256sum] = "643e0abd357ed7b9725876082e849fb95783d0dd93118cf3d3f3ee8e0147f788"

SRC_URI:append = " ${ALMALINUX_MIRROR}/BaseOS/aarch64/os/Packages/libxml2-2.12.5-15.el10.aarch64.rpm;name=aarch64_libxml2;unpack=0"
SRC_URI[aarch64_libxml2.sha256sum] = "412a63deea0fa2b9872bda1ff78bdf26db9dd16b12059706f030f4df8a68c9c5"

SRC_URI:append = " ${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/libxml2-devel-2.12.5-15.el10.aarch64.rpm;name=aarch64_libxml2-devel;unpack=0"
SRC_URI[aarch64_libxml2-devel.sha256sum] = "19c8346619fdea084ee6b4127a2ac7d2d804a02ec59ab5dafbede91ae2c9b885"

SRC_URI:append = " ${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/libxml2-static-2.12.5-15.el10.aarch64.rpm;name=aarch64_libxml2-static;unpack=0"
SRC_URI[aarch64_libxml2-static.sha256sum] = "0df470625d7f80b6ce49d033746dd4029bf4e515f7d8ecf1b371586396cfbff6"

SRC_URI:append = " ${ALMALINUX_MIRROR}/BaseOS/aarch64/os/Packages/python3-libxml2-2.12.5-15.el10.aarch64.rpm;name=aarch64_python3-libxml2;unpack=0"
SRC_URI[aarch64_python3-libxml2.sha256sum] = "992c2fac15a9cef23522a15595469f38a67c993df03ad417b511cb673c6c9ac3"

RDEPENDS:libxml2 = " \
 glibc \
 xz-libs \
 zlib-ng-compat \
 "
RDEPENDS:libxml2-devel = " \
 bash \
 cmake-filesystem \
 libxml2 \
 pkgconf-pkg-config \
 xz-devel \
 zlib-ng-compat-devel \
 "
RDEPENDS:libxml2-static = " \
 "
RDEPENDS:python3-libxml2 = " \
 glibc \
 libxml2 \
 python3 \
 "
