# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "lorax-templates-almalinux"
PV = "10.0"
PR = "56.el10_0.alma.2"
PACKAGES = " \
 lorax-templates-almalinux \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/lorax-templates-almalinux-10.0-56.el10_0.alma.2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "83d27a3e9b66828d1e2b790bf962aefd80955b0c998f413606a9a5d7a547a768"

URI_x86_64_v2_lorax-templates-almalinux = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/lorax-templates-almalinux-10.0-56.el10_0.alma.2.noarch.rpm;name=x86_64_v2_lorax-templates-almalinux;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_lorax-templates-almalinux}"
SRC_URI[x86_64_v2_lorax-templates-almalinux.sha256sum] = "e6a35f3282c2ff3d3554cf0d067cf20eacbcc2f63b1da20a98506cf7f1cf9dc8"
RPROVIDES:lorax-templates-almalinux:x86_64_v2 = "virtual/lorax-templates"

URI_aarch64_lorax-templates-almalinux = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/lorax-templates-almalinux-10.0-56.el10_0.alma.2.noarch.rpm;name=aarch64_lorax-templates-almalinux;unpack=0"
SRC_URI:append = " ${URI_aarch64_lorax-templates-almalinux}"
SRC_URI[aarch64_lorax-templates-almalinux.sha256sum] = "e6a35f3282c2ff3d3554cf0d067cf20eacbcc2f63b1da20a98506cf7f1cf9dc8"
RPROVIDES:lorax-templates-almalinux:aarch64 = "virtual/lorax-templates"

RDEPENDS:lorax-templates-almalinux = " \
 lorax \
 "

PROVIDES:append:x86_64_v2 = " rpm/virtual/lorax-templates"

PROVIDES:append:aarch64 = " rpm/virtual/lorax-templates"
