# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "memstrack"
PV = "0.2.5"
PR = "6.el10"
PACKAGES = " \
 memstrack \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/memstrack-0.2.5-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "73b5d59ca5f904c8acd25412679ab90ef88529e9d359c9abbdbb6efbe77f9531"

URI_x86_64_v2_memstrack = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/memstrack-0.2.5-6.el10.x86_64_v2.rpm;name=x86_64_v2_memstrack;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_memstrack}"
SRC_URI[x86_64_v2_memstrack.sha256sum] = "b234c06d66cf10791ec04cf8b2f9cee6ab0e2fc361aeaf5d4368fd68cbb10540"

URI_aarch64_memstrack = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/memstrack-0.2.5-6.el10.aarch64.rpm;name=aarch64_memstrack;unpack=0"
SRC_URI:append = " ${URI_aarch64_memstrack}"
SRC_URI[aarch64_memstrack.sha256sum] = "bdf6b8492719bca0d6d6a74272d83da14642add353b6d2efdf14e1ab3f5854b9"

RDEPENDS:memstrack = " \
 glibc \
 ncurses-libs \
 "
