# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "opentelemetry-collector"
PV = "0.152.1"
PR = "1.el10_2"
PACKAGES = " \
 opentelemetry-collector \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/opentelemetry-collector-0.152.1-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0b4eb5efa756d59dd99e3c500180a9144ae11fdc6733cc74586ae68b2d5b77b4"

URI_x86_64_v2_opentelemetry-collector = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/opentelemetry-collector-0.152.1-1.el10_2.x86_64_v2.rpm;name=x86_64_v2_opentelemetry-collector;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_opentelemetry-collector}"
SRC_URI[x86_64_v2_opentelemetry-collector.sha256sum] = "327c8b1e895816a7310080360c68d9d13eae3611247704f2a134fe5b98d68ccb"

URI_aarch64_opentelemetry-collector = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/opentelemetry-collector-0.152.1-1.el10_2.aarch64.rpm;name=aarch64_opentelemetry-collector;unpack=0"
SRC_URI:append = " ${URI_aarch64_opentelemetry-collector}"
SRC_URI[aarch64_opentelemetry-collector.sha256sum] = "b69efdd2baa3a6de54776cb3c5209f9207e068b2bce5a6ac7c087a6fa3018cb8"

RDEPENDS:opentelemetry-collector = " \
 bash \
 glibc \
 glibc-common \
 shadow-utils \
 systemd \
 util-linux \
 "
