# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "perl-DBI"
PV = "1.643"
PR = "26.el10"
PACKAGES = " \
 perl-DBI \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/perl-DBI-1.643-26.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4d33875671c16b31ff39f81998fb66a36a2a6a0807779aadfcbabd517997c43d"

URI_x86_64_v2_perl-DBI = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/perl-DBI-1.643-26.el10.x86_64_v2.rpm;name=x86_64_v2_perl-DBI;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_perl-DBI}"
SRC_URI[x86_64_v2_perl-DBI.sha256sum] = "a4588de36cbbe4f6b1f3296d318884f29d96c21c94117c8fbbd3190710c2b396"

URI_aarch64_perl-DBI = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/perl-DBI-1.643-26.el10.aarch64.rpm;name=aarch64_perl-DBI;unpack=0"
SRC_URI:append = " ${URI_aarch64_perl-DBI}"
SRC_URI[aarch64_perl-DBI.sha256sum] = "1166b518934c21d6611cf3441a744994e0a5475b10d24e598df1cce85ef18f6e"

RDEPENDS:perl-DBI = " \
 glibc \
 perl-Carp \
 perl-DBI \
 perl-Data-Dumper \
 perl-DynaLoader \
 perl-Errno \
 perl-Exporter \
 perl-Fcntl \
 perl-File-Basename \
 perl-FileHandle \
 perl-Getopt-Long \
 perl-IO \
 perl-IPC-Open3 \
 perl-Math-BigInt \
 perl-PathTools \
 perl-Scalar-List-Utils \
 perl-Storable \
 perl-Symbol \
 perl-base \
 perl-constant \
 perl-interpreter \
 perl-libs \
 perl-vars \
 "
