# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "python-jinja2"
PV = "3.1.6"
PR = "1.el10"
PACKAGES = " \
 python3-jinja2 \
 python3-jinja2+i18n \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/python-jinja2-3.1.6-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "486602d0c183f92a749f766e9ffc8d440abe51e0d048d2d7023b786a5f54eaac"

URI_x86_64_v2_python3-jinja2 = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/python3-jinja2-3.1.6-1.el10.noarch.rpm;name=x86_64_v2_python3-jinja2;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python3-jinja2}"
SRC_URI[x86_64_v2_python3-jinja2.sha256sum] = "f7812e3509b0e77724e7920f8d466dda1cce63722d73d9aaa95e1007a95c112f"

URI_x86_64_v2_python3-jinja2+i18n = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/python3-jinja2+i18n-3.1.6-1.el10.noarch.rpm;name=x86_64_v2_python3-jinja2+i18n;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python3-jinja2+i18n}"
SRC_URI[x86_64_v2_python3-jinja2+i18n.sha256sum] = "21a36112ee97525ecbf4721d64724e8ff3ec35ac51a4d88a1e4c2ce441cc7a07"

URI_aarch64_python3-jinja2 = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/python3-jinja2-3.1.6-1.el10.noarch.rpm;name=aarch64_python3-jinja2;unpack=0"
SRC_URI:append = " ${URI_aarch64_python3-jinja2}"
SRC_URI[aarch64_python3-jinja2.sha256sum] = "f7812e3509b0e77724e7920f8d466dda1cce63722d73d9aaa95e1007a95c112f"

URI_aarch64_python3-jinja2+i18n = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/python3-jinja2+i18n-3.1.6-1.el10.noarch.rpm;name=aarch64_python3-jinja2+i18n;unpack=0"
SRC_URI:append = " ${URI_aarch64_python3-jinja2+i18n}"
SRC_URI[aarch64_python3-jinja2+i18n.sha256sum] = "21a36112ee97525ecbf4721d64724e8ff3ec35ac51a4d88a1e4c2ce441cc7a07"

RDEPENDS:python3-jinja2 = " \
 python3 \
 python3-markupsafe \
 "
RDEPENDS:python3-jinja2+i18n = " \
 python3 \
 python3-babel \
 python3-jinja2 \
 "
