# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "qt6-qtlocation"
PV = "6.9.1"
PR = "1.el10"
PACKAGES = " \
 qt6-qtlocation \
 qt6-qtlocation-devel \
 qt6-qtlocation-examples \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/qt6-qtlocation-6.9.1-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e0d3b9c31d7f72b8c100139c1f12c7d98bf1078f6d74d75ee81ccb92b08d85b8"

URI_x86_64_v2_qt6-qtlocation = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/qt6-qtlocation-6.9.1-1.el10.x86_64_v2.rpm;name=x86_64_v2_qt6-qtlocation;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_qt6-qtlocation}"
SRC_URI[x86_64_v2_qt6-qtlocation.sha256sum] = "d4f54754cdce056b5f5134ed855f23ef7b502bb3944c92254c5b8947eaa041e6"

URI_x86_64_v2_qt6-qtlocation-devel = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/qt6-qtlocation-devel-6.9.1-1.el10.x86_64_v2.rpm;name=x86_64_v2_qt6-qtlocation-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_qt6-qtlocation-devel}"
SRC_URI[x86_64_v2_qt6-qtlocation-devel.sha256sum] = "a3f7ccfd249c0a3bd57d8372bc2875f92dc6cd8cf9877ba6ecb808d800edb6cb"

URI_x86_64_v2_qt6-qtlocation-examples = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/qt6-qtlocation-examples-6.9.1-1.el10.x86_64_v2.rpm;name=x86_64_v2_qt6-qtlocation-examples;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_qt6-qtlocation-examples}"
SRC_URI[x86_64_v2_qt6-qtlocation-examples.sha256sum] = "44fe9bba57a300973bcc0b9be90fae2dd05878444411ab82e259384a2c0276e3"

URI_aarch64_qt6-qtlocation = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/qt6-qtlocation-6.9.1-1.el10.aarch64.rpm;name=aarch64_qt6-qtlocation;unpack=0"
SRC_URI:append = " ${URI_aarch64_qt6-qtlocation}"
SRC_URI[aarch64_qt6-qtlocation.sha256sum] = "21d3f979e0e6b715142c1faceeb2ac667e9ec1bee4be3d09120e42cde6fe577c"

URI_aarch64_qt6-qtlocation-devel = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/qt6-qtlocation-devel-6.9.1-1.el10.aarch64.rpm;name=aarch64_qt6-qtlocation-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_qt6-qtlocation-devel}"
SRC_URI[aarch64_qt6-qtlocation-devel.sha256sum] = "1aaddcd50b3eb030ae197cd93d9e02f7c0d95d29269e8e915e2d64b1438b09ab"

URI_aarch64_qt6-qtlocation-examples = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/qt6-qtlocation-examples-6.9.1-1.el10.aarch64.rpm;name=aarch64_qt6-qtlocation-examples;unpack=0"
SRC_URI:append = " ${URI_aarch64_qt6-qtlocation-examples}"
SRC_URI[aarch64_qt6-qtlocation-examples.sha256sum] = "56c5ca969cb601d25f973cf4e0a67aaa6dabf72938fab64470bdcdd9b53629b1"

RDEPENDS:qt6-qtlocation = " \
 glibc \
 libstdc++ \
 qt6-qtbase \
 qt6-qtbase-gui \
 qt6-qtdeclarative \
 qt6-qtpositioning \
 "
RDEPENDS:qt6-qtlocation-devel = " \
 cmake-filesystem \
 pkgconf-pkg-config \
 qt6-qtbase-devel \
 qt6-qtdeclarative-devel \
 qt6-qtlocation \
 qt6-qtpositioning-devel \
 "
RDEPENDS:qt6-qtlocation-examples = " \
 glibc \
 libgcc \
 libstdc++ \
 qt6-qtbase \
 qt6-qtbase-gui \
 qt6-qtdeclarative \
 qt6-qtlocation \
 qt6-qtpositioning \
 "
