# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "tomcat"
PE = "1"
PV = "10.1.49"
PR = "3.el10.alma.1"
PACKAGES = " \
 tomcat \
 tomcat-admin-webapps \
 tomcat-docs-webapp \
 tomcat-el-5.0-api \
 tomcat-jsp-3.1-api \
 tomcat-lib \
 tomcat-servlet-6.0-api \
 tomcat-webapps \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/AppStream/Source/Packages/tomcat-10.1.49-3.el10.alma.1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7c36b52b2a808dd81af35eba5c0628e55a099e2efcc012552ebf6cb8499e68b9"

URI_x86_64_v2_tomcat = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/tomcat-10.1.49-3.el10.alma.1.noarch.rpm;name=x86_64_v2_tomcat;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_tomcat}"
SRC_URI[x86_64_v2_tomcat.sha256sum] = "51578c11bfc0cf82e3f3c4e8a6fb1695b568e272c3df8b3d74a68a6dbbd355cc"

URI_x86_64_v2_tomcat-admin-webapps = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/tomcat-admin-webapps-10.1.49-3.el10.alma.1.noarch.rpm;name=x86_64_v2_tomcat-admin-webapps;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_tomcat-admin-webapps}"
SRC_URI[x86_64_v2_tomcat-admin-webapps.sha256sum] = "a28189d391c07c607fc438902abea0f651deb05fe2fa7e7b9bdb998ed33e45cd"

URI_x86_64_v2_tomcat-docs-webapp = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/tomcat-docs-webapp-10.1.49-3.el10.alma.1.noarch.rpm;name=x86_64_v2_tomcat-docs-webapp;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_tomcat-docs-webapp}"
SRC_URI[x86_64_v2_tomcat-docs-webapp.sha256sum] = "1d745aafc2ca8eaafca598080a71486dc613ee5935494b1d8807b519e49326e9"

URI_x86_64_v2_tomcat-el-5.0-api = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/tomcat-el-5.0-api-10.1.49-3.el10.alma.1.noarch.rpm;name=x86_64_v2_tomcat-el-5.0-api;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_tomcat-el-5.0-api}"
SRC_URI[x86_64_v2_tomcat-el-5.0-api.sha256sum] = "b73959fd105545a47b732104df77b38fa964f05b5cabd6525f8adeb5846f938a"

URI_x86_64_v2_tomcat-jsp-3.1-api = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/tomcat-jsp-3.1-api-10.1.49-3.el10.alma.1.noarch.rpm;name=x86_64_v2_tomcat-jsp-3.1-api;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_tomcat-jsp-3.1-api}"
SRC_URI[x86_64_v2_tomcat-jsp-3.1-api.sha256sum] = "11511fe5fed2a6a96f525af9ec8979fbbb585e8108347bdcf9756f5710a39776"

URI_x86_64_v2_tomcat-lib = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/tomcat-lib-10.1.49-3.el10.alma.1.noarch.rpm;name=x86_64_v2_tomcat-lib;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_tomcat-lib}"
SRC_URI[x86_64_v2_tomcat-lib.sha256sum] = "36081f3acb171bf6174e675ff8b4246d2cb8b856fa888cf98a34a4cec423ab21"
RPROVIDES:tomcat-lib:x86_64_v2 = "virtual/mvn_org.apache.tomcat_tomcat-catalina_ virtual/mvn_org.apache.tomcat_tomcat-catalina__ge_9.0.62 virtual/mvn_org.apache.tomcat_tomcat-coyote_ virtual/mvn_org.apache.tomcat_tomcat-coyote__ge_9.0.62 virtual/mvn_org.apache.tomcat_tomcat-juli_ virtual/mvn_org.apache.tomcat_tomcat-juli__ge_9.0.62"

URI_x86_64_v2_tomcat-servlet-6.0-api = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/tomcat-servlet-6.0-api-10.1.49-3.el10.alma.1.noarch.rpm;name=x86_64_v2_tomcat-servlet-6.0-api;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_tomcat-servlet-6.0-api}"
SRC_URI[x86_64_v2_tomcat-servlet-6.0-api.sha256sum] = "5b09b5505f8bbb76190920948d5b30a53a82670cf0ff6a0e5dfe847b57313d35"

URI_x86_64_v2_tomcat-webapps = "${ALMALINUX_MIRROR}/AppStream/x86_64_v2/os/Packages/tomcat-webapps-10.1.49-3.el10.alma.1.noarch.rpm;name=x86_64_v2_tomcat-webapps;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_tomcat-webapps}"
SRC_URI[x86_64_v2_tomcat-webapps.sha256sum] = "51da482786a9aa1f7c439f30f16a93a3ad6e06e87d305caf226bebeccae32e12"

URI_aarch64_tomcat = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/tomcat-10.1.49-3.el10.alma.1.noarch.rpm;name=aarch64_tomcat;unpack=0"
SRC_URI:append = " ${URI_aarch64_tomcat}"
SRC_URI[aarch64_tomcat.sha256sum] = "51578c11bfc0cf82e3f3c4e8a6fb1695b568e272c3df8b3d74a68a6dbbd355cc"

URI_aarch64_tomcat-admin-webapps = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/tomcat-admin-webapps-10.1.49-3.el10.alma.1.noarch.rpm;name=aarch64_tomcat-admin-webapps;unpack=0"
SRC_URI:append = " ${URI_aarch64_tomcat-admin-webapps}"
SRC_URI[aarch64_tomcat-admin-webapps.sha256sum] = "a28189d391c07c607fc438902abea0f651deb05fe2fa7e7b9bdb998ed33e45cd"

URI_aarch64_tomcat-docs-webapp = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/tomcat-docs-webapp-10.1.49-3.el10.alma.1.noarch.rpm;name=aarch64_tomcat-docs-webapp;unpack=0"
SRC_URI:append = " ${URI_aarch64_tomcat-docs-webapp}"
SRC_URI[aarch64_tomcat-docs-webapp.sha256sum] = "1d745aafc2ca8eaafca598080a71486dc613ee5935494b1d8807b519e49326e9"

URI_aarch64_tomcat-el-5.0-api = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/tomcat-el-5.0-api-10.1.49-3.el10.alma.1.noarch.rpm;name=aarch64_tomcat-el-5.0-api;unpack=0"
SRC_URI:append = " ${URI_aarch64_tomcat-el-5.0-api}"
SRC_URI[aarch64_tomcat-el-5.0-api.sha256sum] = "b73959fd105545a47b732104df77b38fa964f05b5cabd6525f8adeb5846f938a"

URI_aarch64_tomcat-jsp-3.1-api = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/tomcat-jsp-3.1-api-10.1.49-3.el10.alma.1.noarch.rpm;name=aarch64_tomcat-jsp-3.1-api;unpack=0"
SRC_URI:append = " ${URI_aarch64_tomcat-jsp-3.1-api}"
SRC_URI[aarch64_tomcat-jsp-3.1-api.sha256sum] = "11511fe5fed2a6a96f525af9ec8979fbbb585e8108347bdcf9756f5710a39776"

URI_aarch64_tomcat-lib = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/tomcat-lib-10.1.49-3.el10.alma.1.noarch.rpm;name=aarch64_tomcat-lib;unpack=0"
SRC_URI:append = " ${URI_aarch64_tomcat-lib}"
SRC_URI[aarch64_tomcat-lib.sha256sum] = "36081f3acb171bf6174e675ff8b4246d2cb8b856fa888cf98a34a4cec423ab21"
RPROVIDES:tomcat-lib:aarch64 = "virtual/mvn_org.apache.tomcat_tomcat-catalina_ virtual/mvn_org.apache.tomcat_tomcat-catalina__ge_9.0.62 virtual/mvn_org.apache.tomcat_tomcat-coyote_ virtual/mvn_org.apache.tomcat_tomcat-coyote__ge_9.0.62 virtual/mvn_org.apache.tomcat_tomcat-juli_ virtual/mvn_org.apache.tomcat_tomcat-juli__ge_9.0.62"

URI_aarch64_tomcat-servlet-6.0-api = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/tomcat-servlet-6.0-api-10.1.49-3.el10.alma.1.noarch.rpm;name=aarch64_tomcat-servlet-6.0-api;unpack=0"
SRC_URI:append = " ${URI_aarch64_tomcat-servlet-6.0-api}"
SRC_URI[aarch64_tomcat-servlet-6.0-api.sha256sum] = "5b09b5505f8bbb76190920948d5b30a53a82670cf0ff6a0e5dfe847b57313d35"

URI_aarch64_tomcat-webapps = "${ALMALINUX_MIRROR}/AppStream/aarch64/os/Packages/tomcat-webapps-10.1.49-3.el10.alma.1.noarch.rpm;name=aarch64_tomcat-webapps;unpack=0"
SRC_URI:append = " ${URI_aarch64_tomcat-webapps}"
SRC_URI[aarch64_tomcat-webapps.sha256sum] = "51da482786a9aa1f7c439f30f16a93a3ad6e06e87d305caf226bebeccae32e12"

RDEPENDS:tomcat = " \
 bash \
 javapackages-tools \
 shadow-utils \
 systemd \
 tomcat-lib \
 virtual/java-headless_or_java-25-headless \
 "
RDEPENDS:tomcat-admin-webapps = " \
 tomcat \
 "
RDEPENDS:tomcat-docs-webapp = " \
 tomcat \
 "
RDEPENDS:tomcat-el-5.0-api = " \
 javapackages-filesystem \
 "
RDEPENDS:tomcat-jsp-3.1-api = " \
 javapackages-filesystem \
 tomcat-el-5.0-api \
 tomcat-servlet-6.0-api \
 "
RDEPENDS:tomcat-lib = " \
 ecj \
 javapackages-filesystem \
 tomcat-el-5.0-api \
 tomcat-jsp-3.1-api \
 tomcat-servlet-6.0-api \
 virtual/coreutils \
 "
RDEPENDS:tomcat-servlet-6.0-api = " \
 javapackages-filesystem \
 "
RDEPENDS:tomcat-webapps = " \
 tomcat \
 "

PROVIDES:append:x86_64_v2 = " rpm/virtual/mvn_org.apache.tomcat_tomcat-catalina_ rpm/virtual/mvn_org.apache.tomcat_tomcat-catalina__ge_9.0.62 rpm/virtual/mvn_org.apache.tomcat_tomcat-coyote_ rpm/virtual/mvn_org.apache.tomcat_tomcat-coyote__ge_9.0.62 rpm/virtual/mvn_org.apache.tomcat_tomcat-juli_ rpm/virtual/mvn_org.apache.tomcat_tomcat-juli__ge_9.0.62"

PROVIDES:append:aarch64 = " rpm/virtual/mvn_org.apache.tomcat_tomcat-catalina_ rpm/virtual/mvn_org.apache.tomcat_tomcat-catalina__ge_9.0.62 rpm/virtual/mvn_org.apache.tomcat_tomcat-coyote_ rpm/virtual/mvn_org.apache.tomcat_tomcat-coyote__ge_9.0.62 rpm/virtual/mvn_org.apache.tomcat_tomcat-juli_ rpm/virtual/mvn_org.apache.tomcat_tomcat-juli__ge_9.0.62"
