# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "vala"
PV = "0.56.17"
PR = "4.el10"
PACKAGES = " \
 libvala \
 libvala-devel \
 vala \
 vala-doc \
 valadoc \
 valadoc-devel \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/CRB/Source/Packages/vala-0.56.17-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f3b174569893f761f30d41740617ac344e0777ae203d89eb459336058107e058"

URI_x86_64_v2_libvala = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/libvala-0.56.17-4.el10.x86_64_v2.rpm;name=x86_64_v2_libvala;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libvala}"
SRC_URI[x86_64_v2_libvala.sha256sum] = "de5ca65d2234d88e239954ae35406dc28028506162383dd2820b70c984a00aaa"

URI_x86_64_v2_libvala-devel = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/libvala-devel-0.56.17-4.el10.x86_64_v2.rpm;name=x86_64_v2_libvala-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libvala-devel}"
SRC_URI[x86_64_v2_libvala-devel.sha256sum] = "a9c025e2a4cc2e3340426814d15f3021b47b48f686ad5776ecdb13187354b754"

URI_x86_64_v2_vala = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/vala-0.56.17-4.el10.x86_64_v2.rpm;name=x86_64_v2_vala;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_vala}"
SRC_URI[x86_64_v2_vala.sha256sum] = "0190255f7a642b4cc612f3e874e5b8cc30755fc35c142941c729ff6ec3676be8"

URI_x86_64_v2_vala-doc = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/vala-doc-0.56.17-4.el10.noarch.rpm;name=x86_64_v2_vala-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_vala-doc}"
SRC_URI[x86_64_v2_vala-doc.sha256sum] = "7b52fc5698f067e5ca0ade2d9dd64c1f108d57e0cec9a6f13cdd34a2fd845826"

URI_x86_64_v2_valadoc = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/valadoc-0.56.17-4.el10.x86_64_v2.rpm;name=x86_64_v2_valadoc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_valadoc}"
SRC_URI[x86_64_v2_valadoc.sha256sum] = "f5bb14371fc91281de27da135e45ad10e75231b2e6416a6ff14d072a938c0e0f"

URI_x86_64_v2_valadoc-devel = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/valadoc-devel-0.56.17-4.el10.x86_64_v2.rpm;name=x86_64_v2_valadoc-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_valadoc-devel}"
SRC_URI[x86_64_v2_valadoc-devel.sha256sum] = "ad4c4a1e56af2970f2663d32bd0e9b51631d830f9cbae9bbb6b8a3f7c2c0a759"

URI_aarch64_libvala = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/libvala-0.56.17-4.el10.aarch64.rpm;name=aarch64_libvala;unpack=0"
SRC_URI:append = " ${URI_aarch64_libvala}"
SRC_URI[aarch64_libvala.sha256sum] = "65cab07fa71b714e9359ef5bfd1d562956085cb83cb8918df5720c7ab68c3d18"

URI_aarch64_libvala-devel = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/libvala-devel-0.56.17-4.el10.aarch64.rpm;name=aarch64_libvala-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_libvala-devel}"
SRC_URI[aarch64_libvala-devel.sha256sum] = "a99d2778c65e3958d899b80131faed7e803e7ef3c732f6002ce03f9593e01024"

URI_aarch64_vala = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/vala-0.56.17-4.el10.aarch64.rpm;name=aarch64_vala;unpack=0"
SRC_URI:append = " ${URI_aarch64_vala}"
SRC_URI[aarch64_vala.sha256sum] = "5f03f0063cae9fcef9c0009276a52701142c2b1cf314b35fe5426e5d14500bba"

URI_aarch64_vala-doc = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/vala-doc-0.56.17-4.el10.noarch.rpm;name=aarch64_vala-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_vala-doc}"
SRC_URI[aarch64_vala-doc.sha256sum] = "7b52fc5698f067e5ca0ade2d9dd64c1f108d57e0cec9a6f13cdd34a2fd845826"

URI_aarch64_valadoc = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/valadoc-0.56.17-4.el10.aarch64.rpm;name=aarch64_valadoc;unpack=0"
SRC_URI:append = " ${URI_aarch64_valadoc}"
SRC_URI[aarch64_valadoc.sha256sum] = "c57c3972d96d9e5029bb23f2f4a7f83873c5b9ee85d271aed36e4e9b1dbc55e0"

URI_aarch64_valadoc-devel = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/valadoc-devel-0.56.17-4.el10.aarch64.rpm;name=aarch64_valadoc-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_valadoc-devel}"
SRC_URI[aarch64_valadoc-devel.sha256sum] = "436a15c7999a3702beb67c39d165eb04fefd9828623014a9305a8a286884a828"

RDEPENDS:libvala = " \
 glib2 \
 glibc \
 libgcc \
 "
RDEPENDS:libvala-devel = " \
 glib2-devel \
 libvala \
 pkgconf-pkg-config \
 "
RDEPENDS:vala = " \
 bash \
 glib2 \
 glibc \
 gobject-introspection-devel \
 libvala \
 pkgconf-pkg-config \
 "
RDEPENDS:vala-doc = " \
 vala \
 "
RDEPENDS:valadoc = " \
 glib2 \
 glibc \
 graphviz \
 libvala \
 vala \
 "
RDEPENDS:valadoc-devel = " \
 glib2-devel \
 graphviz-devel \
 libvala-devel \
 pkgconf-pkg-config \
 valadoc \
 "
