# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "velocity"
PV = "2.3"
PR = "6.el10"
PACKAGES = " \
 velocity \
 velocity-javadoc \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/CRB/Source/Packages/velocity-2.3-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "46f13de7c5c9448d133b4bcc740f5a8c69f111a5145c6951175cf5a27ae44785"

URI_x86_64_v2_velocity = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/velocity-2.3-6.el10.noarch.rpm;name=x86_64_v2_velocity;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_velocity}"
SRC_URI[x86_64_v2_velocity.sha256sum] = "226d43c6de137b825b09891a25b6953b5d9ad2e84ffc1e5ce3624e0410d62cb9"

URI_x86_64_v2_velocity-javadoc = "${ALMALINUX_MIRROR}/CRB/x86_64_v2/os/Packages/velocity-javadoc-2.3-6.el10.noarch.rpm;name=x86_64_v2_velocity-javadoc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_velocity-javadoc}"
SRC_URI[x86_64_v2_velocity-javadoc.sha256sum] = "d68dfc633dbf3f03d7f148fb609fe96753171dd3c4f7e2f9faa64fb80eb765cf"

URI_aarch64_velocity = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/velocity-2.3-6.el10.noarch.rpm;name=aarch64_velocity;unpack=0"
SRC_URI:append = " ${URI_aarch64_velocity}"
SRC_URI[aarch64_velocity.sha256sum] = "226d43c6de137b825b09891a25b6953b5d9ad2e84ffc1e5ce3624e0410d62cb9"

URI_aarch64_velocity-javadoc = "${ALMALINUX_MIRROR}/CRB/aarch64/os/Packages/velocity-javadoc-2.3-6.el10.noarch.rpm;name=aarch64_velocity-javadoc;unpack=0"
SRC_URI:append = " ${URI_aarch64_velocity-javadoc}"
SRC_URI[aarch64_velocity-javadoc.sha256sum] = "d68dfc633dbf3f03d7f148fb609fe96753171dd3c4f7e2f9faa64fb80eb765cf"

RDEPENDS:velocity = " \
 apache-commons-io \
 apache-commons-lang3 \
 javapackages-filesystem \
 slf4j \
 "
RDEPENDS:velocity-javadoc = " \
 javapackages-filesystem \
 "
