# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "which"
PV = "2.21"
PR = "44.el10_0"
PACKAGES = " \
 which \
 "

URI_src = "${ALMALINUXSRC_MIRROR}/BaseOS/Source/Packages/which-2.21-44.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "93885f47269e48f3c5377d36a3cc21d6e307c11cb46830f755d0169f0ae834c2"

URI_x86_64_v2_which = "${ALMALINUX_MIRROR}/BaseOS/x86_64_v2/os/Packages/which-2.21-44.el10_0.x86_64_v2.rpm;name=x86_64_v2_which;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_which}"
SRC_URI[x86_64_v2_which.sha256sum] = "c52ab4496c78bfe50c977e2e0461849403dc145b9dd4aceb598027f477bebe9d"

URI_aarch64_which = "${ALMALINUX_MIRROR}/BaseOS/aarch64/os/Packages/which-2.21-44.el10_0.aarch64.rpm;name=aarch64_which;unpack=0"
SRC_URI:append = " ${URI_aarch64_which}"
SRC_URI[aarch64_which.sha256sum] = "f54bce405945abbce9a7c8b2ab947b92186acd70d871d8f401ab6c25ebc46a40"

RDEPENDS:which = " \
 glibc \
 virtual/coreutils \
 "
