# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "ansible-collection-ansible-utils"
PV = "6.0.1"
PR = "1.el10_2"
PACKAGES = " \
 ansible-collection-ansible-utils \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/a/ansible-collection-ansible-utils-6.0.1-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "cd5d900e5e7e2a0b8b7d18611712f8ce2a4c77fa369ee895bdd60bbc16f964fe"

URI_x86_64_v2_ansible-collection-ansible-utils = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ansible-collection-ansible-utils-6.0.1-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_ansible-collection-ansible-utils;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ansible-collection-ansible-utils}"
SRC_URI[x86_64_v2_ansible-collection-ansible-utils.sha256sum] = "26b6cc468dcfa8db660eada59a96e9f0043b9ec3efea7dfe0f2a4c79ba98c789"

URI_aarch64_ansible-collection-ansible-utils = "${EPEL_MIRROR}/aarch64/Packages/a/ansible-collection-ansible-utils-6.0.1-1.el10_2.noarch.rpm;name=aarch64_ansible-collection-ansible-utils;unpack=0"
SRC_URI:append = " ${URI_aarch64_ansible-collection-ansible-utils}"
SRC_URI[aarch64_ansible-collection-ansible-utils.sha256sum] = "dcbef30c075e2f6a55cb43d1ef3f44d0326e9b9cf343b991312eafff91a56a1d"

RDEPENDS:ansible-collection-ansible-utils = " \
 ansible-core \
 "
