# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "colm"
PV = "0.14.7"
PR = "10.el10_2"
PACKAGES = " \
 colm \
 colm-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/c/colm-0.14.7-10.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e5fa1c899eb92f1588052f68f2f3752513f3a85973601d471640a9aeb09a6c6a"

URI_x86_64_v2_colm = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/colm-0.14.7-10.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_colm;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_colm}"
SRC_URI[x86_64_v2_colm.sha256sum] = "be3a60426e7a294e03db6792d0d4f8b994635f5516db15d89997ef16c79ffbd8"

URI_x86_64_v2_colm-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/colm-devel-0.14.7-10.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_colm-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_colm-devel}"
SRC_URI[x86_64_v2_colm-devel.sha256sum] = "7e43525e50eb5718ab910e4656a6e0152895aac8d4e14af05de6a5cd29fec0f3"

URI_aarch64_colm = "${EPEL_MIRROR}/aarch64/Packages/c/colm-0.14.7-10.el10_2.aarch64.rpm;name=aarch64_colm;unpack=0"
SRC_URI:append = " ${URI_aarch64_colm}"
SRC_URI[aarch64_colm.sha256sum] = "c0a95c1a42d60e675768940dd17bb265597223f9d86b77dcabdc97e5b6bd04a5"

URI_aarch64_colm-devel = "${EPEL_MIRROR}/aarch64/Packages/c/colm-devel-0.14.7-10.el10_2.aarch64.rpm;name=aarch64_colm-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_colm-devel}"
SRC_URI[aarch64_colm-devel.sha256sum] = "27d2d6b2531cd904a7a34c6dff1fa3447c2b2a06b6199276b0327919b0cb4543"

RDEPENDS:colm = " \
 bash \
 glibc \
 libgcc \
 libstdc++ \
 "
RDEPENDS:colm-devel = " \
 colm \
 glibc \
 libgcc \
 libstdc++ \
 "
