# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "coturn"
PV = "4.7.0"
PR = "3.el10_0"
PACKAGES = " \
 coturn \
 coturn-client-devel \
 coturn-client-libs \
 coturn-utils \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/c/coturn-4.7.0-3.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "dbff44cacc2359659e3071367caf9ec93f28fd25f90d94694104484ab04d0529"

URI_x86_64_v2_coturn = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/coturn-4.7.0-3.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_coturn;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_coturn}"
SRC_URI[x86_64_v2_coturn.sha256sum] = "f8a3ca2098fa2e89e59e0f6e6257efc77fa150959a3c74ef21055acfdd361151"

URI_x86_64_v2_coturn-client-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/coturn-client-devel-4.7.0-3.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_coturn-client-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_coturn-client-devel}"
SRC_URI[x86_64_v2_coturn-client-devel.sha256sum] = "0966fc2bc3a28af845e375c3d94a91bd4ba92d032c39c52dff7b54adc37f5c5e"

URI_x86_64_v2_coturn-client-libs = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/coturn-client-libs-4.7.0-3.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_coturn-client-libs;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_coturn-client-libs}"
SRC_URI[x86_64_v2_coturn-client-libs.sha256sum] = "163a8362eb4a548e8f8781182f584836ddb940533f67e8e2857c7cfc9a66e470"

URI_x86_64_v2_coturn-utils = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/coturn-utils-4.7.0-3.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_coturn-utils;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_coturn-utils}"
SRC_URI[x86_64_v2_coturn-utils.sha256sum] = "340b8328b66f22238e324484de082a030cb3959de9a347cc505cee55f09ff92c"

URI_aarch64_coturn = "${EPEL_MIRROR}/aarch64/Packages/c/coturn-4.7.0-3.el10_0.aarch64.rpm;name=aarch64_coturn;unpack=0"
SRC_URI:append = " ${URI_aarch64_coturn}"
SRC_URI[aarch64_coturn.sha256sum] = "735f1e70b87794fef40908842a73bf6a6ddf4aca533fc25be4540f74e13a012b"

URI_aarch64_coturn-client-devel = "${EPEL_MIRROR}/aarch64/Packages/c/coturn-client-devel-4.7.0-3.el10_0.aarch64.rpm;name=aarch64_coturn-client-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_coturn-client-devel}"
SRC_URI[aarch64_coturn-client-devel.sha256sum] = "36be2df4c9484b06b49b2d4e46a3529317210a486a9e9ea79d8255764dd58bc1"

URI_aarch64_coturn-client-libs = "${EPEL_MIRROR}/aarch64/Packages/c/coturn-client-libs-4.7.0-3.el10_0.aarch64.rpm;name=aarch64_coturn-client-libs;unpack=0"
SRC_URI:append = " ${URI_aarch64_coturn-client-libs}"
SRC_URI[aarch64_coturn-client-libs.sha256sum] = "b031871359d3785e9acf7e7ea29b64cd68d2c42e81e7619409ebc1fd24daf125"

URI_aarch64_coturn-utils = "${EPEL_MIRROR}/aarch64/Packages/c/coturn-utils-4.7.0-3.el10_0.aarch64.rpm;name=aarch64_coturn-utils;unpack=0"
SRC_URI:append = " ${URI_aarch64_coturn-utils}"
SRC_URI[aarch64_coturn-utils.sha256sum] = "a0ec008b1c6c635b865eebd6307671c923a9a4f793823a7873dc98b2c23eb538"

RDEPENDS:coturn = " \
 bash \
 glibc \
 hiredis \
 libevent \
 libpq \
 mariadb-connector-c \
 openssl-libs \
 shadow-utils \
 sqlite-libs \
 systemd \
 systemd-libs \
 "
RDEPENDS:coturn-client-devel = " \
 "
RDEPENDS:coturn-client-libs = " \
 "
RDEPENDS:coturn-utils = " \
 glibc \
 libevent \
 openssl-libs \
 "
