# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "datamash"
PV = "1.9"
PR = "1.el10_2"
PACKAGES = " \
 datamash \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/d/datamash-1.9-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "81310b5f2d183cbb3159b36a0eedc9d2540818d05a26717aae4b16c0865ba501"

URI_x86_64_v2_datamash = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/datamash-1.9-1.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_datamash;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_datamash}"
SRC_URI[x86_64_v2_datamash.sha256sum] = "439bf6e58c4d2263dfc0a7c2d287d57cea2503020357b3dfc6f210ecc28455d6"

URI_aarch64_datamash = "${EPEL_MIRROR}/aarch64/Packages/d/datamash-1.9-1.el10_2.aarch64.rpm;name=aarch64_datamash;unpack=0"
SRC_URI:append = " ${URI_aarch64_datamash}"
SRC_URI[aarch64_datamash.sha256sum] = "ef39cfc59559443c4a58c98cf3a8a7eb3f8fddea9357e7a2435e114b7141060d"

RDEPENDS:datamash = " \
 glibc \
 "
