# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "dummy-package-canary"
PV = "2"
PR = "3.el10_1"
PACKAGES = " \
 dummy-package-canary \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/d/dummy-package-canary-2-3.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2559afa2a9ec6d04a0c75d93e0f42b5e6cafaa2ab7100cfce6288900caa65c8f"

URI_x86_64_v2_dummy-package-canary = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/dummy-package-canary-2-3.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_dummy-package-canary;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_dummy-package-canary}"
SRC_URI[x86_64_v2_dummy-package-canary.sha256sum] = "02e78fa9af2f3ca6269e145df13aeaa3b752b81e41abc33d4ad90cd18c7734b3"

URI_aarch64_dummy-package-canary = "${EPEL_MIRROR}/aarch64/Packages/d/dummy-package-canary-2-3.el10_1.noarch.rpm;name=aarch64_dummy-package-canary;unpack=0"
SRC_URI:append = " ${URI_aarch64_dummy-package-canary}"
SRC_URI[aarch64_dummy-package-canary.sha256sum] = "9a69da7918d5331c0ccaf74d9f9311aded95d363e9da070597c19d8ea3536683"

RDEPENDS:dummy-package-canary = " \
 "
