# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "eggdrop"
PV = "1.10.1"
PR = "1.el10_1"
PACKAGES = " \
 eggdrop \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/e/eggdrop-1.10.1-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "92e17dddcc8738965bd6d41312d16d6ad4dad43537cab383c37463b12473dcc3"

URI_x86_64_v2_eggdrop = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/eggdrop-1.10.1-1.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_eggdrop;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_eggdrop}"
SRC_URI[x86_64_v2_eggdrop.sha256sum] = "75c3a5b13640f329d0a29dff76219e6b8002f8be56d2f6e5ef4a8600abeb6bf0"

URI_aarch64_eggdrop = "${EPEL_MIRROR}/aarch64/Packages/e/eggdrop-1.10.1-1.el10_1.aarch64.rpm;name=aarch64_eggdrop;unpack=0"
SRC_URI:append = " ${URI_aarch64_eggdrop}"
SRC_URI[aarch64_eggdrop.sha256sum] = "d06aba6416c00d2b5ffaa4b1ea1f716bf35f97eefeb6ca4f437c6f835b57a281"

RDEPENDS:eggdrop = " \
 bash \
 glibc \
 openssl-libs \
 python3-libs \
 tcl \
 zlib-ng-compat \
 "
