# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "fast-cdr"
PV = "2.3.5"
PR = "1.el10_3"
PACKAGES = " \
 fast-cdr \
 fast-cdr-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/f/fast-cdr-2.3.5-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "23c701053b790d37ee588d7f2d1a2dc6d10bee0ca58a3e173f67730c1a5397fa"

URI_x86_64_v2_fast-cdr = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/fast-cdr-2.3.5-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_fast-cdr;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_fast-cdr}"
SRC_URI[x86_64_v2_fast-cdr.sha256sum] = "4afa3395e414a1cc3b2e85d02f8a7d531992a8fad0e495e528c877810bccfb60"

URI_x86_64_v2_fast-cdr-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/fast-cdr-devel-2.3.5-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_fast-cdr-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_fast-cdr-devel}"
SRC_URI[x86_64_v2_fast-cdr-devel.sha256sum] = "f8260fc3fd686c1c383c4e4a548c099ac664714039940adc07231a18e5140438"

URI_aarch64_fast-cdr = "${EPEL_MIRROR}/aarch64/Packages/f/fast-cdr-2.3.5-1.el10_3.aarch64.rpm;name=aarch64_fast-cdr;unpack=0"
SRC_URI:append = " ${URI_aarch64_fast-cdr}"
SRC_URI[aarch64_fast-cdr.sha256sum] = "f42f7f89e8f1603c6d371783d9d14a6640b22ee8cdd8408bd0192dd8b28169de"

URI_aarch64_fast-cdr-devel = "${EPEL_MIRROR}/aarch64/Packages/f/fast-cdr-devel-2.3.5-1.el10_3.aarch64.rpm;name=aarch64_fast-cdr-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_fast-cdr-devel}"
SRC_URI[aarch64_fast-cdr-devel.sha256sum] = "86fc69fb1ca2f8bfdfe4d5f7c75e2a8ed1d16431c4e054b7b6826910d10c22ab"

RDEPENDS:fast-cdr = " \
 glibc \
 libgcc \
 libstdc++ \
 "
RDEPENDS:fast-cdr-devel = " \
 cmake-filesystem \
 fast-cdr \
 "
