# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "ghc-aeson"
PV = "2.1.2.1"
PR = "7.el10_0"
PACKAGES = " \
 ghc-OneTuple \
 ghc-OneTuple-devel \
 ghc-OneTuple-doc \
 ghc-OneTuple-prof \
 ghc-aeson \
 ghc-aeson-devel \
 ghc-aeson-doc \
 ghc-aeson-prof \
 ghc-generically \
 ghc-generically-devel \
 ghc-generically-doc \
 ghc-generically-prof \
 ghc-indexed-traversable-instances \
 ghc-indexed-traversable-instances-devel \
 ghc-indexed-traversable-instances-doc \
 ghc-indexed-traversable-instances-prof \
 ghc-semialign \
 ghc-semialign-devel \
 ghc-semialign-doc \
 ghc-semialign-prof \
 ghc-witherable \
 ghc-witherable-devel \
 ghc-witherable-doc \
 ghc-witherable-prof \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/ghc-aeson-2.1.2.1-7.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c6256c0af6ad420c7c07095b9ef192c0815ee518e512ebdccd123c27738bb23b"

URI_x86_64_v2_ghc-OneTuple = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-OneTuple-0.4.2-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-OneTuple;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-OneTuple}"
SRC_URI[x86_64_v2_ghc-OneTuple.sha256sum] = "071b77e844826f4c179500566e99e162a99b2c2d3d6a42a1711536027cee67b3"

URI_x86_64_v2_ghc-OneTuple-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-OneTuple-devel-0.4.2-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-OneTuple-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-OneTuple-devel}"
SRC_URI[x86_64_v2_ghc-OneTuple-devel.sha256sum] = "6e9ddf6d010205469b25da7798fcb3eeb36b317b4449ffac2655542f426d5697"

URI_x86_64_v2_ghc-OneTuple-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-OneTuple-doc-0.4.2-7.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_ghc-OneTuple-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-OneTuple-doc}"
SRC_URI[x86_64_v2_ghc-OneTuple-doc.sha256sum] = "50285f3b256d481c2da1058badca768a47863a4551f9d8643f210ec855d43579"

URI_x86_64_v2_ghc-OneTuple-prof = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-OneTuple-prof-0.4.2-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-OneTuple-prof;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-OneTuple-prof}"
SRC_URI[x86_64_v2_ghc-OneTuple-prof.sha256sum] = "42ccfb138e45b2dd1791460bec9ee418f351513d4eefd1e1e36ddec35c72fde2"

URI_x86_64_v2_ghc-aeson = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-aeson-2.1.2.1-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-aeson;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-aeson}"
SRC_URI[x86_64_v2_ghc-aeson.sha256sum] = "1e9d164c5d902341381ea55f8e7bbfba186520edc5c35b02d91e6131940ef3a8"

URI_x86_64_v2_ghc-aeson-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-aeson-devel-2.1.2.1-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-aeson-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-aeson-devel}"
SRC_URI[x86_64_v2_ghc-aeson-devel.sha256sum] = "2d9098c760d6fe747c0d7d89a8c3e17a55b395b29effb6743a4d29b1a6a6ff48"

URI_x86_64_v2_ghc-aeson-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-aeson-doc-2.1.2.1-7.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_ghc-aeson-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-aeson-doc}"
SRC_URI[x86_64_v2_ghc-aeson-doc.sha256sum] = "8870d2a7af96c671ec8fd3bab95e3350232be5eeb38baa8828700648175f7eb8"

URI_x86_64_v2_ghc-aeson-prof = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-aeson-prof-2.1.2.1-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-aeson-prof;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-aeson-prof}"
SRC_URI[x86_64_v2_ghc-aeson-prof.sha256sum] = "dd0c60539f53e55a1a858b0ee3b3f4e652a84f093e03ec23294bfcc75edb7f68"

URI_x86_64_v2_ghc-generically = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-generically-0.1.1-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-generically;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-generically}"
SRC_URI[x86_64_v2_ghc-generically.sha256sum] = "10aa8973873c0ed0cfb1a28f5c48e71287867c963794e891447ecc83151fc486"

URI_x86_64_v2_ghc-generically-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-generically-devel-0.1.1-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-generically-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-generically-devel}"
SRC_URI[x86_64_v2_ghc-generically-devel.sha256sum] = "029514701fcac57ae2aa5296b6e9e2820873f2fde518edff7ba378414d23d1cc"

URI_x86_64_v2_ghc-generically-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-generically-doc-0.1.1-7.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_ghc-generically-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-generically-doc}"
SRC_URI[x86_64_v2_ghc-generically-doc.sha256sum] = "34908f3c15e90082559cf867ef6e1c466d1bbcbd4a3acd2e379a70378ed17220"

URI_x86_64_v2_ghc-generically-prof = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-generically-prof-0.1.1-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-generically-prof;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-generically-prof}"
SRC_URI[x86_64_v2_ghc-generically-prof.sha256sum] = "ce1f7061c977a10d24880fb3742c005c37aaacd15767caf979f828b8d9883acd"

URI_x86_64_v2_ghc-indexed-traversable-instances = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-indexed-traversable-instances-0.1.2-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-indexed-traversable-instances;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-indexed-traversable-instances}"
SRC_URI[x86_64_v2_ghc-indexed-traversable-instances.sha256sum] = "a28f08c31b0ca844d8afc043dec7c21ed6cd05cbebf0d78b3f7a2d86f22ec181"

URI_x86_64_v2_ghc-indexed-traversable-instances-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-indexed-traversable-instances-devel-0.1.2-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-indexed-traversable-instances-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-indexed-traversable-instances-devel}"
SRC_URI[x86_64_v2_ghc-indexed-traversable-instances-devel.sha256sum] = "dd9c2f8da017f2d2b26d66133d8e5db94f231c59533dbf7dca24341702c1113d"

URI_x86_64_v2_ghc-indexed-traversable-instances-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-indexed-traversable-instances-doc-0.1.2-7.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_ghc-indexed-traversable-instances-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-indexed-traversable-instances-doc}"
SRC_URI[x86_64_v2_ghc-indexed-traversable-instances-doc.sha256sum] = "7b448750f323c3411ae0355e73196e84743abdeddfeae121d96af4256bfb07db"

URI_x86_64_v2_ghc-indexed-traversable-instances-prof = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-indexed-traversable-instances-prof-0.1.2-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-indexed-traversable-instances-prof;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-indexed-traversable-instances-prof}"
SRC_URI[x86_64_v2_ghc-indexed-traversable-instances-prof.sha256sum] = "549c64998f9ba6c8bc5f98e866b3da3744b0232ba11567834f9f15358011f22f"

URI_x86_64_v2_ghc-semialign = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-semialign-1.3.1-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-semialign;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-semialign}"
SRC_URI[x86_64_v2_ghc-semialign.sha256sum] = "57b86d209622a020609802e9a1791068a3b3c57f6ff30b6c7ddd79f5be160845"

URI_x86_64_v2_ghc-semialign-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-semialign-devel-1.3.1-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-semialign-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-semialign-devel}"
SRC_URI[x86_64_v2_ghc-semialign-devel.sha256sum] = "46919e164cb1f40728dc4673b6f7bfbe7bd14608c5cf011431784b8b56aebfd0"

URI_x86_64_v2_ghc-semialign-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-semialign-doc-1.3.1-7.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_ghc-semialign-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-semialign-doc}"
SRC_URI[x86_64_v2_ghc-semialign-doc.sha256sum] = "5cfcb6bac230f25e063fda0a1c9d1942246b600af6f68c3233d5defbcf1ecfaf"

URI_x86_64_v2_ghc-semialign-prof = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-semialign-prof-1.3.1-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-semialign-prof;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-semialign-prof}"
SRC_URI[x86_64_v2_ghc-semialign-prof.sha256sum] = "3c43c25394c683fe8d691239b8cbe8b99d5807aa4c9d573fc5055a3fb0bd524d"

URI_x86_64_v2_ghc-witherable = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-witherable-0.4.2-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-witherable;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-witherable}"
SRC_URI[x86_64_v2_ghc-witherable.sha256sum] = "4982ad301a3343c4718ce14dcb91a27577847fdbbcd38230d86a75f574c89f32"

URI_x86_64_v2_ghc-witherable-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-witherable-devel-0.4.2-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-witherable-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-witherable-devel}"
SRC_URI[x86_64_v2_ghc-witherable-devel.sha256sum] = "230ae747fa20b716f26fc0e45f28142c1eac5b97f914eb6979bb999b1013cdc5"

URI_x86_64_v2_ghc-witherable-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-witherable-doc-0.4.2-7.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_ghc-witherable-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-witherable-doc}"
SRC_URI[x86_64_v2_ghc-witherable-doc.sha256sum] = "44ec80898222f0db5259d249acc6aa1b15f3d11d55cb389e0670e92ef3584d5d"

URI_x86_64_v2_ghc-witherable-prof = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-witherable-prof-0.4.2-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-witherable-prof;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-witherable-prof}"
SRC_URI[x86_64_v2_ghc-witherable-prof.sha256sum] = "9f86d5a9bce7d082ed654cd50653e5ed2f8ebc688753442334de820e66bb37c7"

URI_aarch64_ghc-OneTuple = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-OneTuple-0.4.2-7.el10_0.aarch64.rpm;name=aarch64_ghc-OneTuple;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-OneTuple}"
SRC_URI[aarch64_ghc-OneTuple.sha256sum] = "a5144886fccad5e0acbd4e5bc9f69b652aa25eb11ed8553b3b9500a57108ca89"

URI_aarch64_ghc-OneTuple-devel = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-OneTuple-devel-0.4.2-7.el10_0.aarch64.rpm;name=aarch64_ghc-OneTuple-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-OneTuple-devel}"
SRC_URI[aarch64_ghc-OneTuple-devel.sha256sum] = "cb2a7016576fb1a2b611eb8887070b244f76ee6bf074e4b4ad6cbbf686be1643"

URI_aarch64_ghc-OneTuple-doc = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-OneTuple-doc-0.4.2-7.el10_0.noarch.rpm;name=aarch64_ghc-OneTuple-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-OneTuple-doc}"
SRC_URI[aarch64_ghc-OneTuple-doc.sha256sum] = "f5b063c948094d9bda8e3480e886817cf565dbeac0f6d0e43f0b41e2cc96a81f"

URI_aarch64_ghc-OneTuple-prof = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-OneTuple-prof-0.4.2-7.el10_0.aarch64.rpm;name=aarch64_ghc-OneTuple-prof;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-OneTuple-prof}"
SRC_URI[aarch64_ghc-OneTuple-prof.sha256sum] = "6957659b16327e3ea000a1cccf1434f381f16ea448e18bd53d1c993161457391"

URI_aarch64_ghc-aeson = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-aeson-2.1.2.1-7.el10_0.aarch64.rpm;name=aarch64_ghc-aeson;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-aeson}"
SRC_URI[aarch64_ghc-aeson.sha256sum] = "862f3df1567621c20e794308febe60d4ebd51e69198175332b3545519e43c023"

URI_aarch64_ghc-aeson-devel = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-aeson-devel-2.1.2.1-7.el10_0.aarch64.rpm;name=aarch64_ghc-aeson-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-aeson-devel}"
SRC_URI[aarch64_ghc-aeson-devel.sha256sum] = "60befcaac43612800ef7b5083f8cff3d4cce9f0de33dfaa8de04a80e4ea3b1f3"

URI_aarch64_ghc-aeson-doc = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-aeson-doc-2.1.2.1-7.el10_0.noarch.rpm;name=aarch64_ghc-aeson-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-aeson-doc}"
SRC_URI[aarch64_ghc-aeson-doc.sha256sum] = "3dbf3c3c8075cbf5f796c4f2ee3bde4947750535ed792ab96817020a318950f3"

URI_aarch64_ghc-aeson-prof = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-aeson-prof-2.1.2.1-7.el10_0.aarch64.rpm;name=aarch64_ghc-aeson-prof;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-aeson-prof}"
SRC_URI[aarch64_ghc-aeson-prof.sha256sum] = "5f550be627ccb874451ca98e984635027a1edd77a891cf1ba64c8104c3ab46f2"

URI_aarch64_ghc-generically = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-generically-0.1.1-7.el10_0.aarch64.rpm;name=aarch64_ghc-generically;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-generically}"
SRC_URI[aarch64_ghc-generically.sha256sum] = "70aa222c006c4c49047f34ccadafefc1e9b3d06cda6e5b3b98b1fdf83c56ccba"

URI_aarch64_ghc-generically-devel = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-generically-devel-0.1.1-7.el10_0.aarch64.rpm;name=aarch64_ghc-generically-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-generically-devel}"
SRC_URI[aarch64_ghc-generically-devel.sha256sum] = "8fc8bd22aa9403b732a28e46e97672418375c4181340c0d7d119b870f77b6ce2"

URI_aarch64_ghc-generically-doc = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-generically-doc-0.1.1-7.el10_0.noarch.rpm;name=aarch64_ghc-generically-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-generically-doc}"
SRC_URI[aarch64_ghc-generically-doc.sha256sum] = "be145ca93f6e21169548db540b301462205800c4c740d185d2fcfac49fc14503"

URI_aarch64_ghc-generically-prof = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-generically-prof-0.1.1-7.el10_0.aarch64.rpm;name=aarch64_ghc-generically-prof;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-generically-prof}"
SRC_URI[aarch64_ghc-generically-prof.sha256sum] = "61fa8536bec8308b8b8b9bfca51d94b350057caa362713a38adf69bb87717182"

URI_aarch64_ghc-indexed-traversable-instances = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-indexed-traversable-instances-0.1.2-7.el10_0.aarch64.rpm;name=aarch64_ghc-indexed-traversable-instances;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-indexed-traversable-instances}"
SRC_URI[aarch64_ghc-indexed-traversable-instances.sha256sum] = "132de6ae695279883141958293ca31e94b7b047adc721d0974872b977987bc46"

URI_aarch64_ghc-indexed-traversable-instances-devel = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-indexed-traversable-instances-devel-0.1.2-7.el10_0.aarch64.rpm;name=aarch64_ghc-indexed-traversable-instances-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-indexed-traversable-instances-devel}"
SRC_URI[aarch64_ghc-indexed-traversable-instances-devel.sha256sum] = "5cf6e9123af4a44e8688218539e814e0be6c025005aa31fe14b9b67360f0edbe"

URI_aarch64_ghc-indexed-traversable-instances-doc = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-indexed-traversable-instances-doc-0.1.2-7.el10_0.noarch.rpm;name=aarch64_ghc-indexed-traversable-instances-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-indexed-traversable-instances-doc}"
SRC_URI[aarch64_ghc-indexed-traversable-instances-doc.sha256sum] = "ebc4fc3ba6c61c8f1ffb2516b64773066328220786ebfefe8e5f4fb424a3118a"

URI_aarch64_ghc-indexed-traversable-instances-prof = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-indexed-traversable-instances-prof-0.1.2-7.el10_0.aarch64.rpm;name=aarch64_ghc-indexed-traversable-instances-prof;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-indexed-traversable-instances-prof}"
SRC_URI[aarch64_ghc-indexed-traversable-instances-prof.sha256sum] = "3ff3ed872ab04a42ba644651e619204c5ecfc6f0f083b90fd1cc791ed2e00784"

URI_aarch64_ghc-semialign = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-semialign-1.3.1-7.el10_0.aarch64.rpm;name=aarch64_ghc-semialign;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-semialign}"
SRC_URI[aarch64_ghc-semialign.sha256sum] = "d5932a86fc75889c72bbba02a99dffa849bce58c2e6976c876b9751b79e23bdb"

URI_aarch64_ghc-semialign-devel = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-semialign-devel-1.3.1-7.el10_0.aarch64.rpm;name=aarch64_ghc-semialign-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-semialign-devel}"
SRC_URI[aarch64_ghc-semialign-devel.sha256sum] = "f42aa57a79f03c316c037905d145cce5e673d325ac9e69c9a93118791bfd80b2"

URI_aarch64_ghc-semialign-doc = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-semialign-doc-1.3.1-7.el10_0.noarch.rpm;name=aarch64_ghc-semialign-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-semialign-doc}"
SRC_URI[aarch64_ghc-semialign-doc.sha256sum] = "426a5f4353343539b081c9055ed2fc9b4f4d7189eaf51d929ba9a258ed1e5621"

URI_aarch64_ghc-semialign-prof = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-semialign-prof-1.3.1-7.el10_0.aarch64.rpm;name=aarch64_ghc-semialign-prof;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-semialign-prof}"
SRC_URI[aarch64_ghc-semialign-prof.sha256sum] = "ad56d17b70832bf8b8115bf6878541fa2d4eb68e4d8eb8e38f9ad0cef3e687d6"

URI_aarch64_ghc-witherable = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-witherable-0.4.2-7.el10_0.aarch64.rpm;name=aarch64_ghc-witherable;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-witherable}"
SRC_URI[aarch64_ghc-witherable.sha256sum] = "21207662b720a5815f427be8aa6e718e4936183e445616c2e8c120d9746d20bd"

URI_aarch64_ghc-witherable-devel = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-witherable-devel-0.4.2-7.el10_0.aarch64.rpm;name=aarch64_ghc-witherable-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-witherable-devel}"
SRC_URI[aarch64_ghc-witherable-devel.sha256sum] = "a7a3576232dcbaff4031437b914eb5fb0f826f5d93aadb0d61d8f522f431e203"

URI_aarch64_ghc-witherable-doc = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-witherable-doc-0.4.2-7.el10_0.noarch.rpm;name=aarch64_ghc-witherable-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-witherable-doc}"
SRC_URI[aarch64_ghc-witherable-doc.sha256sum] = "3193e9aa91408d01b2dde21286de495c22c2f3d78dcd1ef352dd14bd8620c63e"

URI_aarch64_ghc-witherable-prof = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-witherable-prof-0.4.2-7.el10_0.aarch64.rpm;name=aarch64_ghc-witherable-prof;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-witherable-prof}"
SRC_URI[aarch64_ghc-witherable-prof.sha256sum] = "633c8f7c6212f314e73bb840415c09dd5bce34ccc795652f53ecf6b93f120f49"

RDEPENDS:ghc-OneTuple = " \
 ghc-array \
 ghc-base \
 ghc-deepseq \
 ghc-ghc-bignum \
 ghc-ghc-boot-th \
 ghc-pretty \
 ghc-template-haskell \
 glibc \
 gmp \
 "
RDEPENDS:ghc-OneTuple-devel = " \
 ghc-OneTuple \
 ghc-base-devel \
 ghc-compiler \
 ghc-template-haskell-devel \
 "
RDEPENDS:ghc-OneTuple-doc = " \
 ghc-filesystem \
 "
RDEPENDS:ghc-OneTuple-prof = " \
 ghc-OneTuple-devel \
 ghc-base-prof \
 ghc-template-haskell-prof \
 "
RDEPENDS:ghc-aeson = " \
 ghc-OneTuple \
 ghc-QuickCheck \
 ghc-StateVar \
 ghc-array \
 ghc-assoc \
 ghc-attoparsec \
 ghc-base \
 ghc-base-compat \
 ghc-base-compat-batteries \
 ghc-base-orphans \
 ghc-bifunctors \
 ghc-binary \
 ghc-bytestring \
 ghc-comonad \
 ghc-containers \
 ghc-contravariant \
 ghc-data-fix \
 ghc-deepseq \
 ghc-distributive \
 ghc-dlist \
 ghc-exceptions \
 ghc-filepath \
 ghc-generically \
 ghc-ghc-bignum \
 ghc-ghc-boot-th \
 ghc-hashable \
 ghc-indexed-traversable \
 ghc-indexed-traversable-instances \
 ghc-integer-logarithms \
 ghc-mtl \
 ghc-os-string \
 ghc-pretty \
 ghc-primitive \
 ghc-random \
 ghc-scientific \
 ghc-semialign \
 ghc-semigroupoids \
 ghc-splitmix \
 ghc-stm \
 ghc-strict \
 ghc-tagged \
 ghc-template-haskell \
 ghc-text \
 ghc-text-short \
 ghc-th-abstraction \
 ghc-these \
 ghc-time \
 ghc-time-compat \
 ghc-transformers \
 ghc-transformers-compat \
 ghc-unix \
 ghc-unordered-containers \
 ghc-uuid-types \
 ghc-vector \
 ghc-vector-stream \
 ghc-witherable \
 glibc \
 gmp \
 "
RDEPENDS:ghc-aeson-devel = " \
 ghc-OneTuple-devel \
 ghc-QuickCheck-devel \
 ghc-aeson \
 ghc-attoparsec-devel \
 ghc-base-compat-batteries-devel \
 ghc-base-devel \
 ghc-bytestring-devel \
 ghc-compiler \
 ghc-containers-devel \
 ghc-data-fix-devel \
 ghc-deepseq-devel \
 ghc-dlist-devel \
 ghc-exceptions-devel \
 ghc-generically-devel \
 ghc-hashable-devel \
 ghc-indexed-traversable-devel \
 ghc-primitive-devel \
 ghc-scientific-devel \
 ghc-semialign-devel \
 ghc-strict-devel \
 ghc-tagged-devel \
 ghc-template-haskell-devel \
 ghc-text-devel \
 ghc-text-short-devel \
 ghc-th-abstraction-devel \
 ghc-these-devel \
 ghc-time-compat-devel \
 ghc-time-devel \
 ghc-unordered-containers-devel \
 ghc-uuid-types-devel \
 ghc-vector-devel \
 ghc-witherable-devel \
 "
RDEPENDS:ghc-aeson-doc = " \
 ghc-filesystem \
 "
RDEPENDS:ghc-aeson-prof = " \
 ghc-OneTuple-prof \
 ghc-QuickCheck-prof \
 ghc-aeson-devel \
 ghc-attoparsec-prof \
 ghc-base-compat-batteries-prof \
 ghc-base-prof \
 ghc-bytestring-prof \
 ghc-containers-prof \
 ghc-data-fix-prof \
 ghc-deepseq-prof \
 ghc-dlist-prof \
 ghc-exceptions-prof \
 ghc-generically-prof \
 ghc-hashable-prof \
 ghc-indexed-traversable-prof \
 ghc-primitive-prof \
 ghc-scientific-prof \
 ghc-semialign-prof \
 ghc-strict-prof \
 ghc-tagged-prof \
 ghc-template-haskell-prof \
 ghc-text-prof \
 ghc-text-short-prof \
 ghc-th-abstraction-prof \
 ghc-these-prof \
 ghc-time-compat-prof \
 ghc-time-prof \
 ghc-unordered-containers-prof \
 ghc-uuid-types-prof \
 ghc-vector-prof \
 ghc-witherable-prof \
 "
RDEPENDS:ghc-generically = " \
 ghc-base \
 ghc-ghc-bignum \
 glibc \
 gmp \
 "
RDEPENDS:ghc-generically-devel = " \
 ghc-base-devel \
 ghc-compiler \
 ghc-generically \
 "
RDEPENDS:ghc-generically-doc = " \
 ghc-filesystem \
 "
RDEPENDS:ghc-generically-prof = " \
 ghc-base-prof \
 ghc-generically-devel \
 "
RDEPENDS:ghc-indexed-traversable-instances = " \
 ghc-OneTuple \
 ghc-array \
 ghc-base \
 ghc-binary \
 ghc-bytestring \
 ghc-containers \
 ghc-deepseq \
 ghc-exceptions \
 ghc-filepath \
 ghc-ghc-bignum \
 ghc-ghc-boot-th \
 ghc-hashable \
 ghc-indexed-traversable \
 ghc-mtl \
 ghc-os-string \
 ghc-pretty \
 ghc-primitive \
 ghc-stm \
 ghc-tagged \
 ghc-template-haskell \
 ghc-text \
 ghc-transformers \
 ghc-unordered-containers \
 ghc-vector \
 ghc-vector-stream \
 glibc \
 gmp \
 "
RDEPENDS:ghc-indexed-traversable-instances-devel = " \
 ghc-OneTuple-devel \
 ghc-base-devel \
 ghc-compiler \
 ghc-indexed-traversable-devel \
 ghc-indexed-traversable-instances \
 ghc-tagged-devel \
 ghc-unordered-containers-devel \
 ghc-vector-devel \
 "
RDEPENDS:ghc-indexed-traversable-instances-doc = " \
 ghc-filesystem \
 "
RDEPENDS:ghc-indexed-traversable-instances-prof = " \
 ghc-OneTuple-prof \
 ghc-base-prof \
 ghc-indexed-traversable-instances-devel \
 ghc-indexed-traversable-prof \
 ghc-tagged-prof \
 ghc-unordered-containers-prof \
 ghc-vector-prof \
 "
RDEPENDS:ghc-semialign = " \
 ghc-OneTuple \
 ghc-StateVar \
 ghc-array \
 ghc-assoc \
 ghc-base \
 ghc-base-orphans \
 ghc-bifunctors \
 ghc-binary \
 ghc-bytestring \
 ghc-comonad \
 ghc-containers \
 ghc-contravariant \
 ghc-deepseq \
 ghc-distributive \
 ghc-exceptions \
 ghc-filepath \
 ghc-ghc-bignum \
 ghc-ghc-boot-th \
 ghc-hashable \
 ghc-indexed-traversable \
 ghc-indexed-traversable-instances \
 ghc-mtl \
 ghc-os-string \
 ghc-pretty \
 ghc-primitive \
 ghc-semigroupoids \
 ghc-stm \
 ghc-tagged \
 ghc-template-haskell \
 ghc-text \
 ghc-th-abstraction \
 ghc-these \
 ghc-transformers \
 ghc-transformers-compat \
 ghc-unordered-containers \
 ghc-vector \
 ghc-vector-stream \
 glibc \
 gmp \
 "
RDEPENDS:ghc-semialign-devel = " \
 ghc-base-devel \
 ghc-compiler \
 ghc-containers-devel \
 ghc-hashable-devel \
 ghc-indexed-traversable-devel \
 ghc-indexed-traversable-instances-devel \
 ghc-semialign \
 ghc-semigroupoids-devel \
 ghc-tagged-devel \
 ghc-these-devel \
 ghc-transformers-devel \
 ghc-unordered-containers-devel \
 ghc-vector-devel \
 "
RDEPENDS:ghc-semialign-doc = " \
 ghc-filesystem \
 "
RDEPENDS:ghc-semialign-prof = " \
 ghc-base-prof \
 ghc-containers-prof \
 ghc-hashable-prof \
 ghc-indexed-traversable-instances-prof \
 ghc-indexed-traversable-prof \
 ghc-semialign-devel \
 ghc-semigroupoids-prof \
 ghc-tagged-prof \
 ghc-these-prof \
 ghc-transformers-prof \
 ghc-unordered-containers-prof \
 ghc-vector-prof \
 "
RDEPENDS:ghc-witherable = " \
 ghc-OneTuple \
 ghc-array \
 ghc-base \
 ghc-base-orphans \
 ghc-binary \
 ghc-bytestring \
 ghc-containers \
 ghc-deepseq \
 ghc-exceptions \
 ghc-filepath \
 ghc-ghc-bignum \
 ghc-ghc-boot-th \
 ghc-hashable \
 ghc-indexed-traversable \
 ghc-indexed-traversable-instances \
 ghc-mtl \
 ghc-os-string \
 ghc-pretty \
 ghc-primitive \
 ghc-stm \
 ghc-tagged \
 ghc-template-haskell \
 ghc-text \
 ghc-transformers \
 ghc-unordered-containers \
 ghc-vector \
 ghc-vector-stream \
 glibc \
 gmp \
 "
RDEPENDS:ghc-witherable-devel = " \
 ghc-base-devel \
 ghc-base-orphans-devel \
 ghc-compiler \
 ghc-containers-devel \
 ghc-hashable-devel \
 ghc-indexed-traversable-devel \
 ghc-indexed-traversable-instances-devel \
 ghc-transformers-devel \
 ghc-unordered-containers-devel \
 ghc-vector-devel \
 ghc-witherable \
 "
RDEPENDS:ghc-witherable-doc = " \
 ghc-filesystem \
 "
RDEPENDS:ghc-witherable-prof = " \
 ghc-base-orphans-prof \
 ghc-base-prof \
 ghc-containers-prof \
 ghc-hashable-prof \
 ghc-indexed-traversable-instances-prof \
 ghc-indexed-traversable-prof \
 ghc-transformers-prof \
 ghc-unordered-containers-prof \
 ghc-vector-prof \
 ghc-witherable-devel \
 "
