# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "ghc-pretty-show"
PV = "1.10"
PR = "20.el10_0"
PACKAGES = " \
 ghc-pretty-show \
 ghc-pretty-show-devel \
 ghc-pretty-show-doc \
 ghc-pretty-show-prof \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/ghc-pretty-show-1.10-20.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "48dc1ecd9cc7993e09a86f53377469c26696f97e470ddb428c7817bf9e20cd2a"

URI_x86_64_v2_ghc-pretty-show = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-pretty-show-1.10-20.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-pretty-show;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-pretty-show}"
SRC_URI[x86_64_v2_ghc-pretty-show.sha256sum] = "0321e6598bc94809b61a56a8ff329e42b944213de83ecd4def097cbd41af6d15"

URI_x86_64_v2_ghc-pretty-show-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-pretty-show-devel-1.10-20.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-pretty-show-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-pretty-show-devel}"
SRC_URI[x86_64_v2_ghc-pretty-show-devel.sha256sum] = "5291ce1996eac95baec539ea951d4e82a51a08d8116e80fb39b10236f3cf80ce"

URI_x86_64_v2_ghc-pretty-show-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-pretty-show-doc-1.10-20.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_ghc-pretty-show-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-pretty-show-doc}"
SRC_URI[x86_64_v2_ghc-pretty-show-doc.sha256sum] = "ec9ac03d64759c1de436c4e975771167e7ef3e3afd86a4010dbf5e135ac93b65"

URI_x86_64_v2_ghc-pretty-show-prof = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-pretty-show-prof-1.10-20.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-pretty-show-prof;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-pretty-show-prof}"
SRC_URI[x86_64_v2_ghc-pretty-show-prof.sha256sum] = "90c5bb79989e2df453661149782026daf283fe2276ac582fed813fe96a24b2ea"

URI_aarch64_ghc-pretty-show = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-pretty-show-1.10-20.el10_0.aarch64.rpm;name=aarch64_ghc-pretty-show;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-pretty-show}"
SRC_URI[aarch64_ghc-pretty-show.sha256sum] = "576bc03d07937e3d1e41b33ead05a412993cb1efffcab4c40bdb18d3b5172073"

URI_aarch64_ghc-pretty-show-devel = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-pretty-show-devel-1.10-20.el10_0.aarch64.rpm;name=aarch64_ghc-pretty-show-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-pretty-show-devel}"
SRC_URI[aarch64_ghc-pretty-show-devel.sha256sum] = "7f75ec5639592d24a8c4be11d682c5003224ae551db2c2f2905f1887f69b26fd"

URI_aarch64_ghc-pretty-show-doc = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-pretty-show-doc-1.10-20.el10_0.noarch.rpm;name=aarch64_ghc-pretty-show-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-pretty-show-doc}"
SRC_URI[aarch64_ghc-pretty-show-doc.sha256sum] = "e5e084544e46a4d6c395ab08f7a917d5015a27d36896397c3a32ca0b9fd5cd1a"

URI_aarch64_ghc-pretty-show-prof = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-pretty-show-prof-1.10-20.el10_0.aarch64.rpm;name=aarch64_ghc-pretty-show-prof;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-pretty-show-prof}"
SRC_URI[aarch64_ghc-pretty-show-prof.sha256sum] = "38b00d0911d60b81c188b8951e0318dbfe1521a0ba54eb8d87ddceecafea9403"

RDEPENDS:ghc-pretty-show = " \
 ghc-array \
 ghc-base \
 ghc-binary \
 ghc-bytestring \
 ghc-containers \
 ghc-deepseq \
 ghc-exceptions \
 ghc-filepath \
 ghc-ghc-bignum \
 ghc-ghc-boot-th \
 ghc-haskell-lexer \
 ghc-mtl \
 ghc-pretty \
 ghc-stm \
 ghc-template-haskell \
 ghc-text \
 ghc-transformers \
 glibc \
 gmp \
 "
RDEPENDS:ghc-pretty-show-devel = " \
 ghc-array-devel \
 ghc-base-devel \
 ghc-compiler \
 ghc-filepath-devel \
 ghc-haskell-lexer-devel \
 ghc-pretty-devel \
 ghc-pretty-show \
 ghc-text-devel \
 glibc \
 gmp \
 libffi \
 "
RDEPENDS:ghc-pretty-show-doc = " \
 ghc-filesystem \
 "
RDEPENDS:ghc-pretty-show-prof = " \
 ghc-array-prof \
 ghc-base-prof \
 ghc-filepath-prof \
 ghc-haskell-lexer-prof \
 ghc-pretty-prof \
 ghc-pretty-show-devel \
 ghc-text-prof \
 "
