# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "ghc-cmdargs"
PV = "0.10.22"
PR = "4.el10_0"
PACKAGES = " \
 ghc-cmdargs \
 ghc-cmdargs-devel \
 ghc-cmdargs-doc \
 ghc-cmdargs-prof \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/ghc-cmdargs-0.10.22-4.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "62c66370810248e78b075763bcc69e5285aabcab7596f3a90015be2b2dfa4588"

URI_x86_64_v2_ghc-cmdargs = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-cmdargs-0.10.22-4.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-cmdargs;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-cmdargs}"
SRC_URI[x86_64_v2_ghc-cmdargs.sha256sum] = "19b9a7defd0a01e25e0d7832aea10992f75e4e8c8592dc1288e4ba8fac070dc2"

URI_x86_64_v2_ghc-cmdargs-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-cmdargs-devel-0.10.22-4.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-cmdargs-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-cmdargs-devel}"
SRC_URI[x86_64_v2_ghc-cmdargs-devel.sha256sum] = "38d0a3d6b4bf5511d383f6943334c9f1ac75dc05be8fa4edfbb095513532cfc2"

URI_x86_64_v2_ghc-cmdargs-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-cmdargs-doc-0.10.22-4.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_ghc-cmdargs-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-cmdargs-doc}"
SRC_URI[x86_64_v2_ghc-cmdargs-doc.sha256sum] = "3c4f1848bd1a23cf71a9cb3bca28948d81fb269f81600a304ac6a2b680c5d39c"

URI_x86_64_v2_ghc-cmdargs-prof = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-cmdargs-prof-0.10.22-4.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-cmdargs-prof;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-cmdargs-prof}"
SRC_URI[x86_64_v2_ghc-cmdargs-prof.sha256sum] = "6f3488d0abdf38f59488f6c43c7896e684787212a547f9b1fdab5ee44d30ec65"

URI_aarch64_ghc-cmdargs = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-cmdargs-0.10.22-4.el10_0.aarch64.rpm;name=aarch64_ghc-cmdargs;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-cmdargs}"
SRC_URI[aarch64_ghc-cmdargs.sha256sum] = "b4e7c5a0c67f526d1a473e448dffe9e3266462341e055712d5c2f9f041e93cf0"

URI_aarch64_ghc-cmdargs-devel = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-cmdargs-devel-0.10.22-4.el10_0.aarch64.rpm;name=aarch64_ghc-cmdargs-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-cmdargs-devel}"
SRC_URI[aarch64_ghc-cmdargs-devel.sha256sum] = "8160d905f8eb8e1a0c472af3b18f7eeaa7c6402637e1c9932006758bedbf6992"

URI_aarch64_ghc-cmdargs-doc = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-cmdargs-doc-0.10.22-4.el10_0.noarch.rpm;name=aarch64_ghc-cmdargs-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-cmdargs-doc}"
SRC_URI[aarch64_ghc-cmdargs-doc.sha256sum] = "7fbf52da8cb515eab8ad0fe45a338f050bdd2724df1752c01f7c1c6379d5053f"

URI_aarch64_ghc-cmdargs-prof = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-cmdargs-prof-0.10.22-4.el10_0.aarch64.rpm;name=aarch64_ghc-cmdargs-prof;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-cmdargs-prof}"
SRC_URI[aarch64_ghc-cmdargs-prof.sha256sum] = "42a34cc3ee0f4bae1acd7206041afc4eced6f6e4517b1db375af42bfb811c6d4"

RDEPENDS:ghc-cmdargs = " \
 ghc-array \
 ghc-base \
 ghc-bytestring \
 ghc-deepseq \
 ghc-directory \
 ghc-exceptions \
 ghc-filepath \
 ghc-ghc-bignum \
 ghc-ghc-boot-th \
 ghc-mtl \
 ghc-pretty \
 ghc-process \
 ghc-stm \
 ghc-template-haskell \
 ghc-time \
 ghc-transformers \
 ghc-unix \
 glibc \
 gmp \
 "
RDEPENDS:ghc-cmdargs-devel = " \
 ghc-base-devel \
 ghc-cmdargs \
 ghc-compiler \
 ghc-filepath-devel \
 ghc-process-devel \
 ghc-template-haskell-devel \
 ghc-transformers-devel \
 "
RDEPENDS:ghc-cmdargs-doc = " \
 ghc-filesystem \
 "
RDEPENDS:ghc-cmdargs-prof = " \
 ghc-base-prof \
 ghc-cmdargs-devel \
 ghc-filepath-prof \
 ghc-process-prof \
 ghc-template-haskell-prof \
 ghc-transformers-prof \
 "
