# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "ghc-cborg"
PV = "0.2.10.0"
PR = "1.el10_0"
PACKAGES = " \
 ghc-cborg \
 ghc-cborg-devel \
 ghc-cborg-doc \
 ghc-cborg-prof \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/ghc-cborg-0.2.10.0-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "181564c8a22af43165c6484540ef2a9dfb140619e19a03654761586a922ba341"

URI_x86_64_v2_ghc-cborg = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-cborg-0.2.10.0-1.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-cborg;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-cborg}"
SRC_URI[x86_64_v2_ghc-cborg.sha256sum] = "3453c8be65814303142ba869634493624374b29db9161b10430a5bd6889b0ec6"

URI_x86_64_v2_ghc-cborg-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-cborg-devel-0.2.10.0-1.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-cborg-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-cborg-devel}"
SRC_URI[x86_64_v2_ghc-cborg-devel.sha256sum] = "04fcc18b6e8d715b8d864c7ac2ba76cd1ec120d2b5565407355ceb1b822f0f54"

URI_x86_64_v2_ghc-cborg-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-cborg-doc-0.2.10.0-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_ghc-cborg-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-cborg-doc}"
SRC_URI[x86_64_v2_ghc-cborg-doc.sha256sum] = "9d565999c6bbdb051bda4279651bfbdea0a5a9b24d8b46a9c1782c0930c707a8"

URI_x86_64_v2_ghc-cborg-prof = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/ghc-cborg-prof-0.2.10.0-1.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_ghc-cborg-prof;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_ghc-cborg-prof}"
SRC_URI[x86_64_v2_ghc-cborg-prof.sha256sum] = "1a485ad61a7b60188ef688d6a773c5bb58c0918d1680507913e86455144e99b2"

URI_aarch64_ghc-cborg = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-cborg-0.2.10.0-1.el10_0.aarch64.rpm;name=aarch64_ghc-cborg;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-cborg}"
SRC_URI[aarch64_ghc-cborg.sha256sum] = "4ae22c900b3513f638c013f9351e96bad773d20735a205d19e6c07df5e9e7f10"

URI_aarch64_ghc-cborg-devel = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-cborg-devel-0.2.10.0-1.el10_0.aarch64.rpm;name=aarch64_ghc-cborg-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-cborg-devel}"
SRC_URI[aarch64_ghc-cborg-devel.sha256sum] = "1a5369ded088c773fb7c7a46de217c944ebc793fc43944fbe531ae4699bbb3c6"

URI_aarch64_ghc-cborg-doc = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-cborg-doc-0.2.10.0-1.el10_0.noarch.rpm;name=aarch64_ghc-cborg-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-cborg-doc}"
SRC_URI[aarch64_ghc-cborg-doc.sha256sum] = "dc01b8962714f7d0805aeb26c0e495e362be522958b3fd090787bb33f04f16a9"

URI_aarch64_ghc-cborg-prof = "${EPEL_MIRROR}/aarch64/Packages/g/ghc-cborg-prof-0.2.10.0-1.el10_0.aarch64.rpm;name=aarch64_ghc-cborg-prof;unpack=0"
SRC_URI:append = " ${URI_aarch64_ghc-cborg-prof}"
SRC_URI[aarch64_ghc-cborg-prof.sha256sum] = "e8d3cf7afefa479f4d594b12e0fb392003dae32507c21ad80d982bb9db93579d"

RDEPENDS:ghc-cborg = " \
 ghc-array \
 ghc-base \
 ghc-binary \
 ghc-bytestring \
 ghc-containers \
 ghc-deepseq \
 ghc-ghc-bignum \
 ghc-ghc-boot-th \
 ghc-half \
 ghc-pretty \
 ghc-primitive \
 ghc-template-haskell \
 ghc-text \
 ghc-transformers \
 glibc \
 gmp \
 "
RDEPENDS:ghc-cborg-devel = " \
 ghc-array-devel \
 ghc-base-devel \
 ghc-bytestring-devel \
 ghc-cborg \
 ghc-compiler \
 ghc-containers-devel \
 ghc-deepseq-devel \
 ghc-ghc-bignum-devel \
 ghc-half-devel \
 ghc-primitive-devel \
 ghc-text-devel \
 "
RDEPENDS:ghc-cborg-doc = " \
 ghc-filesystem \
 "
RDEPENDS:ghc-cborg-prof = " \
 ghc-array-prof \
 ghc-base-prof \
 ghc-bytestring-prof \
 ghc-cborg-devel \
 ghc-containers-prof \
 ghc-deepseq-prof \
 ghc-ghc-bignum-prof \
 ghc-half-prof \
 ghc-primitive-prof \
 ghc-text-prof \
 "
