# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "globus-gram-job-manager-condor"
PV = "3.0"
PR = "17.el10_0"
PACKAGES = " \
 globus-gram-job-manager-condor \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/globus-gram-job-manager-condor-3.0-17.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "47333f3847a868d4978383dad77845c91340d58a5599e7503b11d0d43a2e4679"

URI_x86_64_v2_globus-gram-job-manager-condor = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/globus-gram-job-manager-condor-3.0-17.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_globus-gram-job-manager-condor;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_globus-gram-job-manager-condor}"
SRC_URI[x86_64_v2_globus-gram-job-manager-condor.sha256sum] = "1e70b9997324b65a3207257b39865ff69bc48d292c3efd51f3c6c6cf7ae99130"

URI_aarch64_globus-gram-job-manager-condor = "${EPEL_MIRROR}/aarch64/Packages/g/globus-gram-job-manager-condor-3.0-17.el10_0.noarch.rpm;name=aarch64_globus-gram-job-manager-condor;unpack=0"
SRC_URI:append = " ${URI_aarch64_globus-gram-job-manager-condor}"
SRC_URI[aarch64_globus-gram-job-manager-condor.sha256sum] = "7e7adbf1ed5ebc0c2c42753fd0b4921f6d2f37a93b473fdf1874bdf21820e6a9"

RDEPENDS:globus-gram-job-manager-condor = " \
 bash \
 globus-common \
 globus-gass-cache-program \
 globus-gatekeeper \
 globus-gram-job-manager \
 globus-gram-job-manager-scripts \
 globus-gram-protocol \
 perl-IPC-Open3 \
 perl-libs \
 "
