# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "gnuastro"
PV = "0.23"
PR = "4.el10_1"
PACKAGES = " \
 gnuastro \
 gnuastro-devel \
 gnuastro-doc \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/gnuastro-0.23-4.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ef1e0ad90d74149de91ab640489454b3da09a288c1f3a3a1c4e63558e1e9d72b"

URI_x86_64_v2_gnuastro = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/gnuastro-0.23-4.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_gnuastro;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_gnuastro}"
SRC_URI[x86_64_v2_gnuastro.sha256sum] = "bbae34966644234b4f6642d9299503fc60224a6b24391e236f2349e44593ef5c"

URI_x86_64_v2_gnuastro-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/gnuastro-devel-0.23-4.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_gnuastro-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_gnuastro-devel}"
SRC_URI[x86_64_v2_gnuastro-devel.sha256sum] = "59abd0e5c3238a3bda7aba17661510d781e7e9e35a90b114525508ec9a0fa033"

URI_x86_64_v2_gnuastro-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/gnuastro-doc-0.23-4.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_gnuastro-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_gnuastro-doc}"
SRC_URI[x86_64_v2_gnuastro-doc.sha256sum] = "9b31a3aefb415443327b98ddbfe9b928ad5dd282af4f77a92ee15b0e00a83f74"

URI_aarch64_gnuastro = "${EPEL_MIRROR}/aarch64/Packages/g/gnuastro-0.23-4.el10_1.aarch64.rpm;name=aarch64_gnuastro;unpack=0"
SRC_URI:append = " ${URI_aarch64_gnuastro}"
SRC_URI[aarch64_gnuastro.sha256sum] = "f724365920bac6964b529bf2412be19136ba8520ab4f875a8f2cd2483df5b492"

URI_aarch64_gnuastro-devel = "${EPEL_MIRROR}/aarch64/Packages/g/gnuastro-devel-0.23-4.el10_1.aarch64.rpm;name=aarch64_gnuastro-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_gnuastro-devel}"
SRC_URI[aarch64_gnuastro-devel.sha256sum] = "f6b6281be180b6739b32a0f457c282d3cb7e3f0e9b3e58e6be670452b1c9dbc0"

URI_aarch64_gnuastro-doc = "${EPEL_MIRROR}/aarch64/Packages/g/gnuastro-doc-0.23-4.el10_1.noarch.rpm;name=aarch64_gnuastro-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_gnuastro-doc}"
SRC_URI[aarch64_gnuastro-doc.sha256sum] = "29634ee58dee784cdb90f4f884ca0e6476122fa6afb58e07ef9039210127a218"

RDEPENDS:gnuastro = " \
 bash \
 cfitsio \
 glibc \
 gsl \
 libgit2 \
 libjpeg-turbo \
 libtiff \
 wcslib \
 zlib-ng-compat \
 "
RDEPENDS:gnuastro-devel = " \
 cfitsio-devel \
 gnuastro \
 gsl-devel \
 libgit2-devel \
 libjpeg-turbo-devel \
 libtiff-devel \
 pkgconf-pkg-config \
 wcslib-devel \
 "
RDEPENDS:gnuastro-doc = " \
 "
