# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "goaccess"
PV = "1.11"
PR = "1.el10_2"
PACKAGES = " \
 goaccess \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/goaccess-1.11-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "51170192f5be727be657b1493deb8968a8a386889c8bc50c7089263b29532615"

URI_x86_64_v2_goaccess = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/goaccess-1.11-1.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_goaccess;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_goaccess}"
SRC_URI[x86_64_v2_goaccess.sha256sum] = "d54c937e14b5db5b6f39d4cf4b3deda431098dcee29a41cfe498c8c3168f6ee7"

URI_aarch64_goaccess = "${EPEL_MIRROR}/aarch64/Packages/g/goaccess-1.11-1.el10_2.aarch64.rpm;name=aarch64_goaccess;unpack=0"
SRC_URI:append = " ${URI_aarch64_goaccess}"
SRC_URI[aarch64_goaccess.sha256sum] = "ca4be200f4704761c537786f30bc8badfda4faed0306a2f67381628bff4a759a"

RDEPENDS:goaccess = " \
 glibc \
 libmaxminddb \
 ncurses-libs \
 openssl-libs \
 "
