# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "golang-github-tonistiigi-archvariant"
PV = "1.0.0"
PR = "7.el10_0"
PACKAGES = " \
 golang-github-tonistiigi-archvariant \
 golang-github-tonistiigi-archvariant-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/golang-github-tonistiigi-archvariant-1.0.0-7.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2fad30f490a0cce99858b619efa3de871c4baf31d6b2ccd90e606b3ecec5d11e"

URI_x86_64_v2_golang-github-tonistiigi-archvariant = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/golang-github-tonistiigi-archvariant-1.0.0-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_golang-github-tonistiigi-archvariant;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_golang-github-tonistiigi-archvariant}"
SRC_URI[x86_64_v2_golang-github-tonistiigi-archvariant.sha256sum] = "dfb6008410f708e336b0ee081efaad58c8374c094b5841c564b730abfd80aeeb"

URI_x86_64_v2_golang-github-tonistiigi-archvariant-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/golang-github-tonistiigi-archvariant-devel-1.0.0-7.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_golang-github-tonistiigi-archvariant-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_golang-github-tonistiigi-archvariant-devel}"
SRC_URI[x86_64_v2_golang-github-tonistiigi-archvariant-devel.sha256sum] = "92bdd5bb568debb722eb40ad6144a797904fa076d48758837ce31e856b49a0bd"

URI_aarch64_golang-github-tonistiigi-archvariant = "${EPEL_MIRROR}/aarch64/Packages/g/golang-github-tonistiigi-archvariant-1.0.0-7.el10_0.aarch64.rpm;name=aarch64_golang-github-tonistiigi-archvariant;unpack=0"
SRC_URI:append = " ${URI_aarch64_golang-github-tonistiigi-archvariant}"
SRC_URI[aarch64_golang-github-tonistiigi-archvariant.sha256sum] = "d4eb3f788a04d47008324606653e21c911687227ca1f10566e88feeaf36c2fe6"

URI_aarch64_golang-github-tonistiigi-archvariant-devel = "${EPEL_MIRROR}/aarch64/Packages/g/golang-github-tonistiigi-archvariant-devel-1.0.0-7.el10_0.noarch.rpm;name=aarch64_golang-github-tonistiigi-archvariant-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_golang-github-tonistiigi-archvariant-devel}"
SRC_URI[aarch64_golang-github-tonistiigi-archvariant-devel.sha256sum] = "5fba616148a1d417dcfebc9369512969ba6882a87bce9df74110dbd55f9ef986"

RDEPENDS:golang-github-tonistiigi-archvariant = " \
 glibc \
 "
RDEPENDS:golang-github-tonistiigi-archvariant-devel = " \
 go-filesystem \
 "
