# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "golang-github-task-slim-sprig"
PV = "3.2.0"
PR = "7.20220509gitafa1e20.el10_0"
PACKAGES = " \
 golang-github-task-slim-sprig-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/golang-github-task-slim-sprig-3.2.0-7.20220509gitafa1e20.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1ed10a6fcff330afcc9e679a9e22cf70d0cd2a0de74def991c6e619712127be1"

URI_aarch64_golang-github-task-slim-sprig-devel = "${EPEL_MIRROR}/aarch64/Packages/g/golang-github-task-slim-sprig-devel-3.2.0-7.20220509gitafa1e20.el10_0.noarch.rpm;name=aarch64_golang-github-task-slim-sprig-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_golang-github-task-slim-sprig-devel}"
SRC_URI[aarch64_golang-github-task-slim-sprig-devel.sha256sum] = "0638ea5367c112177d11ca96418858df9edbb6bdd9bb95cda4e144b27e510204"

RDEPENDS:golang-github-task-slim-sprig-devel = " \
 go-filesystem \
 "
