# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "golang-sigs-k8s-structured-merge-diff"
PV = "4.2.1"
PR = "9.el10_0"
PACKAGES = " \
 compat-golang-sigs-k8s-structured-merge-diff-4-devel \
 golang-sigs-k8s-structured-merge-diff-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/golang-sigs-k8s-structured-merge-diff-4.2.1-9.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "739d6697d0ee3602b2db0a5c7c12fb755654fea6eae0fe54facca2496012d404"

URI_x86_64_v2_compat-golang-sigs-k8s-structured-merge-diff-4-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/compat-golang-sigs-k8s-structured-merge-diff-4-devel-4.2.1-9.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_compat-golang-sigs-k8s-structured-merge-diff-4-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_compat-golang-sigs-k8s-structured-merge-diff-4-devel}"
SRC_URI[x86_64_v2_compat-golang-sigs-k8s-structured-merge-diff-4-devel.sha256sum] = "fe9c1108b529bb290bd5e86fdc524af7595f41c9c760c6343b537bf988ac8414"

URI_x86_64_v2_golang-sigs-k8s-structured-merge-diff-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/golang-sigs-k8s-structured-merge-diff-devel-4.2.1-9.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_golang-sigs-k8s-structured-merge-diff-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_golang-sigs-k8s-structured-merge-diff-devel}"
SRC_URI[x86_64_v2_golang-sigs-k8s-structured-merge-diff-devel.sha256sum] = "988b7bd4e6a209822417af1b4696dd1b96485fefb44c80508ae91a24f9c2b34c"

URI_aarch64_compat-golang-sigs-k8s-structured-merge-diff-4-devel = "${EPEL_MIRROR}/aarch64/Packages/c/compat-golang-sigs-k8s-structured-merge-diff-4-devel-4.2.1-9.el10_0.noarch.rpm;name=aarch64_compat-golang-sigs-k8s-structured-merge-diff-4-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_compat-golang-sigs-k8s-structured-merge-diff-4-devel}"
SRC_URI[aarch64_compat-golang-sigs-k8s-structured-merge-diff-4-devel.sha256sum] = "ef653e748c00a557c2cb9b29e8dbde5ad4f0fd0874fce32e3dc0be737cf23ec9"

URI_aarch64_golang-sigs-k8s-structured-merge-diff-devel = "${EPEL_MIRROR}/aarch64/Packages/g/golang-sigs-k8s-structured-merge-diff-devel-4.2.1-9.el10_0.noarch.rpm;name=aarch64_golang-sigs-k8s-structured-merge-diff-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_golang-sigs-k8s-structured-merge-diff-devel}"
SRC_URI[aarch64_golang-sigs-k8s-structured-merge-diff-devel.sha256sum] = "1279b1586e77324b7cd4ea9b5c9cd7d5057eef25c5325961926612f2208bcb60"

RDEPENDS:compat-golang-sigs-k8s-structured-merge-diff-4-devel = " \
 go-filesystem \
 golang-sigs-k8s-structured-merge-diff-devel \
 "
RDEPENDS:golang-sigs-k8s-structured-merge-diff-devel = " \
 go-filesystem \
 golang-github-json-iterator-devel \
 golang-gopkg-yaml-2-devel \
 "
