# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "golang-gotest"
PV = "3.5.1"
PR = "2.el10_0"
PACKAGES = " \
 compat-golang-gotest3-devel \
 golang-gotest-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/g/golang-gotest-3.5.1-2.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0f7ebe321f7ae5f16e7ce7826de736d33474ef5a41d41b86517d464cec7f6a2e"

URI_x86_64_v2_compat-golang-gotest3-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/compat-golang-gotest3-devel-3.5.1-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_compat-golang-gotest3-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_compat-golang-gotest3-devel}"
SRC_URI[x86_64_v2_compat-golang-gotest3-devel.sha256sum] = "535ea0713fd9902b98e66217781f7bbde1fbe5dec20804c44258d0a5e0a654be"

URI_x86_64_v2_golang-gotest-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/golang-gotest-devel-3.5.1-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_golang-gotest-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_golang-gotest-devel}"
SRC_URI[x86_64_v2_golang-gotest-devel.sha256sum] = "7c76fb444500449245d1bd8091e4a949b92609eae79ef1e8c3fc112e38babaf2"

URI_aarch64_compat-golang-gotest3-devel = "${EPEL_MIRROR}/aarch64/Packages/c/compat-golang-gotest3-devel-3.5.1-2.el10_0.noarch.rpm;name=aarch64_compat-golang-gotest3-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_compat-golang-gotest3-devel}"
SRC_URI[aarch64_compat-golang-gotest3-devel.sha256sum] = "397fe07586ab53d041e88ace24525ebf528bc94fbfce29108ebeb3ea8f1823f5"

URI_aarch64_golang-gotest-devel = "${EPEL_MIRROR}/aarch64/Packages/g/golang-gotest-devel-3.5.1-2.el10_0.noarch.rpm;name=aarch64_golang-gotest-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_golang-gotest-devel}"
SRC_URI[aarch64_golang-gotest-devel.sha256sum] = "691f61265ae6a86167f81ef6e6cf07977396b5e13b53801ea4c642b735d127cf"

RDEPENDS:compat-golang-gotest3-devel = " \
 go-filesystem \
 golang-gotest-devel \
 "
RDEPENDS:golang-gotest-devel = " \
 go-filesystem \
 golang-github-google-cmp-devel \
 "
