# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "HepMC"
PV = "2.06.11"
PR = "19.el10_1"
PACKAGES = " \
 HepMC \
 HepMC-devel \
 HepMC-doc \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/h/HepMC-2.06.11-19.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "746710d38d20899e30c7721c67261efc02af3d0a4a50629bfd8ec01dfb684403"

URI_x86_64_v2_HepMC = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/HepMC-2.06.11-19.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_HepMC;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_HepMC}"
SRC_URI[x86_64_v2_HepMC.sha256sum] = "c1f1bd26d4d39a11a668640719faf866c6e7c4dd378d1c63d744809fb12afadc"

URI_x86_64_v2_HepMC-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/HepMC-devel-2.06.11-19.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_HepMC-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_HepMC-devel}"
SRC_URI[x86_64_v2_HepMC-devel.sha256sum] = "c61cd00b16fd16fc2f583074064a6cdf8fde3fef313b83e62268fa156937ed2c"

URI_x86_64_v2_HepMC-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/HepMC-doc-2.06.11-19.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_HepMC-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_HepMC-doc}"
SRC_URI[x86_64_v2_HepMC-doc.sha256sum] = "6d915db9f20348e306831b72d7a898718710110d9921da57e3c3e75ee89d0197"

URI_aarch64_HepMC = "${EPEL_MIRROR}/aarch64/Packages/h/HepMC-2.06.11-19.el10_1.aarch64.rpm;name=aarch64_HepMC;unpack=0"
SRC_URI:append = " ${URI_aarch64_HepMC}"
SRC_URI[aarch64_HepMC.sha256sum] = "5a13d8f107c164a3178df9b43fcf092ece2cb30dcef6504fde64625e5bbef209"

URI_aarch64_HepMC-devel = "${EPEL_MIRROR}/aarch64/Packages/h/HepMC-devel-2.06.11-19.el10_1.aarch64.rpm;name=aarch64_HepMC-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_HepMC-devel}"
SRC_URI[aarch64_HepMC-devel.sha256sum] = "e15a462e89fbf3daabc2f2dc9a5320a4dd9d45dcde2ec6f063cd26351edbf10c"

URI_aarch64_HepMC-doc = "${EPEL_MIRROR}/aarch64/Packages/h/HepMC-doc-2.06.11-19.el10_1.noarch.rpm;name=aarch64_HepMC-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_HepMC-doc}"
SRC_URI[aarch64_HepMC-doc.sha256sum] = "39d8b6e9c55d1568f0e717b74894b78f4c322f6c127b733cbfea0fa6f6c8ccc4"

RDEPENDS:HepMC = " \
 glibc \
 libgcc \
 libstdc++ \
 "
RDEPENDS:HepMC-devel = " \
 HepMC \
 "
RDEPENDS:HepMC-doc = " \
 "
