# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "homebank"
PV = "5.10.3"
PR = "1.el10_3"
PACKAGES = " \
 homebank \
 homebank-doc \
 "

SRC_URI = "${EPELSRC_MIRROR}/Packages/h/homebank-5.10.3-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "5c8a5986b35e5882b3b2043d73e3cdd4e0f390d7575f89548d5316c8ec4b6261"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/homebank-5.10.3-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_homebank;unpack=0"
SRC_URI[x86_64_v2_homebank.sha256sum] = "e7fadf1f0a15d4781dec4697bda0fcb990590bdcf3b8bfa46c3eda06f1d996a9"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/homebank-doc-5.10.3-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_homebank-doc;unpack=0"
SRC_URI[x86_64_v2_homebank-doc.sha256sum] = "68597d6d5d8f8cb61c9659819c5231d0defbd63f196328b380800df8f15e211d"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/h/homebank-5.10.3-1.el10_3.aarch64.rpm;name=aarch64_homebank;unpack=0"
SRC_URI[aarch64_homebank.sha256sum] = "8ecf4493bef2fb24693624540eb23c0ae9cb69d2796719eb94468fefa4feb051"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/h/homebank-doc-5.10.3-1.el10_3.noarch.rpm;name=aarch64_homebank-doc;unpack=0"
SRC_URI[aarch64_homebank-doc.sha256sum] = "2b36a7c82ff4fa70c268fe371a57f6850580f46c03bf50db91f1d73f5aaff318"

RDEPENDS:homebank = " \
 cairo \
 gdk-pixbuf2 \
 glib2 \
 glibc \
 gtk3 \
 libgcc \
 libofx \
 libsoup3 \
 pango \
 "
RDEPENDS:homebank-doc = " \
 homebank \
 "
