# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "iverilog"
PV = "13.0"
PR = "7.el10_2"
PACKAGES = " \
 iverilog \
 iverilog-devel \
 iverilog-static \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/i/iverilog-13.0-7.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "da6337a5c44b57c8317b4503e0644397bbc09a163907028217ba8bed0b4ff18b"

URI_x86_64_v2_iverilog = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/iverilog-13.0-7.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_iverilog;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_iverilog}"
SRC_URI[x86_64_v2_iverilog.sha256sum] = "a7a1a593e2f881fdb19f6e4e7d37dacda797668cdb74664118876cdec46611f8"

URI_x86_64_v2_iverilog-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/iverilog-devel-13.0-7.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_iverilog-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_iverilog-devel}"
SRC_URI[x86_64_v2_iverilog-devel.sha256sum] = "19b46bf57684a4bf217af1e6c3257c614096ba88ef2e36d55a254af98d8e6833"

URI_x86_64_v2_iverilog-static = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/iverilog-static-13.0-7.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_iverilog-static;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_iverilog-static}"
SRC_URI[x86_64_v2_iverilog-static.sha256sum] = "d3344077bc3b5974965ec235a3f2acbb86609a12548625eb6fccb89e7cfed006"

URI_aarch64_iverilog = "${EPEL_MIRROR}/aarch64/Packages/i/iverilog-13.0-7.el10_2.aarch64.rpm;name=aarch64_iverilog;unpack=0"
SRC_URI:append = " ${URI_aarch64_iverilog}"
SRC_URI[aarch64_iverilog.sha256sum] = "b94529ea4d9ba453bf862b6e27390a3b4e916f20320b8cad767321b0b2216ffc"

URI_aarch64_iverilog-devel = "${EPEL_MIRROR}/aarch64/Packages/i/iverilog-devel-13.0-7.el10_2.aarch64.rpm;name=aarch64_iverilog-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_iverilog-devel}"
SRC_URI[aarch64_iverilog-devel.sha256sum] = "825d28d4d5cfc3357668312f3670947df223852558ba9a1ee1a2f9fab944fbd7"

URI_aarch64_iverilog-static = "${EPEL_MIRROR}/aarch64/Packages/i/iverilog-static-13.0-7.el10_2.aarch64.rpm;name=aarch64_iverilog-static;unpack=0"
SRC_URI:append = " ${URI_aarch64_iverilog-static}"
SRC_URI[aarch64_iverilog-static.sha256sum] = "ef38302da4d06ab1b05819b7bda0c6b04676c11ab545bab987473692213112bc"

RDEPENDS:iverilog = " \
 bash \
 bzip2-libs \
 glibc \
 libgcc \
 libstdc++ \
 readline \
 zlib-ng-compat \
 "
RDEPENDS:iverilog-devel = " \
 iverilog \
 "
RDEPENDS:iverilog-static = " \
 iverilog-devel \
 "
