# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "k2hash"
PV = "1.0.98"
PR = "1.el10_0"
PACKAGES = " \
 k2hash \
 k2hash-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/k/k2hash-1.0.98-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "9a65a79123735c2ab75e5cc329be188edc468c25445622c46e57cae294ad4dd7"

URI_x86_64_v2_k2hash = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/k2hash-1.0.98-1.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_k2hash;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_k2hash}"
SRC_URI[x86_64_v2_k2hash.sha256sum] = "1d3cd1687dc0e929e48a5b96d769027f1d996cea15e664f2f41601a8faf35bab"

URI_x86_64_v2_k2hash-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/k2hash-devel-1.0.98-1.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_k2hash-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_k2hash-devel}"
SRC_URI[x86_64_v2_k2hash-devel.sha256sum] = "b66b3085702defbf089ca69c8d27cb712d66115f311b4f1e8361f179bb92bfaf"

URI_aarch64_k2hash = "${EPEL_MIRROR}/aarch64/Packages/k/k2hash-1.0.98-1.el10_0.aarch64.rpm;name=aarch64_k2hash;unpack=0"
SRC_URI:append = " ${URI_aarch64_k2hash}"
SRC_URI[aarch64_k2hash.sha256sum] = "c125ad05b13d5117fcb7b253c658c5c83252ca66cdb8dd7ee40cebd5dc8bd4be"

URI_aarch64_k2hash-devel = "${EPEL_MIRROR}/aarch64/Packages/k/k2hash-devel-1.0.98-1.el10_0.aarch64.rpm;name=aarch64_k2hash-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_k2hash-devel}"
SRC_URI[aarch64_k2hash-devel.sha256sum] = "a15d96fa7249e244d8dfdcfdfc167c7acb8fcdb1fff8dc930e6924e666219983"

RDEPENDS:k2hash = " \
 bash \
 glibc \
 libfullock \
 libgcc \
 libstdc++ \
 nspr \
 nss \
 nss-util \
 "
RDEPENDS:k2hash-devel = " \
 k2hash \
 libfullock-devel \
 pkgconf-pkg-config \
 "
