# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "kaccounts-providers"
PV = "26.08.1"
PR = "1.el10_3"
PACKAGES = " \
 kaccounts-providers \
 "

SRC_URI = "${EPELSRC_MIRROR}/Packages/k/kaccounts-providers-26.08.1-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "fee5fea8551d4105e9d7f8630dccce1c8ec86ebe929b90c630dfe0b046d7f18a"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/kaccounts-providers-26.08.1-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_kaccounts-providers;unpack=0"
SRC_URI[x86_64_v2_kaccounts-providers.sha256sum] = "793c8c59790e73d79f9551f7ccc1a9414884fc8ef42a2864f667114162d3a907"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/k/kaccounts-providers-26.08.1-1.el10_3.aarch64.rpm;name=aarch64_kaccounts-providers;unpack=0"
SRC_URI[aarch64_kaccounts-providers.sha256sum] = "b94c3e83e9e3add1cabcc313073584fa34fc9e6e17004aa57c8cd73a6e2b45cd"

RDEPENDS:kaccounts-providers = " \
 glibc \
 kaccounts-integration-qt6 \
 kf6-kcoreaddons \
 kf6-ki18n \
 kf6-kio-core-libs \
 kf6-kpackage \
 libstdc++ \
 qt6-qtbase \
 qt6-qtbase-gui \
 qt6-qtdeclarative \
 qt6-qtwebengine \
 signon-plugin-oauth2 \
 signon-ui \
 "
