# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "kf6-kpty"
PV = "6.30.0"
PR = "1.el10_3"
PACKAGES = " \
 kf6-kpty \
 kf6-kpty-devel \
 kf6-kpty-doc \
 kf6-kpty-html \
 "

SRC_URI = "${EPELSRC_MIRROR}/Packages/k/kf6-kpty-6.30.0-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "604d689a2ae9c2abacb54165ba1bdf1016a7d7157dafd1f177a5fb8f9540a6eb"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/kf6-kpty-6.30.0-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_kf6-kpty;unpack=0"
SRC_URI[x86_64_v2_kf6-kpty.sha256sum] = "dfd7a50491723c0948d28fe65e29c5af6d979b4152326b1f641fc1b17b422db0"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/kf6-kpty-devel-6.30.0-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_kf6-kpty-devel;unpack=0"
SRC_URI[x86_64_v2_kf6-kpty-devel.sha256sum] = "6e56c515c9506ca34ec355115643e7b4411b00d269577da13dc2b12309c49ec7"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/kf6-kpty-doc-6.30.0-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_kf6-kpty-doc;unpack=0"
SRC_URI[x86_64_v2_kf6-kpty-doc.sha256sum] = "8f2b7b62e69eb8dcd9056279cf3b46b48f6d0a224927e0da93ac2d3aeb2d73c0"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/kf6-kpty-html-6.30.0-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_kf6-kpty-html;unpack=0"
SRC_URI[x86_64_v2_kf6-kpty-html.sha256sum] = "3aff2056c0614620129d8acf763d573508e9c99f9f83059fb1a1655e95579ba6"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/k/kf6-kpty-6.30.0-1.el10_3.aarch64.rpm;name=aarch64_kf6-kpty;unpack=0"
SRC_URI[aarch64_kf6-kpty.sha256sum] = "a21a0cdd30a4b8046fbbf195912548009a2c2731bd1f24348fa5a8eb0ece422b"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/k/kf6-kpty-devel-6.30.0-1.el10_3.aarch64.rpm;name=aarch64_kf6-kpty-devel;unpack=0"
SRC_URI[aarch64_kf6-kpty-devel.sha256sum] = "ec00bd4b7ffc9a0d89260a53ad2920fc9dd1092aaa5b5318191b29e76b52d7f7"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/k/kf6-kpty-doc-6.30.0-1.el10_3.noarch.rpm;name=aarch64_kf6-kpty-doc;unpack=0"
SRC_URI[aarch64_kf6-kpty-doc.sha256sum] = "47c2bc81a8a968c7a88063e9afa652f698fbce02877b79280af36c277b0c3927"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/k/kf6-kpty-html-6.30.0-1.el10_3.noarch.rpm;name=aarch64_kf6-kpty-html;unpack=0"
SRC_URI[aarch64_kf6-kpty-html.sha256sum] = "1f0e1810bd9c5d18332ec0ceb35a278f81727303c8ce16c0ab2af056ed9b377d"

RDEPENDS:kf6-kpty = " \
 glibc \
 kf6-filesystem \
 kf6-kcoreaddons \
 kf6-ki18n \
 libstdc++ \
 libutempter \
 qt6-qtbase \
 "
RDEPENDS:kf6-kpty-devel = " \
 cmake-filesystem \
 kf6-kcoreaddons-devel \
 kf6-kpty \
 "
RDEPENDS:kf6-kpty-doc = " \
 "
RDEPENDS:kf6-kpty-html = " \
 "
