# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "kf6-kapidox"
PV = "6.12.0"
PR = "1.el10_0"
PACKAGES = " \
 kf6-kapidox \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/k/kf6-kapidox-6.12.0-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a50adf405c66d359ccbca768779349ae60e74a677b687d52cb6a2dc336833b42"

URI_x86_64_v2_kf6-kapidox = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/kf6-kapidox-6.12.0-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_kf6-kapidox;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_kf6-kapidox}"
SRC_URI[x86_64_v2_kf6-kapidox.sha256sum] = "6fe2275a320b6fc29bc42b2815327dcc775f8fefe4cc81cdf546e9b19850fad5"

URI_aarch64_kf6-kapidox = "${EPEL_MIRROR}/aarch64/Packages/k/kf6-kapidox-6.12.0-1.el10_0.noarch.rpm;name=aarch64_kf6-kapidox;unpack=0"
SRC_URI:append = " ${URI_aarch64_kf6-kapidox}"
SRC_URI[aarch64_kf6-kapidox.sha256sum] = "85c1a432e4193868c09ec788e0698e2b97f38a0700fb80efff4990e6d14e71df"

RDEPENDS:kf6-kapidox = " \
 bash \
 doxygen \
 kf6-filesystem \
 python3 \
 python3-doxypypy \
 python3-doxyqml \
 python3-jinja2 \
 python3-pyyaml \
 python3-requests \
 qt6-doc-devel \
 "
