# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "koji-tool"
PV = "1.3.1"
PR = "1.el10_2"
PACKAGES = " \
 koji-tool \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/k/koji-tool-1.3.1-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b8d0018c116c67bbf9a22e6e8d4adb4e89c57d98c301993d798fe256daa91d32"

URI_x86_64_v2_koji-tool = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/koji-tool-1.3.1-1.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_koji-tool;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_koji-tool}"
SRC_URI[x86_64_v2_koji-tool.sha256sum] = "5e28f4c8f464af30b76e429f874c5e3508e168114e81a9cf5cecb5cd284abe84"

URI_aarch64_koji-tool = "${EPEL_MIRROR}/aarch64/Packages/k/koji-tool-1.3.1-1.el10_2.aarch64.rpm;name=aarch64_koji-tool;unpack=0"
SRC_URI:append = " ${URI_aarch64_koji-tool}"
SRC_URI[aarch64_koji-tool.sha256sum] = "c87e53fb7556e8bc842cc780763a2d0aba8141902093750716916d25900670fb"

RDEPENDS:koji-tool = " \
 glibc \
 gmp \
 libffi \
 ncurses-libs \
 openssl-libs \
 zlib-ng-compat \
 "
