# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "kteatime"
PV = "26.04.3"
PR = "1.el10_3"
PACKAGES = " \
 kteatime \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/k/kteatime-26.04.3-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f3067a13d8c4d3b73f222c628425c7a2ddacfa5e400037b8882ef80eacfcd828"

URI_x86_64_v2_kteatime = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/kteatime-26.04.3-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_kteatime;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_kteatime}"
SRC_URI[x86_64_v2_kteatime.sha256sum] = "e3bf710045e6433beed67bb57ea4b36daf00db907b514c5c7a063b4e5fb911e9"

URI_aarch64_kteatime = "${EPEL_MIRROR}/aarch64/Packages/k/kteatime-26.04.3-1.el10_3.aarch64.rpm;name=aarch64_kteatime;unpack=0"
SRC_URI:append = " ${URI_aarch64_kteatime}"
SRC_URI[aarch64_kteatime.sha256sum] = "387a41c0644fb2bebfa8ae1a089aa7a9d7480eb08773d35db634167e333d266e"

RDEPENDS:kteatime = " \
 glibc \
 kf6-kconfig \
 kf6-kconfigwidgets \
 kf6-kcoreaddons \
 kf6-kcrash \
 kf6-ki18n \
 kf6-knotifications \
 kf6-knotifyconfig \
 kf6-kstatusnotifieritem \
 kf6-ktextwidgets \
 kf6-kxmlgui \
 libstdc++ \
 qt6-qtbase \
 qt6-qtbase-gui \
 "
