# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "livesys-scripts"
PV = "0.9.6"
PR = "1.el10_2"
PACKAGES = " \
 livesys-scripts \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/l/livesys-scripts-0.9.6-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c946f46cd0b3a5ebc2458b6f96bf442599f83ecc2695d099712e2e3ed39c3d7a"

URI_x86_64_v2_livesys-scripts = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/livesys-scripts-0.9.6-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_livesys-scripts;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_livesys-scripts}"
SRC_URI[x86_64_v2_livesys-scripts.sha256sum] = "d2de5fa7cafe61bc793b7a3be924b5d1db51269f19a4b0feeccbd0446f4088b0"

URI_aarch64_livesys-scripts = "${EPEL_MIRROR}/aarch64/Packages/l/livesys-scripts-0.9.6-1.el10_2.noarch.rpm;name=aarch64_livesys-scripts;unpack=0"
SRC_URI:append = " ${URI_aarch64_livesys-scripts}"
SRC_URI[aarch64_livesys-scripts.sha256sum] = "1311dc66b62208c61019c505a5e2ac7e7ac6a719d11d3eb71fcf690ead5c8469"

RDEPENDS:livesys-scripts = " \
 bash \
 "
