# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "maven-invoker"
PV = "3.1.0"
PR = "16.el10_0"
PACKAGES = " \
 maven-invoker \
 maven-invoker-javadoc \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/m/maven-invoker-3.1.0-16.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "88ea26492ac8613763d9f390242ea68a68c00741ece682ea0711f50515604efe"

URI_x86_64_v2_maven-invoker = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/maven-invoker-3.1.0-16.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_maven-invoker;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_maven-invoker}"
SRC_URI[x86_64_v2_maven-invoker.sha256sum] = "d40f996393ccdb2b058e3e175e015e92fed18ca7adf541ce37913940ece85dec"

URI_x86_64_v2_maven-invoker-javadoc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/maven-invoker-javadoc-3.1.0-16.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_maven-invoker-javadoc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_maven-invoker-javadoc}"
SRC_URI[x86_64_v2_maven-invoker-javadoc.sha256sum] = "fe0f77260d089908f499e836aade7b483ff25b5603fc981c290e4ed78c772560"

URI_aarch64_maven-invoker = "${EPEL_MIRROR}/aarch64/Packages/m/maven-invoker-3.1.0-16.el10_0.noarch.rpm;name=aarch64_maven-invoker;unpack=0"
SRC_URI:append = " ${URI_aarch64_maven-invoker}"
SRC_URI[aarch64_maven-invoker.sha256sum] = "efadab374ea9c3c60c8936c59d6a247cc34dd0ce6495cb7bd399fcda2731782b"

URI_aarch64_maven-invoker-javadoc = "${EPEL_MIRROR}/aarch64/Packages/m/maven-invoker-javadoc-3.1.0-16.el10_0.noarch.rpm;name=aarch64_maven-invoker-javadoc;unpack=0"
SRC_URI:append = " ${URI_aarch64_maven-invoker-javadoc}"
SRC_URI[aarch64_maven-invoker-javadoc.sha256sum] = "6c51ea8e3827cc30d515f12678d89adefcbf0a0b90d4f18a605e0f20c49b1024"

RDEPENDS:maven-invoker = " \
 javapackages-filesystem \
 maven-shared-utils \
 sisu \
 "
RDEPENDS:maven-invoker-javadoc = " \
 javapackages-filesystem \
 "
