# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "nbd"
PV = "3.27.0"
PR = "1.el10_3"
PACKAGES = " \
 nbd \
 "

SRC_URI = "${EPELSRC_MIRROR}/Packages/n/nbd-3.27.0-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "1e420203367c5158ebaaee583380911a816e5e9d6afa0eb14997c4716f575f81"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/nbd-3.27.0-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_nbd;unpack=0"
SRC_URI[x86_64_v2_nbd.sha256sum] = "d8ed620e2b405f38b056eeea72c139956cfcda126e4e6da0f0f16ccc5a6a0f09"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/n/nbd-3.27.0-1.el10_3.aarch64.rpm;name=aarch64_nbd;unpack=0"
SRC_URI[aarch64_nbd.sha256sum] = "60a6c9fbdb7cc2337ceb66c28593e3dcd27b48ca243205e2a1418711f6fd6404"

RDEPENDS:nbd = " \
 bash \
 glib2 \
 glibc \
 gnutls \
 libgcc \
 libnl3 \
 systemd \
 "
