# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "notcurses"
PV = "3.0.14"
PR = "2.el10_1"
PACKAGES = " \
 notcurses \
 notcurses-devel \
 notcurses-static \
 notcurses-utils \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/n/notcurses-3.0.14-2.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e546dd3fef0a1f6739b7323d8e3bc22722e3d11c9fa100d7d0439f3f95088acb"

URI_x86_64_v2_notcurses = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/notcurses-3.0.14-2.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_notcurses;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_notcurses}"
SRC_URI[x86_64_v2_notcurses.sha256sum] = "87b8bf32340634c3ae6dd4e31001b2f7df106c3a014dd96d50c3ae980f101501"

URI_x86_64_v2_notcurses-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/notcurses-devel-3.0.14-2.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_notcurses-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_notcurses-devel}"
SRC_URI[x86_64_v2_notcurses-devel.sha256sum] = "aaa600366e654369264110c165837394ef9604919fb652215129fd209334387b"

URI_x86_64_v2_notcurses-static = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/notcurses-static-3.0.14-2.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_notcurses-static;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_notcurses-static}"
SRC_URI[x86_64_v2_notcurses-static.sha256sum] = "9d8297c4e35ccb922dc1e0cb42cc524100ca1c0ed808a69ca58069c2de3c743e"

URI_x86_64_v2_notcurses-utils = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/notcurses-utils-3.0.14-2.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_notcurses-utils;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_notcurses-utils}"
SRC_URI[x86_64_v2_notcurses-utils.sha256sum] = "92fd9d0b824dd7e020726ec0daaba356aa3ac640bebb3c7de34844fb68ef4a51"

URI_aarch64_notcurses = "${EPEL_MIRROR}/aarch64/Packages/n/notcurses-3.0.14-2.el10_1.aarch64.rpm;name=aarch64_notcurses;unpack=0"
SRC_URI:append = " ${URI_aarch64_notcurses}"
SRC_URI[aarch64_notcurses.sha256sum] = "5f4465d9de1243350cb5b3bb53b6a0c714c99a4bd5a1023fb247fab880ffc9c2"

URI_aarch64_notcurses-devel = "${EPEL_MIRROR}/aarch64/Packages/n/notcurses-devel-3.0.14-2.el10_1.aarch64.rpm;name=aarch64_notcurses-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_notcurses-devel}"
SRC_URI[aarch64_notcurses-devel.sha256sum] = "a55a330a9cd52453d3262acbb811c2d4c3a487bef32b8520ac297d2b648de8c8"

URI_aarch64_notcurses-static = "${EPEL_MIRROR}/aarch64/Packages/n/notcurses-static-3.0.14-2.el10_1.aarch64.rpm;name=aarch64_notcurses-static;unpack=0"
SRC_URI:append = " ${URI_aarch64_notcurses-static}"
SRC_URI[aarch64_notcurses-static.sha256sum] = "170ff72642110d7ea05e37c7eeb965eed56e7bbeef1d51b8670422df80f87c81"

URI_aarch64_notcurses-utils = "${EPEL_MIRROR}/aarch64/Packages/n/notcurses-utils-3.0.14-2.el10_1.aarch64.rpm;name=aarch64_notcurses-utils;unpack=0"
SRC_URI:append = " ${URI_aarch64_notcurses-utils}"
SRC_URI[aarch64_notcurses-utils.sha256sum] = "db2f121b3aed8691804d099ecb95eed596a07bf823c39b68676dc2c4235aafa6"

RDEPENDS:notcurses = " \
 glibc \
 libavcodec-free \
 libavdevice-free \
 libavformat-free \
 libavutil-free \
 libdeflate \
 libgcc \
 libstdc++ \
 libswscale-free \
 libunistring \
 ncurses-libs \
 "
RDEPENDS:notcurses-devel = " \
 cmake-filesystem \
 ncurses-devel \
 notcurses \
 notcurses-devel \
 pkgconf-pkg-config \
 "
RDEPENDS:notcurses-static = " \
 notcurses \
 "
RDEPENDS:notcurses-utils = " \
 glibc \
 libdeflate \
 libgcc \
 libstdc++ \
 libunistring \
 ncurses-libs \
 notcurses \
 "
