# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "perl-GTop"
PV = "0.18"
PR = "44.el10_0"
PACKAGES = " \
 perl-GTop \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/perl-GTop-0.18-44.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "88e70237dbac920fcbc0b345f1aee2730c34e4b25e0f320d047b6463ae6dddc8"

URI_x86_64_v2_perl-GTop = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/perl-GTop-0.18-44.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_perl-GTop;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_perl-GTop}"
SRC_URI[x86_64_v2_perl-GTop.sha256sum] = "5d250f5601023d11a33875212d2bca8a744c535e88360c65e58ae747b32c76ab"

URI_aarch64_perl-GTop = "${EPEL_MIRROR}/aarch64/Packages/p/perl-GTop-0.18-44.el10_0.aarch64.rpm;name=aarch64_perl-GTop;unpack=0"
SRC_URI:append = " ${URI_aarch64_perl-GTop}"
SRC_URI[aarch64_perl-GTop.sha256sum] = "1e2d38e6d8d10f8948c47126eb4ffb8c4a576cd819e25e345631512e9671f32a"

RDEPENDS:perl-GTop = " \
 glib2 \
 glibc \
 libgtop2 \
 perl-DynaLoader \
 perl-Scalar-List-Utils \
 perl-constant \
 perl-libs \
 perl-subs \
 "
