# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "perl-AuthCAS"
PV = "1.7"
PR = "25.el10_0"
PACKAGES = " \
 perl-AuthCAS \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/perl-AuthCAS-1.7-25.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "81b9a512ab8e7bbeda8dd440b9803204284fef56a2b2d863944816726ddd8bc2"

URI_x86_64_v2_perl-AuthCAS = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/perl-AuthCAS-1.7-25.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_perl-AuthCAS;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_perl-AuthCAS}"
SRC_URI[x86_64_v2_perl-AuthCAS.sha256sum] = "448cc086b933f0a1f5e1590ecc07602dd7ee762467c8f79b6f4487b49b9329ea"

URI_aarch64_perl-AuthCAS = "${EPEL_MIRROR}/aarch64/Packages/p/perl-AuthCAS-1.7-25.el10_0.noarch.rpm;name=aarch64_perl-AuthCAS;unpack=0"
SRC_URI:append = " ${URI_aarch64_perl-AuthCAS}"
SRC_URI[aarch64_perl-AuthCAS.sha256sum] = "7ede99f6f06cc42af2533aee3dfeffc833095b363ce92ead8f72dec554513b0e"

RDEPENDS:perl-AuthCAS = " \
 perl-Carp \
 perl-libs \
 perl-vars \
 "
