# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "perl-No-Worries"
PV = "1.7"
PR = "14.el10_2"
PACKAGES = " \
 perl-No-Worries \
 perl-No-Worries-tests \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/perl-No-Worries-1.7-14.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7471faed590b3cba89942365bc55fb2181aa34e16dd2e67209b52f24a1ae0b54"

URI_x86_64_v2_perl-No-Worries = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/perl-No-Worries-1.7-14.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_perl-No-Worries;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_perl-No-Worries}"
SRC_URI[x86_64_v2_perl-No-Worries.sha256sum] = "d171b899544ebe13947c72c59a143256dd7b18661a741bd6b18921edf91f7890"

URI_x86_64_v2_perl-No-Worries-tests = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/perl-No-Worries-tests-1.7-14.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_perl-No-Worries-tests;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_perl-No-Worries-tests}"
SRC_URI[x86_64_v2_perl-No-Worries-tests.sha256sum] = "f0334d09ca06ebb16239982e83e725d0d575e108c2ff6be0047c91caf2dd08b3"

URI_aarch64_perl-No-Worries = "${EPEL_MIRROR}/aarch64/Packages/p/perl-No-Worries-1.7-14.el10_2.noarch.rpm;name=aarch64_perl-No-Worries;unpack=0"
SRC_URI:append = " ${URI_aarch64_perl-No-Worries}"
SRC_URI[aarch64_perl-No-Worries.sha256sum] = "27ebdc4b439d832fd8d462f7fb0a6104c379a72c5a69ed942d1e465ec62e8294"

URI_aarch64_perl-No-Worries-tests = "${EPEL_MIRROR}/aarch64/Packages/p/perl-No-Worries-tests-1.7-14.el10_2.noarch.rpm;name=aarch64_perl-No-Worries-tests;unpack=0"
SRC_URI:append = " ${URI_aarch64_perl-No-Worries-tests}"
SRC_URI[aarch64_perl-No-Worries-tests.sha256sum] = "434189090cc4a1803c0cb3accc646e8c1676a5be1ef83e5fdd8eec8886ba0943"

RDEPENDS:perl-No-Worries = " \
 perl-Carp \
 perl-Encode \
 perl-Fcntl \
 perl-HTTP-Date \
 perl-IO \
 perl-No-Worries \
 perl-POSIX \
 perl-Params-Validate \
 perl-Sys-Hostname \
 perl-Sys-Syslog \
 perl-Time-HiRes \
 perl-URI \
 perl-constant \
 perl-libs \
 "
RDEPENDS:perl-No-Worries-tests = " \
 bash \
 perl-Encode \
 perl-File-Temp \
 perl-No-Worries \
 perl-Test-Harness \
 perl-Test-Simple \
 perl-constant \
 perl-libs \
 "
