# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "pg_top"
PV = "4.1.3"
PR = "1.el10_1"
PACKAGES = " \
 pg_top \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/pg_top-4.1.3-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0e6609fef0e56be41e4811847064c0e5d3aec2d258960a59271ad1b6060f0715"

URI_x86_64_v2_pg_top = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/pg_top-4.1.3-1.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_pg_top;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_pg_top}"
SRC_URI[x86_64_v2_pg_top.sha256sum] = "90bbb85c89d02004746e8367a9d774eff48de7e86b881ac3b2b38448c9ef3ee1"

URI_aarch64_pg_top = "${EPEL_MIRROR}/aarch64/Packages/p/pg_top-4.1.3-1.el10_1.aarch64.rpm;name=aarch64_pg_top;unpack=0"
SRC_URI:append = " ${URI_aarch64_pg_top}"
SRC_URI[aarch64_pg_top.sha256sum] = "a800c5041d6f9146ef41fd38a8ea3212bf925a8827997abb08436b32309a2993"

RDEPENDS:pg_top = " \
 glibc \
 libpq \
 ncurses-libs \
 postgresql-server \
 "
