# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "python-collectd_cvmfs"
PV = "1.4.0"
PR = "2.el10_1"
PACKAGES = " \
 python3-collectd_cvmfs \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/python-collectd_cvmfs-1.4.0-2.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c655674e372dc24a2d0d74ae8bf2b474fe9e192bc816fd57e092ea305e0101ca"

URI_x86_64_v2_python3-collectd_cvmfs = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/python3-collectd_cvmfs-1.4.0-2.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_python3-collectd_cvmfs;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python3-collectd_cvmfs}"
SRC_URI[x86_64_v2_python3-collectd_cvmfs.sha256sum] = "06dcbb8862725cbd47d1edd525cac9f79794990e19a01949e48a260924db7455"

URI_aarch64_python3-collectd_cvmfs = "${EPEL_MIRROR}/aarch64/Packages/p/python3-collectd_cvmfs-1.4.0-2.el10_1.noarch.rpm;name=aarch64_python3-collectd_cvmfs;unpack=0"
SRC_URI:append = " ${URI_aarch64_python3-collectd_cvmfs}"
SRC_URI[aarch64_python3-collectd_cvmfs.sha256sum] = "ded52f4f112db5bb879948111744350266a5511c12483319291ac9a12137d94f"

RDEPENDS:python3-collectd_cvmfs = " \
 python3 \
 python3-psutil \
 python3-pyxattr \
 "
