# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "python-osrf-pycommon"
PV = "2.1.5"
PR = "1.el10_0"
PACKAGES = " \
 python-osrf-pycommon-doc \
 python3-osrf-pycommon \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/python-osrf-pycommon-2.1.5-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "63da70f26e64d520d1a9647a93062cde692c0d782c39f86ba6d57a23dd2fffd8"

URI_x86_64_v2_python-osrf-pycommon-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/python-osrf-pycommon-doc-2.1.5-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_python-osrf-pycommon-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python-osrf-pycommon-doc}"
SRC_URI[x86_64_v2_python-osrf-pycommon-doc.sha256sum] = "061c19747b5167238a00903cadf2d714bad050c8949b021f99933acd5f11c75a"

URI_x86_64_v2_python3-osrf-pycommon = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/python3-osrf-pycommon-2.1.5-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_python3-osrf-pycommon;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python3-osrf-pycommon}"
SRC_URI[x86_64_v2_python3-osrf-pycommon.sha256sum] = "a498262dd3329aa2e44679e92f9c8459633bfd1686664d662c0aaab294c83bcd"

URI_aarch64_python-osrf-pycommon-doc = "${EPEL_MIRROR}/aarch64/Packages/p/python-osrf-pycommon-doc-2.1.5-1.el10_0.noarch.rpm;name=aarch64_python-osrf-pycommon-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_python-osrf-pycommon-doc}"
SRC_URI[aarch64_python-osrf-pycommon-doc.sha256sum] = "63fda1a3be6bd9bb18d43e4bf22d5ef1a7fb354ac570982512e115726528ed61"

URI_aarch64_python3-osrf-pycommon = "${EPEL_MIRROR}/aarch64/Packages/p/python3-osrf-pycommon-2.1.5-1.el10_0.noarch.rpm;name=aarch64_python3-osrf-pycommon;unpack=0"
SRC_URI:append = " ${URI_aarch64_python3-osrf-pycommon}"
SRC_URI[aarch64_python3-osrf-pycommon.sha256sum] = "2345b87f44b1aea476be17aa345a762cc050a6c090cb563b6eb6a98f5071f26d"

RDEPENDS:python-osrf-pycommon-doc = " \
 "
RDEPENDS:python3-osrf-pycommon = " \
 python3 \
 "
