# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "python-matplotlib-inline"
PV = "0.1.7"
PR = "5.el10_0"
PACKAGES = " \
 python3-matplotlib-inline \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/python-matplotlib-inline-0.1.7-5.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "231e7b4e3e6e139b7f8ad9b1c83c0a744937656a95f386eb20c384af4569b905"

URI_x86_64_v2_python3-matplotlib-inline = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/python3-matplotlib-inline-0.1.7-5.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_python3-matplotlib-inline;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python3-matplotlib-inline}"
SRC_URI[x86_64_v2_python3-matplotlib-inline.sha256sum] = "305b4db6d66f47dee2675bba9d70b06538216328652f4b04c3bbb46a706d95e4"

URI_aarch64_python3-matplotlib-inline = "${EPEL_MIRROR}/aarch64/Packages/p/python3-matplotlib-inline-0.1.7-5.el10_0.noarch.rpm;name=aarch64_python3-matplotlib-inline;unpack=0"
SRC_URI:append = " ${URI_aarch64_python3-matplotlib-inline}"
SRC_URI[aarch64_python3-matplotlib-inline.sha256sum] = "a65850c1771c52dea9b552603d71a3a0c4c88de03064bdb27074acbe37782ef7"

RDEPENDS:python3-matplotlib-inline = " \
 python3 \
 python3-traitlets \
 "
