# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "python-ldap3"
PV = "2.9.1"
PR = "10.el10_0"
PACKAGES = " \
 python3-ldap3 \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/python-ldap3-2.9.1-10.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1c0cd0930a9e38857eb09ae5ec6b41034123c25e4ca97cc592184e7b510f8151"

URI_x86_64_v2_python3-ldap3 = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/python3-ldap3-2.9.1-10.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_python3-ldap3;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python3-ldap3}"
SRC_URI[x86_64_v2_python3-ldap3.sha256sum] = "0e49517d2ef166585e772ff3c9a6be9634e00c3d7ac5c366c47332ed8d53c0c1"

URI_aarch64_python3-ldap3 = "${EPEL_MIRROR}/aarch64/Packages/p/python3-ldap3-2.9.1-10.el10_0.noarch.rpm;name=aarch64_python3-ldap3;unpack=0"
SRC_URI:append = " ${URI_aarch64_python3-ldap3}"
SRC_URI[aarch64_python3-ldap3.sha256sum] = "96373b3da0c3893d2b1e80e3b7049b0bf85a598b420ef8b700651c9abfcdcd18"

RDEPENDS:python3-ldap3 = " \
 python3 \
 python3-pyasn1 \
 "
