# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "python-pyzstd"
PV = "0.16.2"
PR = "1.el10_1"
PACKAGES = " \
 python3-pyzstd \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/python-pyzstd-0.16.2-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7575fad16f48bf285472a9e715d8d355b29c390f9903301c9639e129207a7407"

URI_x86_64_v2_python3-pyzstd = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/python3-pyzstd-0.16.2-1.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_python3-pyzstd;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python3-pyzstd}"
SRC_URI[x86_64_v2_python3-pyzstd.sha256sum] = "8bde3718eb00fc76d0c88462f4efbd46a73a7b7b04c45730ee6484f7dd5fa2d3"

URI_aarch64_python3-pyzstd = "${EPEL_MIRROR}/aarch64/Packages/p/python3-pyzstd-0.16.2-1.el10_1.aarch64.rpm;name=aarch64_python3-pyzstd;unpack=0"
SRC_URI:append = " ${URI_aarch64_python3-pyzstd}"
SRC_URI[aarch64_python3-pyzstd.sha256sum] = "dc1a83bd64e9fcf79074e7bba85c02e68564f5b43be18f73a736d917d8c74ce7"

RDEPENDS:python3-pyzstd = " \
 glibc \
 libzstd \
 python3 \
 "
