# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "python-sphinxcontrib-trio"
PV = "1.1.2"
PR = "25.el10_1"
PACKAGES = " \
 python3-sphinxcontrib-trio \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/p/python-sphinxcontrib-trio-1.1.2-25.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d46aed48daf19cf14f3beaa958b60eab7a482cbcc910de2e7062d0121f095ed7"

URI_x86_64_v2_python3-sphinxcontrib-trio = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/python3-sphinxcontrib-trio-1.1.2-25.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_python3-sphinxcontrib-trio;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_python3-sphinxcontrib-trio}"
SRC_URI[x86_64_v2_python3-sphinxcontrib-trio.sha256sum] = "153d1515a6dcdce23dcb5a60fd9a08eb3e6118ed6e41613f9b363d14e103bcde"

URI_aarch64_python3-sphinxcontrib-trio = "${EPEL_MIRROR}/aarch64/Packages/p/python3-sphinxcontrib-trio-1.1.2-25.el10_1.noarch.rpm;name=aarch64_python3-sphinxcontrib-trio;unpack=0"
SRC_URI:append = " ${URI_aarch64_python3-sphinxcontrib-trio}"
SRC_URI[aarch64_python3-sphinxcontrib-trio.sha256sum] = "662cd1c85bbe36a8b313adee79c82cad3400a5d73d1ba18f59547d9095961bcc"

RDEPENDS:python3-sphinxcontrib-trio = " \
 python3 \
 python3-sphinx \
 "
