# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "python-blazarclient"
PV = "4.5.0"
PR = "1.el10_2"
PACKAGES = " \
 python3-blazarclient \
 "

SRC_URI = "${EPELSRC_MIRROR}/Packages/p/python-blazarclient-4.5.0-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "f8f019c3c93d330015455b9a7edbfeae3f43abf2aa890be6531f15bbcb755eec"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/python3-blazarclient-4.5.0-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_python3-blazarclient;unpack=0"
SRC_URI[x86_64_v2_python3-blazarclient.sha256sum] = "21fd2468a1fdcf83883a98c1d6343e6c7373667041daa42c3b5bd0fd5df30dc7"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/p/python3-blazarclient-4.5.0-1.el10_2.noarch.rpm;name=aarch64_python3-blazarclient;unpack=0"
SRC_URI[aarch64_python3-blazarclient.sha256sum] = "3f1b11974abec3d90858f2bc035156773e67bea83fdd14c552c794f46173267f"

RDEPENDS:python3-blazarclient = " \
 python3 \
 python3-cliff \
 python3-keystoneauth1 \
 python3-osc-lib \
 python3-oslo-i18n \
 python3-oslo-log \
 python3-oslo-utils \
 python3-pbr \
 python3-prettytable \
 "
