# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rocm-validation-suite"
PV = "7.2.1"
PR = "1.el10_3"
PACKAGES:x86_64_v2 = " \
 rocm-validation-suite \
"
PACKAGES:aarch64 = " \
  \
"

URI_src = "${EPELSRC_MIRROR}/Packages/r/rocm-validation-suite-7.2.1-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "af2446096bff08da05b8fad82bde804e7f59e33957d8d20ad54887cbdf19ea99"

URI_x86_64_v2_rocm-validation-suite = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rocm-validation-suite-7.2.1-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_rocm-validation-suite;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rocm-validation-suite}"
SRC_URI[x86_64_v2_rocm-validation-suite.sha256sum] = "76bdaa50a7a72c67f9c560b658f10e5f4113b727b6df21049daa388640cb724b"

RDEPENDS:rocm-validation-suite = " \
 amdsmi \
 glibc \
 hipblaslt \
 hiprand \
 libgcc \
 libstdc++ \
 pciutils-libs \
 rocblas \
 rocm-hip \
 rocm-runtime \
 virtual/libomp.so_VERSION__64bit_ \
 virtual/libomp.so___64bit_ \
 yaml-cpp \
 "
