# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rocm-origami"
PV = "7.1.1"
PR = "3.el10_2"
PACKAGES:x86_64_v2 = " \
 rocm-origami \
 rocm-origami-devel \
"
PACKAGES:aarch64 = " \
  \
"

SRC_URI = "${EPELSRC_MIRROR}/Packages/r/rocm-origami-7.1.1-3.el10_2.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "3ecbfdc0375a8edf957cbb6d74540fb8c8aa70694a74bc02f209af7e61c9c671"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rocm-origami-7.1.1-3.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_rocm-origami;unpack=0"
SRC_URI[x86_64_v2_rocm-origami.sha256sum] = "4ffa253f451183073b9ea92aaf1f12c689b0910e2dc12b39bd6f99f0c25a498d"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rocm-origami-devel-7.1.1-3.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_rocm-origami-devel;unpack=0"
SRC_URI[x86_64_v2_rocm-origami-devel.sha256sum] = "b664c77e755f26a5bac05fc773cfea5b742b1a8d0ecac21b9bfe253d9168e079"

RDEPENDS:rocm-origami = " \
 glibc \
 libgcc \
 libstdc++ \
 "
RDEPENDS:rocm-origami-devel = " \
 cmake-filesystem \
 rocm-origami \
 "
