# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rocs"
PV = "26.08.1"
PR = "1.el10_3"
PACKAGES = " \
 rocs \
 rocs-devel \
 rocs-libs \
 "

SRC_URI = "${EPELSRC_MIRROR}/Packages/r/rocs-26.08.1-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "c5ce1490a828224b60666815b26da0fcba35c127c1783b52c8d5204c2d90f813"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rocs-26.08.1-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_rocs;unpack=0"
SRC_URI[x86_64_v2_rocs.sha256sum] = "399ea48e45d263d49dc8a16b60ed036dc9fe0aea4eff862860af706e6ef4e6ce"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rocs-devel-26.08.1-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_rocs-devel;unpack=0"
SRC_URI[x86_64_v2_rocs-devel.sha256sum] = "012a16bcd88e7d6d5f8703fcdd1f207c570a4839c2f371dfc6343da05ec144b2"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rocs-libs-26.08.1-1.el10_3.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_rocs-libs;unpack=0"
SRC_URI[x86_64_v2_rocs-libs.sha256sum] = "105bd5806cdf9f14216baed1003ab82227f958dab01717805fc11f357b8c7e72"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/r/rocs-26.08.1-1.el10_3.aarch64.rpm;name=aarch64_rocs;unpack=0"
SRC_URI[aarch64_rocs.sha256sum] = "89586633e1e4faa313120b46900df72553a65ea821a7a3b963d8869f6148bd8c"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/r/rocs-devel-26.08.1-1.el10_3.aarch64.rpm;name=aarch64_rocs-devel;unpack=0"
SRC_URI[aarch64_rocs-devel.sha256sum] = "ebefb4cae5335dc81c75adaf9820d283707b1f6be043c01a6cc559cc9ddb0a83"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/r/rocs-libs-26.08.1-1.el10_3.aarch64.rpm;name=aarch64_rocs-libs;unpack=0"
SRC_URI[aarch64_rocs-libs.sha256sum] = "477c833930701b2f18c67adc9c39c7917e9e4126a25148308b7f02cdc54050f7"

RDEPENDS:rocs = " \
 glibc \
 kf6-karchive \
 kf6-kcompletion \
 kf6-kconfig \
 kf6-kconfigwidgets \
 kf6-kcoreaddons \
 kf6-kcrash \
 kf6-ki18n \
 kf6-kitemviews \
 kf6-kparts \
 kf6-ktexteditor \
 kf6-ktexttemplate \
 kf6-ktextwidgets \
 kf6-kwidgetsaddons \
 kf6-kxmlgui \
 libgcc \
 libstdc++ \
 qt6-qtbase \
 qt6-qtbase-gui \
 qt6-qtdeclarative \
 rocs-libs \
 "
RDEPENDS:rocs-devel = " \
 rocs-libs \
 "
RDEPENDS:rocs-libs = " \
 glibc \
 kf6-kcoreaddons \
 kf6-ki18n \
 kf6-kitemviews \
 kf6-kwidgetsaddons \
 libgcc \
 libstdc++ \
 qt6-qtbase \
 qt6-qtbase-gui \
 qt6-qtdeclarative \
 rocs \
 "
