# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rs"
PV = "20200313"
PR = "7.el10_0"
PACKAGES = " \
 rs \
 "

SRC_URI = "${EPELSRC_MIRROR}/Packages/r/rs-20200313-7.el10_0.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "0395aa8554bf1e4314acc7a6a00411cfdef2224f67c51d88f1a000f6c942129a"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rs-20200313-7.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_rs;unpack=0"
SRC_URI[x86_64_v2_rs.sha256sum] = "89dc4ac020fc62d6b50340205e94d6de2f79bdf05ca1e137df4b125ca5f997cd"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/r/rs-20200313-7.el10_0.aarch64.rpm;name=aarch64_rs;unpack=0"
SRC_URI[aarch64_rs.sha256sum] = "0b847009fc93bbc695c4d993966531848fbe3f6906b548401974beb2ba12b1bc"

RDEPENDS:rs = " \
 glibc \
 "
