# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rubygem-ffi"
PV = "1.15.5"
PR = "11.el10_0"
PACKAGES = " \
 rubygem-ffi \
 rubygem-ffi-doc \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rubygem-ffi-1.15.5-11.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d43a9adfd3ee05e6dca2d38b067f64b0abccd24f2e0f9f77169219c61bc02752"

URI_x86_64_v2_rubygem-ffi = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rubygem-ffi-1.15.5-11.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_rubygem-ffi;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rubygem-ffi}"
SRC_URI[x86_64_v2_rubygem-ffi.sha256sum] = "2dc63c52f404fcb136d4a38511614dd7a21588245c3d835c1f49317359515e98"

URI_x86_64_v2_rubygem-ffi-doc = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rubygem-ffi-doc-1.15.5-11.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rubygem-ffi-doc;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rubygem-ffi-doc}"
SRC_URI[x86_64_v2_rubygem-ffi-doc.sha256sum] = "00c5e03f625270e759c8ceb4b9e100dd6828d5d777c249bd8536d5f6ea0dfae6"

URI_aarch64_rubygem-ffi = "${EPEL_MIRROR}/aarch64/Packages/r/rubygem-ffi-1.15.5-11.el10_0.aarch64.rpm;name=aarch64_rubygem-ffi;unpack=0"
SRC_URI:append = " ${URI_aarch64_rubygem-ffi}"
SRC_URI[aarch64_rubygem-ffi.sha256sum] = "d16061eb1763001c547676d0fb1f5135c3a9b13f8276594f03d3bd5327bf8e13"

URI_aarch64_rubygem-ffi-doc = "${EPEL_MIRROR}/aarch64/Packages/r/rubygem-ffi-doc-1.15.5-11.el10_0.noarch.rpm;name=aarch64_rubygem-ffi-doc;unpack=0"
SRC_URI:append = " ${URI_aarch64_rubygem-ffi-doc}"
SRC_URI[aarch64_rubygem-ffi-doc.sha256sum] = "e9ac529ae47e47d524eee6099203fb362a7ea0289d534eec04d1447f16fbe12a"

RDEPENDS:rubygem-ffi = " \
 glibc \
 libffi \
 ruby-libs \
 rubygems \
 "
RDEPENDS:rubygem-ffi-doc = " \
 rubygem-ffi \
 "
