# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-asn1_derive"
PV = "0.24.1"
PR = "1.el10_2"
PACKAGES = " \
 rust-asn1_derive+default-devel \
 rust-asn1_derive-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-asn1_derive-0.24.1-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ceea1d3bcea619ad8b183f39777a39f4298902a7a5e3ebc55098d46cfb1b5c0d"

URI_x86_64_v2_rust-asn1_derive+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-asn1_derive+default-devel-0.24.1-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-asn1_derive+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-asn1_derive+default-devel}"
SRC_URI[x86_64_v2_rust-asn1_derive+default-devel.sha256sum] = "b399cf0dcba5edf9220b922a696d67ab9efa6c5908fe4d9af9e2be172392dfe0"

URI_x86_64_v2_rust-asn1_derive-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-asn1_derive-devel-0.24.1-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-asn1_derive-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-asn1_derive-devel}"
SRC_URI[x86_64_v2_rust-asn1_derive-devel.sha256sum] = "a3c802d648ce74418e7684630a420c85ac019da2966710560dab7627ca98ef74"

URI_aarch64_rust-asn1_derive+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-asn1_derive+default-devel-0.24.1-1.el10_2.noarch.rpm;name=aarch64_rust-asn1_derive+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-asn1_derive+default-devel}"
SRC_URI[aarch64_rust-asn1_derive+default-devel.sha256sum] = "122c9cb9562d7632f9a43b36c9710fdcb1a940a96f7643b9053faa35d76ed070"

URI_aarch64_rust-asn1_derive-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-asn1_derive-devel-0.24.1-1.el10_2.noarch.rpm;name=aarch64_rust-asn1_derive-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-asn1_derive-devel}"
SRC_URI[aarch64_rust-asn1_derive-devel.sha256sum] = "63f105850eab01323318aa76fcdc769001ab8d289a9cedd596a4645057157f23"

RDEPENDS:rust-asn1_derive+default-devel = " \
 cargo \
 rust-asn1_derive-devel \
 "
RDEPENDS:rust-asn1_derive-devel = " \
 cargo \
 rust \
 rust-proc-macro2+default-devel \
 rust-quote+default-devel \
 rust-syn+default-devel \
 "
