# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-libc"
PV = "0.2.183"
PR = "1.el10_1"
PACKAGES = " \
 rust-libc+align-devel \
 rust-libc+const-extern-fn-devel \
 rust-libc+default-devel \
 rust-libc+extra_traits-devel \
 rust-libc+std-devel \
 rust-libc+use_std-devel \
 rust-libc-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-libc-0.2.183-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "9751dbdd15ec7d9f8ba2fee5212963730dd4872f8e27ac28e21c76ad57c5ad29"

URI_x86_64_v2_rust-libc+align-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libc+align-devel-0.2.183-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libc+align-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libc+align-devel}"
SRC_URI[x86_64_v2_rust-libc+align-devel.sha256sum] = "15adc27bb1725e7e1c98da475c73658ef8db0be9991ea8a975c0133646e12073"

URI_x86_64_v2_rust-libc+const-extern-fn-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libc+const-extern-fn-devel-0.2.183-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libc+const-extern-fn-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libc+const-extern-fn-devel}"
SRC_URI[x86_64_v2_rust-libc+const-extern-fn-devel.sha256sum] = "d2cab8ae44d259a4412ce42d5c62619bfe371aaa8dc39d3ccc31568553344c8c"

URI_x86_64_v2_rust-libc+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libc+default-devel-0.2.183-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libc+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libc+default-devel}"
SRC_URI[x86_64_v2_rust-libc+default-devel.sha256sum] = "703e54ad704ea9829229b1758a85939b7225cdb48d15315cad29a17b3aad4c3f"

URI_x86_64_v2_rust-libc+extra_traits-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libc+extra_traits-devel-0.2.183-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libc+extra_traits-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libc+extra_traits-devel}"
SRC_URI[x86_64_v2_rust-libc+extra_traits-devel.sha256sum] = "92b95f5de2e2e0f6bef1229ae5779010206c9354a8bbc9860926372f70c05863"

URI_x86_64_v2_rust-libc+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libc+std-devel-0.2.183-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libc+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libc+std-devel}"
SRC_URI[x86_64_v2_rust-libc+std-devel.sha256sum] = "7da92075cf472a02c8cf2bc98ec7dce8eb534a9043098905250726dcfb67ff21"

URI_x86_64_v2_rust-libc+use_std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libc+use_std-devel-0.2.183-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libc+use_std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libc+use_std-devel}"
SRC_URI[x86_64_v2_rust-libc+use_std-devel.sha256sum] = "c036d16159f581991cd33689b5e6fca6cb4c3e412ded64dadc7e29c4b2a58b77"

URI_x86_64_v2_rust-libc-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libc-devel-0.2.183-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libc-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libc-devel}"
SRC_URI[x86_64_v2_rust-libc-devel.sha256sum] = "bb157ad82151d43d0df1bb874028ce2a6e9295e5b918ef74933ebf98d795a06d"

URI_aarch64_rust-libc+align-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libc+align-devel-0.2.183-1.el10_1.noarch.rpm;name=aarch64_rust-libc+align-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libc+align-devel}"
SRC_URI[aarch64_rust-libc+align-devel.sha256sum] = "a0551ae343e6d4e391ff86530f86fdab437d40020dcb0f7025c1e7973b7bb1e7"

URI_aarch64_rust-libc+const-extern-fn-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libc+const-extern-fn-devel-0.2.183-1.el10_1.noarch.rpm;name=aarch64_rust-libc+const-extern-fn-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libc+const-extern-fn-devel}"
SRC_URI[aarch64_rust-libc+const-extern-fn-devel.sha256sum] = "dccebda5abefa539dff1175f9dc8935b75129fd371fc67aa445713c74c5af6a4"

URI_aarch64_rust-libc+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libc+default-devel-0.2.183-1.el10_1.noarch.rpm;name=aarch64_rust-libc+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libc+default-devel}"
SRC_URI[aarch64_rust-libc+default-devel.sha256sum] = "1cfde836f1bfadc3f48a94ee4f4b308698f1fb9751e9d2f62dae00de4ec8499e"

URI_aarch64_rust-libc+extra_traits-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libc+extra_traits-devel-0.2.183-1.el10_1.noarch.rpm;name=aarch64_rust-libc+extra_traits-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libc+extra_traits-devel}"
SRC_URI[aarch64_rust-libc+extra_traits-devel.sha256sum] = "df6fa4c717b6af24d8bfb57169da3d6ebe8c3d2e44e5a71eea105ba6f28e6507"

URI_aarch64_rust-libc+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libc+std-devel-0.2.183-1.el10_1.noarch.rpm;name=aarch64_rust-libc+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libc+std-devel}"
SRC_URI[aarch64_rust-libc+std-devel.sha256sum] = "73c201d724486c1e1a0e39ebdada2210c4017de9e935ab058372a43d1300299a"

URI_aarch64_rust-libc+use_std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libc+use_std-devel-0.2.183-1.el10_1.noarch.rpm;name=aarch64_rust-libc+use_std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libc+use_std-devel}"
SRC_URI[aarch64_rust-libc+use_std-devel.sha256sum] = "6c00b27abaf0f23ced095a4d69819effe936b53f73e8756cb580eb901d92095e"

URI_aarch64_rust-libc-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libc-devel-0.2.183-1.el10_1.noarch.rpm;name=aarch64_rust-libc-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libc-devel}"
SRC_URI[aarch64_rust-libc-devel.sha256sum] = "a7616ebfa5f9152603e2ee4cbf7a1d9a51e252203e26b7f0883b67c26b3574d3"

RDEPENDS:rust-libc+align-devel = " \
 cargo \
 rust-libc-devel \
 "
RDEPENDS:rust-libc+const-extern-fn-devel = " \
 cargo \
 rust-libc-devel \
 "
RDEPENDS:rust-libc+default-devel = " \
 cargo \
 rust-libc+std-devel \
 rust-libc-devel \
 "
RDEPENDS:rust-libc+extra_traits-devel = " \
 cargo \
 rust-libc-devel \
 "
RDEPENDS:rust-libc+std-devel = " \
 cargo \
 rust-libc-devel \
 "
RDEPENDS:rust-libc+use_std-devel = " \
 cargo \
 rust-libc+std-devel \
 rust-libc-devel \
 "
RDEPENDS:rust-libc-devel = " \
 cargo \
 glibc-devel \
 rust \
 "
