# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-parking_lot_core"
PV = "0.9.12"
PR = "1.el10_2"
PACKAGES = " \
 rust-parking_lot_core+backtrace-devel \
 rust-parking_lot_core+deadlock_detection-devel \
 rust-parking_lot_core+default-devel \
 rust-parking_lot_core+nightly-devel \
 rust-parking_lot_core+petgraph-devel \
 rust-parking_lot_core-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-parking_lot_core-0.9.12-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a5bcfa2f176462bd44dc567fa0499de77ac80e329e4ed8ce5b809d516822fb9f"

URI_x86_64_v2_rust-parking_lot_core+backtrace-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-parking_lot_core+backtrace-devel-0.9.12-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-parking_lot_core+backtrace-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-parking_lot_core+backtrace-devel}"
SRC_URI[x86_64_v2_rust-parking_lot_core+backtrace-devel.sha256sum] = "d83d476d4b5e9a7afd97188c497247a2754e3f331a9469bbe026154b251fa584"

URI_x86_64_v2_rust-parking_lot_core+deadlock_detection-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-parking_lot_core+deadlock_detection-devel-0.9.12-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-parking_lot_core+deadlock_detection-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-parking_lot_core+deadlock_detection-devel}"
SRC_URI[x86_64_v2_rust-parking_lot_core+deadlock_detection-devel.sha256sum] = "ae88c8fa2b411dee369747dee0cfdbd6a7ba796a9f685fe590de00cda41fdf27"

URI_x86_64_v2_rust-parking_lot_core+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-parking_lot_core+default-devel-0.9.12-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-parking_lot_core+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-parking_lot_core+default-devel}"
SRC_URI[x86_64_v2_rust-parking_lot_core+default-devel.sha256sum] = "b3444e1f8d2ff8d8322126249a7b0b815a49ddc1b390cb5714c54192e5a60534"

URI_x86_64_v2_rust-parking_lot_core+nightly-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-parking_lot_core+nightly-devel-0.9.12-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-parking_lot_core+nightly-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-parking_lot_core+nightly-devel}"
SRC_URI[x86_64_v2_rust-parking_lot_core+nightly-devel.sha256sum] = "1d18e150eaab1b9774ba04cc709aaaa32e63cdeab203efe1587e0d22ac9b305c"

URI_x86_64_v2_rust-parking_lot_core+petgraph-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-parking_lot_core+petgraph-devel-0.9.12-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-parking_lot_core+petgraph-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-parking_lot_core+petgraph-devel}"
SRC_URI[x86_64_v2_rust-parking_lot_core+petgraph-devel.sha256sum] = "2f298fa5e36dbdb40e048b33810c4018654f2d42fd5710ead167d84f17618699"

URI_x86_64_v2_rust-parking_lot_core-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-parking_lot_core-devel-0.9.12-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-parking_lot_core-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-parking_lot_core-devel}"
SRC_URI[x86_64_v2_rust-parking_lot_core-devel.sha256sum] = "30d38d270dba9518ac85fd29d85c28594929d751ecf5a0d142c609ec9a05976c"

URI_aarch64_rust-parking_lot_core+backtrace-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-parking_lot_core+backtrace-devel-0.9.12-1.el10_2.noarch.rpm;name=aarch64_rust-parking_lot_core+backtrace-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-parking_lot_core+backtrace-devel}"
SRC_URI[aarch64_rust-parking_lot_core+backtrace-devel.sha256sum] = "c5cf71d9d400c28b1e1414b68fd6102fc728e7fd3f6d6ce7373da4ef9544bf32"

URI_aarch64_rust-parking_lot_core+deadlock_detection-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-parking_lot_core+deadlock_detection-devel-0.9.12-1.el10_2.noarch.rpm;name=aarch64_rust-parking_lot_core+deadlock_detection-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-parking_lot_core+deadlock_detection-devel}"
SRC_URI[aarch64_rust-parking_lot_core+deadlock_detection-devel.sha256sum] = "831c2cce3ad6630929be5f6373a6beb8d7d126161d8ccaa2fc0da082b87aa1c1"

URI_aarch64_rust-parking_lot_core+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-parking_lot_core+default-devel-0.9.12-1.el10_2.noarch.rpm;name=aarch64_rust-parking_lot_core+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-parking_lot_core+default-devel}"
SRC_URI[aarch64_rust-parking_lot_core+default-devel.sha256sum] = "fb3deb633ea168f486f56287d5577e257549c06ec2bbca2dd92e94c8d33c7bbc"

URI_aarch64_rust-parking_lot_core+nightly-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-parking_lot_core+nightly-devel-0.9.12-1.el10_2.noarch.rpm;name=aarch64_rust-parking_lot_core+nightly-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-parking_lot_core+nightly-devel}"
SRC_URI[aarch64_rust-parking_lot_core+nightly-devel.sha256sum] = "6cf79eb76e91707c8ea53d7e7ed918d8071f91e28fc0b047934a12425d3ae569"

URI_aarch64_rust-parking_lot_core+petgraph-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-parking_lot_core+petgraph-devel-0.9.12-1.el10_2.noarch.rpm;name=aarch64_rust-parking_lot_core+petgraph-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-parking_lot_core+petgraph-devel}"
SRC_URI[aarch64_rust-parking_lot_core+petgraph-devel.sha256sum] = "0c47a4765e69a84f47ef1eae430b6499df30ecc985f8bbce37f0e28d9cc3fad6"

URI_aarch64_rust-parking_lot_core-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-parking_lot_core-devel-0.9.12-1.el10_2.noarch.rpm;name=aarch64_rust-parking_lot_core-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-parking_lot_core-devel}"
SRC_URI[aarch64_rust-parking_lot_core-devel.sha256sum] = "e5f5a6b793bad6eed220d8e126a9b26fe0807d1ab7b0af8c8dc67a07808d6695"

RDEPENDS:rust-parking_lot_core+backtrace-devel = " \
 cargo \
 rust-backtrace+default-devel \
 rust-parking_lot_core-devel \
 "
RDEPENDS:rust-parking_lot_core+deadlock_detection-devel = " \
 cargo \
 rust-parking_lot_core+backtrace-devel \
 rust-parking_lot_core+petgraph-devel \
 rust-parking_lot_core-devel \
 "
RDEPENDS:rust-parking_lot_core+default-devel = " \
 cargo \
 rust-parking_lot_core-devel \
 "
RDEPENDS:rust-parking_lot_core+nightly-devel = " \
 cargo \
 rust-parking_lot_core-devel \
 "
RDEPENDS:rust-parking_lot_core+petgraph-devel = " \
 cargo \
 rust-parking_lot_core-devel \
 rust-petgraph0.6+default-devel \
 "
RDEPENDS:rust-parking_lot_core-devel = " \
 cargo \
 rust \
 rust-cfg-if+default-devel \
 rust-libc+default-devel \
 rust-smallvec+default-devel \
 "
