# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-is-docker"
PV = "0.2.0"
PR = "5.el10_1"
PACKAGES = " \
 rust-is-docker+default-devel \
 rust-is-docker-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-is-docker-0.2.0-5.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "fdb5c199f685795748627ffc43355d65ec536a959ca6cf3be35386cfe7939a12"

URI_x86_64_v2_rust-is-docker+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-is-docker+default-devel-0.2.0-5.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-is-docker+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-is-docker+default-devel}"
SRC_URI[x86_64_v2_rust-is-docker+default-devel.sha256sum] = "b47a1d3513756aa64d690727620cf156067619becf66313d3e0dc19e953d1b03"

URI_x86_64_v2_rust-is-docker-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-is-docker-devel-0.2.0-5.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-is-docker-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-is-docker-devel}"
SRC_URI[x86_64_v2_rust-is-docker-devel.sha256sum] = "16b125b3ee05074aa60da6da4a78d887f5b8fdbcbafb977d3bf6201098223c53"

URI_aarch64_rust-is-docker+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-is-docker+default-devel-0.2.0-5.el10_1.noarch.rpm;name=aarch64_rust-is-docker+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-is-docker+default-devel}"
SRC_URI[aarch64_rust-is-docker+default-devel.sha256sum] = "17551f8f89ab61650950e11ea0947337b1b3aa8297c11d84509e675ccb87cffd"

URI_aarch64_rust-is-docker-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-is-docker-devel-0.2.0-5.el10_1.noarch.rpm;name=aarch64_rust-is-docker-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-is-docker-devel}"
SRC_URI[aarch64_rust-is-docker-devel.sha256sum] = "243f6530f904361988e2021ffab8439e26323bd25b3ee0f7d68ef4298d41040e"

RDEPENDS:rust-is-docker+default-devel = " \
 cargo \
 rust-is-docker-devel \
 "
RDEPENDS:rust-is-docker-devel = " \
 cargo \
 rust-once_cell+default-devel \
 "
