# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-char_str"
PV = "0.0.2"
PR = "1.el10_3"
PACKAGES = " \
 rust-char_str+arbitrary-devel \
 rust-char_str+default-devel \
 rust-char_str+get-size-devel \
 rust-char_str+serde-devel \
 rust-char_str+std-devel \
 rust-char_str-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-char_str-0.0.2-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c8a046734b991c910b2f64a304bc6db00264426b8361603bea865837e4e4143a"

URI_aarch64_rust-char_str+arbitrary-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-char_str+arbitrary-devel-0.0.2-1.el10_3.noarch.rpm;name=aarch64_rust-char_str+arbitrary-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-char_str+arbitrary-devel}"
SRC_URI[aarch64_rust-char_str+arbitrary-devel.sha256sum] = "934101caf6a1760356172a8848c4f1ae9361db5f7fac502c142782eba749a08d"

URI_aarch64_rust-char_str+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-char_str+default-devel-0.0.2-1.el10_3.noarch.rpm;name=aarch64_rust-char_str+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-char_str+default-devel}"
SRC_URI[aarch64_rust-char_str+default-devel.sha256sum] = "0131184e30e8358a224240e997495882eaf2a84f2ff8a90f3cbb4b400d53246d"

URI_aarch64_rust-char_str+get-size-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-char_str+get-size-devel-0.0.2-1.el10_3.noarch.rpm;name=aarch64_rust-char_str+get-size-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-char_str+get-size-devel}"
SRC_URI[aarch64_rust-char_str+get-size-devel.sha256sum] = "11437121be7a0974e30996e43733626cd07cf665cb49b94480272be918acedb2"

URI_aarch64_rust-char_str+serde-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-char_str+serde-devel-0.0.2-1.el10_3.noarch.rpm;name=aarch64_rust-char_str+serde-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-char_str+serde-devel}"
SRC_URI[aarch64_rust-char_str+serde-devel.sha256sum] = "d707e7766ab17b994000f4f131106a17a6a30432eaa47218bf7d907817895464"

URI_aarch64_rust-char_str+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-char_str+std-devel-0.0.2-1.el10_3.noarch.rpm;name=aarch64_rust-char_str+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-char_str+std-devel}"
SRC_URI[aarch64_rust-char_str+std-devel.sha256sum] = "3bae10b80d9809da16e4b6a59c37f2b793cac0b5d286c72b1a632b754fdefc1d"

URI_aarch64_rust-char_str-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-char_str-devel-0.0.2-1.el10_3.noarch.rpm;name=aarch64_rust-char_str-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-char_str-devel}"
SRC_URI[aarch64_rust-char_str-devel.sha256sum] = "8bd28454d7066ccc2c5229edb883c2a7e06b7f24f21ead941a6758089158689c"

RDEPENDS:rust-char_str+arbitrary-devel = " \
 cargo \
 rust-arbitrary-devel \
 rust-char_str-devel \
 "
RDEPENDS:rust-char_str+default-devel = " \
 cargo \
 rust-char_str+std-devel \
 rust-char_str-devel \
 "
RDEPENDS:rust-char_str+get-size-devel = " \
 cargo \
 rust-char_str+std-devel \
 rust-char_str-devel \
 rust-get-size2+default-devel \
 "
RDEPENDS:rust-char_str+serde-devel = " \
 cargo \
 rust-char_str-devel \
 rust-serde_core-devel \
 "
RDEPENDS:rust-char_str+std-devel = " \
 cargo \
 rust-char_str-devel \
 "
RDEPENDS:rust-char_str-devel = " \
 cargo \
 rust-castaway+alloc-devel \
 rust-castaway-devel \
 rust-itoa+default-devel \
 rust-ryu+default-devel \
 "
