# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-enum_dispatch"
PV = "0.3.13"
PR = "2.el10_0"
PACKAGES = " \
 rust-enum_dispatch+default-devel \
 rust-enum_dispatch-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-enum_dispatch-0.3.13-2.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5347dffeb2238f87eb068f738f2c79f54553ffb8c5768f7aeb4d27ec4d1d3be3"

URI_x86_64_v2_rust-enum_dispatch+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-enum_dispatch+default-devel-0.3.13-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-enum_dispatch+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-enum_dispatch+default-devel}"
SRC_URI[x86_64_v2_rust-enum_dispatch+default-devel.sha256sum] = "fa654977fd5e00472e86f9e43c24d46ef70d4235cd03914626515dba720302c0"

URI_x86_64_v2_rust-enum_dispatch-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-enum_dispatch-devel-0.3.13-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-enum_dispatch-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-enum_dispatch-devel}"
SRC_URI[x86_64_v2_rust-enum_dispatch-devel.sha256sum] = "05b04c4ecb9e7904fec33ead7119c94b2f089220099582bc57d1e9621c92a3b0"

URI_aarch64_rust-enum_dispatch+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-enum_dispatch+default-devel-0.3.13-2.el10_0.noarch.rpm;name=aarch64_rust-enum_dispatch+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-enum_dispatch+default-devel}"
SRC_URI[aarch64_rust-enum_dispatch+default-devel.sha256sum] = "e6a3e4c264c0288c7501cedd1a1c0961d41d62aa5acecdbcd703c07750f77729"

URI_aarch64_rust-enum_dispatch-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-enum_dispatch-devel-0.3.13-2.el10_0.noarch.rpm;name=aarch64_rust-enum_dispatch-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-enum_dispatch-devel}"
SRC_URI[aarch64_rust-enum_dispatch-devel.sha256sum] = "9e515c746292545042179de634fd8c09572ca9dc364e53926002771baf1be415"

RDEPENDS:rust-enum_dispatch+default-devel = " \
 cargo \
 rust-enum_dispatch-devel \
 "
RDEPENDS:rust-enum_dispatch-devel = " \
 bash \
 cargo \
 rust-once_cell+default-devel \
 rust-proc-macro2+default-devel \
 rust-quote+default-devel \
 rust-syn2+default-devel \
 rust-syn2+full-devel \
 "
