# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-adler32"
PV = "1.2.0"
PR = "13.el10_0"
PACKAGES = " \
 rust-adler32+default-devel \
 rust-adler32+std-devel \
 rust-adler32-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-adler32-1.2.0-13.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "51b13ee0804d4a0c280085495a10cc5d7c06b0d798d2c3fe3ff431a594d3c3e2"

URI_x86_64_v2_rust-adler32+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-adler32+default-devel-1.2.0-13.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-adler32+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-adler32+default-devel}"
SRC_URI[x86_64_v2_rust-adler32+default-devel.sha256sum] = "124f799c4a548f7b74074d3321abaa3323947d1fba71e60971f4f5f88159f9e7"

URI_x86_64_v2_rust-adler32+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-adler32+std-devel-1.2.0-13.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-adler32+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-adler32+std-devel}"
SRC_URI[x86_64_v2_rust-adler32+std-devel.sha256sum] = "c04e9b26df9cf701794475d73ba480cf7f5ad0762ae4823768dc6c55a9b74529"

URI_x86_64_v2_rust-adler32-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-adler32-devel-1.2.0-13.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-adler32-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-adler32-devel}"
SRC_URI[x86_64_v2_rust-adler32-devel.sha256sum] = "68b5f15ba5c7fde148761ee54bfd589ed75865fd531aef0463ad82f1b0420452"

URI_aarch64_rust-adler32+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-adler32+default-devel-1.2.0-13.el10_0.noarch.rpm;name=aarch64_rust-adler32+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-adler32+default-devel}"
SRC_URI[aarch64_rust-adler32+default-devel.sha256sum] = "2ee342dcfbec93d796b402d4fbbf0aa053347e5078324bc80188de6b62474dc7"

URI_aarch64_rust-adler32+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-adler32+std-devel-1.2.0-13.el10_0.noarch.rpm;name=aarch64_rust-adler32+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-adler32+std-devel}"
SRC_URI[aarch64_rust-adler32+std-devel.sha256sum] = "dc0826a5fb8bf25c87f2f24eebd999e7a9aa7a01e01828b028fb8e0ff0fd545a"

URI_aarch64_rust-adler32-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-adler32-devel-1.2.0-13.el10_0.noarch.rpm;name=aarch64_rust-adler32-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-adler32-devel}"
SRC_URI[aarch64_rust-adler32-devel.sha256sum] = "ffc0f603fc1bc7e0b43660f7d7bfc535bf37166457112ac10b4b2eee24df8787"

RDEPENDS:rust-adler32+default-devel = " \
 cargo \
 rust-adler32+std-devel \
 rust-adler32-devel \
 "
RDEPENDS:rust-adler32+std-devel = " \
 cargo \
 rust-adler32-devel \
 "
RDEPENDS:rust-adler32-devel = " \
 cargo \
 "
