# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-simple_logger"
PV = "4.3.3"
PR = "3.el10_0"
PACKAGES = " \
 rust-simple_logger+colored-devel \
 rust-simple_logger+colors-devel \
 rust-simple_logger+default-devel \
 rust-simple_logger+nightly-devel \
 rust-simple_logger+stderr-devel \
 rust-simple_logger+threads-devel \
 rust-simple_logger+time-devel \
 rust-simple_logger+timestamps-devel \
 rust-simple_logger-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-simple_logger-4.3.3-3.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "cb6d4e2b5dc4cb110ae8d645ee3b6e68c489e98c3b54f7223c7a8da7ed06cd41"

URI_x86_64_v2_rust-simple_logger+colored-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-simple_logger+colored-devel-4.3.3-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-simple_logger+colored-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-simple_logger+colored-devel}"
SRC_URI[x86_64_v2_rust-simple_logger+colored-devel.sha256sum] = "ce783bdb55612f7e7179d4aca0409127bf0e1273026e3a4016273c54911ebf11"

URI_x86_64_v2_rust-simple_logger+colors-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-simple_logger+colors-devel-4.3.3-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-simple_logger+colors-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-simple_logger+colors-devel}"
SRC_URI[x86_64_v2_rust-simple_logger+colors-devel.sha256sum] = "337b7b8488fe4cd1243ae7f92aa0b21266039bbff872b53f7111f923a5278159"

URI_x86_64_v2_rust-simple_logger+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-simple_logger+default-devel-4.3.3-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-simple_logger+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-simple_logger+default-devel}"
SRC_URI[x86_64_v2_rust-simple_logger+default-devel.sha256sum] = "8c0f26f85811089a70cc846da009c3c6178506bd2f485db408ceaca5c4ae608c"

URI_x86_64_v2_rust-simple_logger+nightly-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-simple_logger+nightly-devel-4.3.3-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-simple_logger+nightly-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-simple_logger+nightly-devel}"
SRC_URI[x86_64_v2_rust-simple_logger+nightly-devel.sha256sum] = "c8b19d49a0516d72d62130816af38f93f68e2faa50c9dbb5d57360f28aa1cc4a"

URI_x86_64_v2_rust-simple_logger+stderr-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-simple_logger+stderr-devel-4.3.3-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-simple_logger+stderr-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-simple_logger+stderr-devel}"
SRC_URI[x86_64_v2_rust-simple_logger+stderr-devel.sha256sum] = "db40e9b5355acf0fc01ed9b99879a7a0fb8d0d6b7e5ac979928a5907f67d9c7e"

URI_x86_64_v2_rust-simple_logger+threads-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-simple_logger+threads-devel-4.3.3-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-simple_logger+threads-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-simple_logger+threads-devel}"
SRC_URI[x86_64_v2_rust-simple_logger+threads-devel.sha256sum] = "46bc5f111f2f25347e29328eb0d77d36f8856eb3ecc9d5f639202ec637d75905"

URI_x86_64_v2_rust-simple_logger+time-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-simple_logger+time-devel-4.3.3-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-simple_logger+time-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-simple_logger+time-devel}"
SRC_URI[x86_64_v2_rust-simple_logger+time-devel.sha256sum] = "d41002685e5f10f605c9a2c910b9cbc011bfd1332e3523f2649409c13ad46e7a"

URI_x86_64_v2_rust-simple_logger+timestamps-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-simple_logger+timestamps-devel-4.3.3-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-simple_logger+timestamps-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-simple_logger+timestamps-devel}"
SRC_URI[x86_64_v2_rust-simple_logger+timestamps-devel.sha256sum] = "e172e22dc22917abaa18bc92e250150abe9a84c0e6f09786bece66523fdeb92e"

URI_x86_64_v2_rust-simple_logger-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-simple_logger-devel-4.3.3-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-simple_logger-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-simple_logger-devel}"
SRC_URI[x86_64_v2_rust-simple_logger-devel.sha256sum] = "eb0182c19a8c515484446d911519281f3135a1a065ffa4b2f049ee0a9c7c824c"

URI_aarch64_rust-simple_logger+colored-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-simple_logger+colored-devel-4.3.3-3.el10_0.noarch.rpm;name=aarch64_rust-simple_logger+colored-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-simple_logger+colored-devel}"
SRC_URI[aarch64_rust-simple_logger+colored-devel.sha256sum] = "2be05ef16a82d6da624ce35494702c683c9e09785997b22d731638d3b1fdaeeb"

URI_aarch64_rust-simple_logger+colors-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-simple_logger+colors-devel-4.3.3-3.el10_0.noarch.rpm;name=aarch64_rust-simple_logger+colors-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-simple_logger+colors-devel}"
SRC_URI[aarch64_rust-simple_logger+colors-devel.sha256sum] = "5f181b19c719f4c5cf8754b0dca0167ec555e810bb95a99147cd3422f4d0ac7e"

URI_aarch64_rust-simple_logger+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-simple_logger+default-devel-4.3.3-3.el10_0.noarch.rpm;name=aarch64_rust-simple_logger+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-simple_logger+default-devel}"
SRC_URI[aarch64_rust-simple_logger+default-devel.sha256sum] = "1650e240ccd474e642edc211ad295c9fa20cf35bd7f7f5af66a5e09ad6553770"

URI_aarch64_rust-simple_logger+nightly-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-simple_logger+nightly-devel-4.3.3-3.el10_0.noarch.rpm;name=aarch64_rust-simple_logger+nightly-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-simple_logger+nightly-devel}"
SRC_URI[aarch64_rust-simple_logger+nightly-devel.sha256sum] = "4796d284b3a44805576abdbc14db54885470252d8eb30446e10c0ed8dc344c97"

URI_aarch64_rust-simple_logger+stderr-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-simple_logger+stderr-devel-4.3.3-3.el10_0.noarch.rpm;name=aarch64_rust-simple_logger+stderr-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-simple_logger+stderr-devel}"
SRC_URI[aarch64_rust-simple_logger+stderr-devel.sha256sum] = "7d957e09d40f5a03b0d0dd532c349ff02caa5560d59e2042237eeae79ffa9a40"

URI_aarch64_rust-simple_logger+threads-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-simple_logger+threads-devel-4.3.3-3.el10_0.noarch.rpm;name=aarch64_rust-simple_logger+threads-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-simple_logger+threads-devel}"
SRC_URI[aarch64_rust-simple_logger+threads-devel.sha256sum] = "48c949d3180c0bc81a8ed4205c891409024922899c00dfae98619a18d96616bc"

URI_aarch64_rust-simple_logger+time-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-simple_logger+time-devel-4.3.3-3.el10_0.noarch.rpm;name=aarch64_rust-simple_logger+time-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-simple_logger+time-devel}"
SRC_URI[aarch64_rust-simple_logger+time-devel.sha256sum] = "98c17d5cb1203b2dcc8a6685c3a21e17adbcfbc43327083d071323d667ece1f9"

URI_aarch64_rust-simple_logger+timestamps-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-simple_logger+timestamps-devel-4.3.3-3.el10_0.noarch.rpm;name=aarch64_rust-simple_logger+timestamps-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-simple_logger+timestamps-devel}"
SRC_URI[aarch64_rust-simple_logger+timestamps-devel.sha256sum] = "e6d70b3406ed19f2b76d218c302e2d28c3a5701ff2e21528c626241e2ea05d89"

URI_aarch64_rust-simple_logger-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-simple_logger-devel-4.3.3-3.el10_0.noarch.rpm;name=aarch64_rust-simple_logger-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-simple_logger-devel}"
SRC_URI[aarch64_rust-simple_logger-devel.sha256sum] = "682932bf8948652837b7aef4c68ff48b14a0d125b2b2340cacb423089724ad81"

RDEPENDS:rust-simple_logger+colored-devel = " \
 cargo \
 rust-colored2+default-devel \
 rust-simple_logger-devel \
 "
RDEPENDS:rust-simple_logger+colors-devel = " \
 cargo \
 rust-simple_logger+colored-devel \
 rust-simple_logger-devel \
 "
RDEPENDS:rust-simple_logger+default-devel = " \
 cargo \
 rust-simple_logger+colors-devel \
 rust-simple_logger+timestamps-devel \
 rust-simple_logger-devel \
 "
RDEPENDS:rust-simple_logger+nightly-devel = " \
 cargo \
 rust-simple_logger-devel \
 "
RDEPENDS:rust-simple_logger+stderr-devel = " \
 cargo \
 rust-simple_logger-devel \
 "
RDEPENDS:rust-simple_logger+threads-devel = " \
 cargo \
 rust-simple_logger-devel \
 "
RDEPENDS:rust-simple_logger+time-devel = " \
 cargo \
 rust-simple_logger-devel \
 rust-time+default-devel \
 rust-time+formatting-devel \
 rust-time+local-offset-devel \
 rust-time+macros-devel \
 "
RDEPENDS:rust-simple_logger+timestamps-devel = " \
 cargo \
 rust-simple_logger+time-devel \
 rust-simple_logger-devel \
 "
RDEPENDS:rust-simple_logger-devel = " \
 cargo \
 rust-log+default-devel \
 rust-log+std-devel \
 "
