# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-metrics-util"
PV = "0.20.1"
PR = "1.el10_3"
PACKAGES = " \
 rust-metrics-util+ahash-devel \
 rust-metrics-util+aho-corasick-devel \
 rust-metrics-util+crossbeam-epoch-devel \
 rust-metrics-util+crossbeam-utils-devel \
 rust-metrics-util+debugging-devel \
 rust-metrics-util+default-devel \
 rust-metrics-util+hashbrown-devel \
 rust-metrics-util+indexmap-devel \
 rust-metrics-util+layer-filter-devel \
 rust-metrics-util+layer-router-devel \
 rust-metrics-util+layers-devel \
 rust-metrics-util+ordered-float-devel \
 rust-metrics-util+quanta-devel \
 rust-metrics-util+radix_trie-devel \
 rust-metrics-util+rand-devel \
 rust-metrics-util+rand_xoshiro-devel \
 rust-metrics-util+recency-devel \
 rust-metrics-util+registry-devel \
 rust-metrics-util+sketches-ddsketch-devel \
 rust-metrics-util+storage-devel \
 rust-metrics-util-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-metrics-util-0.20.1-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a29479ffe7660d3c1c28c0e6cb256240905e5642e7e04adba7cdf216bd31eb8c"

URI_x86_64_v2_rust-metrics-util+ahash-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+ahash-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+ahash-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+ahash-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+ahash-devel.sha256sum] = "ccd1dc25685383de71dc88359772bebd248156b3cf58dc051f8e299ca69ae88a"

URI_x86_64_v2_rust-metrics-util+aho-corasick-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+aho-corasick-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+aho-corasick-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+aho-corasick-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+aho-corasick-devel.sha256sum] = "936e69ee8e7d7c926f97a4eed0eb070c4fd4483301852b94cff7890cbb23e9df"

URI_x86_64_v2_rust-metrics-util+crossbeam-epoch-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+crossbeam-epoch-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+crossbeam-epoch-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+crossbeam-epoch-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+crossbeam-epoch-devel.sha256sum] = "9f056a95150a2edd12244743c57d99777ebeeeb18df4b0eb570bc2bec32e362d"

URI_x86_64_v2_rust-metrics-util+crossbeam-utils-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+crossbeam-utils-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+crossbeam-utils-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+crossbeam-utils-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+crossbeam-utils-devel.sha256sum] = "77b0a3dd179e78527882ced794cdc862bdf95b49b94b347413d124179178c9be"

URI_x86_64_v2_rust-metrics-util+debugging-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+debugging-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+debugging-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+debugging-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+debugging-devel.sha256sum] = "eb7a53fdb13670fb872ce18a77cb6f0b3c4cc6565fb3fcc95b571eaa1eb73730"

URI_x86_64_v2_rust-metrics-util+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+default-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+default-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+default-devel.sha256sum] = "49aaf125b5a059e581c2f5c85251daceba2bb8dd54cf4070ababa3014ab4b074"

URI_x86_64_v2_rust-metrics-util+hashbrown-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+hashbrown-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+hashbrown-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+hashbrown-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+hashbrown-devel.sha256sum] = "071d0ff6435e7dacc6e6916051ba180c2f8a257410f59ab89b717b5ed644220f"

URI_x86_64_v2_rust-metrics-util+indexmap-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+indexmap-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+indexmap-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+indexmap-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+indexmap-devel.sha256sum] = "108f9be8a569e1d6efdce3975f0383c9ebf827dd464cc0f724f06dd716c4846b"

URI_x86_64_v2_rust-metrics-util+layer-filter-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+layer-filter-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+layer-filter-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+layer-filter-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+layer-filter-devel.sha256sum] = "062b15a202388ff6222eea1dfd83856dc654bf0a8ec7ffcc911f14a1be8e8efc"

URI_x86_64_v2_rust-metrics-util+layer-router-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+layer-router-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+layer-router-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+layer-router-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+layer-router-devel.sha256sum] = "382747173539194218d852337fad589f55b9da970aadb5c9d6225ba3d43c8cc8"

URI_x86_64_v2_rust-metrics-util+layers-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+layers-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+layers-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+layers-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+layers-devel.sha256sum] = "510b1db3faa043fdf92d88f91ee445c860b48bdf6322b854f10b94de7d153f2f"

URI_x86_64_v2_rust-metrics-util+ordered-float-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+ordered-float-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+ordered-float-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+ordered-float-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+ordered-float-devel.sha256sum] = "a745ad5b95c200340f7a07b95dcbf89b438af978b97afc345ece3bfc2236d1de"

URI_x86_64_v2_rust-metrics-util+quanta-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+quanta-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+quanta-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+quanta-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+quanta-devel.sha256sum] = "bdd503fd3043080dba992d20a9c225df1b3307c9956b250557dc99173fcb9d5f"

URI_x86_64_v2_rust-metrics-util+radix_trie-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+radix_trie-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+radix_trie-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+radix_trie-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+radix_trie-devel.sha256sum] = "d123b294de69e0478e01a45dfc9d8e229c4380d23fb76b3809fb507820f1c5bb"

URI_x86_64_v2_rust-metrics-util+rand-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+rand-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+rand-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+rand-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+rand-devel.sha256sum] = "a2727c1f0aaab45ff429faa6c90a27fca570b96c48a2649d0afbe51df1e21ae9"

URI_x86_64_v2_rust-metrics-util+rand_xoshiro-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+rand_xoshiro-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+rand_xoshiro-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+rand_xoshiro-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+rand_xoshiro-devel.sha256sum] = "eead15a5d9f924bc00e1f5b66106816ed1e5abd8ec4e121e445570bbbf406776"

URI_x86_64_v2_rust-metrics-util+recency-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+recency-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+recency-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+recency-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+recency-devel.sha256sum] = "fb595817413d2b5dfabfa3751645ff2c05618c6d74fd3e1e1b21b0533fd2a43a"

URI_x86_64_v2_rust-metrics-util+registry-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+registry-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+registry-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+registry-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+registry-devel.sha256sum] = "4752827962b041b5aa7f509d47838c60239cf4b787b79882f37881f1391e1b0b"

URI_x86_64_v2_rust-metrics-util+sketches-ddsketch-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+sketches-ddsketch-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+sketches-ddsketch-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+sketches-ddsketch-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+sketches-ddsketch-devel.sha256sum] = "00916218d719307c22a101354d5394bb22e3a6c5eb8a6e59cf420a3a65802d60"

URI_x86_64_v2_rust-metrics-util+storage-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util+storage-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util+storage-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util+storage-devel}"
SRC_URI[x86_64_v2_rust-metrics-util+storage-devel.sha256sum] = "c2aed9607242ac066c7a2adc53fb6cf53e39409bceb649b21aa708f2b530ef04"

URI_x86_64_v2_rust-metrics-util-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-metrics-util-devel-0.20.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-metrics-util-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-metrics-util-devel}"
SRC_URI[x86_64_v2_rust-metrics-util-devel.sha256sum] = "e67e56fdd33b4765b27745b556a9cc17b4dece14aa347551cf3678f37226dde9"

URI_aarch64_rust-metrics-util+ahash-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+ahash-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+ahash-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+ahash-devel}"
SRC_URI[aarch64_rust-metrics-util+ahash-devel.sha256sum] = "2108f9c0069b68023956257fc87a2d3a976f2153309afc3b8d54aceb29d76993"

URI_aarch64_rust-metrics-util+aho-corasick-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+aho-corasick-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+aho-corasick-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+aho-corasick-devel}"
SRC_URI[aarch64_rust-metrics-util+aho-corasick-devel.sha256sum] = "f2266410edb25f6a40d36c4a140b6e143cfc364162afdc3e3efaca4323f74842"

URI_aarch64_rust-metrics-util+crossbeam-epoch-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+crossbeam-epoch-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+crossbeam-epoch-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+crossbeam-epoch-devel}"
SRC_URI[aarch64_rust-metrics-util+crossbeam-epoch-devel.sha256sum] = "8452fce5c63ace723a3c607cc777bf236cc1ccc2feec0bbb486d3636ade212f6"

URI_aarch64_rust-metrics-util+crossbeam-utils-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+crossbeam-utils-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+crossbeam-utils-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+crossbeam-utils-devel}"
SRC_URI[aarch64_rust-metrics-util+crossbeam-utils-devel.sha256sum] = "e68b18e65a8399c85f95df5492f7b2db8a5c7b67d3aa35a8ad034540fbf5efb1"

URI_aarch64_rust-metrics-util+debugging-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+debugging-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+debugging-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+debugging-devel}"
SRC_URI[aarch64_rust-metrics-util+debugging-devel.sha256sum] = "e400e31a69e0be03662f2b9cfbc7fee8dffc11381faf4a8b6586c49294ca2a1a"

URI_aarch64_rust-metrics-util+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+default-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+default-devel}"
SRC_URI[aarch64_rust-metrics-util+default-devel.sha256sum] = "8d899aea30b646b9126c83af046741e2e0a8d2e6731ffef7a5f470b71bdc3a42"

URI_aarch64_rust-metrics-util+hashbrown-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+hashbrown-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+hashbrown-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+hashbrown-devel}"
SRC_URI[aarch64_rust-metrics-util+hashbrown-devel.sha256sum] = "2316a658e50fa2404fa663484102caa2207b53ec595e05b983938292df9e08e4"

URI_aarch64_rust-metrics-util+indexmap-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+indexmap-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+indexmap-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+indexmap-devel}"
SRC_URI[aarch64_rust-metrics-util+indexmap-devel.sha256sum] = "2ab2e66d2cdb467b5889df67c1f59058990f0d48d5c9eef1702143c1d8c62777"

URI_aarch64_rust-metrics-util+layer-filter-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+layer-filter-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+layer-filter-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+layer-filter-devel}"
SRC_URI[aarch64_rust-metrics-util+layer-filter-devel.sha256sum] = "131f65605cb6c6e38e625efa48b455daa7ba95bc6ae7023c2358f4b1026f3552"

URI_aarch64_rust-metrics-util+layer-router-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+layer-router-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+layer-router-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+layer-router-devel}"
SRC_URI[aarch64_rust-metrics-util+layer-router-devel.sha256sum] = "53b1bee03b099cc6595939c123dbc6014817501fa2b246d5fc3f1a36e3b95d83"

URI_aarch64_rust-metrics-util+layers-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+layers-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+layers-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+layers-devel}"
SRC_URI[aarch64_rust-metrics-util+layers-devel.sha256sum] = "7cef8ce1826af7ab230ae7f7f238bfd46a0f854b2d4a619c206122cc630c273d"

URI_aarch64_rust-metrics-util+ordered-float-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+ordered-float-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+ordered-float-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+ordered-float-devel}"
SRC_URI[aarch64_rust-metrics-util+ordered-float-devel.sha256sum] = "34cede28f36cfa29cc5159b22bceecf608d7f49b1f2a3bf0bdc707e78c7504cf"

URI_aarch64_rust-metrics-util+quanta-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+quanta-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+quanta-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+quanta-devel}"
SRC_URI[aarch64_rust-metrics-util+quanta-devel.sha256sum] = "a23427d1924e3bb49b488b2faaf5a8377c766a02559ecee7e5bcf40b3176b343"

URI_aarch64_rust-metrics-util+radix_trie-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+radix_trie-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+radix_trie-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+radix_trie-devel}"
SRC_URI[aarch64_rust-metrics-util+radix_trie-devel.sha256sum] = "ad46f8c11080bc3feac55b131116d1bef79c5e5ff9100ee65f66ee6e0ab693a3"

URI_aarch64_rust-metrics-util+rand-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+rand-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+rand-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+rand-devel}"
SRC_URI[aarch64_rust-metrics-util+rand-devel.sha256sum] = "50521c2ddaf4bd7006ac52d2467cc8b87bc4600f472d3d5d07c06ee37bf6f4ee"

URI_aarch64_rust-metrics-util+rand_xoshiro-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+rand_xoshiro-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+rand_xoshiro-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+rand_xoshiro-devel}"
SRC_URI[aarch64_rust-metrics-util+rand_xoshiro-devel.sha256sum] = "96be43fe9e64c4d0c7699f5ceae4e97c1c1a6955182def075046574f0a461cd5"

URI_aarch64_rust-metrics-util+recency-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+recency-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+recency-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+recency-devel}"
SRC_URI[aarch64_rust-metrics-util+recency-devel.sha256sum] = "cf8534e8fabfe8f29346f5900e7dc0eaf8e485d24b9ea47032f15226557e8e11"

URI_aarch64_rust-metrics-util+registry-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+registry-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+registry-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+registry-devel}"
SRC_URI[aarch64_rust-metrics-util+registry-devel.sha256sum] = "f18aa7bb090a40b967159500f4cf12ac65abb66a2dde8bcf42b67a838a09e627"

URI_aarch64_rust-metrics-util+sketches-ddsketch-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+sketches-ddsketch-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+sketches-ddsketch-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+sketches-ddsketch-devel}"
SRC_URI[aarch64_rust-metrics-util+sketches-ddsketch-devel.sha256sum] = "0cc6062dae25c9ca7bae7f9ff46a5d456749a99a6f1879b40f010712f4128656"

URI_aarch64_rust-metrics-util+storage-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util+storage-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util+storage-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util+storage-devel}"
SRC_URI[aarch64_rust-metrics-util+storage-devel.sha256sum] = "611900f94e18cb77e6c9cf5a3cb1a12fe13a0a96edd5abeda52642a5cff6deae"

URI_aarch64_rust-metrics-util-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-metrics-util-devel-0.20.1-1.el10_3.noarch.rpm;name=aarch64_rust-metrics-util-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-metrics-util-devel}"
SRC_URI[aarch64_rust-metrics-util-devel.sha256sum] = "1228cd1ec94d668e55949663c352730aa25372f9ad130562dfd1c9025d59f0ad"

RDEPENDS:rust-metrics-util+ahash-devel = " \
 cargo \
 rust-ahash-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+aho-corasick-devel = " \
 cargo \
 rust-aho-corasick+std-devel \
 rust-aho-corasick-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+crossbeam-epoch-devel = " \
 cargo \
 rust-crossbeam-epoch+alloc-devel \
 rust-crossbeam-epoch+std-devel \
 rust-crossbeam-epoch-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+crossbeam-utils-devel = " \
 cargo \
 rust-crossbeam-utils-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+debugging-devel = " \
 cargo \
 rust-metrics-util+indexmap-devel \
 rust-metrics-util+ordered-float-devel \
 rust-metrics-util+registry-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+default-devel = " \
 cargo \
 rust-metrics-util+debugging-devel \
 rust-metrics-util+layers-devel \
 rust-metrics-util+recency-devel \
 rust-metrics-util+registry-devel \
 rust-metrics-util+storage-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+hashbrown-devel = " \
 cargo \
 rust-hashbrown0.16+default-hasher-devel \
 rust-hashbrown0.16+raw-entry-devel \
 rust-hashbrown0.16-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+indexmap-devel = " \
 cargo \
 rust-indexmap+std-devel \
 rust-indexmap-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+layer-filter-devel = " \
 cargo \
 rust-metrics-util+aho-corasick-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+layer-router-devel = " \
 cargo \
 rust-metrics-util+radix_trie-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+layers-devel = " \
 cargo \
 rust-metrics-util+layer-filter-devel \
 rust-metrics-util+layer-router-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+ordered-float-devel = " \
 cargo \
 rust-metrics-util-devel \
 rust-ordered-float-devel \
 "
RDEPENDS:rust-metrics-util+quanta-devel = " \
 cargo \
 rust-metrics-util-devel \
 rust-quanta-devel \
 "
RDEPENDS:rust-metrics-util+radix_trie-devel = " \
 cargo \
 rust-metrics-util-devel \
 rust-radix_trie-devel \
 "
RDEPENDS:rust-metrics-util+rand-devel = " \
 cargo \
 rust-metrics-util-devel \
 rust-rand0.9+thread_rng-devel \
 rust-rand0.9-devel \
 "
RDEPENDS:rust-metrics-util+rand_xoshiro-devel = " \
 cargo \
 rust-metrics-util-devel \
 rust-rand_xoshiro0.7-devel \
 "
RDEPENDS:rust-metrics-util+recency-devel = " \
 cargo \
 rust-metrics-util+quanta-devel \
 rust-metrics-util+registry-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+registry-devel = " \
 cargo \
 rust-metrics-util+hashbrown-devel \
 rust-metrics-util+storage-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util+sketches-ddsketch-devel = " \
 cargo \
 rust-metrics-util-devel \
 rust-sketches-ddsketch-devel \
 "
RDEPENDS:rust-metrics-util+storage-devel = " \
 cargo \
 rust-metrics-util+crossbeam-epoch-devel \
 rust-metrics-util+crossbeam-utils-devel \
 rust-metrics-util+rand-devel \
 rust-metrics-util+rand_xoshiro-devel \
 rust-metrics-util+sketches-ddsketch-devel \
 rust-metrics-util-devel \
 "
RDEPENDS:rust-metrics-util-devel = " \
 cargo \
 rust \
 rust-metrics+default-devel \
 "
