# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-cfg-expr"
PV = "0.18.0"
PR = "1.el10_1"
PACKAGES = " \
 rust-cfg-expr+default-devel \
 rust-cfg-expr+target-lexicon-devel \
 rust-cfg-expr+targets-devel \
 rust-cfg-expr-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-cfg-expr-0.18.0-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e8e18279a1513f55005bd36d55ad18de6da21c7a8632df86e1096e906b3330e9"

URI_x86_64_v2_rust-cfg-expr+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-cfg-expr+default-devel-0.18.0-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-cfg-expr+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-cfg-expr+default-devel}"
SRC_URI[x86_64_v2_rust-cfg-expr+default-devel.sha256sum] = "58490f0e14ffa128fe6bc5e14cab3e64dd07ef68aa5ce618a6197eb80f484f74"
RPROVIDES:rust-cfg-expr+default-devel:x86_64_v2 = "virtual/crate_cfg-expr/default__ge_0.17.0_with_crate_cfg-expr/default__lt_0.21.0~"

URI_x86_64_v2_rust-cfg-expr+target-lexicon-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-cfg-expr+target-lexicon-devel-0.18.0-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-cfg-expr+target-lexicon-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-cfg-expr+target-lexicon-devel}"
SRC_URI[x86_64_v2_rust-cfg-expr+target-lexicon-devel.sha256sum] = "209cab7322ff40a39810664dc5d547efed08b4d47a9e94f1a1b4f6ab6742de4c"

URI_x86_64_v2_rust-cfg-expr+targets-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-cfg-expr+targets-devel-0.18.0-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-cfg-expr+targets-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-cfg-expr+targets-devel}"
SRC_URI[x86_64_v2_rust-cfg-expr+targets-devel.sha256sum] = "0a87acbe45b545658f55f31951eddbaf3bedaa8f0a91171bc8ce483a124db525"
RPROVIDES:rust-cfg-expr+targets-devel:x86_64_v2 = "virtual/crate_cfg-expr/targets__ge_0.17.0_with_crate_cfg-expr/targets__lt_0.21.0~"

URI_x86_64_v2_rust-cfg-expr-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-cfg-expr-devel-0.18.0-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-cfg-expr-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-cfg-expr-devel}"
SRC_URI[x86_64_v2_rust-cfg-expr-devel.sha256sum] = "b1611df604b61b098ed050ce5adc7e32b2308c297d0f38b18a21167638d883b8"

URI_aarch64_rust-cfg-expr+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-cfg-expr+default-devel-0.18.0-1.el10_1.noarch.rpm;name=aarch64_rust-cfg-expr+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-cfg-expr+default-devel}"
SRC_URI[aarch64_rust-cfg-expr+default-devel.sha256sum] = "3101b328f90ec732bffe6690d5c884a35ddd099ef7e0bf5fca468d20eea3bc8d"
RPROVIDES:rust-cfg-expr+default-devel:aarch64 = "virtual/crate_cfg-expr/default__ge_0.17.0_with_crate_cfg-expr/default__lt_0.21.0~"

URI_aarch64_rust-cfg-expr+target-lexicon-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-cfg-expr+target-lexicon-devel-0.18.0-1.el10_1.noarch.rpm;name=aarch64_rust-cfg-expr+target-lexicon-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-cfg-expr+target-lexicon-devel}"
SRC_URI[aarch64_rust-cfg-expr+target-lexicon-devel.sha256sum] = "dc555d8a3f7cd172d05b81ca247690f692191ea829d3967e4cb5e2ee337d580a"

URI_aarch64_rust-cfg-expr+targets-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-cfg-expr+targets-devel-0.18.0-1.el10_1.noarch.rpm;name=aarch64_rust-cfg-expr+targets-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-cfg-expr+targets-devel}"
SRC_URI[aarch64_rust-cfg-expr+targets-devel.sha256sum] = "7df59dfc29b1fa4d87a257467ab0e6d503276ee1b4e6554c34849caef87a9962"
RPROVIDES:rust-cfg-expr+targets-devel:aarch64 = "virtual/crate_cfg-expr/targets__ge_0.17.0_with_crate_cfg-expr/targets__lt_0.21.0~"

URI_aarch64_rust-cfg-expr-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-cfg-expr-devel-0.18.0-1.el10_1.noarch.rpm;name=aarch64_rust-cfg-expr-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-cfg-expr-devel}"
SRC_URI[aarch64_rust-cfg-expr-devel.sha256sum] = "98881977507a65ef35640126365609f8b477153992cdaf3d28a246530fff3faa"

RDEPENDS:rust-cfg-expr+default-devel = " \
 cargo \
 rust-cfg-expr-devel \
 "
RDEPENDS:rust-cfg-expr+target-lexicon-devel = " \
 cargo \
 rust-cfg-expr-devel \
 rust-target-lexicon+default-devel \
 "
RDEPENDS:rust-cfg-expr+targets-devel = " \
 cargo \
 rust-cfg-expr+target-lexicon-devel \
 rust-cfg-expr-devel \
 "
RDEPENDS:rust-cfg-expr-devel = " \
 cargo \
 rust \
 rust-smallvec+default-devel \
 "

PROVIDES:append:x86_64_v2 = " rpm/virtual/crate_cfg-expr/default__ge_0.17.0_with_crate_cfg-expr/default__lt_0.21.0~ rpm/virtual/crate_cfg-expr/targets__ge_0.17.0_with_crate_cfg-expr/targets__lt_0.21.0~"

PROVIDES:append:aarch64 = " rpm/virtual/crate_cfg-expr/default__ge_0.17.0_with_crate_cfg-expr/default__lt_0.21.0~ rpm/virtual/crate_cfg-expr/targets__ge_0.17.0_with_crate_cfg-expr/targets__lt_0.21.0~"
