# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-clap-cargo"
PV = "0.18.3"
PR = "3.el10_1"
PACKAGES = " \
 rust-clap-cargo+clap-devel \
 rust-clap-cargo+default-devel \
 rust-clap-cargo+testing_colors-devel \
 rust-clap-cargo-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-clap-cargo-0.18.3-3.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "40bf8e222bf98d38542b79e6ce9ff1ee4aebf23b52a3a8da863be4d8a8e26d59"

URI_x86_64_v2_rust-clap-cargo+clap-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-clap-cargo+clap-devel-0.18.3-3.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-clap-cargo+clap-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-clap-cargo+clap-devel}"
SRC_URI[x86_64_v2_rust-clap-cargo+clap-devel.sha256sum] = "6c354a4105a503836d4f06bd8e8fdc221ad2a8dd40b95287b78d5251d9b9ec2a"

URI_x86_64_v2_rust-clap-cargo+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-clap-cargo+default-devel-0.18.3-3.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-clap-cargo+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-clap-cargo+default-devel}"
SRC_URI[x86_64_v2_rust-clap-cargo+default-devel.sha256sum] = "6b3af02c4d84f09fbb789f1e724e54c1fdfd7727842bfe8b041c2ae92691f095"

URI_x86_64_v2_rust-clap-cargo+testing_colors-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-clap-cargo+testing_colors-devel-0.18.3-3.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-clap-cargo+testing_colors-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-clap-cargo+testing_colors-devel}"
SRC_URI[x86_64_v2_rust-clap-cargo+testing_colors-devel.sha256sum] = "6c722e6232d8fede10277f1fcd9ae0f75dafaa1a9b61fe5365c4744a14682ff8"

URI_x86_64_v2_rust-clap-cargo-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-clap-cargo-devel-0.18.3-3.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-clap-cargo-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-clap-cargo-devel}"
SRC_URI[x86_64_v2_rust-clap-cargo-devel.sha256sum] = "e9b595449da34d0b242a94b6965fb30a1a8c6fde48a3cbe8fcb8a455c0180e02"

URI_aarch64_rust-clap-cargo+clap-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-clap-cargo+clap-devel-0.18.3-3.el10_1.noarch.rpm;name=aarch64_rust-clap-cargo+clap-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-clap-cargo+clap-devel}"
SRC_URI[aarch64_rust-clap-cargo+clap-devel.sha256sum] = "cdcc6647ae884225e9c47d5c0032640bb7555360ca26a049a0bf1e1ebf363847"

URI_aarch64_rust-clap-cargo+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-clap-cargo+default-devel-0.18.3-3.el10_1.noarch.rpm;name=aarch64_rust-clap-cargo+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-clap-cargo+default-devel}"
SRC_URI[aarch64_rust-clap-cargo+default-devel.sha256sum] = "5a3924af939efcc2c4375eb41b88c972d1e8ca82a03f4599a05632356b7e1b8f"

URI_aarch64_rust-clap-cargo+testing_colors-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-clap-cargo+testing_colors-devel-0.18.3-3.el10_1.noarch.rpm;name=aarch64_rust-clap-cargo+testing_colors-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-clap-cargo+testing_colors-devel}"
SRC_URI[aarch64_rust-clap-cargo+testing_colors-devel.sha256sum] = "dd06c74bedb7428d60e92e97b14f76e566d2688a6974037f083dd3728065c6d2"

URI_aarch64_rust-clap-cargo-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-clap-cargo-devel-0.18.3-3.el10_1.noarch.rpm;name=aarch64_rust-clap-cargo-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-clap-cargo-devel}"
SRC_URI[aarch64_rust-clap-cargo-devel.sha256sum] = "dce73eda1b0a16efb02d0187fc2075f5a98936a1149fb99504a5eb95c084830d"

RDEPENDS:rust-clap-cargo+clap-devel = " \
 cargo \
 rust-clap+derive-devel \
 rust-clap+std-devel \
 rust-clap-cargo-devel \
 rust-clap-devel \
 "
RDEPENDS:rust-clap-cargo+default-devel = " \
 cargo \
 rust-clap-cargo+clap-devel \
 rust-clap-cargo-devel \
 "
RDEPENDS:rust-clap-cargo+testing_colors-devel = " \
 cargo \
 rust-clap-cargo-devel \
 "
RDEPENDS:rust-clap-cargo-devel = " \
 cargo \
 rust \
 rust-anstyle+default-devel \
 "
