# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-matchit0.8"
PV = "0.8.6"
PR = "1.el10_2"
PACKAGES = " \
 rust-matchit0.8+default-devel \
 rust-matchit0.8-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-matchit0.8-0.8.6-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b1a3fb9056a8c32ae6023a3351f5d51fa9ed46f149e4661e82b27ac7cad55dcb"

URI_x86_64_v2_rust-matchit0.8+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-matchit0.8+default-devel-0.8.6-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-matchit0.8+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-matchit0.8+default-devel}"
SRC_URI[x86_64_v2_rust-matchit0.8+default-devel.sha256sum] = "f6e3d943c756111ffc975fd675a1845d3ecb121c49e40aac309a59abe3d4c5b6"

URI_x86_64_v2_rust-matchit0.8-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-matchit0.8-devel-0.8.6-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-matchit0.8-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-matchit0.8-devel}"
SRC_URI[x86_64_v2_rust-matchit0.8-devel.sha256sum] = "1e5e31cdfad8afaf1c42ce82c6026fc54335bfc0fad6b1af4a9ccdd38ee05691"

URI_aarch64_rust-matchit0.8+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-matchit0.8+default-devel-0.8.6-1.el10_2.noarch.rpm;name=aarch64_rust-matchit0.8+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-matchit0.8+default-devel}"
SRC_URI[aarch64_rust-matchit0.8+default-devel.sha256sum] = "c0b83d7663bcd9afe857d281e8625fc52ed0f76e50a3f7267ef5429f3a970e95"

URI_aarch64_rust-matchit0.8-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-matchit0.8-devel-0.8.6-1.el10_2.noarch.rpm;name=aarch64_rust-matchit0.8-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-matchit0.8-devel}"
SRC_URI[aarch64_rust-matchit0.8-devel.sha256sum] = "3b05dd3f9c1d80ad92f377941a75795471f6e66c232d87732e71e072edddc3bf"

RDEPENDS:rust-matchit0.8+default-devel = " \
 cargo \
 rust-matchit0.8-devel \
 "
RDEPENDS:rust-matchit0.8-devel = " \
 cargo \
 "
