# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-xattr"
PV = "1.6.1"
PR = "1.el10_1"
PACKAGES = " \
 rust-xattr+default-devel \
 rust-xattr+unsupported-devel \
 rust-xattr-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-xattr-1.6.1-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5c50b485aee1e2afc2821e571c780b520a7aff7f19b945356792a54fc4dc5077"

URI_x86_64_v2_rust-xattr+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-xattr+default-devel-1.6.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-xattr+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-xattr+default-devel}"
SRC_URI[x86_64_v2_rust-xattr+default-devel.sha256sum] = "92cef6e812598ff942a17440d8f258836b38e1b9572a9b8436f9b2f0339e48ab"

URI_x86_64_v2_rust-xattr+unsupported-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-xattr+unsupported-devel-1.6.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-xattr+unsupported-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-xattr+unsupported-devel}"
SRC_URI[x86_64_v2_rust-xattr+unsupported-devel.sha256sum] = "2bb0af4c0a298703fc1d15efe5c94326ebf31f5a5bee682a314a4d265107c762"

URI_x86_64_v2_rust-xattr-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-xattr-devel-1.6.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-xattr-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-xattr-devel}"
SRC_URI[x86_64_v2_rust-xattr-devel.sha256sum] = "f1473aaea457b3bfbf5e3e6265dcee1ac19c4ddab3c415dce767612f1b8808a6"

URI_aarch64_rust-xattr+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-xattr+default-devel-1.6.1-1.el10_1.noarch.rpm;name=aarch64_rust-xattr+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-xattr+default-devel}"
SRC_URI[aarch64_rust-xattr+default-devel.sha256sum] = "47bc3a5162cd230c887315bcc6f66b10b84073c02f1a7bb6b57e3b093ebb84e9"

URI_aarch64_rust-xattr+unsupported-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-xattr+unsupported-devel-1.6.1-1.el10_1.noarch.rpm;name=aarch64_rust-xattr+unsupported-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-xattr+unsupported-devel}"
SRC_URI[aarch64_rust-xattr+unsupported-devel.sha256sum] = "c6719b5ff7f3e80ba781897c97b06975fe0ec77af44a1d1ef0b535dbe94615c2"

URI_aarch64_rust-xattr-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-xattr-devel-1.6.1-1.el10_1.noarch.rpm;name=aarch64_rust-xattr-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-xattr-devel}"
SRC_URI[aarch64_rust-xattr-devel.sha256sum] = "f59137986595cfec69999d52906d9a557932a30872a45cbee07fb6ecceaa295e"

RDEPENDS:rust-xattr+default-devel = " \
 cargo \
 rust-xattr+unsupported-devel \
 rust-xattr-devel \
 "
RDEPENDS:rust-xattr+unsupported-devel = " \
 cargo \
 rust-xattr-devel \
 "
RDEPENDS:rust-xattr-devel = " \
 cargo \
 rust-rustix+fs-devel \
 rust-rustix+std-devel \
 rust-rustix-devel \
 "
