# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-colored"
PV = "3.0.0"
PR = "1.el10_0"
PACKAGES = " \
 rust-colored+default-devel \
 rust-colored+no-color-devel \
 rust-colored-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-colored-3.0.0-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1ab2eec7ffae3f0e5dc0cc896f8fe9aaa0190633103c3a4e462537335c9366a0"

URI_x86_64_v2_rust-colored+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-colored+default-devel-3.0.0-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-colored+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-colored+default-devel}"
SRC_URI[x86_64_v2_rust-colored+default-devel.sha256sum] = "3c351c80861212fecd7292dc8ab9322ce779584ab55a016f8915eb182dd220cf"
RPROVIDES:rust-colored+default-devel:append:x86_64_v2 = " virtual/crate_colored/default__ge_2.0.0_with_crate_colored/default__lt_4.0.0~"

URI_x86_64_v2_rust-colored+no-color-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-colored+no-color-devel-3.0.0-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-colored+no-color-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-colored+no-color-devel}"
SRC_URI[x86_64_v2_rust-colored+no-color-devel.sha256sum] = "a05b3b0c0c145a393d66c510dc501cbc59eea87537df8e4a5c3128cf9b1b6bd3"

URI_x86_64_v2_rust-colored-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-colored-devel-3.0.0-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-colored-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-colored-devel}"
SRC_URI[x86_64_v2_rust-colored-devel.sha256sum] = "a78c206acc606cc91caf47c1461417a1554a7c2e60785498ad4c13da6a4d9982"

URI_aarch64_rust-colored+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-colored+default-devel-3.0.0-1.el10_0.noarch.rpm;name=aarch64_rust-colored+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-colored+default-devel}"
SRC_URI[aarch64_rust-colored+default-devel.sha256sum] = "f4e36f795d2ef869124ccc1a506bde756bfa30f9d4abfb20facc586fba2082ec"
RPROVIDES:rust-colored+default-devel:append:aarch64 = " virtual/crate_colored/default__ge_2.0.0_with_crate_colored/default__lt_4.0.0~"

URI_aarch64_rust-colored+no-color-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-colored+no-color-devel-3.0.0-1.el10_0.noarch.rpm;name=aarch64_rust-colored+no-color-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-colored+no-color-devel}"
SRC_URI[aarch64_rust-colored+no-color-devel.sha256sum] = "32a09d60a43bd3547f80d0b0f360943f0b67dc2715a88bb0858d75bd3dcd247d"

URI_aarch64_rust-colored-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-colored-devel-3.0.0-1.el10_0.noarch.rpm;name=aarch64_rust-colored-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-colored-devel}"
SRC_URI[aarch64_rust-colored-devel.sha256sum] = "d33b6223187a944b6bd9d58df3384bbe6123fb0839d418dc3a40aeba5fbd9004"

RDEPENDS:rust-colored+default-devel = " \
 cargo \
 rust-colored-devel \
 "
RDEPENDS:rust-colored+no-color-devel = " \
 cargo \
 rust-colored-devel \
 "
RDEPENDS:rust-colored-devel = " \
 cargo \
 rust \
 "
