# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-bitreader"
PV = "0.3.11"
PR = "1.el10_0"
PACKAGES = " \
 rust-bitreader+default-devel \
 rust-bitreader+std-devel \
 rust-bitreader-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-bitreader-0.3.11-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d92b8d9e03d3cf0153172abd9fac226c419b586ec210d16ecf74c0c69ee3933a"

URI_x86_64_v2_rust-bitreader+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-bitreader+default-devel-0.3.11-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-bitreader+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-bitreader+default-devel}"
SRC_URI[x86_64_v2_rust-bitreader+default-devel.sha256sum] = "6caf52a14521c65cefd21ee98ae1e823d77150b90ea7618a9a338f4b8bae092b"

URI_x86_64_v2_rust-bitreader+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-bitreader+std-devel-0.3.11-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-bitreader+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-bitreader+std-devel}"
SRC_URI[x86_64_v2_rust-bitreader+std-devel.sha256sum] = "fd2bcbe864a624880fc9643cc87e32c2e6e1ae29a80233bb650ad3f8c92757ba"

URI_x86_64_v2_rust-bitreader-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-bitreader-devel-0.3.11-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-bitreader-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-bitreader-devel}"
SRC_URI[x86_64_v2_rust-bitreader-devel.sha256sum] = "478ae8b95bf70ddeee803b767d8cefbbf194f5155fabebdd9c7542bd16505243"

URI_aarch64_rust-bitreader+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-bitreader+default-devel-0.3.11-1.el10_0.noarch.rpm;name=aarch64_rust-bitreader+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-bitreader+default-devel}"
SRC_URI[aarch64_rust-bitreader+default-devel.sha256sum] = "948e7758bdb8ede4acf26336af4b84c6388cb4a9c1128a38ad70f55e6afe1e32"

URI_aarch64_rust-bitreader+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-bitreader+std-devel-0.3.11-1.el10_0.noarch.rpm;name=aarch64_rust-bitreader+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-bitreader+std-devel}"
SRC_URI[aarch64_rust-bitreader+std-devel.sha256sum] = "757354fea366daca40ae3158ad1c572ee42d10babf76cdfad1ac80458255cdfd"

URI_aarch64_rust-bitreader-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-bitreader-devel-0.3.11-1.el10_0.noarch.rpm;name=aarch64_rust-bitreader-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-bitreader-devel}"
SRC_URI[aarch64_rust-bitreader-devel.sha256sum] = "287a5a5964f46a442b6d018fadd2c029e69063ce5343abaced4e6146c89bc537"

RDEPENDS:rust-bitreader+default-devel = " \
 cargo \
 rust-bitreader+std-devel \
 rust-bitreader-devel \
 "
RDEPENDS:rust-bitreader+std-devel = " \
 cargo \
 rust-bitreader-devel \
 "
RDEPENDS:rust-bitreader-devel = " \
 cargo \
 rust-cfg-if+default-devel \
 "
