# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-rustc-hash"
PV = "2.1.3"
PR = "1.el10_3"
PACKAGES = " \
 rust-rustc-hash+default-devel \
 rust-rustc-hash+rand-devel \
 rust-rustc-hash+std-devel \
 rust-rustc-hash-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-rustc-hash-2.1.3-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "bcf3e085b9a12d85cbb8c81a898db107b0f149ea473039614b887b5f1439c287"

URI_x86_64_v2_rust-rustc-hash+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-rustc-hash+default-devel-2.1.3-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-rustc-hash+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-rustc-hash+default-devel}"
SRC_URI[x86_64_v2_rust-rustc-hash+default-devel.sha256sum] = "b6d47007b3dd66cbbbca0e4094fa4e5b21550994c70eb7599c5c9757f4ac0469"

URI_x86_64_v2_rust-rustc-hash+rand-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-rustc-hash+rand-devel-2.1.3-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-rustc-hash+rand-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-rustc-hash+rand-devel}"
SRC_URI[x86_64_v2_rust-rustc-hash+rand-devel.sha256sum] = "f7af4c527b63aae31bc23fbb40434252716fd6c57142b5117d5d6899ac56aeff"

URI_x86_64_v2_rust-rustc-hash+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-rustc-hash+std-devel-2.1.3-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-rustc-hash+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-rustc-hash+std-devel}"
SRC_URI[x86_64_v2_rust-rustc-hash+std-devel.sha256sum] = "da549901a1ec0db8aa86b664db396801ba0f93ab306a052172935121f1781f4d"

URI_x86_64_v2_rust-rustc-hash-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-rustc-hash-devel-2.1.3-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-rustc-hash-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-rustc-hash-devel}"
SRC_URI[x86_64_v2_rust-rustc-hash-devel.sha256sum] = "cc0de33c00ba7981cb2603d208605a838972f7d91f9470d2b7b733dac40c8f16"

URI_aarch64_rust-rustc-hash+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-rustc-hash+default-devel-2.1.3-1.el10_3.noarch.rpm;name=aarch64_rust-rustc-hash+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-rustc-hash+default-devel}"
SRC_URI[aarch64_rust-rustc-hash+default-devel.sha256sum] = "493c3f9931bc150565006c71b693f4dde7ee7fa0e26d705f2feeec6c1cd9cf92"

URI_aarch64_rust-rustc-hash+rand-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-rustc-hash+rand-devel-2.1.3-1.el10_3.noarch.rpm;name=aarch64_rust-rustc-hash+rand-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-rustc-hash+rand-devel}"
SRC_URI[aarch64_rust-rustc-hash+rand-devel.sha256sum] = "72cb2562253912f950b34250d975e168ea36d80c56ef68e2c86115677a843b5e"

URI_aarch64_rust-rustc-hash+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-rustc-hash+std-devel-2.1.3-1.el10_3.noarch.rpm;name=aarch64_rust-rustc-hash+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-rustc-hash+std-devel}"
SRC_URI[aarch64_rust-rustc-hash+std-devel.sha256sum] = "c8901e9a51fccc198fdc7f1b123cade6927a1f00b4981d9f269913edd034e062"

URI_aarch64_rust-rustc-hash-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-rustc-hash-devel-2.1.3-1.el10_3.noarch.rpm;name=aarch64_rust-rustc-hash-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-rustc-hash-devel}"
SRC_URI[aarch64_rust-rustc-hash-devel.sha256sum] = "d0f4b21188d0b03ccf7d68eb7563208b319f31fee5efe446357b42ee67687825"

RDEPENDS:rust-rustc-hash+default-devel = " \
 cargo \
 rust-rustc-hash+std-devel \
 rust-rustc-hash-devel \
 "
RDEPENDS:rust-rustc-hash+rand-devel = " \
 cargo \
 rust-rand0.9+default-devel \
 rust-rustc-hash+std-devel \
 rust-rustc-hash-devel \
 "
RDEPENDS:rust-rustc-hash+std-devel = " \
 cargo \
 rust-rustc-hash-devel \
 "
RDEPENDS:rust-rustc-hash-devel = " \
 cargo \
 rust \
 "
