# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-allocator-api2"
PV = "0.2.21"
PR = "1.el10_1"
PACKAGES = " \
 rust-allocator-api2+alloc-devel \
 rust-allocator-api2+default-devel \
 rust-allocator-api2+fresh-rust-devel \
 rust-allocator-api2+nightly-devel \
 rust-allocator-api2+serde-devel \
 rust-allocator-api2+std-devel \
 rust-allocator-api2-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-allocator-api2-0.2.21-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "9e8df8b25836eea2829f97cb2c204fb72fbbc1a0f43b2cb45971e49cd4e218e0"

URI_x86_64_v2_rust-allocator-api2+alloc-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-allocator-api2+alloc-devel-0.2.21-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-allocator-api2+alloc-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-allocator-api2+alloc-devel}"
SRC_URI[x86_64_v2_rust-allocator-api2+alloc-devel.sha256sum] = "8600b750bf106bf2681f199ac3e0cd663cd13db245790b97bd58822cc7cd63ff"

URI_x86_64_v2_rust-allocator-api2+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-allocator-api2+default-devel-0.2.21-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-allocator-api2+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-allocator-api2+default-devel}"
SRC_URI[x86_64_v2_rust-allocator-api2+default-devel.sha256sum] = "73a14d3af1c02bb1925b9e05fbf43cc20212b6d59b131001067f489956a21c0b"

URI_x86_64_v2_rust-allocator-api2+fresh-rust-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-allocator-api2+fresh-rust-devel-0.2.21-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-allocator-api2+fresh-rust-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-allocator-api2+fresh-rust-devel}"
SRC_URI[x86_64_v2_rust-allocator-api2+fresh-rust-devel.sha256sum] = "cc8cef4b91e57123183d0e25e6e589ca41fe359c94e58292ac24eda0020adae7"

URI_x86_64_v2_rust-allocator-api2+nightly-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-allocator-api2+nightly-devel-0.2.21-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-allocator-api2+nightly-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-allocator-api2+nightly-devel}"
SRC_URI[x86_64_v2_rust-allocator-api2+nightly-devel.sha256sum] = "3d78d3bc12d11b24699b057f604622d23330265d3487b53f9d2b1343b26cc708"

URI_x86_64_v2_rust-allocator-api2+serde-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-allocator-api2+serde-devel-0.2.21-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-allocator-api2+serde-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-allocator-api2+serde-devel}"
SRC_URI[x86_64_v2_rust-allocator-api2+serde-devel.sha256sum] = "9a23a00dcdbc64e7dbabc325655bdb68d25fc27fc9ade2132caa363135fa3385"

URI_x86_64_v2_rust-allocator-api2+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-allocator-api2+std-devel-0.2.21-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-allocator-api2+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-allocator-api2+std-devel}"
SRC_URI[x86_64_v2_rust-allocator-api2+std-devel.sha256sum] = "f53bc031e1091e6fe9cc10673682ff0369925c20a4df04c5fdb27374fc8ff9e7"

URI_x86_64_v2_rust-allocator-api2-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-allocator-api2-devel-0.2.21-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-allocator-api2-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-allocator-api2-devel}"
SRC_URI[x86_64_v2_rust-allocator-api2-devel.sha256sum] = "c814f099c5ea352e9d31c36421f651e069ba50daf017eb35d5854b4199ffeba1"

URI_aarch64_rust-allocator-api2+alloc-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-allocator-api2+alloc-devel-0.2.21-1.el10_1.noarch.rpm;name=aarch64_rust-allocator-api2+alloc-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-allocator-api2+alloc-devel}"
SRC_URI[aarch64_rust-allocator-api2+alloc-devel.sha256sum] = "3c39538303b51baa3480c96c46fad23a98acbe59987154c13bff076a2cc1da2a"

URI_aarch64_rust-allocator-api2+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-allocator-api2+default-devel-0.2.21-1.el10_1.noarch.rpm;name=aarch64_rust-allocator-api2+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-allocator-api2+default-devel}"
SRC_URI[aarch64_rust-allocator-api2+default-devel.sha256sum] = "17141bcbba3bef0279ed4ac15613756e25c464353cd0dc8e0ed3fc06b14f6bcb"

URI_aarch64_rust-allocator-api2+fresh-rust-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-allocator-api2+fresh-rust-devel-0.2.21-1.el10_1.noarch.rpm;name=aarch64_rust-allocator-api2+fresh-rust-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-allocator-api2+fresh-rust-devel}"
SRC_URI[aarch64_rust-allocator-api2+fresh-rust-devel.sha256sum] = "71e3088ac2017d7bd6ea1780d1e4033c9037c09eccf8b3ad84f07b21aabb88d6"

URI_aarch64_rust-allocator-api2+nightly-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-allocator-api2+nightly-devel-0.2.21-1.el10_1.noarch.rpm;name=aarch64_rust-allocator-api2+nightly-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-allocator-api2+nightly-devel}"
SRC_URI[aarch64_rust-allocator-api2+nightly-devel.sha256sum] = "da49a2513b4c3ae7691208e1b594247503a501c294c7bbb5c7ce17c132d1e03a"

URI_aarch64_rust-allocator-api2+serde-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-allocator-api2+serde-devel-0.2.21-1.el10_1.noarch.rpm;name=aarch64_rust-allocator-api2+serde-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-allocator-api2+serde-devel}"
SRC_URI[aarch64_rust-allocator-api2+serde-devel.sha256sum] = "ca69427f3fa3599dbdccda1e6eabeb99682761368bd3f4e8d502b3881765f3ae"

URI_aarch64_rust-allocator-api2+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-allocator-api2+std-devel-0.2.21-1.el10_1.noarch.rpm;name=aarch64_rust-allocator-api2+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-allocator-api2+std-devel}"
SRC_URI[aarch64_rust-allocator-api2+std-devel.sha256sum] = "9fbe0b39c3f220619bd7848d151ecdd81a4dd0c5ade47e6fc56de0a40f350500"

URI_aarch64_rust-allocator-api2-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-allocator-api2-devel-0.2.21-1.el10_1.noarch.rpm;name=aarch64_rust-allocator-api2-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-allocator-api2-devel}"
SRC_URI[aarch64_rust-allocator-api2-devel.sha256sum] = "50cb61c88a69ba52f890b3f4526722020554b86c51caa9aba427b1d72f35741b"

RDEPENDS:rust-allocator-api2+alloc-devel = " \
 cargo \
 rust-allocator-api2-devel \
 "
RDEPENDS:rust-allocator-api2+default-devel = " \
 cargo \
 rust-allocator-api2+std-devel \
 rust-allocator-api2-devel \
 "
RDEPENDS:rust-allocator-api2+fresh-rust-devel = " \
 cargo \
 rust-allocator-api2-devel \
 "
RDEPENDS:rust-allocator-api2+nightly-devel = " \
 cargo \
 rust-allocator-api2-devel \
 "
RDEPENDS:rust-allocator-api2+serde-devel = " \
 cargo \
 rust-allocator-api2-devel \
 rust-serde+default-devel \
 "
RDEPENDS:rust-allocator-api2+std-devel = " \
 cargo \
 rust-allocator-api2+alloc-devel \
 rust-allocator-api2-devel \
 "
RDEPENDS:rust-allocator-api2-devel = " \
 cargo \
 rust \
 "
