# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-tree-sitter-typescript"
PV = "0.23.2"
PR = "2.el10_1"
PACKAGES = " \
 rust-tree-sitter-typescript+default-devel \
 rust-tree-sitter-typescript-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-tree-sitter-typescript-0.23.2-2.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ca96205446b24a474901c6207c145a1973820c0bfc5d461b11813fc8cbbc80b0"

URI_x86_64_v2_rust-tree-sitter-typescript+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-tree-sitter-typescript+default-devel-0.23.2-2.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-tree-sitter-typescript+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-tree-sitter-typescript+default-devel}"
SRC_URI[x86_64_v2_rust-tree-sitter-typescript+default-devel.sha256sum] = "19988dad957007fbae78b04ed709979e7c718734e83bcfa0d823e8fe1805de85"

URI_x86_64_v2_rust-tree-sitter-typescript-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-tree-sitter-typescript-devel-0.23.2-2.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-tree-sitter-typescript-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-tree-sitter-typescript-devel}"
SRC_URI[x86_64_v2_rust-tree-sitter-typescript-devel.sha256sum] = "70f9305a95135ca64e9e78d9adcdf242f4063d6ea658719fabef9be195a9c945"

URI_aarch64_rust-tree-sitter-typescript+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-tree-sitter-typescript+default-devel-0.23.2-2.el10_1.noarch.rpm;name=aarch64_rust-tree-sitter-typescript+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-tree-sitter-typescript+default-devel}"
SRC_URI[aarch64_rust-tree-sitter-typescript+default-devel.sha256sum] = "20b2c5994d727392a44d4811d5f36925548f952bfdd43e5dcab1506437c560a9"

URI_aarch64_rust-tree-sitter-typescript-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-tree-sitter-typescript-devel-0.23.2-2.el10_1.noarch.rpm;name=aarch64_rust-tree-sitter-typescript-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-tree-sitter-typescript-devel}"
SRC_URI[aarch64_rust-tree-sitter-typescript-devel.sha256sum] = "d01e43a044743f3a1d62af7518d4b2d443e2ab4a80187fe8237386e0b89401bb"

RDEPENDS:rust-tree-sitter-typescript+default-devel = " \
 cargo \
 rust-tree-sitter-typescript-devel \
 "
RDEPENDS:rust-tree-sitter-typescript-devel = " \
 cargo \
 rust-cc+default-devel \
 rust-tree-sitter-language+default-devel \
 "
