# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-ipnetwork"
PV = "0.20.0"
PR = "4.el10_1"
PACKAGES = " \
 rust-ipnetwork+default-devel \
 rust-ipnetwork+serde-devel \
 rust-ipnetwork-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-ipnetwork-0.20.0-4.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b7923a85cdd42de40850db82f1c2c3fa5242da559dc361750e72c50dfde8e55f"

URI_x86_64_v2_rust-ipnetwork+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-ipnetwork+default-devel-0.20.0-4.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-ipnetwork+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-ipnetwork+default-devel}"
SRC_URI[x86_64_v2_rust-ipnetwork+default-devel.sha256sum] = "34da501f56efcef19be79af4c23a0d040845fcb5d5df3ff36ad470262740ad09"

URI_x86_64_v2_rust-ipnetwork+serde-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-ipnetwork+serde-devel-0.20.0-4.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-ipnetwork+serde-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-ipnetwork+serde-devel}"
SRC_URI[x86_64_v2_rust-ipnetwork+serde-devel.sha256sum] = "d455e240fb9877a9b712b6c9b217daa7ebe755aae7a6497077f35fb7fc89cd74"

URI_x86_64_v2_rust-ipnetwork-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-ipnetwork-devel-0.20.0-4.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-ipnetwork-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-ipnetwork-devel}"
SRC_URI[x86_64_v2_rust-ipnetwork-devel.sha256sum] = "dcd7bd3a1296426bce33d23bf8b2ab9aa691343b27dcfbda5888b68ef4f385d1"

URI_aarch64_rust-ipnetwork+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-ipnetwork+default-devel-0.20.0-4.el10_1.noarch.rpm;name=aarch64_rust-ipnetwork+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-ipnetwork+default-devel}"
SRC_URI[aarch64_rust-ipnetwork+default-devel.sha256sum] = "99006917d3f51824e62abcd3b3e4e29e1e99115ea7834ee2b9d82798c1f8c7cb"

URI_aarch64_rust-ipnetwork+serde-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-ipnetwork+serde-devel-0.20.0-4.el10_1.noarch.rpm;name=aarch64_rust-ipnetwork+serde-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-ipnetwork+serde-devel}"
SRC_URI[aarch64_rust-ipnetwork+serde-devel.sha256sum] = "23b55ed5fbc1224c5c6076c8d02ab51a5f7e620e008d74215825c88a790e90ae"

URI_aarch64_rust-ipnetwork-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-ipnetwork-devel-0.20.0-4.el10_1.noarch.rpm;name=aarch64_rust-ipnetwork-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-ipnetwork-devel}"
SRC_URI[aarch64_rust-ipnetwork-devel.sha256sum] = "c2a8f1ffafc5000299a50b2443aa3b0715c7f57a827cabb116ab9f684f09e6de"

RDEPENDS:rust-ipnetwork+default-devel = " \
 cargo \
 rust-ipnetwork+serde-devel \
 rust-ipnetwork-devel \
 "
RDEPENDS:rust-ipnetwork+serde-devel = " \
 cargo \
 rust-ipnetwork-devel \
 rust-serde+default-devel \
 "
RDEPENDS:rust-ipnetwork-devel = " \
 cargo \
 "
