# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-libloading"
PV = "0.9.0"
PR = "1.el10_3"
PACKAGES = " \
 rust-libloading+default-devel \
 rust-libloading+std-devel \
 rust-libloading-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-libloading-0.9.0-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f0532cd5057af1a5b3122a8a72492c33840391feec5686d1ff3760c10a05bfb6"

URI_x86_64_v2_rust-libloading+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libloading+default-devel-0.9.0-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libloading+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libloading+default-devel}"
SRC_URI[x86_64_v2_rust-libloading+default-devel.sha256sum] = "460663fc9291e373cf9886718ead90adb3879a5da380fcdc99d09c5589aa3b62"

URI_x86_64_v2_rust-libloading+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libloading+std-devel-0.9.0-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libloading+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libloading+std-devel}"
SRC_URI[x86_64_v2_rust-libloading+std-devel.sha256sum] = "fce3a4396ac1329a764fa916056c1296434a3391c9a3b809bb98eb5cb157008e"

URI_x86_64_v2_rust-libloading-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-libloading-devel-0.9.0-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-libloading-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-libloading-devel}"
SRC_URI[x86_64_v2_rust-libloading-devel.sha256sum] = "ed5e0155f3608cd6c6ddad8efbacf5abebdb95d3a80bc8cbb5945f8cb4746b54"

URI_aarch64_rust-libloading+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libloading+default-devel-0.9.0-1.el10_3.noarch.rpm;name=aarch64_rust-libloading+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libloading+default-devel}"
SRC_URI[aarch64_rust-libloading+default-devel.sha256sum] = "91088cc367b92a0cac4616cbd56cdd8caff15ba953e9c49cec63925ad5fce42b"

URI_aarch64_rust-libloading+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libloading+std-devel-0.9.0-1.el10_3.noarch.rpm;name=aarch64_rust-libloading+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libloading+std-devel}"
SRC_URI[aarch64_rust-libloading+std-devel.sha256sum] = "6704a31157e3c2a849660a9d45519eddb5f17d2ab5438e63835be5c278c4f579"

URI_aarch64_rust-libloading-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-libloading-devel-0.9.0-1.el10_3.noarch.rpm;name=aarch64_rust-libloading-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-libloading-devel}"
SRC_URI[aarch64_rust-libloading-devel.sha256sum] = "c4ef8828d560bffcf9c02e51d492475ee269c1ee54ee7f5bc8083e313a70fbaa"

RDEPENDS:rust-libloading+default-devel = " \
 cargo \
 rust-libloading+std-devel \
 rust-libloading-devel \
 "
RDEPENDS:rust-libloading+std-devel = " \
 cargo \
 rust-libloading-devel \
 "
RDEPENDS:rust-libloading-devel = " \
 cargo \
 rust \
 rust-cfg-if+default-devel \
 "
