# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-dlib"
PV = "0.5.3"
PR = "1.el10_1"
PACKAGES = " \
 rust-dlib+default-devel \
 rust-dlib-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-dlib-0.5.3-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c0f074ed7b2537a83778bee210e3683932838d97209b916ae30b6104f20eafa2"

URI_x86_64_v2_rust-dlib+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dlib+default-devel-0.5.3-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dlib+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dlib+default-devel}"
SRC_URI[x86_64_v2_rust-dlib+default-devel.sha256sum] = "a5ec3156045ec124b12cda09d2d8dce614a695fc0439c15bd531779f0b9738a6"

URI_x86_64_v2_rust-dlib-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dlib-devel-0.5.3-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dlib-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dlib-devel}"
SRC_URI[x86_64_v2_rust-dlib-devel.sha256sum] = "864a31ccf85bd56a164018053defaf1876f080750e4040f405e350ad5ca71700"

URI_aarch64_rust-dlib+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dlib+default-devel-0.5.3-1.el10_1.noarch.rpm;name=aarch64_rust-dlib+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dlib+default-devel}"
SRC_URI[aarch64_rust-dlib+default-devel.sha256sum] = "7f7d186121aeee9449420d46fb60d6273c9181337d8e85b3752bc5af60f6d178"

URI_aarch64_rust-dlib-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dlib-devel-0.5.3-1.el10_1.noarch.rpm;name=aarch64_rust-dlib-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dlib-devel}"
SRC_URI[aarch64_rust-dlib-devel.sha256sum] = "44b2d979df7348ef2741c5005ca1157ffa5574b15c5199a0e0ed943b27ac07a3"

RDEPENDS:rust-dlib+default-devel = " \
 cargo \
 rust-dlib-devel \
 "
RDEPENDS:rust-dlib-devel = " \
 cargo \
 rust \
 virtual/crate_libloading/default__ge_0.7.0_with_crate_libloading/default__lt_0.9.0~ \
 "
