# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-fern"
PV = "0.7.1"
PR = "1.el10_0"
PACKAGES = " \
 rust-fern+chrono-devel \
 rust-fern+colored-devel \
 rust-fern+date-based-devel \
 rust-fern+default-devel \
 rust-fern+libc-devel \
 rust-fern+meta-logging-in-format-devel \
 rust-fern-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-fern-0.7.1-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e1a015ba9d23e9f2904f6dad9cf5cb0d3e8e25c1435b11695472ba9a42b987e0"

URI_x86_64_v2_rust-fern+chrono-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-fern+chrono-devel-0.7.1-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-fern+chrono-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-fern+chrono-devel}"
SRC_URI[x86_64_v2_rust-fern+chrono-devel.sha256sum] = "3310532ceaf6e6774ad29cd2caaa9903d70716790745303af5b43e5b8b5c198f"

URI_x86_64_v2_rust-fern+colored-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-fern+colored-devel-0.7.1-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-fern+colored-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-fern+colored-devel}"
SRC_URI[x86_64_v2_rust-fern+colored-devel.sha256sum] = "e5bb588d33fcd2447216999e0fd0247ad579da327e8442e1bd93bfb0d4d9649e"

URI_x86_64_v2_rust-fern+date-based-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-fern+date-based-devel-0.7.1-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-fern+date-based-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-fern+date-based-devel}"
SRC_URI[x86_64_v2_rust-fern+date-based-devel.sha256sum] = "724640a25f388f23c4a1c9e2d686604caa4828f4aedaa99490e3e5fa8bb19cdc"

URI_x86_64_v2_rust-fern+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-fern+default-devel-0.7.1-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-fern+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-fern+default-devel}"
SRC_URI[x86_64_v2_rust-fern+default-devel.sha256sum] = "f42c4002ac14e62579e91735a78721c94c9db25a09a0a2c100e00f6e85bd64b8"

URI_x86_64_v2_rust-fern+libc-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-fern+libc-devel-0.7.1-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-fern+libc-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-fern+libc-devel}"
SRC_URI[x86_64_v2_rust-fern+libc-devel.sha256sum] = "efdb0e531747cdd8e280a11cf6e19b5353a62a8da20326c9159d8117aa636ce3"

URI_x86_64_v2_rust-fern+meta-logging-in-format-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-fern+meta-logging-in-format-devel-0.7.1-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-fern+meta-logging-in-format-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-fern+meta-logging-in-format-devel}"
SRC_URI[x86_64_v2_rust-fern+meta-logging-in-format-devel.sha256sum] = "aa79a273c6902f03359b5d7b70c97ad193e6e1d5e45012d0db697c5b2b0594ca"

URI_x86_64_v2_rust-fern-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-fern-devel-0.7.1-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-fern-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-fern-devel}"
SRC_URI[x86_64_v2_rust-fern-devel.sha256sum] = "d36fea229a0729b517a68839b32ffb0750f55a9730b9acf876e6e071c4e7cb63"

URI_aarch64_rust-fern+chrono-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-fern+chrono-devel-0.7.1-1.el10_0.noarch.rpm;name=aarch64_rust-fern+chrono-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-fern+chrono-devel}"
SRC_URI[aarch64_rust-fern+chrono-devel.sha256sum] = "07e4965aae7f7875899caf0ebe0c325e126c362536f812b081ad7a5357ca7e64"

URI_aarch64_rust-fern+colored-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-fern+colored-devel-0.7.1-1.el10_0.noarch.rpm;name=aarch64_rust-fern+colored-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-fern+colored-devel}"
SRC_URI[aarch64_rust-fern+colored-devel.sha256sum] = "1e2bdef337b4a1fd9b78e43a88db26cbbf8c65c5cf05d6d782c5874974647a60"

URI_aarch64_rust-fern+date-based-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-fern+date-based-devel-0.7.1-1.el10_0.noarch.rpm;name=aarch64_rust-fern+date-based-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-fern+date-based-devel}"
SRC_URI[aarch64_rust-fern+date-based-devel.sha256sum] = "d551f9faa40234262bd789457dedb265bc2f1de490b36807a80c7dab813e1dcd"

URI_aarch64_rust-fern+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-fern+default-devel-0.7.1-1.el10_0.noarch.rpm;name=aarch64_rust-fern+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-fern+default-devel}"
SRC_URI[aarch64_rust-fern+default-devel.sha256sum] = "aacf9fc208a4a91748db7350b9d9ab1dcb75e3ba2b9b5aba13a3627229e4bdbf"

URI_aarch64_rust-fern+libc-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-fern+libc-devel-0.7.1-1.el10_0.noarch.rpm;name=aarch64_rust-fern+libc-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-fern+libc-devel}"
SRC_URI[aarch64_rust-fern+libc-devel.sha256sum] = "c016a0b39405893dc3685c71850f4cb4c5b56cb99123908363fd3a3b5bd7a9ad"

URI_aarch64_rust-fern+meta-logging-in-format-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-fern+meta-logging-in-format-devel-0.7.1-1.el10_0.noarch.rpm;name=aarch64_rust-fern+meta-logging-in-format-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-fern+meta-logging-in-format-devel}"
SRC_URI[aarch64_rust-fern+meta-logging-in-format-devel.sha256sum] = "c7ca3291eefaf150d1065fe4278b938e49ab387633f4695dce3dbb10e9bb61b8"

URI_aarch64_rust-fern-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-fern-devel-0.7.1-1.el10_0.noarch.rpm;name=aarch64_rust-fern-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-fern-devel}"
SRC_URI[aarch64_rust-fern-devel.sha256sum] = "fdb7f9974dea630b5b45d35960e02eb67f7a511da436f17471f17410db876fc3"

RDEPENDS:rust-fern+chrono-devel = " \
 cargo \
 rust-chrono+clock-devel \
 rust-chrono+std-devel \
 rust-chrono-devel \
 rust-fern-devel \
 "
RDEPENDS:rust-fern+colored-devel = " \
 cargo \
 rust-colored2+default-devel \
 rust-fern-devel \
 "
RDEPENDS:rust-fern+date-based-devel = " \
 cargo \
 rust-fern+chrono-devel \
 rust-fern-devel \
 "
RDEPENDS:rust-fern+default-devel = " \
 cargo \
 rust-fern-devel \
 "
RDEPENDS:rust-fern+libc-devel = " \
 cargo \
 rust-fern-devel \
 rust-libc+default-devel \
 "
RDEPENDS:rust-fern+meta-logging-in-format-devel = " \
 cargo \
 rust-fern-devel \
 "
RDEPENDS:rust-fern-devel = " \
 cargo \
 rust \
 rust-log+default-devel \
 rust-log+std-devel \
 "
