# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-bincode"
PV = "1.3.3"
PR = "10.el10_0"
PACKAGES = " \
 rust-bincode+default-devel \
 rust-bincode+i128-devel \
 rust-bincode-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-bincode-1.3.3-10.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b1839b31c55dd2bfa666f4dc51902ceaf29b883e323a2f802b5deab4df47c6f1"

URI_x86_64_v2_rust-bincode+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-bincode+default-devel-1.3.3-10.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-bincode+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-bincode+default-devel}"
SRC_URI[x86_64_v2_rust-bincode+default-devel.sha256sum] = "6067c1f270a88c4576f246a3f3d9ad036e63c2a4a0e5be2c4d8de2c1c31b326e"

URI_x86_64_v2_rust-bincode+i128-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-bincode+i128-devel-1.3.3-10.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-bincode+i128-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-bincode+i128-devel}"
SRC_URI[x86_64_v2_rust-bincode+i128-devel.sha256sum] = "8e640b23ed76ab73495e8cc0de4b2fac8e73f59ac1719493aa545342ca62689d"

URI_x86_64_v2_rust-bincode-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-bincode-devel-1.3.3-10.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-bincode-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-bincode-devel}"
SRC_URI[x86_64_v2_rust-bincode-devel.sha256sum] = "cdae47cf1f7622ec7e9382560003888e7787a297aa15f6530dd2695490c457ff"

URI_aarch64_rust-bincode+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-bincode+default-devel-1.3.3-10.el10_0.noarch.rpm;name=aarch64_rust-bincode+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-bincode+default-devel}"
SRC_URI[aarch64_rust-bincode+default-devel.sha256sum] = "381f32f24dd01af73bec5fe2b8cc0d5221c00db0c2259916a516be1ad6dfc7d5"

URI_aarch64_rust-bincode+i128-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-bincode+i128-devel-1.3.3-10.el10_0.noarch.rpm;name=aarch64_rust-bincode+i128-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-bincode+i128-devel}"
SRC_URI[aarch64_rust-bincode+i128-devel.sha256sum] = "c222c65acc1eadf5d97f16b6b627f30226a4789b9dcc6484434c0013d34ddf63"

URI_aarch64_rust-bincode-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-bincode-devel-1.3.3-10.el10_0.noarch.rpm;name=aarch64_rust-bincode-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-bincode-devel}"
SRC_URI[aarch64_rust-bincode-devel.sha256sum] = "c79c68070b74de960e2a60f4aafba23bf28951be02c9e285591b3d65f2e523ef"

RDEPENDS:rust-bincode+default-devel = " \
 cargo \
 rust-bincode-devel \
 "
RDEPENDS:rust-bincode+i128-devel = " \
 cargo \
 rust-bincode-devel \
 "
RDEPENDS:rust-bincode-devel = " \
 cargo \
 rust-serde+default-devel \
 "
