# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-base16ct0.2"
PV = "0.2.0"
PR = "1.el10_3"
PACKAGES = " \
 rust-base16ct0.2+alloc-devel \
 rust-base16ct0.2+default-devel \
 rust-base16ct0.2+std-devel \
 rust-base16ct0.2-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-base16ct0.2-0.2.0-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d76234738aacd7052dab02b8dc86ff6be5de1a75e45a4b5752001c31c1af0465"

URI_x86_64_v2_rust-base16ct0.2+alloc-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-base16ct0.2+alloc-devel-0.2.0-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-base16ct0.2+alloc-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-base16ct0.2+alloc-devel}"
SRC_URI[x86_64_v2_rust-base16ct0.2+alloc-devel.sha256sum] = "092c57056383cacb5b1ae1d5de77c471dbd5d5f0a56cd86a2a4a690556708717"

URI_x86_64_v2_rust-base16ct0.2+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-base16ct0.2+default-devel-0.2.0-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-base16ct0.2+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-base16ct0.2+default-devel}"
SRC_URI[x86_64_v2_rust-base16ct0.2+default-devel.sha256sum] = "b53ae8a8db94c4f680970760b725b46fa6d7f330e79c576ca02cbba03b45086b"

URI_x86_64_v2_rust-base16ct0.2+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-base16ct0.2+std-devel-0.2.0-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-base16ct0.2+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-base16ct0.2+std-devel}"
SRC_URI[x86_64_v2_rust-base16ct0.2+std-devel.sha256sum] = "c0367c72dfb4c813cff9ab82b062bfbd6cfe1e49d05d370c47ecb61aea262534"

URI_x86_64_v2_rust-base16ct0.2-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-base16ct0.2-devel-0.2.0-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-base16ct0.2-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-base16ct0.2-devel}"
SRC_URI[x86_64_v2_rust-base16ct0.2-devel.sha256sum] = "927a743c7d259913655128e6712131a4b38589b45dceb64b473f20883f7ca957"

URI_aarch64_rust-base16ct0.2+alloc-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-base16ct0.2+alloc-devel-0.2.0-1.el10_3.noarch.rpm;name=aarch64_rust-base16ct0.2+alloc-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-base16ct0.2+alloc-devel}"
SRC_URI[aarch64_rust-base16ct0.2+alloc-devel.sha256sum] = "14b860e8100b39eeb01632f59e105e2afd675748e6472a3ee2f1825d83048536"

URI_aarch64_rust-base16ct0.2+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-base16ct0.2+default-devel-0.2.0-1.el10_3.noarch.rpm;name=aarch64_rust-base16ct0.2+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-base16ct0.2+default-devel}"
SRC_URI[aarch64_rust-base16ct0.2+default-devel.sha256sum] = "5e98d1c9ee482406c23c0243e723ce82ad0796f265784260a1a458a5ec03980f"

URI_aarch64_rust-base16ct0.2+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-base16ct0.2+std-devel-0.2.0-1.el10_3.noarch.rpm;name=aarch64_rust-base16ct0.2+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-base16ct0.2+std-devel}"
SRC_URI[aarch64_rust-base16ct0.2+std-devel.sha256sum] = "b12c464d72c9bba6263146e7996b00c56f34d835bf1bd1c028a3211bd17dba66"

URI_aarch64_rust-base16ct0.2-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-base16ct0.2-devel-0.2.0-1.el10_3.noarch.rpm;name=aarch64_rust-base16ct0.2-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-base16ct0.2-devel}"
SRC_URI[aarch64_rust-base16ct0.2-devel.sha256sum] = "a8704541825e128c86c53284df85b3e548ce25d031bf97112ba7f6fc11fc694f"

RDEPENDS:rust-base16ct0.2+alloc-devel = " \
 cargo \
 rust-base16ct0.2-devel \
 "
RDEPENDS:rust-base16ct0.2+default-devel = " \
 cargo \
 rust-base16ct0.2-devel \
 "
RDEPENDS:rust-base16ct0.2+std-devel = " \
 cargo \
 rust-base16ct0.2+alloc-devel \
 rust-base16ct0.2-devel \
 "
RDEPENDS:rust-base16ct0.2-devel = " \
 cargo \
 rust \
 "
