# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-gix-lock"
PV = "19.0.0"
PR = "1.el10_2"
PACKAGES = " \
 rust-gix-lock+default-devel \
 rust-gix-lock-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-gix-lock-19.0.0-1.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a5b7ed8f79cf25f8da843a7bf38de60ddfcab8a18d26aeb8a70bb00e834975a4"

URI_x86_64_v2_rust-gix-lock+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-gix-lock+default-devel-19.0.0-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-gix-lock+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-gix-lock+default-devel}"
SRC_URI[x86_64_v2_rust-gix-lock+default-devel.sha256sum] = "88ae97819728d16e1c86c88e16d6dadd0e7c83292dd01a42216ba30a62a9b95c"

URI_x86_64_v2_rust-gix-lock-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-gix-lock-devel-19.0.0-1.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-gix-lock-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-gix-lock-devel}"
SRC_URI[x86_64_v2_rust-gix-lock-devel.sha256sum] = "e4340c8c6e39be1d8a0f0a2fc81da1742e67f561d8f852b327006ac3963ed106"

URI_aarch64_rust-gix-lock+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-gix-lock+default-devel-19.0.0-1.el10_2.noarch.rpm;name=aarch64_rust-gix-lock+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-gix-lock+default-devel}"
SRC_URI[aarch64_rust-gix-lock+default-devel.sha256sum] = "f6162feec20dd031b304b0c1bb2586cd4a0081a50288dbf4b49d50e6e9a9d7bf"

URI_aarch64_rust-gix-lock-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-gix-lock-devel-19.0.0-1.el10_2.noarch.rpm;name=aarch64_rust-gix-lock-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-gix-lock-devel}"
SRC_URI[aarch64_rust-gix-lock-devel.sha256sum] = "f2d0825935548a2955aa16a2a3a2601dc8c3c2529588f9e971fb7f35979adce1"

RDEPENDS:rust-gix-lock+default-devel = " \
 cargo \
 rust-gix-lock-devel \
 "
RDEPENDS:rust-gix-lock-devel = " \
 cargo \
 rust \
 rust-gix-tempfile-devel \
 rust-gix-utils-devel \
 rust-thiserror+default-devel \
 "
