# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-twox-hash"
PV = "2.1.2"
PR = "1.el10_0"
PACKAGES = " \
 rust-twox-hash+alloc-devel \
 rust-twox-hash+default-devel \
 rust-twox-hash+random-devel \
 rust-twox-hash+serialize-devel \
 rust-twox-hash+std-devel \
 rust-twox-hash+xxhash32-devel \
 rust-twox-hash+xxhash3_128-devel \
 rust-twox-hash+xxhash3_64-devel \
 rust-twox-hash+xxhash64-devel \
 rust-twox-hash-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-twox-hash-2.1.2-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "828814549283d02fd2733904cddbf051574f3abc40f3f13c4e62e07eac810101"

URI_x86_64_v2_rust-twox-hash+alloc-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash+alloc-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash+alloc-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash+alloc-devel}"
SRC_URI[x86_64_v2_rust-twox-hash+alloc-devel.sha256sum] = "46dee53387e8c84f119648f1171dfa66b976bfc502ac4885ce0b6aabfc690254"

URI_x86_64_v2_rust-twox-hash+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash+default-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash+default-devel}"
SRC_URI[x86_64_v2_rust-twox-hash+default-devel.sha256sum] = "e6e64fa87c953949544833f488be8dc49adf91e120b77638533387355ac1f436"

URI_x86_64_v2_rust-twox-hash+random-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash+random-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash+random-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash+random-devel}"
SRC_URI[x86_64_v2_rust-twox-hash+random-devel.sha256sum] = "d8273224cf935fd73829bdfdabd35ac2dd915dc25dea6a628d94584f30521ce6"

URI_x86_64_v2_rust-twox-hash+serialize-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash+serialize-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash+serialize-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash+serialize-devel}"
SRC_URI[x86_64_v2_rust-twox-hash+serialize-devel.sha256sum] = "565de39c6dfa62d5bff696f7837987d65e726228b991887fc02885ba07b6c81f"

URI_x86_64_v2_rust-twox-hash+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash+std-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash+std-devel}"
SRC_URI[x86_64_v2_rust-twox-hash+std-devel.sha256sum] = "7a7eff705f4bdaf06907ac7a7bbae9dd22a858628ce7aef0e3f206d7b765b914"

URI_x86_64_v2_rust-twox-hash+xxhash32-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash+xxhash32-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash+xxhash32-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash+xxhash32-devel}"
SRC_URI[x86_64_v2_rust-twox-hash+xxhash32-devel.sha256sum] = "5cbfddfa0f9e460880872cb310495c4b6dd75531cf5a7bf01ab088a5147f82df"

URI_x86_64_v2_rust-twox-hash+xxhash3_128-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash+xxhash3_128-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash+xxhash3_128-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash+xxhash3_128-devel}"
SRC_URI[x86_64_v2_rust-twox-hash+xxhash3_128-devel.sha256sum] = "1c234c463f3bd34cac37e7327bbef1da0cac218b7fe6773f4a7a599066d2354f"

URI_x86_64_v2_rust-twox-hash+xxhash3_64-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash+xxhash3_64-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash+xxhash3_64-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash+xxhash3_64-devel}"
SRC_URI[x86_64_v2_rust-twox-hash+xxhash3_64-devel.sha256sum] = "fd46f4054a235e1961b655b55f90393b0bfcc8f7b8392002918ed88805d7485c"

URI_x86_64_v2_rust-twox-hash+xxhash64-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash+xxhash64-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash+xxhash64-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash+xxhash64-devel}"
SRC_URI[x86_64_v2_rust-twox-hash+xxhash64-devel.sha256sum] = "0d435f3a36c616d155618b70525c203a00d596f179db4939f2d941a592ae97a5"

URI_x86_64_v2_rust-twox-hash-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-twox-hash-devel-2.1.2-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-twox-hash-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-twox-hash-devel}"
SRC_URI[x86_64_v2_rust-twox-hash-devel.sha256sum] = "7be4d5859a78204727a086cd178edc46d4476bdec4999a426adc4b9424b9c774"

URI_aarch64_rust-twox-hash+alloc-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash+alloc-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash+alloc-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash+alloc-devel}"
SRC_URI[aarch64_rust-twox-hash+alloc-devel.sha256sum] = "8b8c5411b23ee88e6a8d1088978e0ebf662a5d7add4b2b2c95c42d1123dd7294"

URI_aarch64_rust-twox-hash+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash+default-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash+default-devel}"
SRC_URI[aarch64_rust-twox-hash+default-devel.sha256sum] = "20033a1d0b127258a29e00cbd134bd2c7ea0186f70aa77d22262963da530b6a9"

URI_aarch64_rust-twox-hash+random-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash+random-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash+random-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash+random-devel}"
SRC_URI[aarch64_rust-twox-hash+random-devel.sha256sum] = "cbf655e2db3a88554d240301b3e0e1cd742d5e557086109a0186993026d5e1a3"

URI_aarch64_rust-twox-hash+serialize-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash+serialize-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash+serialize-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash+serialize-devel}"
SRC_URI[aarch64_rust-twox-hash+serialize-devel.sha256sum] = "382cea54e19b6b11892573e561b066b0bf6f5df4e04ccad8e971378cd1b9af44"

URI_aarch64_rust-twox-hash+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash+std-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash+std-devel}"
SRC_URI[aarch64_rust-twox-hash+std-devel.sha256sum] = "24025dd62d24ce432e44be734def4e2535412f85e59cb478ae03e062d8ec8035"

URI_aarch64_rust-twox-hash+xxhash32-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash+xxhash32-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash+xxhash32-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash+xxhash32-devel}"
SRC_URI[aarch64_rust-twox-hash+xxhash32-devel.sha256sum] = "8ae2a57fcf2a31b7bde6dd7f715c8a8d31ba3aa55a2b3505d5b9186650428753"

URI_aarch64_rust-twox-hash+xxhash3_128-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash+xxhash3_128-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash+xxhash3_128-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash+xxhash3_128-devel}"
SRC_URI[aarch64_rust-twox-hash+xxhash3_128-devel.sha256sum] = "7d2b7e97d37147dc051bb1b13bf294de2fd3365aebb142d96f5e40092ad6254c"

URI_aarch64_rust-twox-hash+xxhash3_64-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash+xxhash3_64-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash+xxhash3_64-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash+xxhash3_64-devel}"
SRC_URI[aarch64_rust-twox-hash+xxhash3_64-devel.sha256sum] = "8e4077e5a467aa80a86a25aa9600186ccd7faef6ba90285fa165d3ed742b5079"

URI_aarch64_rust-twox-hash+xxhash64-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash+xxhash64-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash+xxhash64-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash+xxhash64-devel}"
SRC_URI[aarch64_rust-twox-hash+xxhash64-devel.sha256sum] = "aefcad325accbe39dfea1effcec2594adccd980ce520a3121ec9e70025ac991f"

URI_aarch64_rust-twox-hash-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-twox-hash-devel-2.1.2-1.el10_0.noarch.rpm;name=aarch64_rust-twox-hash-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-twox-hash-devel}"
SRC_URI[aarch64_rust-twox-hash-devel.sha256sum] = "bddec5f343a012508f37f5bc75b5d6dae94f6a693ec7309527d2c6f3221b4fe5"

RDEPENDS:rust-twox-hash+alloc-devel = " \
 cargo \
 rust-twox-hash-devel \
 "
RDEPENDS:rust-twox-hash+default-devel = " \
 cargo \
 rust-twox-hash+random-devel \
 rust-twox-hash+std-devel \
 rust-twox-hash+xxhash32-devel \
 rust-twox-hash+xxhash3_128-devel \
 rust-twox-hash+xxhash3_64-devel \
 rust-twox-hash+xxhash64-devel \
 rust-twox-hash-devel \
 "
RDEPENDS:rust-twox-hash+random-devel = " \
 cargo \
 rust-rand+thread_rng-devel \
 rust-rand-devel \
 rust-twox-hash-devel \
 "
RDEPENDS:rust-twox-hash+serialize-devel = " \
 cargo \
 rust-serde+derive-devel \
 rust-serde-devel \
 rust-twox-hash-devel \
 "
RDEPENDS:rust-twox-hash+std-devel = " \
 cargo \
 rust-twox-hash+alloc-devel \
 rust-twox-hash-devel \
 "
RDEPENDS:rust-twox-hash+xxhash32-devel = " \
 cargo \
 rust-twox-hash-devel \
 "
RDEPENDS:rust-twox-hash+xxhash3_128-devel = " \
 cargo \
 rust-twox-hash-devel \
 "
RDEPENDS:rust-twox-hash+xxhash3_64-devel = " \
 cargo \
 rust-twox-hash-devel \
 "
RDEPENDS:rust-twox-hash+xxhash64-devel = " \
 cargo \
 rust-twox-hash-devel \
 "
RDEPENDS:rust-twox-hash-devel = " \
 cargo \
 rust \
 "
