# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-onefetch-manifest"
PV = "2.25.0"
PR = "1.el10_1"
PACKAGES = " \
 rust-onefetch-manifest+default-devel \
 rust-onefetch-manifest-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-onefetch-manifest-2.25.0-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "9e1fb715737697fd38bd6093e251cba5c5d78ebc6b60e5d320b167a418630c3c"

URI_x86_64_v2_rust-onefetch-manifest+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-onefetch-manifest+default-devel-2.25.0-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-onefetch-manifest+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-onefetch-manifest+default-devel}"
SRC_URI[x86_64_v2_rust-onefetch-manifest+default-devel.sha256sum] = "8404361cd58dcad2aef9b1c35ef6ac6fba5e06b7a7271d91714f9f77858a43a9"

URI_x86_64_v2_rust-onefetch-manifest-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-onefetch-manifest-devel-2.25.0-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-onefetch-manifest-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-onefetch-manifest-devel}"
SRC_URI[x86_64_v2_rust-onefetch-manifest-devel.sha256sum] = "5ca25b74e4df3b57af0ca079d169acc83719f6e61b44751f77c0736242f09bfc"

URI_aarch64_rust-onefetch-manifest+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-onefetch-manifest+default-devel-2.25.0-1.el10_1.noarch.rpm;name=aarch64_rust-onefetch-manifest+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-onefetch-manifest+default-devel}"
SRC_URI[aarch64_rust-onefetch-manifest+default-devel.sha256sum] = "e8ada8434aa1f5e120c548112a53684adabf56148462c7b1d445feb2d66013d8"

URI_aarch64_rust-onefetch-manifest-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-onefetch-manifest-devel-2.25.0-1.el10_1.noarch.rpm;name=aarch64_rust-onefetch-manifest-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-onefetch-manifest-devel}"
SRC_URI[aarch64_rust-onefetch-manifest-devel.sha256sum] = "1c61b64d2969c980fa1fdc0e9fbc5c32ef9cefdee89fbb6b087eec8dc81a15df"

RDEPENDS:rust-onefetch-manifest+default-devel = " \
 cargo \
 rust-onefetch-manifest-devel \
 "
RDEPENDS:rust-onefetch-manifest-devel = " \
 cargo \
 rust-anyhow+default-devel \
 rust-cargo_toml+default-devel \
 rust-npm-package-json+default-devel \
 rust-strum0.26+default-devel \
 rust-strum0.26+derive-devel \
 "
