# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-arboard"
PV = "3.6.1"
PR = "1.el10_1"
PACKAGES = " \
 rust-arboard+default-devel \
 rust-arboard+image-data-devel \
 rust-arboard+image-devel \
 rust-arboard+wayland-data-control-devel \
 rust-arboard+wl-clipboard-rs-devel \
 rust-arboard-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-arboard-3.6.1-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c1a0224cb35883e989f1f8700c6033055a6a0f806fa9bfacc855d8ae6378380e"

URI_x86_64_v2_rust-arboard+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-arboard+default-devel-3.6.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-arboard+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-arboard+default-devel}"
SRC_URI[x86_64_v2_rust-arboard+default-devel.sha256sum] = "01bf63006006bf93a6c55f80633e2d5714814b495a8c6ec452d6d2c1ce190c86"

URI_x86_64_v2_rust-arboard+image-data-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-arboard+image-data-devel-3.6.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-arboard+image-data-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-arboard+image-data-devel}"
SRC_URI[x86_64_v2_rust-arboard+image-data-devel.sha256sum] = "7a8ff9a8ab46ca765b65eca507afd69e83072ceb93d61d6a49691221a929cb51"

URI_x86_64_v2_rust-arboard+image-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-arboard+image-devel-3.6.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-arboard+image-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-arboard+image-devel}"
SRC_URI[x86_64_v2_rust-arboard+image-devel.sha256sum] = "8e23a104f83d7839893a964ed50b25737aec51cf70e16aead90c5bb39f83ab0f"

URI_x86_64_v2_rust-arboard+wayland-data-control-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-arboard+wayland-data-control-devel-3.6.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-arboard+wayland-data-control-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-arboard+wayland-data-control-devel}"
SRC_URI[x86_64_v2_rust-arboard+wayland-data-control-devel.sha256sum] = "0e978487e0222eb7cfa1ba3823dd62dbdb081a7c0fee9f7c876438d2953a2a3a"

URI_x86_64_v2_rust-arboard+wl-clipboard-rs-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-arboard+wl-clipboard-rs-devel-3.6.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-arboard+wl-clipboard-rs-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-arboard+wl-clipboard-rs-devel}"
SRC_URI[x86_64_v2_rust-arboard+wl-clipboard-rs-devel.sha256sum] = "a2502b2721c4135bcc36eb3a8cd1655c94245ab5d8c7c10db1fb58a487d358b8"

URI_x86_64_v2_rust-arboard-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-arboard-devel-3.6.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-arboard-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-arboard-devel}"
SRC_URI[x86_64_v2_rust-arboard-devel.sha256sum] = "b3ab13b44adedd257ae560d0b993b0a5b08844ba9eaa16c48d3914ffa565a2ac"

URI_aarch64_rust-arboard+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-arboard+default-devel-3.6.1-1.el10_1.noarch.rpm;name=aarch64_rust-arboard+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-arboard+default-devel}"
SRC_URI[aarch64_rust-arboard+default-devel.sha256sum] = "5c99bf32155ea0fc2c256073093150b6464d8ed08aa99180cda4d1818e05a82d"

URI_aarch64_rust-arboard+image-data-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-arboard+image-data-devel-3.6.1-1.el10_1.noarch.rpm;name=aarch64_rust-arboard+image-data-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-arboard+image-data-devel}"
SRC_URI[aarch64_rust-arboard+image-data-devel.sha256sum] = "671203ef41a0a43804eab85aaa2326516380f019cc0f0dd9adc27becbedfc5fa"

URI_aarch64_rust-arboard+image-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-arboard+image-devel-3.6.1-1.el10_1.noarch.rpm;name=aarch64_rust-arboard+image-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-arboard+image-devel}"
SRC_URI[aarch64_rust-arboard+image-devel.sha256sum] = "5e8240c1b37f37ccb9cb722d95d83932e7c1fea036d8832a1cab246298d56fe1"

URI_aarch64_rust-arboard+wayland-data-control-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-arboard+wayland-data-control-devel-3.6.1-1.el10_1.noarch.rpm;name=aarch64_rust-arboard+wayland-data-control-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-arboard+wayland-data-control-devel}"
SRC_URI[aarch64_rust-arboard+wayland-data-control-devel.sha256sum] = "393acb5aaea5cb8fd9200d2eebeef7f5a6291fde942040da6fedd6d0f9758a79"

URI_aarch64_rust-arboard+wl-clipboard-rs-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-arboard+wl-clipboard-rs-devel-3.6.1-1.el10_1.noarch.rpm;name=aarch64_rust-arboard+wl-clipboard-rs-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-arboard+wl-clipboard-rs-devel}"
SRC_URI[aarch64_rust-arboard+wl-clipboard-rs-devel.sha256sum] = "b26d1d95eac60330d0a80144feefb8bf3b0be206de81ae84f0866f0cb4176952"

URI_aarch64_rust-arboard-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-arboard-devel-3.6.1-1.el10_1.noarch.rpm;name=aarch64_rust-arboard-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-arboard-devel}"
SRC_URI[aarch64_rust-arboard-devel.sha256sum] = "12de9def0b946eb5eb452f4e6044861be933473d69eaff5ec1af3cdbff659edf"

RDEPENDS:rust-arboard+default-devel = " \
 cargo \
 rust-arboard+image-data-devel \
 rust-arboard-devel \
 "
RDEPENDS:rust-arboard+image-data-devel = " \
 cargo \
 rust-arboard+image-devel \
 rust-arboard-devel \
 "
RDEPENDS:rust-arboard+image-devel = " \
 cargo \
 rust-arboard-devel \
 rust-image+png-devel \
 rust-image-devel \
 "
RDEPENDS:rust-arboard+wayland-data-control-devel = " \
 cargo \
 rust-arboard+wl-clipboard-rs-devel \
 rust-arboard-devel \
 "
RDEPENDS:rust-arboard+wl-clipboard-rs-devel = " \
 cargo \
 rust-arboard-devel \
 rust-wl-clipboard-rs+default-devel \
 "
RDEPENDS:rust-arboard-devel = " \
 bash \
 cargo \
 rust \
 rust-log+default-devel \
 rust-parking_lot+default-devel \
 rust-percent-encoding+default-devel \
 rust-x11rb+default-devel \
 "
