# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-axum-macros"
PV = "0.4.2"
PR = "2.el10_1"
PACKAGES = " \
 rust-axum-macros+__private-devel \
 rust-axum-macros+default-devel \
 rust-axum-macros-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-axum-macros-0.4.2-2.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "80e5bc97be13ef8347a942c196a83b877d04eefb3ffdd0719987d9f91d421dbc"

URI_x86_64_v2_rust-axum-macros+__private-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-axum-macros+__private-devel-0.4.2-2.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-axum-macros+__private-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-axum-macros+__private-devel}"
SRC_URI[x86_64_v2_rust-axum-macros+__private-devel.sha256sum] = "bb39ece709ab89a62036c7fcb27f5926e9fb3474fb49d2cf118fc4b5178b4f98"

URI_x86_64_v2_rust-axum-macros+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-axum-macros+default-devel-0.4.2-2.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-axum-macros+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-axum-macros+default-devel}"
SRC_URI[x86_64_v2_rust-axum-macros+default-devel.sha256sum] = "2da362064807d2ea90497b690a61c04fba7ee1720aeb5c1682007c9ab2727f93"

URI_x86_64_v2_rust-axum-macros-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-axum-macros-devel-0.4.2-2.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-axum-macros-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-axum-macros-devel}"
SRC_URI[x86_64_v2_rust-axum-macros-devel.sha256sum] = "255a5a949d04b64e06a17cea1ba9b03847a0522fb03d5a80e7ebf03dd107556e"

URI_aarch64_rust-axum-macros+__private-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-axum-macros+__private-devel-0.4.2-2.el10_1.noarch.rpm;name=aarch64_rust-axum-macros+__private-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-axum-macros+__private-devel}"
SRC_URI[aarch64_rust-axum-macros+__private-devel.sha256sum] = "e2f93d6982956f03a6cb92c30abcaa38d3911b0220186b7dff8fb3ab7e4db5d7"

URI_aarch64_rust-axum-macros+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-axum-macros+default-devel-0.4.2-2.el10_1.noarch.rpm;name=aarch64_rust-axum-macros+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-axum-macros+default-devel}"
SRC_URI[aarch64_rust-axum-macros+default-devel.sha256sum] = "15d189407dc899e0d96b8685cf8b001b6b89ffb74fb6ef223c60850cbebacae8"

URI_aarch64_rust-axum-macros-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-axum-macros-devel-0.4.2-2.el10_1.noarch.rpm;name=aarch64_rust-axum-macros-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-axum-macros-devel}"
SRC_URI[aarch64_rust-axum-macros-devel.sha256sum] = "9e80b3067eed87c75d65c53e59027b49324bd726511b9bf857ee6ec4b9380ea3"

RDEPENDS:rust-axum-macros+__private-devel = " \
 cargo \
 rust-axum-macros-devel \
 rust-syn+visit-mut-devel \
 "
RDEPENDS:rust-axum-macros+default-devel = " \
 cargo \
 rust-axum-macros-devel \
 "
RDEPENDS:rust-axum-macros-devel = " \
 cargo \
 rust \
 rust-proc-macro2+default-devel \
 rust-quote+default-devel \
 rust-syn+default-devel \
 rust-syn+extra-traits-devel \
 rust-syn+full-devel \
 rust-syn+parsing-devel \
 "
