# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-hyper-util"
PV = "0.1.18"
PR = "1.el10_1"
PACKAGES = " \
 rust-hyper-util+client-devel \
 rust-hyper-util+client-legacy-devel \
 rust-hyper-util+client-proxy-devel \
 rust-hyper-util+client-proxy-system-devel \
 rust-hyper-util+default-devel \
 rust-hyper-util+full-devel \
 rust-hyper-util+http1-devel \
 rust-hyper-util+http2-devel \
 rust-hyper-util+server-auto-devel \
 rust-hyper-util+server-devel \
 rust-hyper-util+server-graceful-devel \
 rust-hyper-util+service-devel \
 rust-hyper-util+tokio-devel \
 rust-hyper-util+tracing-devel \
 rust-hyper-util-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-hyper-util-0.1.18-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c42e0e41c4227f62eae9ee9c0a5d4583363368c24c3b831e17c3f183307f8c6a"

URI_x86_64_v2_rust-hyper-util+client-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+client-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+client-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+client-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+client-devel.sha256sum] = "bc717b2cf73c894de0a63ce996090fa686d62a72c4d0330a95c8b5846c9a829d"

URI_x86_64_v2_rust-hyper-util+client-legacy-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+client-legacy-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+client-legacy-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+client-legacy-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+client-legacy-devel.sha256sum] = "5efc8abba4204d0c841697b39fd410a1bfa7527f65534a069f5e32695ec77728"

URI_x86_64_v2_rust-hyper-util+client-proxy-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+client-proxy-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+client-proxy-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+client-proxy-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+client-proxy-devel.sha256sum] = "9a66c93abb3783b0bc652ceae8d8b0815f659952222fbb8153e8bce009f54245"

URI_x86_64_v2_rust-hyper-util+client-proxy-system-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+client-proxy-system-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+client-proxy-system-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+client-proxy-system-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+client-proxy-system-devel.sha256sum] = "617f41b72b3bdc01a52efafd159e0c70ad4e5d20e8fd33ba474353329c2d7d6d"

URI_x86_64_v2_rust-hyper-util+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+default-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+default-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+default-devel.sha256sum] = "52232ea3a2df8f8343b734dd0e61408390a982d4408cd486a6d2d1716ac1bbe2"

URI_x86_64_v2_rust-hyper-util+full-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+full-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+full-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+full-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+full-devel.sha256sum] = "7c3df0c52c68a1b3d6c5586568f9d953ee60c6828a117ba769e45890804001d4"

URI_x86_64_v2_rust-hyper-util+http1-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+http1-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+http1-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+http1-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+http1-devel.sha256sum] = "ee83408f9efb2b8fa19a8025fc56b6e053fe90a1067e278741a4799da7949423"

URI_x86_64_v2_rust-hyper-util+http2-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+http2-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+http2-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+http2-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+http2-devel.sha256sum] = "018f47555449180531838600e1a3130e3641dacb6baa1c2b2d9ef15f6bf9d98d"

URI_x86_64_v2_rust-hyper-util+server-auto-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+server-auto-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+server-auto-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+server-auto-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+server-auto-devel.sha256sum] = "78eb7f5cca3e19ef683af767cca67066c441321d566f1f105abb9dea2817280c"

URI_x86_64_v2_rust-hyper-util+server-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+server-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+server-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+server-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+server-devel.sha256sum] = "609620e94c719bae0403e9ecd3b4d26573323a7d7dd6cd585512098d74ae8ada"

URI_x86_64_v2_rust-hyper-util+server-graceful-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+server-graceful-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+server-graceful-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+server-graceful-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+server-graceful-devel.sha256sum] = "b688d4b37dcb49af308fda1d500ab4656820add3c57be907883b6b58eb4ec4f5"

URI_x86_64_v2_rust-hyper-util+service-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+service-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+service-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+service-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+service-devel.sha256sum] = "485ac93fb05dd0e1f062108e9824842a5e209a821350b578c210e3d79399a27c"

URI_x86_64_v2_rust-hyper-util+tokio-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+tokio-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+tokio-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+tokio-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+tokio-devel.sha256sum] = "20ab9e18db1efbac4ef5b3e941947b416dea3b189402f4829ae08dfa3d2533c9"

URI_x86_64_v2_rust-hyper-util+tracing-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util+tracing-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util+tracing-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util+tracing-devel}"
SRC_URI[x86_64_v2_rust-hyper-util+tracing-devel.sha256sum] = "e1effd44982fd99ae1a109c9bedbbdb3fbb03a9b527a3fbf1366f1dedfd5327f"

URI_x86_64_v2_rust-hyper-util-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-hyper-util-devel-0.1.18-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-hyper-util-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-hyper-util-devel}"
SRC_URI[x86_64_v2_rust-hyper-util-devel.sha256sum] = "3b54c29d51a053ee5a46e4052f7110180b8a8e6ae10cc83b4ed4d8671233858f"

URI_aarch64_rust-hyper-util+client-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+client-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+client-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+client-devel}"
SRC_URI[aarch64_rust-hyper-util+client-devel.sha256sum] = "f758519394d186cb90e569247dbbb17daae5ef12dce96af2c7d8828d449ecb3a"

URI_aarch64_rust-hyper-util+client-legacy-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+client-legacy-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+client-legacy-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+client-legacy-devel}"
SRC_URI[aarch64_rust-hyper-util+client-legacy-devel.sha256sum] = "db70380c65a89423a18b3a8abf10c4399efead36f2ec365ea493ea76dcfe09c9"

URI_aarch64_rust-hyper-util+client-proxy-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+client-proxy-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+client-proxy-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+client-proxy-devel}"
SRC_URI[aarch64_rust-hyper-util+client-proxy-devel.sha256sum] = "5eab281248c82b95ae0ffde4148b64d20d0af68fb78ed1c466b7e58410d4f054"

URI_aarch64_rust-hyper-util+client-proxy-system-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+client-proxy-system-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+client-proxy-system-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+client-proxy-system-devel}"
SRC_URI[aarch64_rust-hyper-util+client-proxy-system-devel.sha256sum] = "c6f3b45d27f122f4c46e25de48e86ed296a789e4db04f324442ae062656ce00b"

URI_aarch64_rust-hyper-util+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+default-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+default-devel}"
SRC_URI[aarch64_rust-hyper-util+default-devel.sha256sum] = "fa6fd565d0c38e4163ec760d325684976c8e149c0787b889774a86bf4d3aa9d0"

URI_aarch64_rust-hyper-util+full-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+full-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+full-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+full-devel}"
SRC_URI[aarch64_rust-hyper-util+full-devel.sha256sum] = "57bfbbedd271920427aff8ec42df9c7ff17653861ac643ac69f43c88441a0346"

URI_aarch64_rust-hyper-util+http1-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+http1-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+http1-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+http1-devel}"
SRC_URI[aarch64_rust-hyper-util+http1-devel.sha256sum] = "b6a108566390f801833de1e427966ebd114157e7f0e77f4074c304818728e071"

URI_aarch64_rust-hyper-util+http2-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+http2-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+http2-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+http2-devel}"
SRC_URI[aarch64_rust-hyper-util+http2-devel.sha256sum] = "903fd508b807476addce5246432a09ad0745e0fa167792c042b97322175ca206"

URI_aarch64_rust-hyper-util+server-auto-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+server-auto-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+server-auto-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+server-auto-devel}"
SRC_URI[aarch64_rust-hyper-util+server-auto-devel.sha256sum] = "83640f870de3e54d930e04763d6ca04cd6bdafad248ef01736a51ea5346c107a"

URI_aarch64_rust-hyper-util+server-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+server-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+server-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+server-devel}"
SRC_URI[aarch64_rust-hyper-util+server-devel.sha256sum] = "63b71be1a51f756f2240a8b467da88e9ad78d7a9e7631f68943acc9566ce1ec2"

URI_aarch64_rust-hyper-util+server-graceful-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+server-graceful-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+server-graceful-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+server-graceful-devel}"
SRC_URI[aarch64_rust-hyper-util+server-graceful-devel.sha256sum] = "c9ce05a92fb7e177a8851e66280ce7ad03ef203bab64a717bbc4a0f908a15b05"

URI_aarch64_rust-hyper-util+service-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+service-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+service-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+service-devel}"
SRC_URI[aarch64_rust-hyper-util+service-devel.sha256sum] = "bb76b554074feb52e856d0010a9ec322f69bd30e2381d64670fc192dfaa3deb9"

URI_aarch64_rust-hyper-util+tokio-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+tokio-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+tokio-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+tokio-devel}"
SRC_URI[aarch64_rust-hyper-util+tokio-devel.sha256sum] = "0a045b57e7f5e9f472fe625af29400c51f3355560351429d8cc7a1849e27f4bf"

URI_aarch64_rust-hyper-util+tracing-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util+tracing-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util+tracing-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util+tracing-devel}"
SRC_URI[aarch64_rust-hyper-util+tracing-devel.sha256sum] = "3687cc985d8a13558d9bde1cc2f85ebc7508b7c993c3e11c8c6230a05d2c61a4"

URI_aarch64_rust-hyper-util-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-hyper-util-devel-0.1.18-1.el10_1.noarch.rpm;name=aarch64_rust-hyper-util-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-hyper-util-devel}"
SRC_URI[aarch64_rust-hyper-util-devel.sha256sum] = "1b2fc648004aa1030682a66540c19560ac4f39869e126ec0a237453d0d81081f"

RDEPENDS:rust-hyper-util+client-devel = " \
 cargo \
 rust-futures-channel+default-devel \
 rust-hyper+client-devel \
 rust-hyper-util-devel \
 rust-tokio+net-devel \
 rust-tokio-devel \
 rust-tower-service+default-devel \
 rust-tracing+std-devel \
 rust-tracing-devel \
 "
RDEPENDS:rust-hyper-util+client-legacy-devel = " \
 cargo \
 rust-futures-util-devel \
 rust-hyper-util+client-devel \
 rust-hyper-util-devel \
 rust-libc+default-devel \
 rust-tokio+sync-devel \
 rust-tokio-devel \
 virtual/crate_socket2/all__ge_0.5.9_with_crate_socket2/all__lt_0.7.0~ \
 virtual/crate_socket2/default__ge_0.5.9_with_crate_socket2/default__lt_0.7.0~ \
 "
RDEPENDS:rust-hyper-util+client-proxy-devel = " \
 cargo \
 rust-base64+default-devel \
 rust-hyper-util+client-devel \
 rust-hyper-util-devel \
 rust-ipnet+default-devel \
 rust-percent-encoding+default-devel \
 "
RDEPENDS:rust-hyper-util+client-proxy-system-devel = " \
 cargo \
 rust-hyper-util-devel \
 "
RDEPENDS:rust-hyper-util+default-devel = " \
 cargo \
 rust-hyper-util-devel \
 "
RDEPENDS:rust-hyper-util+full-devel = " \
 cargo \
 rust-hyper-util+client-devel \
 rust-hyper-util+client-legacy-devel \
 rust-hyper-util+client-proxy-devel \
 rust-hyper-util+client-proxy-system-devel \
 rust-hyper-util+http1-devel \
 rust-hyper-util+http2-devel \
 rust-hyper-util+server-auto-devel \
 rust-hyper-util+server-devel \
 rust-hyper-util+server-graceful-devel \
 rust-hyper-util+service-devel \
 rust-hyper-util+tokio-devel \
 rust-hyper-util+tracing-devel \
 rust-hyper-util-devel \
 "
RDEPENDS:rust-hyper-util+http1-devel = " \
 cargo \
 rust-hyper+http1-devel \
 rust-hyper-util-devel \
 "
RDEPENDS:rust-hyper-util+http2-devel = " \
 cargo \
 rust-hyper+http2-devel \
 rust-hyper-util-devel \
 "
RDEPENDS:rust-hyper-util+server-auto-devel = " \
 cargo \
 rust-hyper-util+http1-devel \
 rust-hyper-util+http2-devel \
 rust-hyper-util+server-devel \
 rust-hyper-util-devel \
 "
RDEPENDS:rust-hyper-util+server-devel = " \
 cargo \
 rust-hyper+server-devel \
 rust-hyper-util-devel \
 "
RDEPENDS:rust-hyper-util+server-graceful-devel = " \
 cargo \
 rust-hyper-util+server-devel \
 rust-hyper-util-devel \
 rust-tokio+sync-devel \
 rust-tokio-devel \
 "
RDEPENDS:rust-hyper-util+service-devel = " \
 cargo \
 rust-hyper-util-devel \
 rust-tower-service+default-devel \
 "
RDEPENDS:rust-hyper-util+tokio-devel = " \
 cargo \
 rust-hyper-util-devel \
 rust-tokio+rt-devel \
 rust-tokio+time-devel \
 rust-tokio-devel \
 "
RDEPENDS:rust-hyper-util+tracing-devel = " \
 cargo \
 rust-hyper-util-devel \
 rust-tracing+std-devel \
 rust-tracing-devel \
 "
RDEPENDS:rust-hyper-util-devel = " \
 cargo \
 rust \
 rust-bytes+default-devel \
 rust-futures-core+default-devel \
 rust-http+default-devel \
 rust-http-body+default-devel \
 rust-hyper+default-devel \
 rust-pin-project-lite+default-devel \
 "
