# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-dlv-list"
PV = "0.5.2"
PR = "2.el10_2"
PACKAGES = " \
 rust-dlv-list+default-devel \
 rust-dlv-list+serde-devel \
 rust-dlv-list+std-devel \
 rust-dlv-list-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-dlv-list-0.5.2-2.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "877560764c4140fe673a0092f14acd7397c10fc36c20d139f56162f095208c1c"

URI_x86_64_v2_rust-dlv-list+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dlv-list+default-devel-0.5.2-2.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dlv-list+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dlv-list+default-devel}"
SRC_URI[x86_64_v2_rust-dlv-list+default-devel.sha256sum] = "557a5d8fd2466030f7ecac868309c67a1f5afc7af2142cbe45b4b48ca552da6e"

URI_x86_64_v2_rust-dlv-list+serde-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dlv-list+serde-devel-0.5.2-2.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dlv-list+serde-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dlv-list+serde-devel}"
SRC_URI[x86_64_v2_rust-dlv-list+serde-devel.sha256sum] = "71b90cc4afb6a357c4f57e3cb575f3aa00eeb6b8aed3721f553105df3a826e7c"

URI_x86_64_v2_rust-dlv-list+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dlv-list+std-devel-0.5.2-2.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dlv-list+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dlv-list+std-devel}"
SRC_URI[x86_64_v2_rust-dlv-list+std-devel.sha256sum] = "879f9b087173bb469c4787a720b17c8ecea3ef89bcdf8b26bb899233b862bf61"

URI_x86_64_v2_rust-dlv-list-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dlv-list-devel-0.5.2-2.el10_2.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dlv-list-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dlv-list-devel}"
SRC_URI[x86_64_v2_rust-dlv-list-devel.sha256sum] = "c160ddab41f4d6935c9c1e51fed9e41351fcf81c41367b8bcf2ce95342579e0c"

URI_aarch64_rust-dlv-list+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dlv-list+default-devel-0.5.2-2.el10_2.noarch.rpm;name=aarch64_rust-dlv-list+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dlv-list+default-devel}"
SRC_URI[aarch64_rust-dlv-list+default-devel.sha256sum] = "23a10c9bea3ab8f4359c5b4094c1d27aa4bf9ae7ccae519e8f55b70b8814845b"

URI_aarch64_rust-dlv-list+serde-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dlv-list+serde-devel-0.5.2-2.el10_2.noarch.rpm;name=aarch64_rust-dlv-list+serde-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dlv-list+serde-devel}"
SRC_URI[aarch64_rust-dlv-list+serde-devel.sha256sum] = "0e0e685c3e985634724f557f722e8f883b34eac5cb5b32d1e75221b451a51f18"

URI_aarch64_rust-dlv-list+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dlv-list+std-devel-0.5.2-2.el10_2.noarch.rpm;name=aarch64_rust-dlv-list+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dlv-list+std-devel}"
SRC_URI[aarch64_rust-dlv-list+std-devel.sha256sum] = "04b92ba9d1a34190a6e58ba45bd31bc5d9fb743859fe7741f6fd0dd2b625a379"

URI_aarch64_rust-dlv-list-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dlv-list-devel-0.5.2-2.el10_2.noarch.rpm;name=aarch64_rust-dlv-list-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dlv-list-devel}"
SRC_URI[aarch64_rust-dlv-list-devel.sha256sum] = "3734b598e390048dad786089d28c6d876e7a04c553aa237d7e3f64d933522ed4"

RDEPENDS:rust-dlv-list+default-devel = " \
 cargo \
 rust-dlv-list+std-devel \
 rust-dlv-list-devel \
 "
RDEPENDS:rust-dlv-list+serde-devel = " \
 cargo \
 rust-dlv-list-devel \
 rust-serde-devel \
 "
RDEPENDS:rust-dlv-list+std-devel = " \
 cargo \
 rust-dlv-list-devel \
 "
RDEPENDS:rust-dlv-list-devel = " \
 cargo \
 rust-const-random+default-devel \
 "
