# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-serde_json"
PV = "1.0.143"
PR = "1.el10_0"
PACKAGES = " \
 rust-serde_json+alloc-devel \
 rust-serde_json+arbitrary_precision-devel \
 rust-serde_json+default-devel \
 rust-serde_json+float_roundtrip-devel \
 rust-serde_json+indexmap-devel \
 rust-serde_json+preserve_order-devel \
 rust-serde_json+raw_value-devel \
 rust-serde_json+std-devel \
 rust-serde_json+unbounded_depth-devel \
 rust-serde_json-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-serde_json-1.0.143-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "59af2b056c283a99186c7c964a8245fed396cc35a906cc5ce60e4a283657937c"

URI_x86_64_v2_rust-serde_json+alloc-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json+alloc-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json+alloc-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json+alloc-devel}"
SRC_URI[x86_64_v2_rust-serde_json+alloc-devel.sha256sum] = "d7ebbc95cfc44043007a8c174898d1c9a952d49c4b9fcc3501001acf6a29da94"

URI_x86_64_v2_rust-serde_json+arbitrary_precision-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json+arbitrary_precision-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json+arbitrary_precision-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json+arbitrary_precision-devel}"
SRC_URI[x86_64_v2_rust-serde_json+arbitrary_precision-devel.sha256sum] = "130e7f362ba11a9d93c801f327fc24f102e3dd859aa1b20ae3bf9699f7bf8390"

URI_x86_64_v2_rust-serde_json+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json+default-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json+default-devel}"
SRC_URI[x86_64_v2_rust-serde_json+default-devel.sha256sum] = "c5b9374e6dac9e2699903e02876357750aecfa86b4310b117faefc94bcd06807"

URI_x86_64_v2_rust-serde_json+float_roundtrip-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json+float_roundtrip-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json+float_roundtrip-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json+float_roundtrip-devel}"
SRC_URI[x86_64_v2_rust-serde_json+float_roundtrip-devel.sha256sum] = "642e0d7b3366f1d531944e1fe94d9fea6a7da2606ebb3d82bcb9f051e2ff6e82"

URI_x86_64_v2_rust-serde_json+indexmap-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json+indexmap-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json+indexmap-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json+indexmap-devel}"
SRC_URI[x86_64_v2_rust-serde_json+indexmap-devel.sha256sum] = "9aa2cf69d977e83374d75c67d5966a29bcc4b1bd34317eab0318ade957a49ce9"

URI_x86_64_v2_rust-serde_json+preserve_order-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json+preserve_order-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json+preserve_order-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json+preserve_order-devel}"
SRC_URI[x86_64_v2_rust-serde_json+preserve_order-devel.sha256sum] = "ba17e5b4afd152caa0e891b1f8a89def1f0573430431b65a9fdae307734a918c"

URI_x86_64_v2_rust-serde_json+raw_value-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json+raw_value-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json+raw_value-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json+raw_value-devel}"
SRC_URI[x86_64_v2_rust-serde_json+raw_value-devel.sha256sum] = "44cbec74083988f514a8350af0c265c5813cfe7c8c38c4536413a352ea4bcb73"

URI_x86_64_v2_rust-serde_json+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json+std-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json+std-devel}"
SRC_URI[x86_64_v2_rust-serde_json+std-devel.sha256sum] = "3be4d3352255c5d3c756d44539d4d3c58760e878907fbd5d604d2a777c513973"

URI_x86_64_v2_rust-serde_json+unbounded_depth-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json+unbounded_depth-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json+unbounded_depth-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json+unbounded_depth-devel}"
SRC_URI[x86_64_v2_rust-serde_json+unbounded_depth-devel.sha256sum] = "b82bfd51605cddced32f4d76d188bf200dcdabb82b5fa87b58ea4c319e2fa439"

URI_x86_64_v2_rust-serde_json-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-serde_json-devel-1.0.143-1.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-serde_json-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-serde_json-devel}"
SRC_URI[x86_64_v2_rust-serde_json-devel.sha256sum] = "e3cfc5c439c2f314de6193e41318f275088a16434a5ea0a4d8ddb91f37ddede5"

URI_aarch64_rust-serde_json+alloc-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json+alloc-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json+alloc-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json+alloc-devel}"
SRC_URI[aarch64_rust-serde_json+alloc-devel.sha256sum] = "cd7d44ef8a67f69e07bd301edd42b2206dec1edb27240b84931a07d3923da3a5"

URI_aarch64_rust-serde_json+arbitrary_precision-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json+arbitrary_precision-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json+arbitrary_precision-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json+arbitrary_precision-devel}"
SRC_URI[aarch64_rust-serde_json+arbitrary_precision-devel.sha256sum] = "c9ac91e237f4f92c02ff929ec4ffff4ec689e4bedb982dda4c08a693207864b2"

URI_aarch64_rust-serde_json+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json+default-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json+default-devel}"
SRC_URI[aarch64_rust-serde_json+default-devel.sha256sum] = "7a5282eb0446e1e4ca56d881055c9fdaa924bbf22f10e024f02ab9008381fc11"

URI_aarch64_rust-serde_json+float_roundtrip-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json+float_roundtrip-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json+float_roundtrip-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json+float_roundtrip-devel}"
SRC_URI[aarch64_rust-serde_json+float_roundtrip-devel.sha256sum] = "c09d9a838a0ee5f86a5bd6f40989fc5d1f4f0a039c25822fa24325a9ca50a373"

URI_aarch64_rust-serde_json+indexmap-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json+indexmap-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json+indexmap-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json+indexmap-devel}"
SRC_URI[aarch64_rust-serde_json+indexmap-devel.sha256sum] = "9c7cda180f796791a69570d6c5135484a384d77dc3bc852e8dd54cf0638e6081"

URI_aarch64_rust-serde_json+preserve_order-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json+preserve_order-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json+preserve_order-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json+preserve_order-devel}"
SRC_URI[aarch64_rust-serde_json+preserve_order-devel.sha256sum] = "2a4668b1c67f726e629be769a355a06d171841de18649e0bb6f4aba7f6217265"

URI_aarch64_rust-serde_json+raw_value-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json+raw_value-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json+raw_value-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json+raw_value-devel}"
SRC_URI[aarch64_rust-serde_json+raw_value-devel.sha256sum] = "2795cea8ff68e002dfac13d0934f4d6dc06da1eae3ed34fc54c52a22886c8207"

URI_aarch64_rust-serde_json+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json+std-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json+std-devel}"
SRC_URI[aarch64_rust-serde_json+std-devel.sha256sum] = "b64a78cea2c3337997e2059cfb4c005ae1ad0a265570aaabf7d146b1ffd7061c"

URI_aarch64_rust-serde_json+unbounded_depth-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json+unbounded_depth-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json+unbounded_depth-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json+unbounded_depth-devel}"
SRC_URI[aarch64_rust-serde_json+unbounded_depth-devel.sha256sum] = "b9487ce62996c2b93d32d5bdbc0c0e6270999e44933fa53d92d1cb92c04cd688"

URI_aarch64_rust-serde_json-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-serde_json-devel-1.0.143-1.el10_0.noarch.rpm;name=aarch64_rust-serde_json-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-serde_json-devel}"
SRC_URI[aarch64_rust-serde_json-devel.sha256sum] = "b2f257e7453bfbb49511b46c4bb2405b539df6779ba6255f0587ff0ff5a1489f"

RDEPENDS:rust-serde_json+alloc-devel = " \
 cargo \
 rust-serde+alloc-devel \
 rust-serde_json-devel \
 "
RDEPENDS:rust-serde_json+arbitrary_precision-devel = " \
 cargo \
 rust-serde_json-devel \
 "
RDEPENDS:rust-serde_json+default-devel = " \
 cargo \
 rust-serde_json+std-devel \
 rust-serde_json-devel \
 "
RDEPENDS:rust-serde_json+float_roundtrip-devel = " \
 cargo \
 rust-serde_json-devel \
 "
RDEPENDS:rust-serde_json+indexmap-devel = " \
 cargo \
 rust-indexmap+default-devel \
 rust-serde_json-devel \
 "
RDEPENDS:rust-serde_json+preserve_order-devel = " \
 cargo \
 rust-serde_json+indexmap-devel \
 rust-serde_json+std-devel \
 rust-serde_json-devel \
 "
RDEPENDS:rust-serde_json+raw_value-devel = " \
 cargo \
 rust-serde_json-devel \
 "
RDEPENDS:rust-serde_json+std-devel = " \
 cargo \
 rust-memchr+std-devel \
 rust-serde+std-devel \
 rust-serde_json-devel \
 "
RDEPENDS:rust-serde_json+unbounded_depth-devel = " \
 cargo \
 rust-serde_json-devel \
 "
RDEPENDS:rust-serde_json-devel = " \
 cargo \
 rust \
 rust-itoa+default-devel \
 rust-memchr-devel \
 rust-ryu+default-devel \
 rust-serde-devel \
 "
