# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-rand_xoshiro"
PV = "0.8.1"
PR = "1.el10_3"
PACKAGES = " \
 rust-rand_xoshiro+default-devel \
 rust-rand_xoshiro+serde-devel \
 rust-rand_xoshiro-devel \
 "

SRC_URI = "${EPELSRC_MIRROR}/Packages/r/rust-rand_xoshiro-0.8.1-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI[src.sha256sum] = "7e0e2c8eba4193668a2bd64fc0042208418dd09273f89999ac3de38b099bff5a"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-rand_xoshiro+default-devel-0.8.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-rand_xoshiro+default-devel;unpack=0"
SRC_URI[x86_64_v2_rust-rand_xoshiro+default-devel.sha256sum] = "fc6f7c6233ae4fe1f70505cc70a4001c094281b9c6a4f1817b94f156efc2d1c2"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-rand_xoshiro+serde-devel-0.8.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-rand_xoshiro+serde-devel;unpack=0"
SRC_URI[x86_64_v2_rust-rand_xoshiro+serde-devel.sha256sum] = "29b2e2190f1562ff1500c979d08c3b0a28abd4695690b71751594bcfa646175c"

SRC_URI:append = " ${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-rand_xoshiro-devel-0.8.1-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-rand_xoshiro-devel;unpack=0"
SRC_URI[x86_64_v2_rust-rand_xoshiro-devel.sha256sum] = "0bc3016674fdbc4867ccfe01aec1836044e2f09800c2d5fd482b0e89802db0ed"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/r/rust-rand_xoshiro+default-devel-0.8.1-1.el10_3.noarch.rpm;name=aarch64_rust-rand_xoshiro+default-devel;unpack=0"
SRC_URI[aarch64_rust-rand_xoshiro+default-devel.sha256sum] = "7cf01599caaf76a0031ec4a231c2fa1c88b3782c5b1cda11d27e2d128494e8c5"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/r/rust-rand_xoshiro+serde-devel-0.8.1-1.el10_3.noarch.rpm;name=aarch64_rust-rand_xoshiro+serde-devel;unpack=0"
SRC_URI[aarch64_rust-rand_xoshiro+serde-devel.sha256sum] = "43908033674bc36f025f708d1e96610a6de55edce98555369172aedb825b51c4"

SRC_URI:append = " ${EPEL_MIRROR}/aarch64/Packages/r/rust-rand_xoshiro-devel-0.8.1-1.el10_3.noarch.rpm;name=aarch64_rust-rand_xoshiro-devel;unpack=0"
SRC_URI[aarch64_rust-rand_xoshiro-devel.sha256sum] = "5b96d331543a3e57f8a6a8e455ee342b41789d07b86836d3e190f201b59c6eb0"

RDEPENDS:rust-rand_xoshiro+default-devel = " \
 cargo \
 rust-rand_xoshiro-devel \
 "
RDEPENDS:rust-rand_xoshiro+serde-devel = " \
 cargo \
 rust-rand_xoshiro-devel \
 rust-serde+default-devel \
 rust-serde+derive-devel \
 "
RDEPENDS:rust-rand_xoshiro-devel = " \
 cargo \
 rust \
 rust-rand_core+default-devel \
 "
