# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-portable-atomic"
PV = "1.13.1"
PR = "1.el10_1"
PACKAGES = " \
 rust-portable-atomic+critical-section-devel \
 rust-portable-atomic+default-devel \
 rust-portable-atomic+disable-fiq-devel \
 rust-portable-atomic+fallback-devel \
 rust-portable-atomic+float-devel \
 rust-portable-atomic+force-amo-devel \
 rust-portable-atomic+require-cas-devel \
 rust-portable-atomic+s-mode-devel \
 rust-portable-atomic+serde-devel \
 rust-portable-atomic+std-devel \
 rust-portable-atomic+unsafe-assume-privileged-devel \
 rust-portable-atomic+unsafe-assume-single-core-devel \
 rust-portable-atomic-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-portable-atomic-1.13.1-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2d428bb3e8de5220646b05faf7ee6387d7727a2f34ae13f031ec13300945f32d"

URI_x86_64_v2_rust-portable-atomic+critical-section-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+critical-section-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+critical-section-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+critical-section-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+critical-section-devel.sha256sum] = "cb2602e08f66d1febfcd3137111cfb66383dfc3de71088ec8fbda7785dd4953d"

URI_x86_64_v2_rust-portable-atomic+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+default-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+default-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+default-devel.sha256sum] = "516a20081f059f4065dc594d64bd6a1fdf3a8983181515868d36ddf3d6610203"

URI_x86_64_v2_rust-portable-atomic+disable-fiq-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+disable-fiq-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+disable-fiq-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+disable-fiq-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+disable-fiq-devel.sha256sum] = "ec67b4dda0f13f7287f8cf684cb1aea33277dc3a56a75b6c1d73e58124573116"

URI_x86_64_v2_rust-portable-atomic+fallback-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+fallback-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+fallback-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+fallback-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+fallback-devel.sha256sum] = "a9322a59a2d50440a6862ab9dae2b86e27caf7e5f1db17604e83066e1026692c"

URI_x86_64_v2_rust-portable-atomic+float-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+float-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+float-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+float-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+float-devel.sha256sum] = "4af10dc494972a98d300c58b006c8451e51b4124634d5d5fa53e5e940e25e75f"

URI_x86_64_v2_rust-portable-atomic+force-amo-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+force-amo-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+force-amo-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+force-amo-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+force-amo-devel.sha256sum] = "7d7dfba3e294887c7b90b2aeee124d1d79a121db28329eb720cce742a4d782e9"

URI_x86_64_v2_rust-portable-atomic+require-cas-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+require-cas-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+require-cas-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+require-cas-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+require-cas-devel.sha256sum] = "e41f10f109d78ae481cfed630b47b6dae447eaf4b1e91b4c8a2646773ded5ebf"

URI_x86_64_v2_rust-portable-atomic+s-mode-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+s-mode-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+s-mode-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+s-mode-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+s-mode-devel.sha256sum] = "f64aa70a64d605de3e8295db6491277c2cf43cf8a8cfb6a66bdb22fa93b39fc5"

URI_x86_64_v2_rust-portable-atomic+serde-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+serde-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+serde-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+serde-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+serde-devel.sha256sum] = "7f82d280ebb3d89f56599039526f187fbcd6af7ea115e1bd0f8a960263af8748"

URI_x86_64_v2_rust-portable-atomic+std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+std-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+std-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+std-devel.sha256sum] = "00bac4ce6c319cda05012a00ea3f884dd59f22737c2c088e7c429d9fb43e3308"

URI_x86_64_v2_rust-portable-atomic+unsafe-assume-privileged-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+unsafe-assume-privileged-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+unsafe-assume-privileged-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+unsafe-assume-privileged-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+unsafe-assume-privileged-devel.sha256sum] = "d63865fdca48a034c53eee6de9e217fd67ff120ab7d17336069cdaa0c852d4a8"

URI_x86_64_v2_rust-portable-atomic+unsafe-assume-single-core-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic+unsafe-assume-single-core-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic+unsafe-assume-single-core-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic+unsafe-assume-single-core-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic+unsafe-assume-single-core-devel.sha256sum] = "708fc3ae3378ce9ccc0e6623ae4f13a5d0d15f81bb3f368d4b908674d2250225"

URI_x86_64_v2_rust-portable-atomic-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-portable-atomic-devel-1.13.1-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_rust-portable-atomic-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-portable-atomic-devel}"
SRC_URI[x86_64_v2_rust-portable-atomic-devel.sha256sum] = "712dbe1f3a9a5dd4ed15f20fa3133891ba1630af17319eb740c9fd3194b7967d"

URI_aarch64_rust-portable-atomic+critical-section-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+critical-section-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+critical-section-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+critical-section-devel}"
SRC_URI[aarch64_rust-portable-atomic+critical-section-devel.sha256sum] = "6f6c93586bd482f44dcb36a9225d61c8914679249346a61c0364ad2dac6f2208"

URI_aarch64_rust-portable-atomic+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+default-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+default-devel}"
SRC_URI[aarch64_rust-portable-atomic+default-devel.sha256sum] = "06cac4c869e6e11404352ce951090f513f4f27c31970b1d6df83701df5f81450"

URI_aarch64_rust-portable-atomic+disable-fiq-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+disable-fiq-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+disable-fiq-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+disable-fiq-devel}"
SRC_URI[aarch64_rust-portable-atomic+disable-fiq-devel.sha256sum] = "c1191477413fea0151c4f0bd17af84137ae955b6b379ed02393347a3e27fc7a8"

URI_aarch64_rust-portable-atomic+fallback-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+fallback-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+fallback-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+fallback-devel}"
SRC_URI[aarch64_rust-portable-atomic+fallback-devel.sha256sum] = "cb979a63c0d5ea0bc03507d79fd5e9dbde4e54649ffce4e1ed437cbdc86a21ed"

URI_aarch64_rust-portable-atomic+float-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+float-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+float-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+float-devel}"
SRC_URI[aarch64_rust-portable-atomic+float-devel.sha256sum] = "dda6e4b23e2942936c72330063eac3ed16018ca38ff96951bd3c43b22b10979f"

URI_aarch64_rust-portable-atomic+force-amo-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+force-amo-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+force-amo-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+force-amo-devel}"
SRC_URI[aarch64_rust-portable-atomic+force-amo-devel.sha256sum] = "cd29ea05661eaee3403fb030e15b9344223c05fe28ec1123d1d792b58dfd2bcd"

URI_aarch64_rust-portable-atomic+require-cas-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+require-cas-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+require-cas-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+require-cas-devel}"
SRC_URI[aarch64_rust-portable-atomic+require-cas-devel.sha256sum] = "19f2fc0062d7214e31aa04f7ad9bd0ea846cf4e577e09d9c6e0bf0f9bcc3410e"

URI_aarch64_rust-portable-atomic+s-mode-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+s-mode-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+s-mode-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+s-mode-devel}"
SRC_URI[aarch64_rust-portable-atomic+s-mode-devel.sha256sum] = "af54682bd51633737b4f00f38eba148e7299dd0fb9fcfe052b5ad479b60eabdd"

URI_aarch64_rust-portable-atomic+serde-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+serde-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+serde-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+serde-devel}"
SRC_URI[aarch64_rust-portable-atomic+serde-devel.sha256sum] = "32a9c871d14adf27f335742f24e565d6f3fc52d0acb3a800cbdf6fb6ed2f574c"

URI_aarch64_rust-portable-atomic+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+std-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+std-devel}"
SRC_URI[aarch64_rust-portable-atomic+std-devel.sha256sum] = "74d7c5d72ea36d9d23e10f2fc51e3478fb21c87c81880caeb7a7cb46b128cbb5"

URI_aarch64_rust-portable-atomic+unsafe-assume-privileged-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+unsafe-assume-privileged-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+unsafe-assume-privileged-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+unsafe-assume-privileged-devel}"
SRC_URI[aarch64_rust-portable-atomic+unsafe-assume-privileged-devel.sha256sum] = "45f999371049ee76a7e1f9bd133f99997130519cf8202278236167853b4f6c6d"

URI_aarch64_rust-portable-atomic+unsafe-assume-single-core-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic+unsafe-assume-single-core-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic+unsafe-assume-single-core-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic+unsafe-assume-single-core-devel}"
SRC_URI[aarch64_rust-portable-atomic+unsafe-assume-single-core-devel.sha256sum] = "9f99c7145ec740cbe732521064273c9dad5ce1afd6b4574c7e5d9f226a03188a"

URI_aarch64_rust-portable-atomic-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-portable-atomic-devel-1.13.1-1.el10_1.noarch.rpm;name=aarch64_rust-portable-atomic-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-portable-atomic-devel}"
SRC_URI[aarch64_rust-portable-atomic-devel.sha256sum] = "ca0cdf831fc2d552430c958d0563c23ab300748dabf01fe4d1400f8f5d7e929d"

RDEPENDS:rust-portable-atomic+critical-section-devel = " \
 cargo \
 rust-critical-section+default-devel \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+default-devel = " \
 cargo \
 rust-portable-atomic+fallback-devel \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+disable-fiq-devel = " \
 cargo \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+fallback-devel = " \
 cargo \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+float-devel = " \
 cargo \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+force-amo-devel = " \
 cargo \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+require-cas-devel = " \
 cargo \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+s-mode-devel = " \
 cargo \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+serde-devel = " \
 cargo \
 rust-portable-atomic-devel \
 rust-serde-devel \
 "
RDEPENDS:rust-portable-atomic+std-devel = " \
 cargo \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+unsafe-assume-privileged-devel = " \
 cargo \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic+unsafe-assume-single-core-devel = " \
 cargo \
 rust-portable-atomic-devel \
 "
RDEPENDS:rust-portable-atomic-devel = " \
 cargo \
 rust \
 "
