# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-sqlx-macros-core"
PV = "0.8.6"
PR = "4.el10_3"
PACKAGES = " \
 rust-sqlx-macros-core+_rt-tokio-devel \
 rust-sqlx-macros-core+_sqlite-devel \
 rust-sqlx-macros-core+_tls-native-tls-devel \
 rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel \
 rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel \
 rust-sqlx-macros-core+async-std-devel \
 rust-sqlx-macros-core+bigdecimal-devel \
 rust-sqlx-macros-core+bit-vec-devel \
 rust-sqlx-macros-core+chrono-devel \
 rust-sqlx-macros-core+default-devel \
 rust-sqlx-macros-core+derive-devel \
 rust-sqlx-macros-core+ipnet-devel \
 rust-sqlx-macros-core+ipnetwork-devel \
 rust-sqlx-macros-core+json-devel \
 rust-sqlx-macros-core+mac_address-devel \
 rust-sqlx-macros-core+macros-devel \
 rust-sqlx-macros-core+migrate-devel \
 rust-sqlx-macros-core+mysql-devel \
 rust-sqlx-macros-core+postgres-devel \
 rust-sqlx-macros-core+rust_decimal-devel \
 rust-sqlx-macros-core+sqlite-devel \
 rust-sqlx-macros-core+sqlite-unbundled-devel \
 rust-sqlx-macros-core+sqlx-mysql-devel \
 rust-sqlx-macros-core+sqlx-postgres-devel \
 rust-sqlx-macros-core+sqlx-sqlite-devel \
 rust-sqlx-macros-core+time-devel \
 rust-sqlx-macros-core+tokio-devel \
 rust-sqlx-macros-core+uuid-devel \
 rust-sqlx-macros-core-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-sqlx-macros-core-0.8.6-4.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7cda1e0c84a148f2c86f80270662defe814dc5ac886874b9981bd7a0ae4fd24a"

URI_x86_64_v2_rust-sqlx-macros-core+_rt-tokio-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+_rt-tokio-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+_rt-tokio-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+_rt-tokio-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+_rt-tokio-devel.sha256sum] = "5153bb7f68d420bbbeb017502674018016474ffec194502d6ab9fd3e00bce723"

URI_x86_64_v2_rust-sqlx-macros-core+_sqlite-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+_sqlite-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+_sqlite-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+_sqlite-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+_sqlite-devel.sha256sum] = "f002d42d44a8bed3423af978e3449567bf29ccfcbb93ede0e48122d0a21c7f06"

URI_x86_64_v2_rust-sqlx-macros-core+_tls-native-tls-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+_tls-native-tls-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+_tls-native-tls-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+_tls-native-tls-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+_tls-native-tls-devel.sha256sum] = "d08dbc80c4035c51465fedfdeb3598d6cceeb039787d006575e940447d27f8e1"

URI_x86_64_v2_rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel.sha256sum] = "6c083278a1b2d18c620622e2367dfdd505e9d77ec8cc6657624a25e071f89d60"

URI_x86_64_v2_rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel.sha256sum] = "32f833a1eb8f933ff507b8c3c87e490e2f23b34a96040165341df28b76ad31ed"

URI_x86_64_v2_rust-sqlx-macros-core+async-std-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+async-std-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+async-std-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+async-std-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+async-std-devel.sha256sum] = "9930e7f892046954f891464ebcf77f41353cb8f3b48569fa78d80136db013df1"

URI_x86_64_v2_rust-sqlx-macros-core+bigdecimal-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+bigdecimal-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+bigdecimal-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+bigdecimal-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+bigdecimal-devel.sha256sum] = "5a9aef841123b85c680f4a561208e55cb1e0e15763a6832f673cbb3ae8dfd04f"

URI_x86_64_v2_rust-sqlx-macros-core+bit-vec-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+bit-vec-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+bit-vec-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+bit-vec-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+bit-vec-devel.sha256sum] = "a8ea2fdd7e31c6900b38779a3ecdc860a130c3b0666e4384c6129f2ab69e571e"

URI_x86_64_v2_rust-sqlx-macros-core+chrono-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+chrono-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+chrono-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+chrono-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+chrono-devel.sha256sum] = "ae72a48b833231f630341ed91eb7103559115c96e7563443be0d12e79e32e6df"

URI_x86_64_v2_rust-sqlx-macros-core+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+default-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+default-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+default-devel.sha256sum] = "ccea44e659a0aa5eb911442c27514cd8b67455694308c6089f4f5ef9a1df9950"

URI_x86_64_v2_rust-sqlx-macros-core+derive-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+derive-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+derive-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+derive-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+derive-devel.sha256sum] = "65b191af3a4333ffb658b187e98f7f637370f701c405d9a2f4692cefb32994f9"

URI_x86_64_v2_rust-sqlx-macros-core+ipnet-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+ipnet-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+ipnet-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+ipnet-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+ipnet-devel.sha256sum] = "d6a94dd9b6c4970dcaffdd3624575d1e801e3b00cc99d65cfbe018e431e89a3b"

URI_x86_64_v2_rust-sqlx-macros-core+ipnetwork-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+ipnetwork-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+ipnetwork-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+ipnetwork-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+ipnetwork-devel.sha256sum] = "30c69af5c805acdda1390eabc3494b33be93377d4987cf3c372b0b8a3a05ae47"

URI_x86_64_v2_rust-sqlx-macros-core+json-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+json-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+json-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+json-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+json-devel.sha256sum] = "ef2d12da9160eaf7be274c84f3c89113da250d149b87620147c9c32f4c202c15"

URI_x86_64_v2_rust-sqlx-macros-core+mac_address-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+mac_address-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+mac_address-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+mac_address-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+mac_address-devel.sha256sum] = "ce7dcd19c5633718fe720c098f147fd64b534548d5abf7dcba6a157116070fe4"

URI_x86_64_v2_rust-sqlx-macros-core+macros-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+macros-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+macros-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+macros-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+macros-devel.sha256sum] = "82292ee31272b0d0d20a4c02732fd184287384dfeb7f50fd2cecf16049d38f7e"

URI_x86_64_v2_rust-sqlx-macros-core+migrate-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+migrate-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+migrate-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+migrate-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+migrate-devel.sha256sum] = "b13e523079395175752c77832525b0832ed0450881f838089224471f5a990fe8"

URI_x86_64_v2_rust-sqlx-macros-core+mysql-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+mysql-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+mysql-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+mysql-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+mysql-devel.sha256sum] = "03d3344261e1e2916d1cfb947eddadafa0dc660e8b7e042d5ac1697903d79088"

URI_x86_64_v2_rust-sqlx-macros-core+postgres-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+postgres-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+postgres-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+postgres-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+postgres-devel.sha256sum] = "464684b8e91701aab9d5e8240f58442eec66abea3afc66c8e27f896d5c963869"

URI_x86_64_v2_rust-sqlx-macros-core+rust_decimal-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+rust_decimal-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+rust_decimal-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+rust_decimal-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+rust_decimal-devel.sha256sum] = "31db540c499c37c8eb94d5573a286544962e42a3b4ba769a871d2e640c02737a"

URI_x86_64_v2_rust-sqlx-macros-core+sqlite-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+sqlite-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+sqlite-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+sqlite-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+sqlite-devel.sha256sum] = "e31a0e52d41580ddf7e337169f463dc181ef6f978ca02d9f413f50d1157f5f2d"

URI_x86_64_v2_rust-sqlx-macros-core+sqlite-unbundled-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+sqlite-unbundled-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+sqlite-unbundled-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+sqlite-unbundled-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+sqlite-unbundled-devel.sha256sum] = "756f7edd543b71f95d000e89ac3b22d71b6e4b5f3484fe9df0ee13d5634d8b67"

URI_x86_64_v2_rust-sqlx-macros-core+sqlx-mysql-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+sqlx-mysql-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+sqlx-mysql-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+sqlx-mysql-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+sqlx-mysql-devel.sha256sum] = "98453b73065920fb62ca437ef253436b804d9cad3b118d831eac076999052dcb"

URI_x86_64_v2_rust-sqlx-macros-core+sqlx-postgres-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+sqlx-postgres-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+sqlx-postgres-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+sqlx-postgres-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+sqlx-postgres-devel.sha256sum] = "4fb799981b2585bab33d37487e1908ac72ba3c156c467c7ae8ab6e773aa53659"

URI_x86_64_v2_rust-sqlx-macros-core+sqlx-sqlite-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+sqlx-sqlite-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+sqlx-sqlite-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+sqlx-sqlite-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+sqlx-sqlite-devel.sha256sum] = "4469953e5f6751432558c4a38f73d57ed42741d47647a106abbf14469eb3efca"

URI_x86_64_v2_rust-sqlx-macros-core+time-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+time-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+time-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+time-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+time-devel.sha256sum] = "391edc0464f93ea372973fe4fd53ca516970859a96ca4b15befdde9371ca5626"

URI_x86_64_v2_rust-sqlx-macros-core+tokio-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+tokio-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+tokio-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+tokio-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+tokio-devel.sha256sum] = "34051bb112b67b509f1384a6bc8e91e581bf137fb9690bdc453ae1f0c55b841d"

URI_x86_64_v2_rust-sqlx-macros-core+uuid-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core+uuid-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core+uuid-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core+uuid-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core+uuid-devel.sha256sum] = "e6e5172554cdf4600649c608833c9e2228de80fa99700d62279c866bccaf753b"

URI_x86_64_v2_rust-sqlx-macros-core-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-sqlx-macros-core-devel-0.8.6-4.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-sqlx-macros-core-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-sqlx-macros-core-devel}"
SRC_URI[x86_64_v2_rust-sqlx-macros-core-devel.sha256sum] = "eed6436a05c4f96c8e82beec5007c837e7ac2b06caddd693730c211544760384"

URI_aarch64_rust-sqlx-macros-core+_rt-tokio-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+_rt-tokio-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+_rt-tokio-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+_rt-tokio-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+_rt-tokio-devel.sha256sum] = "52967bb679b5a68bc86e9e15e919010f429518410dc15c6cefa92e5a46e66da9"

URI_aarch64_rust-sqlx-macros-core+_sqlite-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+_sqlite-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+_sqlite-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+_sqlite-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+_sqlite-devel.sha256sum] = "de4bbe7e1df30d473b89f2f1f4f5e82c70e5bc9d9d174aae63ccd49601c03492"

URI_aarch64_rust-sqlx-macros-core+_tls-native-tls-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+_tls-native-tls-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+_tls-native-tls-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+_tls-native-tls-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+_tls-native-tls-devel.sha256sum] = "976de15d6dd480fb41cc2467083eb801cb05f8846b411e333c1a1151a64f8932"

URI_aarch64_rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel.sha256sum] = "bca5d9f0185c504e59039781b65a02fa4bc5e8635e8cdd686946bc212b3b2ded"

URI_aarch64_rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel.sha256sum] = "5e4b8ab7ec325686f0d2f75519c4c85ee16d45f1bf55e59c2407aa253d2fd10f"

URI_aarch64_rust-sqlx-macros-core+async-std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+async-std-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+async-std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+async-std-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+async-std-devel.sha256sum] = "a41180a1ff477a5b413340e4d2d1663216b4e60882498cfaa876e5c1a6aae67e"

URI_aarch64_rust-sqlx-macros-core+bigdecimal-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+bigdecimal-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+bigdecimal-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+bigdecimal-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+bigdecimal-devel.sha256sum] = "4b4ce3e5946039da5dc478b14fcc7867006c8e5aa9ef4e8383cd91004be3f50f"

URI_aarch64_rust-sqlx-macros-core+bit-vec-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+bit-vec-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+bit-vec-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+bit-vec-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+bit-vec-devel.sha256sum] = "d01586d13f446e291be9e805fdf93ade4ee832d487d65286cc2a969c0ee95d0a"

URI_aarch64_rust-sqlx-macros-core+chrono-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+chrono-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+chrono-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+chrono-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+chrono-devel.sha256sum] = "8e049628abcd97136b10e5d13ca0e39e088c9a5dae0f5e9df89510874f27d267"

URI_aarch64_rust-sqlx-macros-core+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+default-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+default-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+default-devel.sha256sum] = "b6dbe9cc795ca07fa6d85ff5ba7a634f8f55665e18427d4dafb7d21fffd3dbfa"

URI_aarch64_rust-sqlx-macros-core+derive-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+derive-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+derive-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+derive-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+derive-devel.sha256sum] = "83df3f1f371d47b814ca279f738675ea6c1649dc65ef5478ccb6af4bc883470d"

URI_aarch64_rust-sqlx-macros-core+ipnet-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+ipnet-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+ipnet-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+ipnet-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+ipnet-devel.sha256sum] = "99a2be5f862b37495f86103b4149e57c371725b3e8e3a312dad87bf0562bb68a"

URI_aarch64_rust-sqlx-macros-core+ipnetwork-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+ipnetwork-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+ipnetwork-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+ipnetwork-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+ipnetwork-devel.sha256sum] = "1b2211c1f7781af10db1fa4a543029e899d88c5592f40bdb2659f0833d9bb2a3"

URI_aarch64_rust-sqlx-macros-core+json-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+json-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+json-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+json-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+json-devel.sha256sum] = "c67c7a8f8fde7b666fb12c34b5707bb3677cbe0d3456a6da20c862849c632320"

URI_aarch64_rust-sqlx-macros-core+mac_address-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+mac_address-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+mac_address-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+mac_address-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+mac_address-devel.sha256sum] = "a5b3f84bb700ec513dedaf37c6ad9022ad99fabb1f10abae3d0aca345978c416"

URI_aarch64_rust-sqlx-macros-core+macros-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+macros-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+macros-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+macros-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+macros-devel.sha256sum] = "d945cab01a0fab47f8a5ee890fa8b7b2ba7ad2242e43cf1a1b49be8062846c95"

URI_aarch64_rust-sqlx-macros-core+migrate-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+migrate-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+migrate-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+migrate-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+migrate-devel.sha256sum] = "b31893e0143857ffb6bea6cf7fd98d7927cf1407aa4bd0f10a8ec1b95be1fed1"

URI_aarch64_rust-sqlx-macros-core+mysql-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+mysql-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+mysql-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+mysql-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+mysql-devel.sha256sum] = "92950344c60fb89b21a8961fcfcb3e1d0df69c2cbac23dae2f51ea2ebae632f5"

URI_aarch64_rust-sqlx-macros-core+postgres-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+postgres-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+postgres-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+postgres-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+postgres-devel.sha256sum] = "911048505f6acba56c68de6c7ca5ea8d905d46e5a109dd4ed148642c8467b044"

URI_aarch64_rust-sqlx-macros-core+rust_decimal-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+rust_decimal-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+rust_decimal-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+rust_decimal-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+rust_decimal-devel.sha256sum] = "ab905fb483cf1c517d7469ae58ec114851df26de599d8095a9f089f2e7c1eb56"

URI_aarch64_rust-sqlx-macros-core+sqlite-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+sqlite-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+sqlite-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+sqlite-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+sqlite-devel.sha256sum] = "a3b800675663b495ad34d592a99a91f3e214a5bfc2a9fc35614e1c48d30f4902"

URI_aarch64_rust-sqlx-macros-core+sqlite-unbundled-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+sqlite-unbundled-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+sqlite-unbundled-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+sqlite-unbundled-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+sqlite-unbundled-devel.sha256sum] = "8f19f31b7f60c5684dc0da241e565eba24c1945e9654fcc26db36ca6175c0ea8"

URI_aarch64_rust-sqlx-macros-core+sqlx-mysql-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+sqlx-mysql-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+sqlx-mysql-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+sqlx-mysql-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+sqlx-mysql-devel.sha256sum] = "57ef855df2e360428b0675b25ddd5be3f15d0965fcb6b6cd71b0312ec6727d8b"

URI_aarch64_rust-sqlx-macros-core+sqlx-postgres-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+sqlx-postgres-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+sqlx-postgres-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+sqlx-postgres-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+sqlx-postgres-devel.sha256sum] = "aaaf4e1e55cf514ce29dfca1697ca7beb2e2520fd2c08aafe1a194cbfe22c904"

URI_aarch64_rust-sqlx-macros-core+sqlx-sqlite-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+sqlx-sqlite-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+sqlx-sqlite-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+sqlx-sqlite-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+sqlx-sqlite-devel.sha256sum] = "1eaf159fe38caeb05f9dca0a76135cde3ce50dffaf63503ed0fe045731f0028e"

URI_aarch64_rust-sqlx-macros-core+time-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+time-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+time-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+time-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+time-devel.sha256sum] = "4ac0102597473d56f271a9cccf490f564064a1272e9faff8694f71dde2487816"

URI_aarch64_rust-sqlx-macros-core+tokio-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+tokio-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+tokio-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+tokio-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+tokio-devel.sha256sum] = "ca5649969cc5c15e2cb4780d6a09bc2dc4a0fe383ab0e1da653414e0869756be"

URI_aarch64_rust-sqlx-macros-core+uuid-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core+uuid-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core+uuid-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core+uuid-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core+uuid-devel.sha256sum] = "2e67e1494ef6ba9697eeafd846c5b7e8fef2fa21dc8ad08b3189244abc36000f"

URI_aarch64_rust-sqlx-macros-core-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-sqlx-macros-core-devel-0.8.6-4.el10_3.noarch.rpm;name=aarch64_rust-sqlx-macros-core-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-sqlx-macros-core-devel}"
SRC_URI[aarch64_rust-sqlx-macros-core-devel.sha256sum] = "f4b7409aba731a51d8dc828b4880b148e000ee8f139ca6c300f9356a69810d33"

RDEPENDS:rust-sqlx-macros-core+_rt-tokio-devel = " \
 cargo \
 rust-sqlx-core+_rt-tokio-devel \
 rust-sqlx-macros-core+tokio-devel \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+_sqlite-devel = " \
 cargo \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+_tls-native-tls-devel = " \
 cargo \
 rust-sqlx-core+_tls-native-tls-devel \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+_tls-rustls-ring-native-roots-devel = " \
 cargo \
 rust-sqlx-core+_tls-rustls-ring-native-roots-devel \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+_tls-rustls-ring-webpki-devel = " \
 cargo \
 rust-sqlx-core+_tls-rustls-ring-webpki-devel \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+async-std-devel = " \
 cargo \
 rust-async-std+default-devel \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+bigdecimal-devel = " \
 cargo \
 rust-sqlx-core+bigdecimal-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-mysql+bigdecimal-devel \
 rust-sqlx-mysql+default-devel \
 rust-sqlx-mysql+migrate-devel \
 rust-sqlx-mysql+offline-devel \
 rust-sqlx-postgres+bigdecimal-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+bit-vec-devel = " \
 cargo \
 rust-sqlx-core+bit-vec-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-postgres+bit-vec-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+chrono-devel = " \
 cargo \
 rust-sqlx-core+chrono-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-mysql+chrono-devel \
 rust-sqlx-mysql+default-devel \
 rust-sqlx-mysql+migrate-devel \
 rust-sqlx-mysql+offline-devel \
 rust-sqlx-postgres+chrono-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 rust-sqlx-sqlite+chrono-devel \
 rust-sqlx-sqlite+default-devel \
 rust-sqlx-sqlite+migrate-devel \
 rust-sqlx-sqlite+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+default-devel = " \
 cargo \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+derive-devel = " \
 cargo \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+ipnet-devel = " \
 cargo \
 rust-sqlx-core+ipnet-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+ipnet-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+ipnetwork-devel = " \
 cargo \
 rust-sqlx-core+ipnetwork-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+ipnetwork-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+json-devel = " \
 cargo \
 rust-sqlx-core+json-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-mysql+default-devel \
 rust-sqlx-mysql+json-devel \
 rust-sqlx-mysql+migrate-devel \
 rust-sqlx-mysql+offline-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+json-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 rust-sqlx-sqlite+default-devel \
 rust-sqlx-sqlite+json-devel \
 rust-sqlx-sqlite+migrate-devel \
 rust-sqlx-sqlite+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+mac_address-devel = " \
 cargo \
 rust-sqlx-core+mac_address-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+mac_address-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+macros-devel = " \
 cargo \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+migrate-devel = " \
 cargo \
 rust-sqlx-core+migrate-devel \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+mysql-devel = " \
 cargo \
 rust-sqlx-macros-core+sqlx-mysql-devel \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+postgres-devel = " \
 cargo \
 rust-sqlx-macros-core+sqlx-postgres-devel \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+rust_decimal-devel = " \
 cargo \
 rust-sqlx-core+rust_decimal-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-mysql+default-devel \
 rust-sqlx-mysql+migrate-devel \
 rust-sqlx-mysql+offline-devel \
 rust-sqlx-mysql+rust_decimal-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 rust-sqlx-postgres+rust_decimal-devel \
 "
RDEPENDS:rust-sqlx-macros-core+sqlite-devel = " \
 cargo \
 rust-sqlx-macros-core+sqlite-unbundled-devel \
 rust-sqlx-macros-core-devel \
 "
RDEPENDS:rust-sqlx-macros-core+sqlite-unbundled-devel = " \
 cargo \
 rust-sqlx-macros-core+_sqlite-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-sqlite+default-devel \
 rust-sqlx-sqlite+migrate-devel \
 rust-sqlx-sqlite+offline-devel \
 rust-sqlx-sqlite+unbundled-devel \
 "
RDEPENDS:rust-sqlx-macros-core+sqlx-mysql-devel = " \
 cargo \
 rust-sqlx-macros-core-devel \
 rust-sqlx-mysql+default-devel \
 rust-sqlx-mysql+migrate-devel \
 rust-sqlx-mysql+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+sqlx-postgres-devel = " \
 cargo \
 rust-sqlx-macros-core-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+sqlx-sqlite-devel = " \
 cargo \
 rust-sqlx-macros-core-devel \
 rust-sqlx-sqlite+default-devel \
 rust-sqlx-sqlite+migrate-devel \
 rust-sqlx-sqlite+offline-devel \
 "
RDEPENDS:rust-sqlx-macros-core+time-devel = " \
 cargo \
 rust-sqlx-core+time-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-mysql+default-devel \
 rust-sqlx-mysql+migrate-devel \
 rust-sqlx-mysql+offline-devel \
 rust-sqlx-mysql+time-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 rust-sqlx-postgres+time-devel \
 rust-sqlx-sqlite+default-devel \
 rust-sqlx-sqlite+migrate-devel \
 rust-sqlx-sqlite+offline-devel \
 rust-sqlx-sqlite+time-devel \
 "
RDEPENDS:rust-sqlx-macros-core+tokio-devel = " \
 cargo \
 rust-sqlx-macros-core-devel \
 rust-tokio+fs-devel \
 rust-tokio+io-util-devel \
 rust-tokio+net-devel \
 rust-tokio+rt-devel \
 rust-tokio+sync-devel \
 rust-tokio+time-devel \
 rust-tokio-devel \
 "
RDEPENDS:rust-sqlx-macros-core+uuid-devel = " \
 cargo \
 rust-sqlx-core+uuid-devel \
 rust-sqlx-macros-core-devel \
 rust-sqlx-mysql+default-devel \
 rust-sqlx-mysql+migrate-devel \
 rust-sqlx-mysql+offline-devel \
 rust-sqlx-mysql+uuid-devel \
 rust-sqlx-postgres+default-devel \
 rust-sqlx-postgres+migrate-devel \
 rust-sqlx-postgres+offline-devel \
 rust-sqlx-postgres+uuid-devel \
 rust-sqlx-sqlite+default-devel \
 rust-sqlx-sqlite+migrate-devel \
 rust-sqlx-sqlite+offline-devel \
 rust-sqlx-sqlite+uuid-devel \
 "
RDEPENDS:rust-sqlx-macros-core-devel = " \
 cargo \
 rust-dotenvy-devel \
 rust-either+default-devel \
 rust-heck+default-devel \
 rust-hex+default-devel \
 rust-once_cell+default-devel \
 rust-proc-macro2-devel \
 rust-quote-devel \
 rust-serde+default-devel \
 rust-serde+derive-devel \
 rust-serde_json+default-devel \
 rust-sha2_0.10+default-devel \
 rust-sqlx-core+default-devel \
 rust-sqlx-core+offline-devel \
 rust-syn2+clone-impls-devel \
 rust-syn2+derive-devel \
 rust-syn2+full-devel \
 rust-syn2+parsing-devel \
 rust-syn2+printing-devel \
 rust-syn2-devel \
 rust-url+default-devel \
 "
