# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-gix-quote"
PV = "0.7.2"
PR = "1.el10_3"
PACKAGES = " \
 rust-gix-quote+default-devel \
 rust-gix-quote-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-gix-quote-0.7.2-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b58e41107fd5632dcebfff9312cab092cac11b970e65275b966140f9760dd073"

URI_x86_64_v2_rust-gix-quote+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-gix-quote+default-devel-0.7.2-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-gix-quote+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-gix-quote+default-devel}"
SRC_URI[x86_64_v2_rust-gix-quote+default-devel.sha256sum] = "df37e3943f3338a53650616b35524531886531c8eff357941f931ecf89364314"

URI_x86_64_v2_rust-gix-quote-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-gix-quote-devel-0.7.2-1.el10_3.alma_altarch.noarch.rpm;name=x86_64_v2_rust-gix-quote-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-gix-quote-devel}"
SRC_URI[x86_64_v2_rust-gix-quote-devel.sha256sum] = "4e9501e3be86187fbfa42fb0e4396de1c47e39234b9479c2c613a4083441a388"

URI_aarch64_rust-gix-quote+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-gix-quote+default-devel-0.7.2-1.el10_3.noarch.rpm;name=aarch64_rust-gix-quote+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-gix-quote+default-devel}"
SRC_URI[aarch64_rust-gix-quote+default-devel.sha256sum] = "29a4b9c098939c62b330409f466ec5dfa12a7d69a1723730ccadaa2b4875463b"

URI_aarch64_rust-gix-quote-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-gix-quote-devel-0.7.2-1.el10_3.noarch.rpm;name=aarch64_rust-gix-quote-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-gix-quote-devel}"
SRC_URI[aarch64_rust-gix-quote-devel.sha256sum] = "617346f280971dafc43e61c4c300ccc817c8891650b7fadbf59bc9165e90ec9e"

RDEPENDS:rust-gix-quote+default-devel = " \
 cargo \
 rust-gix-quote-devel \
 "
RDEPENDS:rust-gix-quote-devel = " \
 cargo \
 rust \
 rust-bstr+std-devel \
 rust-bstr-devel \
 rust-gix-error+default-devel \
 rust-gix-utils+default-devel \
 "
