# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-rustix-linux-procfs"
PV = "0.1.1"
PR = "1.el10_3"
PACKAGES = " \
 rust-rustix-linux-procfs+default-devel \
 rust-rustix-linux-procfs+std-devel \
 rust-rustix-linux-procfs-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-rustix-linux-procfs-0.1.1-1.el10_3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4c87df3196c366e85183bbcb739294e8b08356a82a7d8822f932388262079d65"

URI_aarch64_rust-rustix-linux-procfs+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-rustix-linux-procfs+default-devel-0.1.1-1.el10_3.noarch.rpm;name=aarch64_rust-rustix-linux-procfs+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-rustix-linux-procfs+default-devel}"
SRC_URI[aarch64_rust-rustix-linux-procfs+default-devel.sha256sum] = "6e2d6675d9871f2bec03cb2c8f6de01bca9af9e4b677937a52a3b874e75f76f4"

URI_aarch64_rust-rustix-linux-procfs+std-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-rustix-linux-procfs+std-devel-0.1.1-1.el10_3.noarch.rpm;name=aarch64_rust-rustix-linux-procfs+std-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-rustix-linux-procfs+std-devel}"
SRC_URI[aarch64_rust-rustix-linux-procfs+std-devel.sha256sum] = "ebdbd19ceacc23cc9cc8d92a1be8f2297c2aa3c6e4277b6ed762ca8b7d595cf5"

URI_aarch64_rust-rustix-linux-procfs-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-rustix-linux-procfs-devel-0.1.1-1.el10_3.noarch.rpm;name=aarch64_rust-rustix-linux-procfs-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-rustix-linux-procfs-devel}"
SRC_URI[aarch64_rust-rustix-linux-procfs-devel.sha256sum] = "d2d31dbcaa53d66ed55a2f6d351532719db60ebcaf5359448a666e4b5ac9e6c9"

RDEPENDS:rust-rustix-linux-procfs+default-devel = " \
 cargo \
 rust-rustix-linux-procfs+std-devel \
 rust-rustix-linux-procfs-devel \
 "
RDEPENDS:rust-rustix-linux-procfs+std-devel = " \
 cargo \
 rust-rustix+std-devel \
 rust-rustix-linux-procfs-devel \
 "
RDEPENDS:rust-rustix-linux-procfs-devel = " \
 cargo \
 rust \
 rust-once_cell+default-devel \
 rust-rustix+alloc-devel \
 rust-rustix+fs-devel \
 rust-rustix-devel \
 "
