# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-dialoguer"
PV = "0.11.0"
PR = "3.el10_0"
PACKAGES = " \
 rust-dialoguer+completion-devel \
 rust-dialoguer+default-devel \
 rust-dialoguer+editor-devel \
 rust-dialoguer+fuzzy-matcher-devel \
 rust-dialoguer+fuzzy-select-devel \
 rust-dialoguer+history-devel \
 rust-dialoguer+password-devel \
 rust-dialoguer+tempfile-devel \
 rust-dialoguer+zeroize-devel \
 rust-dialoguer-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-dialoguer-0.11.0-3.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3c52a5414071a8272122310be7b6abd4f677c1b1eb0b6e9093b71ed53c366116"

URI_x86_64_v2_rust-dialoguer+completion-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer+completion-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer+completion-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer+completion-devel}"
SRC_URI[x86_64_v2_rust-dialoguer+completion-devel.sha256sum] = "f9d4cc82f01921b30fe4c8269bfecd6d59b28151b7b422421f86b830b78a6994"

URI_x86_64_v2_rust-dialoguer+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer+default-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer+default-devel}"
SRC_URI[x86_64_v2_rust-dialoguer+default-devel.sha256sum] = "8111055326b5dd6b1f190587bdd9d8d72f4579b9a741c63bb47cdf0edd7c6ca1"

URI_x86_64_v2_rust-dialoguer+editor-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer+editor-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer+editor-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer+editor-devel}"
SRC_URI[x86_64_v2_rust-dialoguer+editor-devel.sha256sum] = "660dbb8323bdc2e495a4d819e1a5da19d8fea878a6830ad1664e4bfbfbb93fb6"

URI_x86_64_v2_rust-dialoguer+fuzzy-matcher-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer+fuzzy-matcher-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer+fuzzy-matcher-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer+fuzzy-matcher-devel}"
SRC_URI[x86_64_v2_rust-dialoguer+fuzzy-matcher-devel.sha256sum] = "181506dd4589c963f8f8f85d297891bf5c7e67d75a3213d16e41199ac16c623d"

URI_x86_64_v2_rust-dialoguer+fuzzy-select-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer+fuzzy-select-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer+fuzzy-select-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer+fuzzy-select-devel}"
SRC_URI[x86_64_v2_rust-dialoguer+fuzzy-select-devel.sha256sum] = "5ad13e3ff515005d2e7e0cf8a1deadd7f55b31b919b08ce67153cdfad6c849a7"

URI_x86_64_v2_rust-dialoguer+history-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer+history-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer+history-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer+history-devel}"
SRC_URI[x86_64_v2_rust-dialoguer+history-devel.sha256sum] = "763d36f283de1bc8998abb14a0eee6dbef9b76cdff2b64b54ecd917471c6d796"

URI_x86_64_v2_rust-dialoguer+password-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer+password-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer+password-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer+password-devel}"
SRC_URI[x86_64_v2_rust-dialoguer+password-devel.sha256sum] = "3043829b3ed1c140b85b8690c234fdcc88e60e4fcabd8271ffcead9d82598c8c"

URI_x86_64_v2_rust-dialoguer+tempfile-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer+tempfile-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer+tempfile-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer+tempfile-devel}"
SRC_URI[x86_64_v2_rust-dialoguer+tempfile-devel.sha256sum] = "7543eb64113633d2ab7f968d823b4b64a4fb09244a3fe75222723e76f9132cbb"

URI_x86_64_v2_rust-dialoguer+zeroize-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer+zeroize-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer+zeroize-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer+zeroize-devel}"
SRC_URI[x86_64_v2_rust-dialoguer+zeroize-devel.sha256sum] = "c2aa72cf4791cdfecd3959b97898a18730f85522e5f2984dbb84518b6d73e9dd"

URI_x86_64_v2_rust-dialoguer-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-dialoguer-devel-0.11.0-3.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-dialoguer-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-dialoguer-devel}"
SRC_URI[x86_64_v2_rust-dialoguer-devel.sha256sum] = "7b3957d1afdf9103350da1150f9a19a4a57ecb1e75fb86f1bf10e7661c5d7664"

URI_aarch64_rust-dialoguer+completion-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer+completion-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer+completion-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer+completion-devel}"
SRC_URI[aarch64_rust-dialoguer+completion-devel.sha256sum] = "06fb7e057524a601fae216798024638f49c88320359ca6cd40ae0c682b709222"

URI_aarch64_rust-dialoguer+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer+default-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer+default-devel}"
SRC_URI[aarch64_rust-dialoguer+default-devel.sha256sum] = "dd4cb3af96d2a4ebaa04dba904c5be47afc64d508674153c5047ddc52c89765c"

URI_aarch64_rust-dialoguer+editor-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer+editor-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer+editor-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer+editor-devel}"
SRC_URI[aarch64_rust-dialoguer+editor-devel.sha256sum] = "8b8117c3b0a0f8801c7440f4e6c42a1b304430091b2f60cbba58fe0ed3127d37"

URI_aarch64_rust-dialoguer+fuzzy-matcher-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer+fuzzy-matcher-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer+fuzzy-matcher-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer+fuzzy-matcher-devel}"
SRC_URI[aarch64_rust-dialoguer+fuzzy-matcher-devel.sha256sum] = "e923c27f5f4d0c9dc5d1ed2cbe515339b09f8c8f869276143e66a4d59d26d370"

URI_aarch64_rust-dialoguer+fuzzy-select-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer+fuzzy-select-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer+fuzzy-select-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer+fuzzy-select-devel}"
SRC_URI[aarch64_rust-dialoguer+fuzzy-select-devel.sha256sum] = "dd361cc7e2f997b259a93e057efb56645dfa8c12fb558fd528da9be33769b540"

URI_aarch64_rust-dialoguer+history-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer+history-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer+history-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer+history-devel}"
SRC_URI[aarch64_rust-dialoguer+history-devel.sha256sum] = "9fc16e91a15523dc57a7c1179d81500697c19bdc8c14617007252ed16439d047"

URI_aarch64_rust-dialoguer+password-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer+password-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer+password-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer+password-devel}"
SRC_URI[aarch64_rust-dialoguer+password-devel.sha256sum] = "f05b83d1c1e0e3f85ee58e1cdeba18f6e4e765f2afe4fad42f42ed80eb198037"

URI_aarch64_rust-dialoguer+tempfile-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer+tempfile-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer+tempfile-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer+tempfile-devel}"
SRC_URI[aarch64_rust-dialoguer+tempfile-devel.sha256sum] = "a1672a0abed8bfd4f6c494268725d00f8e60aea4e9b9372b83e01f4910018ef6"

URI_aarch64_rust-dialoguer+zeroize-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer+zeroize-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer+zeroize-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer+zeroize-devel}"
SRC_URI[aarch64_rust-dialoguer+zeroize-devel.sha256sum] = "7aef3eb9c8c70129edacc615797be79cb72fccb22f005c821ca76f8012904808"

URI_aarch64_rust-dialoguer-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-dialoguer-devel-0.11.0-3.el10_0.noarch.rpm;name=aarch64_rust-dialoguer-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-dialoguer-devel}"
SRC_URI[aarch64_rust-dialoguer-devel.sha256sum] = "28cb238c00ffe3478d74d8fd5aae6c176be8e07b44745063c95db1b45f596de2"

RDEPENDS:rust-dialoguer+completion-devel = " \
 cargo \
 rust-dialoguer-devel \
 "
RDEPENDS:rust-dialoguer+default-devel = " \
 cargo \
 rust-dialoguer+editor-devel \
 rust-dialoguer+password-devel \
 rust-dialoguer-devel \
 "
RDEPENDS:rust-dialoguer+editor-devel = " \
 cargo \
 rust-dialoguer+tempfile-devel \
 rust-dialoguer-devel \
 "
RDEPENDS:rust-dialoguer+fuzzy-matcher-devel = " \
 cargo \
 rust-dialoguer-devel \
 rust-fuzzy-matcher+default-devel \
 "
RDEPENDS:rust-dialoguer+fuzzy-select-devel = " \
 cargo \
 rust-dialoguer+fuzzy-matcher-devel \
 rust-dialoguer-devel \
 "
RDEPENDS:rust-dialoguer+history-devel = " \
 cargo \
 rust-dialoguer-devel \
 "
RDEPENDS:rust-dialoguer+password-devel = " \
 cargo \
 rust-dialoguer+zeroize-devel \
 rust-dialoguer-devel \
 "
RDEPENDS:rust-dialoguer+tempfile-devel = " \
 cargo \
 rust-dialoguer-devel \
 rust-tempfile+default-devel \
 "
RDEPENDS:rust-dialoguer+zeroize-devel = " \
 cargo \
 rust-dialoguer-devel \
 rust-zeroize+default-devel \
 "
RDEPENDS:rust-dialoguer-devel = " \
 cargo \
 rust \
 rust-console+default-devel \
 rust-shell-words+default-devel \
 rust-thiserror1+default-devel \
 "
