# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "rust-zip0.6"
PV = "0.6.6"
PR = "2.el10_0"
PACKAGES = " \
 rust-zip0.6+aes-crypto-devel \
 rust-zip0.6+aes-devel \
 rust-zip0.6+bzip2-devel \
 rust-zip0.6+constant_time_eq-devel \
 rust-zip0.6+default-devel \
 rust-zip0.6+deflate-devel \
 rust-zip0.6+deflate-miniz-devel \
 rust-zip0.6+deflate-zlib-devel \
 rust-zip0.6+flate2-devel \
 rust-zip0.6+hmac-devel \
 rust-zip0.6+pbkdf2-devel \
 rust-zip0.6+sha1-devel \
 rust-zip0.6+time-devel \
 rust-zip0.6+unreserved-devel \
 rust-zip0.6+zstd-devel \
 rust-zip0.6-devel \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/r/rust-zip0.6-0.6.6-2.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a1d6d12523dc6dec6bda10d703feb38de7734fda1bd3730b643a27f4def1a6d8"

URI_x86_64_v2_rust-zip0.6+aes-crypto-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+aes-crypto-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+aes-crypto-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+aes-crypto-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+aes-crypto-devel.sha256sum] = "082e337186f3fda0316fe5e5f1821e568c8f584525ef4997b8553ea4d9890123"

URI_x86_64_v2_rust-zip0.6+aes-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+aes-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+aes-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+aes-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+aes-devel.sha256sum] = "256fc3aa9db19f48726bfe877449cd8095d40959ebc6056b631ffceb0ed8bd6c"

URI_x86_64_v2_rust-zip0.6+bzip2-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+bzip2-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+bzip2-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+bzip2-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+bzip2-devel.sha256sum] = "318303e3fdecae1612d454fc5e6d087ba15ecac68fe02965116e6e1106abfb4d"
RPROVIDES:rust-zip0.6+bzip2-devel:x86_64_v2 = "virtual/crate_zip/bzip2__ge_0.6.0_with_crate_zip/bzip2__lt_3.0.0~"

URI_x86_64_v2_rust-zip0.6+constant_time_eq-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+constant_time_eq-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+constant_time_eq-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+constant_time_eq-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+constant_time_eq-devel.sha256sum] = "411f3615d867fa1c7150179720e27b2add35a20cfb83c13cd1080aa071d8b646"

URI_x86_64_v2_rust-zip0.6+default-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+default-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+default-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+default-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+default-devel.sha256sum] = "69f44614c3e9ac7c4b23e8598706c7933c20695d00470fa4d21fb9d64e38cf63"

URI_x86_64_v2_rust-zip0.6+deflate-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+deflate-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+deflate-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+deflate-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+deflate-devel.sha256sum] = "dcc1b3dc1423e1a36c7b9b72c4ae13bb524a8fe882a853b78852da549d80e3a1"
RPROVIDES:rust-zip0.6+deflate-devel:x86_64_v2 = "virtual/crate_zip/deflate__ge_0.6.0_with_crate_zip/deflate__lt_3.0.0~"

URI_x86_64_v2_rust-zip0.6+deflate-miniz-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+deflate-miniz-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+deflate-miniz-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+deflate-miniz-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+deflate-miniz-devel.sha256sum] = "b3c426f22ba8ec76339191dd273efc8e4a86e41bd943fb9808416717c78ee1f3"

URI_x86_64_v2_rust-zip0.6+deflate-zlib-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+deflate-zlib-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+deflate-zlib-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+deflate-zlib-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+deflate-zlib-devel.sha256sum] = "b67859cb3cb19a76e0b1b265bf4c1e906ecdcb02c3c9fc80a522d25d37205104"

URI_x86_64_v2_rust-zip0.6+flate2-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+flate2-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+flate2-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+flate2-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+flate2-devel.sha256sum] = "a926df75fcb185a59b722fdfe4740c51abc5eb6c5df12c63d8a7f0ec6f092999"

URI_x86_64_v2_rust-zip0.6+hmac-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+hmac-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+hmac-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+hmac-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+hmac-devel.sha256sum] = "2992a44884a85d7b483fb4ab3d1366d6e50d80eddd4a354d8cbee3d9fe362a08"

URI_x86_64_v2_rust-zip0.6+pbkdf2-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+pbkdf2-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+pbkdf2-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+pbkdf2-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+pbkdf2-devel.sha256sum] = "11840aa224d3c1a449d711b32024e4985d323b14d45f4fde1e925044f3727782"

URI_x86_64_v2_rust-zip0.6+sha1-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+sha1-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+sha1-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+sha1-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+sha1-devel.sha256sum] = "bc3a5e10863a9a7c468ef60c707934652d835549a91861e4c1a1d19f14e09b91"

URI_x86_64_v2_rust-zip0.6+time-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+time-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+time-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+time-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+time-devel.sha256sum] = "c29c8509a98323092ab271b4a4e1fb372def9042f2c6ac8469fe7303e158aca1"

URI_x86_64_v2_rust-zip0.6+unreserved-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+unreserved-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+unreserved-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+unreserved-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+unreserved-devel.sha256sum] = "da1f15f240ae456016639a87d0b9c0a700501a239eb8d7651627b2b99c03aab0"

URI_x86_64_v2_rust-zip0.6+zstd-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6+zstd-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6+zstd-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6+zstd-devel}"
SRC_URI[x86_64_v2_rust-zip0.6+zstd-devel.sha256sum] = "952bbb06890e6e79349da513fbe9c4b6776253472d500e204ad7a3c005b472f2"

URI_x86_64_v2_rust-zip0.6-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/rust-zip0.6-devel-0.6.6-2.el10_0.alma_altarch.noarch.rpm;name=x86_64_v2_rust-zip0.6-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_rust-zip0.6-devel}"
SRC_URI[x86_64_v2_rust-zip0.6-devel.sha256sum] = "451ead899cc9f09723d2617ae5d8a739c5b29961004c38c87c094a78849266dd"
RPROVIDES:rust-zip0.6-devel:x86_64_v2 = "virtual/crate_zip__ge_0.6.0_with_crate_zip__lt_3.0.0~"

URI_aarch64_rust-zip0.6+aes-crypto-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+aes-crypto-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+aes-crypto-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+aes-crypto-devel}"
SRC_URI[aarch64_rust-zip0.6+aes-crypto-devel.sha256sum] = "5b45e949f7aeb7e39b9ccab5ea05dd97b09415067835377e88edb5b9753b50a5"

URI_aarch64_rust-zip0.6+aes-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+aes-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+aes-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+aes-devel}"
SRC_URI[aarch64_rust-zip0.6+aes-devel.sha256sum] = "f80f7de87133770afc457e0f291af8e18301e43c4d30f577480771d7c673e911"

URI_aarch64_rust-zip0.6+bzip2-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+bzip2-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+bzip2-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+bzip2-devel}"
SRC_URI[aarch64_rust-zip0.6+bzip2-devel.sha256sum] = "c132406f2ed5ffa9ee24d9e9dffb28565bb3d39d75a6f42af0d71bc83cf2d1c0"
RPROVIDES:rust-zip0.6+bzip2-devel:aarch64 = "virtual/crate_zip/bzip2__ge_0.6.0_with_crate_zip/bzip2__lt_3.0.0~"

URI_aarch64_rust-zip0.6+constant_time_eq-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+constant_time_eq-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+constant_time_eq-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+constant_time_eq-devel}"
SRC_URI[aarch64_rust-zip0.6+constant_time_eq-devel.sha256sum] = "57bf345a4c08d254ebde1fcc8d03249efd4d646dd2671155e669d34dcfd0364b"

URI_aarch64_rust-zip0.6+default-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+default-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+default-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+default-devel}"
SRC_URI[aarch64_rust-zip0.6+default-devel.sha256sum] = "4a9d336ef38ecf4bec8d66ede40ec793eb13b23f9dac2f6b825775b82854256b"

URI_aarch64_rust-zip0.6+deflate-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+deflate-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+deflate-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+deflate-devel}"
SRC_URI[aarch64_rust-zip0.6+deflate-devel.sha256sum] = "3a5666e81a5a314241ecaf1b087593ef777085fff70b0c9eca7e6bd64397b1cd"
RPROVIDES:rust-zip0.6+deflate-devel:aarch64 = "virtual/crate_zip/deflate__ge_0.6.0_with_crate_zip/deflate__lt_3.0.0~"

URI_aarch64_rust-zip0.6+deflate-miniz-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+deflate-miniz-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+deflate-miniz-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+deflate-miniz-devel}"
SRC_URI[aarch64_rust-zip0.6+deflate-miniz-devel.sha256sum] = "ddc0973f5aea179624bd3faa1ba4af6c4ce8cdf7430d732d9ad520d2e3f6cb01"

URI_aarch64_rust-zip0.6+deflate-zlib-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+deflate-zlib-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+deflate-zlib-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+deflate-zlib-devel}"
SRC_URI[aarch64_rust-zip0.6+deflate-zlib-devel.sha256sum] = "bd06f57e2c725cfe2ca8d886af8f857cc1413fca80b74a007d872b4a21ace1e7"

URI_aarch64_rust-zip0.6+flate2-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+flate2-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+flate2-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+flate2-devel}"
SRC_URI[aarch64_rust-zip0.6+flate2-devel.sha256sum] = "cf319150bb53cf407e2e496c6b188defc1d9fcc2eec379947174ce42a8369117"

URI_aarch64_rust-zip0.6+hmac-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+hmac-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+hmac-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+hmac-devel}"
SRC_URI[aarch64_rust-zip0.6+hmac-devel.sha256sum] = "0374a6c4d2728f078c86ffa3d756a435d3852701354f322258e783d189cce1fd"

URI_aarch64_rust-zip0.6+pbkdf2-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+pbkdf2-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+pbkdf2-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+pbkdf2-devel}"
SRC_URI[aarch64_rust-zip0.6+pbkdf2-devel.sha256sum] = "0ed7f5c1a660bd7924349962d77ff4c393bf7f5469880e94441c76e6f3cc47a0"

URI_aarch64_rust-zip0.6+sha1-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+sha1-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+sha1-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+sha1-devel}"
SRC_URI[aarch64_rust-zip0.6+sha1-devel.sha256sum] = "f004b60ca5afb351c56c6d5bd6929ddc4ac79451e18686c8607628b49272f817"

URI_aarch64_rust-zip0.6+time-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+time-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+time-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+time-devel}"
SRC_URI[aarch64_rust-zip0.6+time-devel.sha256sum] = "9fa9fade8e439b391932f4481d5f2f62fc53727445c2d300e1adc611c4ea22bc"

URI_aarch64_rust-zip0.6+unreserved-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+unreserved-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+unreserved-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+unreserved-devel}"
SRC_URI[aarch64_rust-zip0.6+unreserved-devel.sha256sum] = "269bdcc8eb37acd23b2fdc6f9b413352b7e190051b3fca1f0f9469ca4e324828"

URI_aarch64_rust-zip0.6+zstd-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6+zstd-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6+zstd-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6+zstd-devel}"
SRC_URI[aarch64_rust-zip0.6+zstd-devel.sha256sum] = "de8fb82506421cf4b8c4c80124997efe95bea6f9123c9592a710cbf59f5439be"

URI_aarch64_rust-zip0.6-devel = "${EPEL_MIRROR}/aarch64/Packages/r/rust-zip0.6-devel-0.6.6-2.el10_0.noarch.rpm;name=aarch64_rust-zip0.6-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_rust-zip0.6-devel}"
SRC_URI[aarch64_rust-zip0.6-devel.sha256sum] = "2355f75b1d85f95da30bf0e26516aa3bb8a3917c9eadd3fdfb656b53e491c52d"
RPROVIDES:rust-zip0.6-devel:aarch64 = "virtual/crate_zip__ge_0.6.0_with_crate_zip__lt_3.0.0~"

RDEPENDS:rust-zip0.6+aes-crypto-devel = " \
 cargo \
 rust-zip0.6+aes-devel \
 rust-zip0.6+constant_time_eq-devel \
 rust-zip0.6+hmac-devel \
 rust-zip0.6+pbkdf2-devel \
 rust-zip0.6+sha1-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+aes-devel = " \
 cargo \
 rust-aes+default-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+bzip2-devel = " \
 cargo \
 rust-bzip2+default-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+constant_time_eq-devel = " \
 cargo \
 rust-constant_time_eq+default-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+default-devel = " \
 cargo \
 rust-zip0.6+aes-crypto-devel \
 rust-zip0.6+bzip2-devel \
 rust-zip0.6+deflate-devel \
 rust-zip0.6+time-devel \
 rust-zip0.6+zstd-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+deflate-devel = " \
 cargo \
 rust-flate2+rust_backend-devel \
 rust-flate2-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+deflate-miniz-devel = " \
 cargo \
 rust-flate2+default-devel \
 rust-flate2-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+deflate-zlib-devel = " \
 cargo \
 rust-flate2+zlib-devel \
 rust-flate2-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+flate2-devel = " \
 cargo \
 rust-flate2-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+hmac-devel = " \
 cargo \
 rust-hmac+default-devel \
 rust-hmac+reset-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+pbkdf2-devel = " \
 cargo \
 rust-pbkdf2+default-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+sha1-devel = " \
 cargo \
 rust-sha1+default-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+time-devel = " \
 cargo \
 rust-time+std-devel \
 rust-time-devel \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+unreserved-devel = " \
 cargo \
 rust-zip0.6-devel \
 "
RDEPENDS:rust-zip0.6+zstd-devel = " \
 cargo \
 rust-zip0.6-devel \
 rust-zstd+default-devel \
 "
RDEPENDS:rust-zip0.6-devel = " \
 cargo \
 rust \
 rust-byteorder+default-devel \
 rust-crc32fast+default-devel \
 rust-crossbeam-utils+default-devel \
 "

PROVIDES:append:x86_64_v2 = " rpm/virtual/crate_zip/bzip2__ge_0.6.0_with_crate_zip/bzip2__lt_3.0.0~ rpm/virtual/crate_zip/deflate__ge_0.6.0_with_crate_zip/deflate__lt_3.0.0~ rpm/virtual/crate_zip__ge_0.6.0_with_crate_zip__lt_3.0.0~"

PROVIDES:append:aarch64 = " rpm/virtual/crate_zip/bzip2__ge_0.6.0_with_crate_zip/bzip2__lt_3.0.0~ rpm/virtual/crate_zip/deflate__ge_0.6.0_with_crate_zip/deflate__lt_3.0.0~ rpm/virtual/crate_zip__ge_0.6.0_with_crate_zip__lt_3.0.0~"
