# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "veristat"
PV = "0.5.1"
PR = "1.el10_1"
PACKAGES = " \
 veristat \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/v/veristat-0.5.1-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3ac4fb4f0872d2c66a21f97134d5ff56fe63f3ca5e69ab94f3963151bc2e0a3a"

URI_x86_64_v2_veristat = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/veristat-0.5.1-1.el10_1.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_veristat;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_veristat}"
SRC_URI[x86_64_v2_veristat.sha256sum] = "bc6453cc6b06eb33a515b902109fc4959e83af7c9a3ea0ca8b50c7d2778cc775"

URI_aarch64_veristat = "${EPEL_MIRROR}/aarch64/Packages/v/veristat-0.5.1-1.el10_1.aarch64.rpm;name=aarch64_veristat;unpack=0"
SRC_URI:append = " ${URI_aarch64_veristat}"
SRC_URI[aarch64_veristat.sha256sum] = "7f996efd3369ce87355acef7d499a200819ec6e0e0556c731622ef138e0f2b19"

RDEPENDS:veristat = " \
 elfutils-libelf \
 glibc \
 zlib-ng-compat \
 "
