# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "virtme-ng"
PV = "1.37"
PR = "1.el10_1"
PACKAGES = " \
 virtme-ng \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/v/virtme-ng-1.37-1.el10_1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "501b2b53cbdf2195a7d84425635b2de26d05eab534ccf0ba188d6cfe44915b89"

URI_x86_64_v2_virtme-ng = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/virtme-ng-1.37-1.el10_1.alma_altarch.noarch.rpm;name=x86_64_v2_virtme-ng;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_virtme-ng}"
SRC_URI[x86_64_v2_virtme-ng.sha256sum] = "47ab75e33758327bf8614fa2cf5cb702f4cbe2e4cfc81748e86570a1684f3a94"

URI_aarch64_virtme-ng = "${EPEL_MIRROR}/aarch64/Packages/v/virtme-ng-1.37-1.el10_1.noarch.rpm;name=aarch64_virtme-ng;unpack=0"
SRC_URI:append = " ${URI_aarch64_virtme-ng}"
SRC_URI[aarch64_virtme-ng.sha256sum] = "7630db600577a423e23ded860f2015bb1719e323afc2cb41b97c9fea0e3f49ea"

RDEPENDS:virtme-ng = " \
 bash \
 python3 \
 python3-argcomplete \
 python3-requests \
 python3-setuptools \
 "
