# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "xisxwayland"
PV = "2"
PR = "5.el10_0"
PACKAGES = " \
 xisxwayland \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/x/xisxwayland-2-5.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8de0a5312fc93482e49004f566375a24d39c829ef06dc7b03028af6761ae8359"

URI_x86_64_v2_xisxwayland = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/xisxwayland-2-5.el10_0.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_xisxwayland;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_xisxwayland}"
SRC_URI[x86_64_v2_xisxwayland.sha256sum] = "adc362c492d0ed25231c0210e5a1e75bfc52fd39fd9472c13c2a6276bf2c7e69"

URI_aarch64_xisxwayland = "${EPEL_MIRROR}/aarch64/Packages/x/xisxwayland-2-5.el10_0.aarch64.rpm;name=aarch64_xisxwayland;unpack=0"
SRC_URI:append = " ${URI_aarch64_xisxwayland}"
SRC_URI[aarch64_xisxwayland.sha256sum] = "095d1e9e1558e112abf534cc231ea332de30dd57950a728230cfcc09fc1a5329"

RDEPENDS:xisxwayland = " \
 glibc \
 libX11 \
 libXrandr \
 "
