# File generated by gen-dnf-proxy.py, do not modify

inherit dnf-bridge

PN = "yarnpkg"
PV = "1.22.22"
PR = "16.el10_2"
PACKAGES = " \
 yarnpkg \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/y/yarnpkg-1.22.22-16.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "42ace4ce09a79393c9c3d683dfcf7358b550cb31c2e81b10f702cb04941f14d7"

URI_x86_64_v2_yarnpkg = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/yarnpkg-1.22.22-16.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_yarnpkg;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_yarnpkg}"
SRC_URI[x86_64_v2_yarnpkg.sha256sum] = "a976c0f45893fbf77346d5a0c58a19f1a97307d1c1df25d9c78f2ad30072e8f6"

URI_aarch64_yarnpkg = "${EPEL_MIRROR}/aarch64/Packages/y/yarnpkg-1.22.22-16.el10_2.aarch64.rpm;name=aarch64_yarnpkg;unpack=0"
SRC_URI:append = " ${URI_aarch64_yarnpkg}"
SRC_URI[aarch64_yarnpkg.sha256sum] = "a4822b0d294f340fd94ee2b7c18deb57993a944c4b71ad1e6c3862b66b69b65e"

RDEPENDS:yarnpkg = " \
 bash \
 nodejs \
 "
